objects/Account_Team_Member__c.object
<CustomObject>
    <description>This object replace the standard funcionality for adding team members to accounts.</description>
    <fields>
        <fullName>Organisation_Access__c</fullName>
        <label>Relationship Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only</fullName>
                    <default>true</default>
                    <label>Read Only</label>
                </value>
                <value>
                    <fullName>Read/Write</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Relationship Team Members</relationshipLabel>
        <relationshipName>Account_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Organisation_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate Banker</fullName>
                </value>
                <value>
                    <fullName>Alternate Coverage Support Manager</fullName>
                </value>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>BRSG Relationship Manager</fullName>
                </value>
                <value>
                    <fullName>BRSG Segment Head</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Client Solutions</fullName>
                </value>
                <value>
                    <fullName>Corridor Banker</fullName>
                </value>
                <value>
                    <fullName>Coverage Banker</fullName>
                </value>
                <value>
                    <fullName>Coverage Support Manager</fullName>
                </value>
                <value>
                    <fullName>Coverage Team Head</fullName>
                </value>
                <value>
                    <fullName>CPF</fullName>
                </value>
                <value>
                    <fullName>Credit Manager</fullName>
                </value>
                <value>
                    <fullName>Debt</fullName>
                </value>
                <value>
                    <fullName>ECM (Banking)</fullName>
                </value>
                <value>
                    <fullName>EDC Consultant</fullName>
                </value>
                <value>
                    <fullName>GRD</fullName>
                </value>
                <value>
                    <fullName>Investment and Banking</fullName>
                </value>
                <value>
                    <fullName>Leadership</fullName>
                </value>
                <value>
                    <fullName>Liquidity Sales</fullName>
                </value>
                <value>
                    <fullName>M&amp;A Advisory (Banking)</fullName>
                </value>
                <value>
                    <fullName>Markets</fullName>
                </value>
                <value>
                    <fullName>New Business Development</fullName>
                </value>
                <value>
                    <fullName>Other Product Area</fullName>
                </value>
                <value>
                    <fullName>Regional Banker</fullName>
                </value>
                <value>
                    <fullName>Regional TPS Partner</fullName>
                </value>
                <value>
                    <fullName>RSG</fullName>
                </value>
                <value>
                    <fullName>Senior Sponsor</fullName>
                </value>
                <value>
                    <fullName>STCF Consultant</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Relationship Team Member</label>
    <nameField>
        <displayFormat>ATM-{000000}</displayFormat>
        <label>Client Relationship Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Relationship Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plans</relationshipLabel>
        <relationshipName>ClientPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Plan</label>
    <nameField>
        <displayFormat>PL{00000}</displayFormat>
        <label>Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ZZTEST_ClientPlanTrigger_Helper.cls
/**
* @Author:        Marek Cech
* @Company:       Deloitte
* @Description:   Unit Tests for ClientPlanTrigger_Helper
*                 Tests executed:
*                 1 - testCheckRightsToCreateNewViaTeamMember()
*                   Tests checking rights to create a client plan for team member
*                 2 - testCheckRightsToCreateNewViaOwner()
*                   Tests checking rights to create a client plan for account owner
*                 3 - testCheckRightsToCreateNewErrors()
*                   Tests errors handling during checking rights to create a client plan for account owner
*                 4 - testSharing()
*                   Tests sharing method
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* 24-May-2016	Mohsin Wadee	In testSharing() method used getInsertedProduct() method to create test account instead.
* ---------------------------------------------------------------------------------------------------------------------*/
@isTest
public class ZZTEST_ClientPlanTrigger_Helper {

        private static final String EDIT = 'Edit';

        private class ZZTEST_ClientPlanTrigger_HelperException extends Exception {
        }

        static testMethod void testCheckRightsToCreateNewViaTeamMember() {
                ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();

                ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
                Account acc1 = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);

                ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
                User u1 = userFactory.getExistingUserByProfile('System Administrator');

                Account_Team_Member__c mem1 = new Account_Team_Member__c();
                mem1.Organisation__c = acc1.Id;
                mem1.Organisation_Access__c = 'Read/Write';
                mem1.Team_Member__c = u1.Id;
                mem1.Team_Role__c = 'Markets';
                insert mem1;

                System.runAs(u1) {
                        Client_Plan__c plan1 = new Client_Plan__c();
                        plan1.Relationship__c = acc1.Id;

                        Database.SaveResult[] saveResult = Database.INSERT(new List<Client_Plan__c>{plan1}, false);  
                        
                        System.assertEquals(1, saveResult.size());

                        Database.SaveResult r = saveResult[0];
                        System.assertEquals(true, r.isSuccess());
                }
        }

        static testMethod void testCheckRightsToCreateNewViaOwner() {
                ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();

                ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
                Account acc1 = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);

                Client_Plan__c plan1 = new Client_Plan__c();
                plan1.Relationship__c = acc1.Id;

                Database.SaveResult[] saveResult = Database.INSERT(new List<Client_Plan__c>{plan1}, false); 

                System.assertEquals(1, saveResult.size());

                Database.SaveResult r = saveResult[0];
                System.assertEquals(true, r.isSuccess());
        }

        static testMethod void testCheckRightsToCreateNewErrors() {
                ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();

                ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
                Account acc1 = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);

                ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
                User u1 = userFactory.getExistingUserByProfile('System Administrator');

                System.runAs(u1) {
                        Client_Plan__c plan1 = new Client_Plan__c();
                        plan1.Relationship__c = acc1.Id;

                        Database.SaveResult[] saveResult = Database.INSERT(new List<Client_Plan__c>{plan1}, false);  
                        
                        System.assertEquals(1, saveResult.size());

                        Database.SaveResult r = saveResult[0];
                        System.assertEquals(false, r.isSuccess());
                        System.assertEquals(1, r.getErrors().size());
                        System.assertEquals(Label.errMsg_CantCreateClientPlan, r.getErrors()[0].getMessage());
                }
        }

        static testMethod void testSharing() {
                ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();

                //2 accounts
                ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
                Account acc1 = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);
                Account acc2 = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);
            
                //1 user, second one is running user
                ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
                User u1 = userFactory.getExistingUserByProfile('System Administrator');

                //assigning user to account team
                Account_Team_Member__c mem1 = new Account_Team_Member__c();
                mem1.Organisation__c = acc1.Id;
                mem1.Organisation_Access__c = 'Read/Write';
                mem1.Team_Member__c = u1.Id;
                mem1.Team_Role__c = 'Markets';
                INSERT mem1;

                //2 client plans
                Client_Plan__c plan1 = new Client_Plan__c();
                plan1.Relationship__c = acc1.Id;
                Client_Plan__c plan2 = new Client_Plan__c();
                plan2.Relationship__c = acc2.Id;
				
                try {
                        INSERT new List<Client_Plan__c>{plan1, plan2};
                        throw new ZZTEST_ClientPlanTrigger_HelperException();
                } catch(Exception e) {
                        System.assertEquals(true, e instanceof ZZTEST_ClientPlanTrigger_HelperException);
                }

                List<Client_Plan__Share> shareRecs = [
                        SELECT  RowCause, AccessLevel
                        FROM    Client_Plan__Share
                        WHERE   ParentId = :plan1.Id AND UserOrGroupId = :u1.Id
                ];
                System.assertEquals(1, shareRecs.size());

                String userId = UserInfo.getUserId();

                shareRecs = [
                        SELECT  RowCause, AccessLevel
                        FROM    Client_Plan__Share
                        WHERE   ParentId = :plan1.Id AND UserOrGroupId = :userId
                ];
                //1 record for full access (ownership) and 1 for read/write
                System.assertEquals(2, shareRecs.size());

                shareRecs = [
                        SELECT  RowCause, AccessLevel
                        FROM    Client_Plan__Share
                        WHERE   ParentId = :plan2.Id AND UserOrGroupId = :userId
                ];
                //1 record for full access (ownership) and 1 for read/write
                System.assertEquals(2, shareRecs.size());
            
            	shareRecs = [
                        SELECT  RowCause, AccessLevel
                        FROM    Client_Plan__Share
                        WHERE   ParentId = :plan1.Id AND UserOrGroupId = :userId
                        AND RowCause =: Schema.Client_Plan__Share.RowCause.Client_Plan_Manager__c
                ];
                //1 record for current relationship owner
                System.assertEquals(1, shareRecs.size());
            	acc2.OwnerId = u1.Id;
            	UPDATE acc2;
            	shareRecs = [
                        SELECT  RowCause, AccessLevel
                        FROM    Client_Plan__Share
                        WHERE   ParentId = :plan1.Id AND UserOrGroupId = :userId
                        AND RowCause =: Schema.Client_Plan__Share.RowCause.Client_Plan_Manager__c
                ];
                //0 record for previous relationship owner after account owner update
                System.assertEquals(0, shareRecs.size());
        }
}