objects/Acm_Collateral_Status__c.object
<CustomObject>
    <fields>
        <fullName>Collateral_Id__c</fullName>
        <description>Collateral Id</description>
        <inlineHelpText>Collateral Id</inlineHelpText>
        <label>Collateral Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral_Message__c</fullName>
        <label>Collateral Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral_No__c</fullName>
        <label>Collateral No</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral_Owner__c</fullName>
        <label>Collateral Owner</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Was report email sent</description>
        <inlineHelpText>Was report email sent</inlineHelpText>
        <label>Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of collateral</description>
        <inlineHelpText>Status of collateral</inlineHelpText>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hasError__c</fullName>
        <defaultValue>false</defaultValue>
        <label>has Errors</label>
        <type>Checkbox</type>
    </fields>
    <label>Acm Collateral Status</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acm Collateral Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AcmBatchJobUpdate.cls
global class AcmBatchJobUpdate implements Database.Batchable<sObject> {
    
   global Database.QueryLocator start(Database.BatchableContext BC){
     String sendStatus = 'Sent to ACM';
     String query = 'SELECT Id, Collateral_Id__c, hasError__c, Collateral_No__c, Name, Collateral_Owner__c,Collateral_Message__c, Status__c FROM Acm_Collateral_Status__c where (Email_Sent__c = false AND Status__c = :sendStatus) OR hasError__c = true';
     return Database.getQueryLocator(query);
   }
    
   global void execute(Database.BatchableContext info, List<Acm_Collateral_Status__c> AcmCollateralStatuses){
		List<Acm_Collateral_Status__c> AcmCollateralStatusestoUpdate = new List<Acm_Collateral_Status__c>();
       
        for(Acm_Collateral_Status__c acmCollateralStatus : AcmCollateralStatuses) {
            acmCollateralStatus.Email_Sent__c = true;
            AcmCollateralStatusestoUpdate.add(acmCollateralStatus);
        }
        Database.Update(AcmCollateralStatusestoUpdate, false);
   }
    
   global void finish(Database.BatchableContext info) {
   }
}