objects/Acm_Collateral_Status__c.object
<CustomObject>
    <fields>
        <fullName>Collateral_Id__c</fullName>
        <description>Collateral Id</description>
        <inlineHelpText>Collateral Id</inlineHelpText>
        <label>Collateral Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral_Message__c</fullName>
        <label>Collateral Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral_No__c</fullName>
        <label>Collateral No</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral_Owner__c</fullName>
        <label>Collateral Owner</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Acm Collateral Statuses</relationshipLabel>
        <relationshipName>Acm_Collateral_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of collateral</description>
        <inlineHelpText>Status of collateral</inlineHelpText>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Acm Collateral Status</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acm Collateral Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Acm_Facility__c.object
<CustomObject>
    <description>Acm Facility that come from ACM facilities API</description>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry_Date</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Acm Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acm Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Acm_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Acm External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_Description__c</fullName>
        <label>Asset Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Asset_Type__c</fullName>
        <label>Asset Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>True</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Beneficiary__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>set beneficiary</description>
        <inlineHelpText>set beneficiary</inlineHelpText>
        <label>Beneficiary/Borrower</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Collateral (Account)</relationshipLabel>
        <relationshipName>Collateral1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Collateral Group</label>
        <referenceTo>Collateral_Group__c</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral_No__c</fullName>
        <displayFormat>C-{000000}</displayFormat>
        <label>Collateral No</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Collateral_Type1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Collateral Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Collateral_Type__c.Collateral_Group__c</field>
                <operation>equals</operation>
                <valueField>$Source.Collateral_Group__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Collateral_Type__c</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Collateral Country</description>
        <inlineHelpText>Collateral Country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Description__c</fullName>
        <label>Document Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Expiry_Date__c</fullName>
        <label>Document Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <inlineHelpText>Specifies the Collateral Expiry date</inlineHelpText>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Collaterals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Physical_Location__c</fullName>
        <description>Physical Location where collateral is stored.</description>
        <inlineHelpText>Physical Location where collateral is stored.</inlineHelpText>
        <label>Physical Location of Documentation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Saved_To_Acm__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Variable used to indicate whether collateral was saved to ACM</description>
        <inlineHelpText>check box used to indicate whether collateral was saved to ACM</inlineHelpText>
        <label>Saved To Acm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beneficiary</fullName>
                    <label>Beneficiary/Borrower</label>
                </value>
                <value>
                    <fullName>Facility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Signature_Date__c</fullName>
        <inlineHelpText>Signature date of the Collateral</inlineHelpText>
        <label>Signature Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Outstanding</fullName>
                    <default>true</default>
                    <label>Outstanding</label>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value_Limit__c</fullName>
        <label>Value Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_Type__c</fullName>
        <label>Value Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Limited</fullName>
                </value>
                <value>
                    <fullName>Unlimited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <inlineHelpText>Collateral Value</inlineHelpText>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral_Facility__c.object
<CustomObject>
    <fields>
        <fullName>Acm_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Acm External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipName>Collateral_Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saved_To_Acm__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if collateral facility was saved to acm</description>
        <inlineHelpText>Check if collateral facility was saved to acm</inlineHelpText>
        <label>Saved To Acm</label>
        <type>Checkbox</type>
    </fields>
    <label>Collateral Facility</label>
    <nameField>
        <displayFormat>CF-{00000}</displayFormat>
        <label>Collateral Facility #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral_Group__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Code__c</fullName>
        <externalId>true</externalId>
        <label>Credit Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Collateral Group</label>
    <nameField>
        <label>Collateral Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral_Monitoring__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <fields>
        <fullName>Collateral__c</fullName>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Collateral Monitoring</relationshipLabel>
        <relationshipName>Collateral_Monitoring</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Signature_Date__c</fullName>
        <formula>IF( Agreement__c != null, Agreement__r.Signature_Date__c , Collateral__r.Signature_Date__c)</formula>
        <label>Signature Date</label>
        <type>Date</type>
    </fields>
    <label>Collateral Monitoring</label>
    <nameField>
        <label>Collateral Monitoring Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Monitoring</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Collateral_Relationship__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <fields>
        <fullName>Acm_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Acm External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Collateral Relationship</relationshipLabel>
        <relationshipName>Collateral_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collateral Relationship</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collateral Relationship #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral_Type__c.object
<CustomObject>
    <fields>
        <fullName>Collateral_Group__c</fullName>
        <label>Collateral Group</label>
        <referenceTo>Collateral_Group__c</referenceTo>
        <relationshipLabel>Collateral Types</relationshipLabel>
        <relationshipName>Collateral_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Code__c</fullName>
        <externalId>true</externalId>
        <label>Credit Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Collateral Type</label>
    <nameField>
        <label>Collateral Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Abu Dhabi Global Market</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

classes/Acm_service.cls
global class Acm_service {
    Map<String, String> headers = new Map<String, String>();
    webservice static String callservice(List<String> acmIds)
    {
        Set<String> Ids = new Set<String>();
        for(String id : acmIds){
            Ids.add(id);
        }
        MakeCall(Ids);
        return 'Updating/Creating Collateral from soap:' ;
    }
    
    public static void MakeCall(set<String> Ids) {
        List<Id> collateralIds = new List<Id>();
        List<Id> statusIds = new List<Id>();
        for(String acmId : Ids) {
            collateralIds.add(Id.valueOf(acmId.split('-')[1]));
            statusIds.add(Id.valueOf(acmId.split('-')[0]));
        }
        
        List<Acm_Collateral_Status__c> AcmStatuses = [SELECT Id, Collateral_No__c, Name, Collateral_Id__c,Collateral_Message__c, Collateral_Owner__c,Status__c FROM Acm_Collateral_Status__c where Id IN:statusIds];
        List<Collateral__c> collaterals = [SELECT Id,Acm_External_Id__c, Name, OwnerId, Collateral_Group__c,Collateral_Group__r.Credit_Code__c, Scope__c, Saved_To_Acm__c, Beneficiary__c, Account__c, CurrencyIsoCode, Collateral_Type1__c,Collateral_Type1__r.Credit_Code__c,Expiry_Date__c, Country__c, Signature_Date__c, Physical_Location__c,
                                    Status__c, Comments__c, Asset_Description__c, Value__c, Value_Type__c, Value_Limit__c, Asset__c,
                                    Asset_Type__c, Collateral_No__c, Document_Type__c, Document_Name__c, Document_Expiry_Date__c, Manager__c,
                                    Document_Description__c, Document_Status__c, Supporting_Documentation_Uploaded__c, 
                                    Has_Underlying_Assets__c FROM Collateral__c WHERE Id IN: collateralIds];
            
        List<Collateral_Relationship__c> collateralRelationships =  [SELECT Collateral__c,Relationship__c,isPrimaryRelationship__c,Collateral_Type__c,Active__c, Relationship_Type__c,relationship__r.SDS__c FROM Collateral_Relationship__c where Collateral__c IN: collateralIds];
        List<Collateral_Facility__c> collateralFacilities = [SELECT Collateral__c, Saved_To_Acm__c,Active__c, Facility_Client__c, Acm_Facility__c,Acm_Facility__r.Facility_Id__c, Acm_Facility__r.Bank_Application_key__c FROM Collateral_Facility__c where Collateral__c IN :collateralIds];
        List<Collateral_Monitoring__c> collateralMonitorings = AcmMitigantCRUDService.getAllMonitoringsForCollateral(collateralIds);

        CallAcm(AcmStatuses, collaterals,collateralRelationships,collateralFacilities,collateralMonitorings);   
    }
    
    public static void CallAcm(List<Acm_Collateral_Status__c> AcmStatuses, List<Collateral__c> collaterals,List<Collateral_Relationship__c> collateralRelationships,List<Collateral_Facility__c> collateralFacilities,List<Collateral_Monitoring__c> collateralMonitorings) {
        AcmMitigantCRUDService.createOrUpdateMitigantsList(AcmStatuses, collaterals, collateralRelationships, collateralFacilities,collateralMonitorings);
    }
}