objects/ACMFacility__c.object
<CustomObject>
    <description>Holds all the facilities that come out of ACM linked to a client plan</description>
    <label>ACM Facility</label>
    <nameField>
        <label>ACM Facility ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACM Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcmIntegration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This list contains all details needed for connecting to ACM</description>
    <fields>
        <fullName>POST_URL__c</fullName>
        <description>Used to set the URL to perform post request on via api manager</description>
        <inlineHelpText>set the URL to perform post request on via api manager</inlineHelpText>
        <label>MITIGANT DATA BOX POST URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>AcmIntegration</label>
</CustomObject>

objects/Collateral__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <fields>
        <fullName>ACMFacility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACMFacility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACMFacility__c.Relationship__c</field>
                <operation>equals</operation>
                <valueField>$Source.Facility_Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACMFacility__c</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Beneficiary__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>set beneficiary</description>
        <inlineHelpText>set beneficiary</inlineHelpText>
        <label>Beneficiary/Borrower</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Collateral (Account)</relationshipLabel>
        <relationshipName>Collateral1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Collateral Group</label>
        <referenceTo>Collateral_Group__c</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral_Type1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Collateral Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Collateral_Type__c.Collateral_Group__c</field>
                <operation>equals</operation>
                <valueField>$Source.Collateral_Group__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Collateral_Type__c</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facillity Beneficiary</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Collateral (Account)</relationshipLabel>
        <relationshipName>Collateral_Facility_Client</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beneficiary</fullName>
                    <label>Beneficiary/Borrower</label>
                </value>
                <value>
                    <fullName>Facility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Outstanding</fullName>
                    <default>true</default>
                    <label>Outstanding</label>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_Documentation_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Supporting Documentation Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value_Type__c</fullName>
        <label>Value Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Limited</fullName>
                </value>
                <value>
                    <fullName>Unlimited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <inlineHelpText>Collateral Value</inlineHelpText>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral_Group__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Code__c</fullName>
        <externalId>true</externalId>
        <label>Credit Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Collateral Group</label>
    <nameField>
        <label>Collateral Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral_Relationship__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Collateral Relationship</relationshipLabel>
        <relationshipName>Collateral_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isPrimaryRelationship__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPrimaryRelationship</label>
        <type>Checkbox</type>
    </fields>
    <label>Collateral Relationship</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collateral Relationship #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CollateralControllerExtension_test.cls
@isTest
public class CollateralControllerExtension_test {
    
    public static testmethod void TestControllerSave() {

        Test.startTest();

       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(AcmCollateralTestData.TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();

        Test.stopTest();
    }
    
    public static testmethod void TestControllerWithNullSDSId() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        Collateral__c collateral = AcmCollateralTestData.TestCollateral;
        collateral.Beneficiary__c = AcmCollateralTestData.TestAccountWithoutSDS.Id;
        ApexPages.StandardController collateralController = new ApexPages.StandardController(collateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();

        Test.stopTest();
    }
    
    public static testmethod void TestControllerSaveWithFacilityScope() {

        Test.startTest();

       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(acmCollateralTestData.TestCollateralFacilityScope);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();

        Test.stopTest();
    }
    
    public static testmethod void TestControllerGetCollateralGroups() { 

        Test.startTest();

       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(acmCollateralTestData.TestCollateralFacilityScope);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.getCollateralGroups();

        Test.stopTest();
    }
    
    public static testmethod void TestControllerGetCollateralTypes() {
         Test.startTest();

       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(acmCollateralTestData.TestCollateralFacilityScope);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.getCollateralTypes();
        
        Test.stopTest();
    }
    
    public static testmethod void TestControllerWithUnSavedCollateralAndCallWebservice() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(acmCollateralTestData.TestCollateralUnsaved);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
        Test.stopTest();
    }
    
    public static testmethod void TestControllerCancel() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(acmCollateralTestData.TestCollateralUnsaved);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.Cancel();
        Test.stopTest();
    }
    
    public static testmethod void TestControllerWithUnSavedErroneousCollateral() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        Collateral__c TestCollateralUnsavedErroneous = acmCollateralTestData.TestCollateralUnsaved;
        TestCollateralUnsavedErroneous.Beneficiary__c = null;
        TestCollateralUnsavedErroneous.Scope__c = 'Beneficiary';       
        ApexPages.StandardController collateralController = new ApexPages.StandardController(TestCollateralUnsavedErroneous);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
        Test.stopTest();
    }
    
    
	public static testmethod void TestControllerSaveNew() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(acmCollateralTestData.TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.saveNew();
        Test.stopTest();
    }
    
   public static testmethod void TestControllerCallWebsrvice() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(acmCollateralTestData.TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
       Test.stopTest();
    }
    
   public static testmethod void TestControllerGetAndCreateFacilities() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(acmCollateralTestData.TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.GetAndCreateFacilities();
        Test.stopTest();
    }
    
   public static testmethod void TestControllerValidationOptions() {
		Test.startTest();
    
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        Collateral__c TestCollateral = acmCollateralTestData.TestCollateralUnsaved;
        // When collateral Type does not match collateral Group
        Collateral_Group__c TestCollateralGroupUnMatch = new Collateral_Group__c
            (
                Name = 'AVIATION BOND',
                Credit_Code__c = 'AVIATION_BOND'
            );
        Insert TestCollateralGroupUnMatch;
        TestCollateral.Collateral_Group__c =  TestCollateralGroupUnMatch.Id;
        ApexPages.StandardController collateralController = new ApexPages.StandardController(TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
       
        // When collateral Type is null
        TestCollateral.Collateral_Type1__c = null;
        collateralController = new ApexPages.StandardController(TestCollateral);
        collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();

       //When released with no supporting docs
        TestCollateral.Supporting_Documentation_Uploaded__c = false;
        TestCollateral.Status__c = 'Released';
        collateralController = new ApexPages.StandardController(TestCollateral);
        collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
       

       //When Facility does not match facility beneficiary
        Collateral__c testCollateralFacilityScope = acmCollateralTestData.TestCollateralFacilityScope;
        testCollateralFacilityScope.Facility_Client__c = acmCollateralTestData.TestAccountWithoutSDS.Id;
 		collateralController = new ApexPages.StandardController(testCollateralFacilityScope);
        collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
       
        //When Value type is limited but value is null
        testCollateralFacilityScope = acmCollateralTestData.TestCollateralFacilityScope;
        testCollateralFacilityScope.Value_Type__c = 'Limited';
        testCollateralFacilityScope.Value__c = null;
 		collateralController = new ApexPages.StandardController(testCollateralFacilityScope);
        collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
       
       // When provider has null SDS
        testCollateralFacilityScope = acmCollateralTestData.TestCollateralFacilityScope;
        testCollateralFacilityScope.Account__c = acmCollateralTestData.TestAccountWithoutSDS.Id;
 		collateralController = new ApexPages.StandardController(testCollateralFacilityScope);
        collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();

        Test.stopTest();
   }
    
     public static testmethod void TestControllerValidationOtherOptions() {
       	Test.startTest();
        AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        Collateral__c TestCollateral = acmCollateralTestData.TestCollateralUnsaved;
        // When providers change
        TestCollateral = acmCollateralTestData.TestCollateral;
 		ApexPages.StandardController collateralController = new ApexPages.StandardController(TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        TestCollateral.Account__c = acmCollateralTestData.TestAccountChanged.Id;
        collateralControllerExtension.save();
       
        // When beneficiaries change
        TestCollateral = acmCollateralTestData.TestCollateral;
 		collateralController = new ApexPages.StandardController(TestCollateral);
        collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        TestCollateral.Beneficiary__c = acmCollateralTestData.TestAccountChanged.Id;
        collateralControllerExtension.save();
        Test.stopTest();
     }
    
    public static testmethod void TestControllerValidationFacilityChange() {
        // When facilities change
        Test.startTest();
        AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        Collateral__c TestCollateral = acmCollateralTestData.TestCollateralUnsaved;
        Collateral__c testCollateralFacilityScope = acmCollateralTestData.TestCollateralFacilityScopeWithoutFacility;
        
 		ApexPages.StandardController collateralController = new ApexPages.StandardController(testCollateralFacilityScope);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        testCollateralFacilityScope.AcmFacility__c = acmCollateralTestData.TestAcmFacilityChange.Id;
        collateralControllerExtension.save();
        Test.stopTest();
    }
    
    public static testmethod void TestControllerValidationOptionsStatusFiveHundred() {
        Test.startTest();
        AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        Collateral__c TestCollateral = acmCollateralTestData.TestCollateralUnsaved;
        ApexPages.StandardController collateralController = new ApexPages.StandardController(TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        
        AcmIntegration__c status500 = acmCollateralTestData.TestAcmIntegration;
        status500.POST_URL__c = 'http:\\test.url\FiveHundred';
        update status500;
        Test.setMock(HttpCalloutMock.class, new AcmCollateralTestData.MockHttpResponseGenerator());
        collateralController = new ApexPages.StandardController(AcmCollateralTestData.testCollateralFacilityScope);
        collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
   
        collateralControllerExtension.CallWebService();
        Test.stopTest();
    }
    
    public static testmethod void TestControllerValidationOptionsStatusFourHundred() {
        Test.startTest();
        AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        Collateral__c TestCollateral = acmCollateralTestData.TestCollateralUnsaved;
        ApexPages.StandardController collateralController = new ApexPages.StandardController(TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        
        // When status is 400
        AcmIntegration__c status400 = acmCollateralTestData.TestAcmIntegration;
        status400.POST_URL__c = 'http:\\test.url\FourHundred';
        update status400;
        Test.setMock(HttpCalloutMock.class, new AcmCollateralTestData.MockHttpResponseGenerator());
        collateralController = new ApexPages.StandardController(AcmCollateralTestData.testCollateralFacilityScope);
        collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();

        collateralControllerExtension.CallWebService();
        Test.stopTest();
    }
    
   public static testmethod void TestAcmCollateralTriggerAfter() {
        Test.startTest(); 
        AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        Collateral__c TestCollateralOne = acmCollateralTestData.TestCollateralUnsaved;
        Collateral__c TestCollateralTwo = acmCollateralTestData.TestCollateralUnsavedBenef;
        List<Collateral__c> collateralInserts  = new List<Collateral__c>();
        collateralInserts.add(TestCollateralOne);
       	collateralInserts.add(TestCollateralTwo);
        Insert collateralInserts;
       
        update collateralInserts;
        Test.stopTest();
    }
    
    public static testmethod void TestControllerCallWebsrviceScopeChange() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        ApexPages.StandardController collateralController = new ApexPages.StandardController(acmCollateralTestData.TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
       Test.stopTest();
    }
    
    public static testmethod void TestControllerWithUnSavedErroneousCollateralScopeFac() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();
        Collateral__c TestCollateral = new Collateral__c
            (
                Scope__c = 'Beneficiary',
                Name = 'Collateral Test',
                Status__c = 'Outstanding',
                Account__c = acmCollateralTestData.TestAccount.Id,
                Beneficiary__c = acmCollateralTestData.TestAccount.Id,
                Collateral_Group__c = acmCollateralTestData.TestCollateralGroup.Id,
                Collateral_Type1__c = acmCollateralTestData.TestCollateralType.Id
            );     
        ApexPages.StandardController collateralController = new ApexPages.StandardController(TestCollateral);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
        Test.stopTest();
    }
    
    public static testmethod void TestControllerCollateralChangeScope() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();   
        Collateral__c Cl = acmCollateralTestData.TestCollateral;
        CL.Scope__c = 'Facility';
        CL.Facility_Client__c = acmCollateralTestData.TestAccount.Id;
        CL.ACMFacility__c = acmCollateralTestData.TestAcmFacility.Id;
        update CL;
        ApexPages.StandardController collateralController = new ApexPages.StandardController(Cl);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
        Test.stopTest();
    }
    
    public static testmethod void TestControllerCollateralChangeScopeBen() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();   
        Collateral__c Cl = acmCollateralTestData.TestCollateralFacilityScope;
        CL.Scope__c = 'Beneficiary';
        CL.Beneficiary__c = acmCollateralTestData.TestAccountChanged.Id;
        update CL;
        ApexPages.StandardController collateralController = new ApexPages.StandardController(Cl);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
        Test.stopTest();
    }
    
    public static testmethod void TestControllerCollateralChangeScopeBenActive() {
        Test.startTest();
       	AcmCollateralTestData acmCollateralTestData = new AcmCollateralTestData();   
        Collateral__c Cl = acmCollateralTestData.TestCollateral;
        Collateral_Relationship__c Cr = acmCollateralTestData.TestCollateralRelationshipBeneficiary;
        cr.Active__c = true;  
        cr.isPrimaryRelationship__c = true;
        update Cr;
            
        ApexPages.StandardController collateralController = new ApexPages.StandardController(Cl);
        CollateralControllerExtension collateralControllerExtension = new CollateralControllerExtension(collateralController);
        collateralControllerExtension.save();
        collateralControllerExtension.CallWebService();
        Test.stopTest();
    }
}