objects/ACMFacility__c.object
<CustomObject>
    <description>Holds all the facilities that come out of ACM linked to a client plan</description>
    <fields>
        <fullName>EXPIRYDATE__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FACILITYAMOUNT__c</fullName>
        <label>Facility Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FACILITYCURRENCY__c</fullName>
        <label>Facility Currency</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STARTDATE__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>ACM Facility</label>
    <nameField>
        <label>ACM Facility ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACM Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Availability__c</fullName>
        <description>Field used to calculate the Period of a Deal</description>
        <label>Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Month(s)</fullName>
                </value>
                <value>
                    <fullName>Year(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>advpm__Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matters</relationshipLabel>
        <relationshipName>Matters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facility_Limit__c</fullName>
        <description>Facility limit to determine each Lender&apos;s portion</description>
        <label>Facility Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <description>Facility limit to determine each Lender&apos;s portion</description>
        <label>Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Facility__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>ACMFacility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACMFacility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Agreement_Account__c</field>
                <operation>equals</operation>
                <valueField>ACMFacility__c.Relationship__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACMFacility__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Availability_Start_Date__c</fullName>
        <label>Availability Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Day(s)</fullName>
                </value>
                <value>
                    <fullName>Month(s)</fullName>
                </value>
                <value>
                    <fullName>Year(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facility_Limit__c</fullName>
        <label>Facility Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FacilityControllerExtension.cls
/**

*** CHANGE LOG ***

31/10/2017 - Patrick Pheme   		- Created Class. 
09/11/2017 - TdB   					- API Name change. Facility_Limit__c  to Limit__c on Agreements Object
27/02/2018 - TdB					- Add additional catch error messages based on Agreement Validation Rules

**/ 

public class FacilityControllerExtension {
    public Facility__c facility;
    public List<Agreement__c> agreements;
    
    public FacilityControllerExtension(ApexPages.StandardController stdController) {
        this.facility = (Facility__c)stdController.getRecord();        
        agreements = [SELECT Matter_Deal__c, Limit__c FROM  Agreement__c WHERE id = :facility.Agreement__c];
        if(facility.Agreement_Account__c == null) {
            if(agreements.size() > 0 ) {
                List<advpm__Matter__c> matters = [SELECT  advpm__Primary_Account__c FROM  advpm__Matter__c WHERE id =:  (agreements.get(0)).Matter_Deal__c];
                if(matters.size() > 0) {
                    System.debug('facility is : ' + matters.get(0));
                    facility.Agreement_Account__c = (matters.get(0)).advpm__Primary_Account__c;
                }
            }
        }
    }
    
    public PageReference save() {
        
        Map<Id,Decimal> agreementFacilityLimit = new  Map<Id,Decimal>();
        Map<Id,Decimal> agreementLimit = new  Map<Id,Decimal>();
        Decimal facilityLimitTotal_temp = 0.00;
        Decimal facilityLimit_temp = 0.00;
        Decimal agreementLimit_temp = 0.00;
        
        PageReference redirectSuccess = null;
        
        try {

            if(facility.Availability__c == null) {
                facility.Availability__c = '';
            }
            upsert facility;
            redirectSuccess = new ApexPages.StandardController(facility).view();
        } catch(Exception e) {
            redirectSuccess = null;
            System.debug('Exception caught : ' + e.getMessage());
            if(e.getMessage().contains('The Total Facility Limit cannot exceed the Agreement Limit'))
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The Total Facility Limit cannot exceed the Agreement Limit')); 
            }
            else if (e.getMessage().contains('The total facility amount of all parties cannot exceed the facility limit'))
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The total facility amount of all parties cannot exceed the facility limit')); 
            }
            else if (e.getMessage().contains('Please ensure that the Agreement Limit is not exceeded'))
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please ensure that the Agreement Limit is not exceeded')); 
            }
            else
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage())); 
            }
            
        }
        return redirectSuccess;
    }
    
    public void GetFacility() {
        String facilityMessage = AcmControllerLogic.ReadCreateCollateralAcmFacilities(facility.Agreement_Account__c);
        if(facilityMessage != ''){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, facilityMessage));   
        }
    }
    
    public PageReference UpdateFacilityFields() {
        List<AcmFacility__c> acmFacilities = [SELECT STARTDATE__c, EXPIRYDATE__c, FACILITYCURRENCY__c, FACILITYAMOUNT__c FROM AcmFacility__c where id =: facility.AcmFacility__c];
        if(acmFacilities.size() > 0) {
            AcmFacility__c acmFacility = acmFacilities.get(0);
            facility.Facility_Limit__c = acmFacility.FACILITYAMOUNT__c;
            facility.CurrencyIsoCode = acmFacility.FACILITYCURRENCY__c;
            if(acmFacility.STARTDATE__c != null) {
                facility.Availability_Start_Date__c = acmFacility.STARTDATE__c;
            }
            
            if(acmFacility.EXPIRYDATE__c != null) {
                facility.Expiry_Date__c = acmFacility.EXPIRYDATE__c;
            }
        }
        return null; 
    }
}