objects/ACMFacility__c.object
<CustomObject>
    <description>Holds all the facilities that come out of ACM linked to a client plan</description>
    <fields>
        <fullName>Facility_Id__c</fullName>
        <label>Facility Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ACM Facility</label>
    <nameField>
        <label>ACM Facility ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACM Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <fields>
        <fullName>ACMFacility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACMFacility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACMFacility__c.Relationship__c</field>
                <operation>equals</operation>
                <valueField>$Source.Facility_Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACMFacility__c</referenceTo>
        <relationshipLabel>Collateral</relationshipLabel>
        <relationshipName>Collateral</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facillity Beneficiary</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Collateral (Account)</relationshipLabel>
        <relationshipName>Collateral_Facility_Client</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Scope</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beneficiary</fullName>
                    <label>Beneficiary/Borrower</label>
                </value>
                <value>
                    <fullName>Facility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral_Facility__c.object
<CustomObject>
    <fields>
        <fullName>ACMFacility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACMFacility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACMFacility__c.Relationship__c</field>
                <operation>equals</operation>
                <valueField>$Source.Facility_Client__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACMFacility__c</referenceTo>
        <relationshipLabel>Collateral Facilities</relationshipLabel>
        <relationshipName>Collateral_Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipName>Collateral_Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility Beneficiary</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Collateral Facilities</relationshipLabel>
        <relationshipName>Collateral_Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Id__c</fullName>
        <formula>ACMFacility__r.Facility_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Facility Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isPrimaryRelationship__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPrimaryRelationship</label>
        <type>Checkbox</type>
    </fields>
    <label>Collateral Facility</label>
    <nameField>
        <displayFormat>CF-{00000}</displayFormat>
        <label>Collateral Facility #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CollateralFacilityExtension.cls
public class CollateralFacilityExtension {
    private Collateral_Facility__c collateralFacility;
    public String facilityMessage { get; set; }
    private ApexPages.StandardController sController;
    private String errorMessage {get ; set; }
    private boolean providerError = false;
    private Collateral__c collateral;
    
    public CollateralFacilityExtension(ApexPages.StandardController stdController) {
        sController = stdController;
        if (!Test.isRunningTest())stdController.addFields(new List<String>{'Facility_Id__c','isPrimaryRelationship__c', 'Collateral__c'});
        this.collateralFacility = (Collateral_Facility__c)stdController.getRecord();
        collateral = AcmMitigantCRUDService.getCollateralFromId(collateralFacility.Collateral__c);
        if(getAccount() != null) {
            collateralFacility.Facility_Client__c = getAccount().Id;
        }
        
        if(collateral.Scope__c != 'Facility') {
         	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Cannot create/edit facility on Collateral with scope : ' + collateral.Scope__c));
        }
    }
    
    public PageReference save() {
        PageReference redirectSuccess = null;
        try {
            
            errorMessage = '';

            List<Collateral_Facility__c> collateralFacs =  new List<Collateral_Facility__c>();
            List<AcmFacility__c> acmFacilities = [SELECT Facility_Id__c FROM AcmFacility__c WHERE Id =:collateralFacility.AcmFacility__c];
            System.debug('Acm fac : ' + acmFacilities);
            if(acmFacilities.size() > 0) {
                AcmFacility__c acmFacility = acmFacilities.get(0);
                if(acmFacility.Facility_Id__c != '' || acmFacility.Facility_Id__c != null  ) {
                    String vv = acmFacility.Facility_Id__c;
                    String hwh = String.valueOf(collateralFacility.Collateral__c);
                    collateralFacs = [SELECT Id, Name, Collateral__c  FROM Collateral_Facility__c where Facility_Id__c =:vv AND collateral__c =:hwh];
                }
            }
			System.debug('Collateral Fac : ' + collateralFacs);
            System.debug('Collateral Fac null : ' + collateralFacility.Id);
            if(collateralFacs.size() >= 2) {
                    errorMessage = 'AllowedProduct/Facility relationship already exists';
                    providerError = true;
            } else if(collateralFacs.size() == 1) {
                if(collateralFacility.Id == null) {
                    errorMessage = 'AllowedProduct/ Facility relationship already exists';
                    providerError = true;
                }
            }
            
            if(collateral.Scope__c != 'Facility') {
         		errorMessage = 'Cannot create facility on Collateral with scope : ' + collateral.Scope__c ;
                providerError = true;
        	} else if(collateralFacility.isPrimaryRelationship__c) {
                errorMessage = 'Cannot update primary Facility on this page, Please edit on collateral';
                providerError = true;
            } 
            
            if(collateralFacility.AcmFacility__c == null) {
                errorMessage = 'Facility is required';
                providerError = true;  
            } else if(!providerError) {
                upsert(collateralFacility);
            }
        } catch(Exception e) {
            errorMessage = e.getMessage();
            System.debug('Exception thrown stuff : ' + errorMessage);
            redirectSuccess = null;
        }
        return redirectSuccess;
    }
    
    public PageReference getAndCreateFacilities() {
        try	{
            facilityMessage = AcmControllerLogic.ReadCreateCollateralAcmFacilities(collateralFacility.Facility_Client__c);
        } catch(Exception e) {
            facilityMessage = 'Empty Response from server';
        }
        
        if(facilityMessage != '') {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, facilityMessage));   
        }
        return null; 
    } 
    
    public Account getAccount() {
        List<Collateral__c> collaterals = [SELECT Facility_Client__c FROM Collateral__c where Id = :collateralFacility.Collateral__c];
        if(collaterals.size() > 0) {
            Collateral__c collateral = collaterals.get(0);
            List <Account> accounts = [SELECT Id, Name FROM Account where Id = :collateral.Facility_Client__c];
            if(accounts.size() > 0) {
                return accounts.get(0);
            }
        }
        return null;
    }
    
    public PageReference callWebService() {
        PageReference redirectSuccess = null;
        PageReferenceMessage pageReferenceMessage = new PageReferenceMessage();
        if(errorMessage == '') {
            pageReferenceMessage = AcmControllerLogic.saveToACM(sController, collateral, false, errorMessage);
            if(pageReferenceMessage.message == 'Mitigant successfully created/update') {
                pageReferenceMessage.redirectSuccess = AcmControllerLogic.redirect(sController, false, collateral);
            } else if(pageReferenceMessage.message == 'Not Saving to ACM') {
                redirectSuccess = pageReferenceMessage.redirectSuccess;
            } else {
                System.debug('Message from service : ' + pageReferenceMessage.message);
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, pageReferenceMessage.message));
                return null; 
            }
        } else {
            String message = '';
            if(providerError) {
                message = errorMessage;
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));  
            return null;
        }
        redirectSuccess = new ApexPages.StandardController(collateralFacility).view();
        return redirectSuccess;
    }
}