objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GMRA Agreement</fullName>
                </value>
                <value>
                    <fullName>GMSLA Agreement</fullName>
                </value>
                <value>
                    <fullName>ISDA Agreement</fullName>
                </value>
                <value>
                    <fullName>Prime Services Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Transaction Relationship</relationshipLabel>
        <relationshipName>Matters_Deals2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agreement_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.TMG_Product_Level_3__c</field>
                <operation>equals</operation>
                <valueField>Product_Agreement__c.TMG_Product_Level_3__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product_Agreement__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_of_Issue__c</fullName>
        <label>Country of Issue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_Agreement_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <formula>Matter_Deal__r.Relationship__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship</label>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Market_Collateral__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Market Collaterals</relationshipLabel>
        <relationshipName>Market_Collaterals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicable_Party__c</fullName>
        <label>Applicable Party</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Counterparty</fullName>
                    <default>true</default>
                    <label>Counterparty</label>
                </value>
                <value>
                    <fullName>Absa</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_Comments__c</fullName>
        <label>Collateral Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Collateral_Type__c</fullName>
        <label>Collateral Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Bonds</fullName>
                </value>
                <value>
                    <fullName>Equities</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Securities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_of_Issue__c</fullName>
        <label>Country of Issue</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Collateral_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Collateral_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Market_Collateral_Type__c</fullName>
        <label>Market Collateral Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible Collateral</fullName>
                </value>
                <value>
                    <fullName>Regulatory Collateral</fullName>
                </value>
                <value>
                    <fullName>Acceptable Collateral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Collateral_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Certified Securities</fullName>
                </value>
                <value>
                    <fullName>Uncertified Debt Securities</fullName>
                </value>
                <value>
                    <fullName>Uncertified Equities</fullName>
                </value>
                <value>
                    <fullName>Certified Equities</fullName>
                </value>
                <value>
                    <fullName>Maturity at issuance &lt; 1 year</fullName>
                </value>
                <value>
                    <fullName>Maturity at issuance &gt;1 year but &lt;10 years</fullName>
                </value>
                <value>
                    <fullName>Maturity at issuance &gt; 10 years</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supporting Agreement</label>
        <referenceTo>Supporting_Agreement__c</referenceTo>
        <relationshipLabel>Market Collaterals</relationshipLabel>
        <relationshipName>Market_Collaterals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Collateral</label>
    <nameField>
        <displayFormat>MC-{00000}</displayFormat>
        <label>Market Collateral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NettingGroupBranch__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Netting Group Branches</relationshipLabel>
        <relationshipName>Netting_Group_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trade_Instrument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade Instrument</label>
        <referenceTo>Trade_Instrument__c</referenceTo>
        <relationshipLabel>Netting Group Branches</relationshipLabel>
        <relationshipName>Netting_Group_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Netting Group Branch</label>
    <nameField>
        <displayFormat>NGB-{0000}</displayFormat>
        <label>Netting Group Branch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Netting Group Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Supporting_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Supporting Agreements</relationshipLabel>
        <relationshipName>Supporting_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral_type__c</fullName>
        <label>Bilateral / Unilateral</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collateral</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GMRA Agreement</fullName>
                </value>
                <value>
                    <fullName>GMSLA Agreement</fullName>
                </value>
                <value>
                    <fullName>ISDA Agreement</fullName>
                </value>
                <value>
                    <fullName>Prime Services Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supporting Agreement</label>
    <nameField>
        <displayFormat>SA-{0}</displayFormat>
        <label>Supporting Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supporting Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trade_Instrument__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <label>Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GMRA Agreement</fullName>
                </value>
                <value>
                    <fullName>GMSLA Agreement</fullName>
                </value>
                <value>
                    <fullName>ISDA Agreement</fullName>
                </value>
                <value>
                    <fullName>Prime Services Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Asset_Class__c</fullName>
        <label>Asset Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commodity</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Equity</fullName>
                </value>
                <value>
                    <fullName>Fixed Income</fullName>
                </value>
                <value>
                    <fullName>Foreign Exchange</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trade_Instrument_ID__c</fullName>
        <externalId>true</externalId>
        <label>Trade Instrument ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trade Instrument</label>
    <nameField>
        <label>Trade Instrument Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Instruments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Agreement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Awaiting Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Executed</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Send to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed/Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Amended</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled/Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Superceded</fullName>
        <isActive>false</isActive>
        <label>Superceded</label>
    </customValue>
    <description>Agreement Management (LEAP)</description>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

globalValueSets/Collateral.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bilateral</fullName>
    </customValue>
    <customValue>
        <fullName>Unilateral (Counterparty)</fullName>
    </customValue>
    <customValue>
        <fullName>Unilateral (Own)</fullName>
    </customValue>
    <masterLabel>Collateral</masterLabel>
</GlobalValueSet>

globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Abu Dhabi Global Market</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

globalValueSets/Currency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AED - UAE Dirham</fullName>
    </customValue>
    <customValue>
        <fullName>AFN - Afghanistan Afghani (New)</fullName>
    </customValue>
    <customValue>
        <fullName>ALL - Albanian Lek</fullName>
    </customValue>
    <customValue>
        <fullName>AMD - Armenian Dram</fullName>
    </customValue>
    <customValue>
        <fullName>ANG - Neth Antilles Guilder</fullName>
    </customValue>
    <customValue>
        <fullName>AOA - Angola Kwanza</fullName>
    </customValue>
    <customValue>
        <fullName>ARS - Argentine Peso</fullName>
    </customValue>
    <customValue>
        <fullName>AUD - Australian Dollar</fullName>
    </customValue>
    <customValue>
        <fullName>AWG - Aruba Florin</fullName>
    </customValue>
    <customValue>
        <fullName>AZN - Azerbaijanian New Manat</fullName>
    </customValue>
    <customValue>
        <fullName>BAM - Convertible Marks</fullName>
    </customValue>
    <customValue>
        <fullName>BBD - Barbados Dollar</fullName>
    </customValue>
    <customValue>
        <fullName>BDT - Bangladesh Taka</fullName>
    </customValue>
    <customValue>
        <fullName>BGN - Bulgaria Lev</fullName>
    </customValue>
    <customValue>
        <fullName>BHD - Bahraini Dinar</fullName>
    </customValue>
    <customValue>
        <fullName>BIF - Burundi Franc</fullName>
    </customValue>
    <customValue>
        <fullName>BMD - Bermuda Dollar</fullName>
    </customValue>
    <customValue>
        <fullName>BND - Brunei Dollar</fullName>
    </customValue>
    <customValue>
        <fullName>BOB - Bolivian Boliviano</fullName>
    </customValue>
    <customValue>
        <fullName>BOV - Bolivia Mvdol</fullName>
    </customValue>
    <customValue>
        <fullName>BRB - Brazilian Cruzeiro (old)</fullName>
    </customValue>
    <customValue>
        <fullName>BRL - Brazilian Real</fullName>
    </customValue>
    <customValue>
        <fullName>BSD - Bahamian Dollar</fullName>
    </customValue>
    <customValue>
        <fullName>BTN - Bhutan Ngultrum</fullName>
    </customValue>
    <customValue>
        <fullName>BWP - Botswana Pula</fullName>
    </customValue>
    <customValue>
        <fullName>BYN - Belarussian Ruble</fullName>
    </customValue>
    <customValue>
        <fullName>BZD - Belize Dollar</fullName>
    </customValue>
    <customValue>
        <fullName>CAD - Canadian Dollar</fullName>
    </customValue>
    <customValue>
        <fullName>CDF - Franc Congolais</fullName>
    </customValue>
    <customValue>
        <fullName>CHF - Swiss Franc</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

globalValueSets/Master_Agreement_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>GMRA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>GMSLA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>ISDA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Prime Services Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Supporting Agreement</fullName>
    </customValue>
    <masterLabel>Master Agreement Type</masterLabel>
</GlobalValueSet>

classes/Libra_Restul_Functions.cls
public class Libra_Restul_Functions {
    
    public static List<advpm__Matter__c> getAll()
    {
        return [Select ID,Name,Relationship__r.Name, Master_agreement_type__c,Relationship__r.SDS__c
                from advpm__Matter__c 
                where ID IN (Select matter_deal__c from Agreement__c where Agreement_Status__c IN ('Confirmed/Completed','Amended'))];
    }
    public static List<Trade_Instrument__c> getTradeInstrumentByIdSet(Set<Id> sObjectIdSet)
    {
        return [Select Trade_Instrument_ID__c, Asset_Class__c, Agreement_Type__c, Id, Name
               From Trade_Instrument__c where ID IN:sObjectIdSet];
    }
    public static List<Market_Collateral__c> getmarketCollateralOnSupportingAgreement(ID matterId)
    {
        return [SELECT Name,Agreement__c,Applicable_Party__c,Collateral_Comments__c,Collateral_Type__c,Country_of_Issue__c,
                Currency__c,Margin__c,Market_Collateral_Type__c,Sub_Type__c,Supporting_Agreement__c,Value__c,Id
                FROM Market_Collateral__c
                where Supporting_Agreement__r.Agreement__r.Matter_Deal__c = :matterId];
    }
    public static List<Market_Collateral__c> getmarketCollateralOnAgreement(ID matterId)
    {
        return [SELECT Name,Agreement__c,Applicable_Party__c,Collateral_Comments__c,Collateral_Type__c,Country_of_Issue__c,
                Currency__c,Margin__c,Market_Collateral_Type__c,Sub_Type__c,Supporting_Agreement__c,Value__c,Id
                FROM Market_Collateral__c
                where Agreement__r.Matter_Deal__c = :matterId];
    }
    public static String listToString(List<SOBJECT> objectList)
    {
        List<String> sObjectId = new List<String>();
        for(SOBJECT obj : objectList)
        {
            sObjectId.add(obj.ID);
        }
        string allstring = '\''+string.join(sObjectId,'\',\'')+'\'';
        return '('+allstring+')';
    }
    public static List<Clause__c> getClauseByIdSet(Set<Id> sObjectIdSet)
    {
        return [Select Clause_Name__c, Clause_Type__c, Sort_Order__c, Name, Afffects_Bank_s_Liquidity__c, Id, Clause_Unique__c, 
                		GMRA_Clause__c, GMRA_Default__c, GMSLA_Clause__c, GMSLA_Default__c, ISDA_Clause__c
               From Clause__c where ID IN:sObjectIdSet];
    }
    public static List<NettingGroupBranch__c> getNettingGroupBranchByIdSet(Set<ID> NettingGroupIDSet)
    {
        return [Select Name, BranchType__c, NettingGroup__c,Relationship__r.Sds__c, Relationship__c, Trade_Instrument__c, Trade_Instrument__r.Name,Id, Relationship__r.Name 
                
                From NettingGroupBranch__c
                Where NettingGroup__c IN:NettingGroupIDSet];
    }
    
    public static List<SObject> getSObjectById(List<String> sObjectId,String sObjectColumns,String sObjectName)
    {        
            
            string allstring = '\''+string.join(sObjectId,'\',\'')+'\'';
        System.debug(allstring);
        String query = 'SELECT ' + sObjectColumns + ' FROM '+sObjectName+' WHERE Id = ('+allstring+')';
        
        return Database.query(query);
    }
    public static List<SObject> getSObjectById(String sObjectId,String sObjectColumns,String sObjectName)
    {        
        String query = 'SELECT ' + sObjectColumns + ' FROM '+sObjectName+' WHERE Id = \''+sObjectId+'\'';
        
        return Database.query(query);
    }
    public static List<SObject> getSObject(String sObjectColumns,String sObjectName)
    {        
        String query = 'SELECT ' + sObjectColumns + ' FROM '+sObjectName;
        
        return Database.query(query);
    }
    public static List<SObject> getSObjectById(String sObjectId,String sObjectColumns,String sObjectName,String additionalClause)
    {        
        String query = 'SELECT ' + sObjectColumns + ' FROM '+sObjectName+' WHERE Id = \''+sObjectId+'\' AND '+additionalClause;
        
        return Database.query(query);
    }
    public static List<SObject> getSObjectByMatterId(String sObjectId,String sObjectColumns,String sObjectName, String whereClause)
    {        
        String query = 'SELECT ' + sObjectColumns + ' FROM '+sObjectName;
        
        if(String.isNotBlank(whereClause))
        {
            query = query +' '+whereClause;
        }
        
        return Database.query(query);
    }
    public static Map<ID,List<NettingGroupBranch__c >> getBranchPerNettingGroup(List<NettingGroupBranch__c> NettingGroupBranchList)
    {
		Map<ID,List<NettingGroupBranch__c >> branchPerNettingGroup = new Map<Id,List<NettingGroupBranch__c >>();
        
        for(NettingGroupBranch__c NGB : NettingGroupBranchList)
        {
            if(branchPerNettingGroup.containsKey(NGB.NettingGroup__c))
            {
                List<NettingGroupBranch__c > tempList= branchPerNettingGroup.get(NGB.NettingGroup__c);
                tempList.add(NGB);
                branchPerNettingGroup.put(NGB.NettingGroup__c,tempList);
            }
            else
            {
                branchPerNettingGroup.put(NGB.NettingGroup__c,new List<NettingGroupBranch__c>{NGB});
            }
        }
        return branchPerNettingGroup;
    }
    
    public static Map<String,List<NettingGroupBranch__c >> getNettingGroupbranch(List<NettingGroupBranch__c> NettingGroupBranchList)
    {
        Map<String,List<NettingGroupBranch__c >> nettingMap = new Map<String,List<NettingGroupBranch__c >>();
        
        for(NettingGroupBranch__c NGB : NettingGroupBranchList)
        {
            if(nettingMap.containsKey(NGB.BranchType__c))
            {
                System.debug(NGB.BranchType__c);
                List<NettingGroupBranch__c > tempList= nettingMap.get(NGB.BranchType__c);
                tempList.add(NGB);
                nettingMap.put(NGB.BranchType__c,tempList);
            }
            else
            {
                nettingMap.put(NGB.BranchType__c,new List<NettingGroupBranch__c>{NGB});
            }
        }
        return nettingMap;
    }
    
    public class AgreementClauseWrapper
    {
        public String agreementClauseId{get;set;}
    }
    public class AmendmentWrapper
    {
        public String amendmentId{get;set;}
        public String amendmentType{get;set;}
    }
    public class NettingGroupBranchWrapper
    {
        public String nettingGroupBranchId{get;set;}
    }
    public class NettingGroupWrapper
    {
        public String nettingGroupId {get;set;}
    }
    public class ClauseWrapper
    {
        public String clauseId {get;set;}
    }
    public class DealPartyWrapper
    {
        public String dealPartyId{get;set;}
    }
    public class MatterWrapper
    {
        public string matterId{get;set;}
    }
    public class AgreementTradeInstrumentWrapper
    {
        public String agreementTradeInstrumentId  {get;set;}
    }
    public class ParticipantWrapper
    {
        public String participantId{get;set;}
    }
    public class jurisdictionWrapper
    {
        public String jurisdictionId{get;set;}
    }
    
    public class TradeInstrumentWrapper
    {
        public String tradeInstrumentId {get;set;}
    }
    public class AgreementWrapper
    {
        public String agreementId{get;set;}
    }
    public class MarketCollateralWrapper
    {
        public String marketCollateralId{get;set;}
    }
    public Static Blob getExceptionResponse(Exception exc)
    {
        ESPUtility.Response exceptionResponse = new ESPUtility.Response();
        exceptionResponse.message  =exc.getMessage();
        exceptionResponse.stackTrace  =exc.getStackTraceString();
        return  Blob.valueOf(System.JSON.serialize(exceptionResponse));
    }
}