objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Box_Legal_Hold_Assignment_Id__c</fullName>
        <description>To hold legal hold assignment id from Box</description>
        <label>Box Legal Hold Assignment Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FolderID__c</fullName>
        <label>FolderID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Imported_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Imported Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>advpm__Legal_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legal Hold</label>
        <type>Checkbox</type>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <recordTypes>
        <fullName>Legal</fullName>
        <active>true</active>
        <description>Legacy record type reserved for imported Matter Management Lite (MML) matters. All teams using MML layout</description>
        <label>Legal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/advpm__Matter_Legal_Hold_Acknowledgement__c.object
<CustomObject>
    <fields>
        <fullName>Box_Assignment_Id__c</fullName>
        <label>Box_Assignment_Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>advpm__Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Legal Hold Acknowledgements</relationshipLabel>
        <relationshipName>Matter_Legal_Hold_Acknowledgements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Matter Legal Hold Acknowledgement</label>
    <nameField>
        <displayFormat>LH-ACK-{000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matter Legal Hold Acknowledgements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Custom_FRUP__c.object
<CustomObject>
    <fields>
        <fullName>CustomKey__c</fullName>
        <externalId>true</externalId>
        <label>CustomKey</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FolderId__c</fullName>
        <externalId>true</externalId>
        <label>FolderId</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentFolderId__c</fullName>
        <externalId>true</externalId>
        <label>ParentFolderId</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Custom FRUP</label>
    <nameField>
        <label>Custom FRUP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom FRUP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BxdMatterService_test.cls
@isTest
public class BxdMatterService_test {
    public static Map <String, Schema.RecordTypeInfo> mapMatterRecordTypes = advpm__Matter__c.sObjectType.getDescribe().getRecordTypeInfosByName(); 
    
    public static testmethod void testMatterCreationExisting(){
        String IMPORT_FOLDER = 'DataMigrations';
        String MATTER_IMPORT_FOLDER = 'Matters';
        String importCustomKey = IMPORT_FOLDER;
        String mattersCustomKey = importCustomKey + MATTER_IMPORT_FOLDER;
        Custom_FRUP__c migration = new Custom_FRUP__c 
            (
                CustomKey__c = importCustomKey,
                FolderId__c = '1',
                ParentFolderId__c = '0'
            );
        Insert migration;
        
        Custom_FRUP__c matterFolder = new Custom_FRUP__c 
            (
                CustomKey__c = mattersCustomKey,
                FolderId__c = '2',
                ParentFolderId__c = '1'
            );
        Insert matterFolder;
        
        test.startTest();
        advpm__Matter__c TestMatter = new advpm__Matter__c(
            Name='Matter Test Box',
            RecordTypeId = mapMatterRecordTypes.get('Legal').getRecordTypeId(),
            Imported_Data__c = true);
        Insert TestMatter;
        Test.stopTest();        
    }
    
    public static testmethod void testMatterCreationNonExisting(){       
        test.startTest();
        advpm__Matter__c TestMatter = new advpm__Matter__c(
            Name='Matter Test Non Box',
            RecordTypeId = mapMatterRecordTypes.get('Legal').getRecordTypeId(),
            Imported_Data__c = true);
        Insert TestMatter;
        Test.stopTest();        
    }
    
    public static testmethod void testMatterCreationLegalHold(){
        advpm__Matter__c TestMatter = new advpm__Matter__c(
            Name='Matter Test Legal',
            RecordTypeId = mapMatterRecordTypes.get('Read-Only Legal Hold (Legal RT)').getRecordTypeId());
        Insert TestMatter;
        
        advpm__Matter_Legal_Hold_Acknowledgement__c Ackow = new advpm__Matter_Legal_Hold_Acknowledgement__c(
            advpm__Matter__c = TestMatter.Id, Box_Assignment_Id__c = '1234');
        Insert Ackow;
        
        test.startTest();
        TestMatter.advpm__Legal_Hold__c = false;
        TestMatter.Box_Legal_Hold_Assignment_Id__c = '1234';
        Update TestMatter;
        Test.stopTest();        
    }
}