objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/advpm__Participant__c.object
<CustomObject>
    <customHelpPage>advpm__HelpParticipant</customHelpPage>
    <fields>
        <fullName>advpm__Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agreement_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Agreement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Awaiting Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Executed</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Send to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed/Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Amended</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled/Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Superceded</fullName>
        <isActive>false</isActive>
        <label>Superceded</label>
    </customValue>
    <description>Agreement Management (LEAP)</description>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

classes/Libra_Restful_Participant.cls
@RestResource(urlMapping='/participant/*')
global class Libra_Restful_Participant {

      @HttpPost
    global static void getParticipant()
    {
        String requestBody = RestContext.request.requestBody.toString();
        try
        {
            List<advpm__Participant__c> participantList;
            if(String.isNotBlank(requestBody))
            {
                Libra_Restul_Functions.ParticipantWrapper participant =(Libra_Restul_Functions.ParticipantWrapper)JSON.deserialize(requestBody,Libra_Restul_Functions.ParticipantWrapper.class);
                
                if(String.isNotBlank(participant.participantId))
                {
                String additionalClause = ' advpm__Matter__c IN(Select matter_deal__c from Agreement__c where Agreement_Status__c IN (\'Confirmed/Completed\',\'Amended\'))';
                    participantList = Libra_Restul_Functions.getSObjectById(participant.participantId,Libra_Restful_Constants.ParticipantColumns,Libra_Restful_Constants.ParticipantObject,additionalClause);
                    
                    if(participantList!=null && participantList.size()>0)
                    {
                        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(new LibraRestfulModel.Participant(participantList[0])));
                    }
                    else
                    {
                        RestContext.response.responseBody = Blob.valueOf(Libra_Restful_Constants.NotFound);
                        RestContext.response.statusCode =Libra_Restful_Constants.statusCodeNotFound;
                    }
                }
            }
            
            
        }
        catch(StringException eex)
        {
            RestContext.response.responseBody = Blob.valueOf(Libra_Restful_Constants.NotFound);
            RestContext.response.statusCode =Libra_Restful_Constants.statusCodeNotFound;
        }catch(QueryException qe)
        {
            RestContext.response.responseBody = Blob.valueOf(qe.getMessage());
            RestContext.response.statusCode =400;
        }
    }
}