objects/advpm__Participant__c.object
<CustomObject>
    <customHelpPage>advpm__HelpParticipant</customHelpPage>
    <fields>
        <fullName>advpm__Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party Guarantor</fullName>
                </value>
                <value>
                    <fullName>Accountant</fullName>
                </value>
                <value>
                    <fullName>Account Bank</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Agent Bank</fullName>
                </value>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Banker</fullName>
                </value>
                <value>
                    <fullName>Business Unit Contact</fullName>
                </value>
                <value>
                    <fullName>Calculation Agent</fullName>
                </value>
                <value>
                    <fullName>CCMG</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>CIB Operations</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Client Service Consultant</fullName>
                </value>
                <value>
                    <fullName>Co-counsel</fullName>
                </value>
                <value>
                    <fullName>Corporate Service Manager</fullName>
                </value>
                <value>
                    <fullName>Counter Party (Borrower/Client)</fullName>
                </value>
                <value>
                    <fullName>Court</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                    <label>Credit Analyst</label>
                </value>
                <value>
                    <fullName>Credit Head</fullName>
                </value>
                <value>
                    <fullName>Cross Guarantor</fullName>
                </value>
                <value>
                    <fullName>Custodian</fullName>
                </value>
                <value>
                    <fullName>DCM</fullName>
                </value>
                <value>
                    <fullName>Defendant</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>ECA</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>External Legal Counsel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Approval__c.object
<CustomObject>
    <fields>
        <fullName>Fit_To_Lend_Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fit To Lend Checklist</label>
        <referenceTo>Fit_To_Lend_Checklist__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Participant</label>
        <referenceTo>advpm__Participant__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Review in Progress</fullName>
                </value>
                <value>
                    <fullName>Review Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Distribution_Group__c.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <inlineHelpText>Is the group Allowed to see Private Deal Information</inlineHelpText>
        <label>Group Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Private</fullName>
                    <default>true</default>
                    <label>Private</label>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Fit_To_Lend_Checklist__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fit To Lend Checklist</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Fit to Lend No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fit To Lend Checklists</pluralLabel>
    <recordTypes>
        <fullName>Fit_To_Lend_Checklist_Cancelled</fullName>
        <active>true</active>
        <description>Used for Cancelled Fit to Lends so that Users cannot modify existing data on them</description>
        <label>Fit To Lend Checklist - Cancelled</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Notification_Group__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Notification Groups</relationshipLabel>
        <relationshipName>Notification_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <formula>Distribution_Group__r.Email_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fit_To_Lend__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fit To Lend Checklist</label>
        <referenceTo>Fit_To_Lend_Checklist__c</referenceTo>
        <relationshipLabel>Notification Groups</relationshipLabel>
        <relationshipName>Notification_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Type__c</fullName>
        <formula>TEXT(Distribution_Group__r.Group_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Type</label>
        <type>Text</type>
    </fields>
    <label>Notification Group</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Notification Group No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Notification_Participant__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Email_Address__c</fullName>
        <formula>Participant__r.advpm__Staff__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fit_To_Lend_Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fit To Lend Checklist</label>
        <referenceTo>Fit_To_Lend_Checklist__c</referenceTo>
        <relationshipLabel>Notification Participants</relationshipLabel>
        <relationshipName>Notification_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>advpm__Participant__c</referenceTo>
        <relationshipLabel>Notification Participants</relationshipLabel>
        <relationshipName>Notification_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Notification Participant</label>
    <nameField>
        <displayFormat>NP-{00000}</displayFormat>
        <label>Notification Participants #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FitToLend_Helper.cls
/**
 _____ _                 _ _____           _ _   _         
/  __ \ |               | /  ___|         (_) | | |        
| /  \/ | ___  _   _  __| \ `--. _ __ ___  _| |_| |__  ___ 
| |   | |/ _ \| | | |/ _` |`--. \ '_ ` _ \| | __| '_ \/ __|
| \__/\ | (_) | |_| | (_| /\__/ / | | | | | | |_| | | \__ \
 \____/_|\___/ \__,_|\__,_\____/|_| |_| |_|_|\__|_| |_|___/
                                                           
 12/12/2017 - PG    - Updated org-wide address to IMPEX one.
 19/01/2018 - PG    - Added Logic to purge task activities after emails are sent.
 22/01/2018 - TdB 	 - Set From email address to xradocmanvalidations@barclayscapital.com
 12/03/2018 - TdB    - Auto Reject Pending Approvals when cancelling a fit to lend
   
**/           
public class FitToLend_Helper 
{
    public static List<Fit_To_Lend_Checklist__c> approvalStatuses(Set<Id> inputFitToLendIds)
    {
	 List<RecordType> FitToLendRecordType_Cancelled = [SELECT Id, Name, DeveloperName, SobjectType 
                                                         FROM RecordType
                                                         WHERE SobjectType = 'Fit_To_Lend_Checklist__c' 
                                                         AND DeveloperName = 'Fit_To_Lend_Checklist_Cancelled' limit 1];
        List<Fit_To_Lend_Checklist__c> fitToLends = [
            SELECT
                Id,
                Name,
				RecordTypeId,
                Status__c,
                (
                    SELECT
                        Id,
                        Status__c
                    FROM
                    Approvals__r
                )
            FROM Fit_To_Lend_Checklist__c
            WHERE 
                Id IN :inputFitToLendIds
        ];
        
        System.debug('### FitToLend_Helper : approvalStatuses : fitToLends : '+fitToLends);
        
        //Loop through all 
        for(Fit_To_Lend_Checklist__c fitToLend : fitToLends)
        {
            //Number of approvals on this item.
            Integer numApprovals    = fitToLend.Approvals__r.size();
            
            //Counters to determine status
            Integer numApproved     = 0;
            Integer numRejected     = 0;
            
            //Loop through related approval records an count statuses.
            for(Approval__c approvalRecord : fitToLend.Approvals__r)
            {
                if(approvalRecord.Status__c == 'Approved')
                {
                   numApproved++;
                }
                
                if(approvalRecord.Status__c == 'Rejected')
                {
                   numRejected++;
                }
            }
            
            //Set the overall status for fit to lend record.
            if(numApprovals == numApproved)
            {
               fitToLend.Status__c = 'Approved'; 
            }
            else if(numRejected > 0)
            {
				if(FitToLendRecordType_Cancelled.size() > 0)
                {
                    if(fitToLend.recordTypeId == FitToLendRecordType_Cancelled[0].id)
                    {
                        fitToLend.Status__c = 'Cancelled'; 
                    }
                    else
                    {
                        fitToLend.Status__c = 'Rejected'; 
                    }
                }

            }
            else
            {
                fitToLend.Status__c = 'Pending Approval'; 
            }
        }
        
        //Default return.
        return fitToLends;
    }
    
    public static void sendNotificationEmails(Set<Id> inputFitToLendIds) 
    {
        System.debug('### FitToLend_Helper : sendNotificationEmails');
        
        List<OrgWideEmailAddress> OrgWideEmails = [select Id from OrgWideEmailAddress where Address = 'xradocmanvalidations@barclayscapital.com'];
        //Blank list.
        List<Fit_To_Lend_Checklist__c> fitToLends = new List<Fit_To_Lend_Checklist__c>();
        
        //Attachment to fit to lend
        Map<Id, Attachment> fitToLendAttachments = new Map<Id, Attachment>();
        
        //Get any contact for email template.  Never emailed...
        Id randomContactId = [SELECT Id FROM Contact WHERE Email != null LIMIT 1].Id;
        
        //Get file attachments
        for(Attachment attachment : [SELECT Id, Name, Body, ContentType, ParentId FROM Attachment WHERE ParentId IN :inputFitToLendIds])
        {
            //Not in map already.
            if(!fitToLendAttachments.containsKey(attachment.ParentId))
            {
                fitToLendAttachments.put(attachment.ParentId, attachment);
            }
        }
        
        //Final list of all email messages for sending.
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
        
        //Get the ids of the email template
        Id publicEmailTempateId     = [SELECT Id, Name FROM EmailTemplate WHERE DeveloperName = 'TMG_Public_Fit_to_Lend_Approval_Notifications'].Id;
        Id privateEmailTempateId    = [SELECT Id, Name FROM EmailTemplate WHERE DeveloperName = 'TMG_Private_Fit_to_Lend_Approval_Notification'].Id;
        
        //Get the fit to lend records and notificiation groups.
        fitToLends = [
            SELECT 
                Id,
                Name,
                (
                    SELECT 
                        Id,
                        Distribution_Group__c,
                        Distribution_Group__r.Name,
                        Distribution_Group__r.Email_Address__c,
                        Distribution_Group__r.Group_Type__c
                    FROM Notification_Groups__r
                ),
                (
                    SELECT 
                        Id,
                        Email_Address__c,
                        Participant__c,
                        Participant__r.advpm__Role__c
                    FROM Notification_Participants__r
                )
            FROM Fit_To_Lend_Checklist__c
            WHERE
                Id IN :inputFitToLendIds
        ];

        //Loop through checklists.
        for(Fit_To_Lend_Checklist__c fitToLend : fitToLends)
        {
            //Create the email attachment
            Messaging.EmailFileAttachment emailAttachment = new Messaging.EmailFileAttachment();
            emailAttachment.setFileName(fitToLendAttachments.get(fitToLend.Id).Name);
            emailAttachment.setBody(fitToLendAttachments.get(fitToLend.Id).Body);
        
            //Loop through notification groups.
            for(Notification_Group__c notifyGroup : fitToLend.Notification_Groups__r)
            {
                System.debug('### FitToLend_Helper : sendNotificationEmails : notifyGroup : FOR');
                
                //Group email address.
                List<String> toAddresses = new List<String> { notifyGroup.Distribution_Group__r.Email_Address__c };
               
                //Single email object.
                Messaging.SingleEmailMessage singleEmail = new Messaging.SingleEmailMessage();
                singleEmail.setTargetObjectId(randomContactId);
                singleEmail.setTreatTargetObjectAsRecipient(false); //Prevent sending to random contact
                singleEmail.setToAddresses(toAddresses);
                singleEmail.setWhatId(fitToLend.Id);
                if ( OrgWideEmails.size() > 0 ) 
                {
                    singleEmail.setOrgWideEmailAddressId(OrgWideEmails.get(0).Id);
                }
                
                //Private
                if(notifyGroup.Distribution_Group__r.Group_Type__c == 'Private')
                {
                    singleEmail.setTemplateId(privateEmailTempateId);
                    
                    //Add file attachment.
                    singleEmail.setFileAttachments(new Messaging.EmailFileAttachment[] { emailAttachment });
                }
                //Public
                else
                {
                    singleEmail.setTemplateId(publicEmailTempateId); 
                }
                
                //Add to list.
                emailMessages.add(singleEmail);
            }
            
            //Loop through participant notifications.
            for(Notification_Participant__c notifyParticipant : fitToLend.Notification_Participants__r)
            {
                System.debug('### FitToLend_Helper : sendNotificationEmails : notifyParticipant : FOR');
                
                //Group email address.
                List<String> toAddresses = new List<String> { notifyParticipant.Email_Address__c };
               
                //Single email object.
                Messaging.SingleEmailMessage singleEmail = new Messaging.SingleEmailMessage();
                singleEmail.setTargetObjectId(randomContactId);
                singleEmail.setTreatTargetObjectAsRecipient(false); //Prevent sending to random contact
                singleEmail.setToAddresses(toAddresses);
                singleEmail.setWhatId(fitToLend.Id);
                singleEmail.setTemplateId(privateEmailTempateId);
                if ( OrgWideEmails.size() > 0 ) 
                {
                    singleEmail.setOrgWideEmailAddressId(OrgWideEmails.get(0).Id);
                }
                    
                //Add file attachment.
                singleEmail.setFileAttachments(new Messaging.EmailFileAttachment[] { emailAttachment });
                
                //Add to list.
                emailMessages.add(singleEmail);
            }
        }

        //Send emails.
        Messaging.SendEmailResult[] emailResults = Messaging.sendEmail(emailMessages);

        //Finally delete any F2L tasks created against the random contact.  Needed as a workaround when using a template.
        List<Task> tasks = [
            SELECT 
                Id 
            FROM Task 
            WHERE 
                WhoId = :randomContactId 
                AND WhatId IN :inputFitToLendIds
        ];

        //Delete records.
        delete tasks;
    }
}