objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Transaction</relationshipLabel>
        <relationshipName>Matters_Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GMRA Agreement</fullName>
                </value>
                <value>
                    <fullName>GMSLA Agreement</fullName>
                </value>
                <value>
                    <fullName>ISDA Agreement</fullName>
                </value>
                <value>
                    <fullName>Prime Services Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Netting_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Netting Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prime_Services_Client__c</fullName>
        <inlineHelpText>Selecting &apos;Yes&apos; indicates that this client will be signing a master Prime Brokerage Agreement</inlineHelpText>
        <label>Prime Services Client</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Master_Agreement_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_Type_picklist__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>Counterparty</fullName>
                </value>
                <value>
                    <fullName>Collective Investment Scheme Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Transaction Relationship</relationshipLabel>
        <relationshipName>Matters_Deals2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Description__c</fullName>
        <label>Agreement Description</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <formula>Matter_Deal__r.Bank__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bank</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Counterparty/Client</inlineHelpText>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <description>Facility limit to determine each Lender&apos;s portion</description>
        <label>Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Required_Prior_to_First__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Master Agreement Required Prior to First</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_Agreement_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Services_Client__c</fullName>
        <formula>TEXT(Matter_Deal__r.Prime_Services_Client__c)</formula>
        <label>Prime Services Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement Product Grouping</label>
        <referenceTo>Product_Level_2__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <formula>Matter_Deal__r.Relationship__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReviewDate__c</fullName>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Exposure_Calculation_Method__c</fullName>
        <label>Transaction Exposure Calculation Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Method A</fullName>
                </value>
                <value>
                    <fullName>Method B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HotDocs_Request__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>HotDocs Requests</relationshipLabel>
        <relationshipName>HotDocs_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supporting Agreement</label>
        <referenceTo>Supporting_Agreement__c</referenceTo>
        <relationshipLabel>HotDocs Requests</relationshipLabel>
        <relationshipName>HotDocs_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Item_ID__c</fullName>
        <label>Work Item ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HotDocs Request</label>
    <nameField>
        <displayFormat>HR-{0}</displayFormat>
        <label>Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HotDocs Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HotDocs_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>HotDocs_Request__c</fullName>
        <label>HotDocs Request</label>
        <referenceTo>HotDocs_Request__c</referenceTo>
        <relationshipLabel>HotDocs Request Items</relationshipLabel>
        <relationshipName>HotDocs_Request_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <label>Item ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Answer File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>HotDocs Request Item</label>
    <nameField>
        <displayFormat>HRI-{0}</displayFormat>
        <label>Request Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HotDocs Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Supporting_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Supporting Agreements</relationshipLabel>
        <relationshipName>Supporting_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Frequency__c</fullName>
        <label>Call Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Frequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collateral_type__c</fullName>
        <label>Bilateral / Unilateral</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Collateral</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GMRA Agreement</fullName>
                </value>
                <value>
                    <fullName>GMSLA Agreement</fullName>
                </value>
                <value>
                    <fullName>ISDA Agreement</fullName>
                </value>
                <value>
                    <fullName>Prime Services Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Exposure_Calculation_Method__c</fullName>
        <label>Transaction Exposure Calculation Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Method A</fullName>
                </value>
                <value>
                    <fullName>Method B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valuation_Agent__c</fullName>
        <label>Valuation Agent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Valuation_Agent</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valuation__c</fullName>
        <label>Valuation %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Supporting Agreement</label>
    <nameField>
        <displayFormat>SA-{0}</displayFormat>
        <label>Supporting Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supporting Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Collateral.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bilateral</fullName>
    </customValue>
    <customValue>
        <fullName>Unilateral (Counterparty)</fullName>
    </customValue>
    <customValue>
        <fullName>Unilateral (Own)</fullName>
    </customValue>
    <masterLabel>Collateral</masterLabel>
</GlobalValueSet>

globalValueSets/Frequency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-Annually</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Once Off</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

globalValueSets/Master_Agreement_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>GMRA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>GMSLA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>ISDA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Prime Services Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Supporting Agreement</fullName>
    </customValue>
    <masterLabel>Master Agreement Type</masterLabel>
</GlobalValueSet>

globalValueSets/Valuation_Agent.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Counterparty</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Valuation Agent</masterLabel>
</GlobalValueSet>

classes/HotDocs_Test.cls
/**
 _____ _                 _ _____           _ _   _         
/  __ \ |               | /  ___|         (_) | | |        
| /  \/ | ___  _   _  __| \ `--. _ __ ___  _| |_| |__  ___ 
| |   | |/ _ \| | | |/ _` |`--. \ '_ ` _ \| | __| '_ \/ __|
| \__/\ | (_) | |_| | (_| /\__/ / | | | | | | |_| | | \__ \
 \____/_|\___/ \__,_|\__,_\____/|_| |_| |_|_|\__|_| |_|___/
 
 *** CHANGE LOG ***
 
 22/11/2017 - PG    - Created Class.
 13/03/2018 - PG 	- Removed TestSetup method, as new metadata can see records.

**/
@IsTest
private class HotDocs_Test 
{
    public static Map <String, Schema.RecordTypeInfo> AgreementRecordTypes = Agreement__c.sObjectType.getDescribe().getRecordTypeInfosByName();
    public static Map <String, Schema.RecordTypeInfo> mapMatterRecordTypes = advpm__Matter__c.sObjectType.getDescribe().getRecordTypeInfosByName();
    
	@IsTest
	static void api_getInterviewUrl()
	{
		Test.startTest();

		HotDocs_API api = new HotDocs_API();
		api.getInterviewUrl('fake hotdocs id', 'fake answer set id'); 

		Test.stopTest();
	}

	@IsTest 
	static void queue_HotDocsRequest_Manual()
	{
		//Test Data
		Cloudsmiths_TestDataClass testData = new Cloudsmiths_TestDataClass();

		//HotDocs_Request
		HotDocs_Helper.createRequest('<fake work id>', testData.TestAgreement.Id, null); 

		Id hotdocsRequestId = [
			SELECT
				Id
			FROM HotDocs_Request__c
			WHERE
				Work_Item_ID__c = '<fake work id>'
			LIMIT 1
		].Id;

		//Insert an existing request item
		HotDocs_Request_Item__c requestItem = new HotDocs_Request_Item__c(
			Item_ID__c = '123',
			HotDocs_Request__c = hotdocsRequestId,
			Type__c = 'Document'
		);
		insert requestItem;

		Test.startTest();

		//Queue job.
		System.enqueueJob(new HotDocs_Request_Queue(hotdocsRequestId));
		
		Test.stopTest();
	}

	@IsTest
	static void api_createToken_Manual()
	{
		Test.startTest();

		HotDocs_API api = new HotDocs_API();
		api.createToken();

		Test.stopTest();
	}

	@IsTest
	static void api_createSession_Manual()
	{
		Test.startTest();

		HotDocs_API api = new HotDocs_API();
		api.createSession('fake hotdocs id', 'fake answer set id');

		Test.stopTest();
	}

	@IsTest
	static void api_createAnswerSet_Manual()
	{
		Test.startTest();

		//New Answer Set
		HotDocs_AnswerSet answerSet = new HotDocs_AnswerSet();

		//Sample Answers
		List<IHotDocs_Answer> textAnswerList = new List<IHotDocs_Answer>();
		textAnswerList.add(new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data'));
		textAnswerList.add(new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data'));

		//Plain text
		answerSet.add(new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data'));
		answerSet.add(new HotDocs_Answer_Generic('SELECT', 'Sample Variable 2', 'Test Data'));

		//Test both constructors on multi and repeat.
		answerSet.add(new HotDocs_Answer_Multi('Sample Multi', new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data')));
		answerSet.add(new HotDocs_Answer_Repeat('Sample Repeat', new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data')));
		answerSet.add(new HotDocs_Answer_Multi('Sample Multi', textAnswerList));
		answerSet.add(new HotDocs_Answer_Repeat('Sample Repeat', textAnswerList));

		HotDocs_API api = new HotDocs_API();
		api.createAnswerSet('Test Answer', 'Test Description', answerSet); 

		Test.stopTest();
	}

	@IsTest
	static void api_createAnswerSetOverlay_Manual()
	{
		Test.startTest();

		//New Answer Set
		HotDocs_AnswerSet answerSet = new HotDocs_AnswerSet();

		//Sample Answers
		List<IHotDocs_Answer> textAnswerList = new List<IHotDocs_Answer>();
		textAnswerList.add(new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data'));
		textAnswerList.add(new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data'));

		//Plain text
		answerSet.add(new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data'));
		answerSet.add(new HotDocs_Answer_Generic('SELECT', 'Sample Variable 2', 'Test Data'));

		//Test both constructors on multi and repeat.
		answerSet.add(new HotDocs_Answer_Multi('Sample Multi', new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data')));
		answerSet.add(new HotDocs_Answer_Repeat('Sample Repeat', new HotDocs_Answer_Generic('TEXT', 'Sample Variable', 'Test Data')));
		answerSet.add(new HotDocs_Answer_Multi('Sample Multi', textAnswerList));
		answerSet.add(new HotDocs_Answer_Repeat('Sample Repeat', textAnswerList));

		HotDocs_API api = new HotDocs_API();
		api.createAnswerSetOverlay('Test HotDocs Id','Test Answer', 'Test Description', answerSet); 

		Test.stopTest();
	}

	@IsTest
	static void service_execute_createSession()
	{
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new HotDocs_MockResponse());

		HotDocs_Service service = new HotDocs_Service();
		service.endpoint = 'https://testendpoint.com/Session/CreateSession';
		service.requestMethod = 'POST';

		//Request Headers
		service.requestHeaders.put('Authorization', 'Bearer '+'fake access token');

		//URL parameters
		service.requestParameters.put('templateId', 'fake package id'); 
		service.requestParameters.put('answersetId', 'fake id set'); 

		//Call method.
		service.execute(null);

		Test.stopTest();
	}

	@IsTest
	static void page_HotDocsInterview()
	{
		//Test Data
		Cloudsmiths_TestDataClass testData = new Cloudsmiths_TestDataClass();

		Test.startTest();

		PageReference pageRef = Page.HotDocs_Interview;
		pageRef.getParameters().put('id', testData.TestAgreement.Id);
		Test.setCurrentPage(pageRef);

		HotDocs_Interview controller = new HotDocs_Interview();

		//Set Template ID
		controller.hotDocsTemplateId = 'fake template id';

		//Methods.
		controller.actionLaunchInterview(); 
		HotDocs_Interview.createRequest('fake work item id',testData.TestAgreement.Id, null); 

		Test.stopTest();  
	}

	@IsTest
	static void schedule_Monitoring()
	{
		//Test Data
		Cloudsmiths_TestDataClass testData = new Cloudsmiths_TestDataClass();

		//HotDocs_Request
		HotDocs_Helper.createRequest('<fake work id>', testData.TestAgreement.Id, null);

		Id hotdocsRequestId = [
			SELECT
				Id
			FROM HotDocs_Request__c
			WHERE
				Work_Item_ID__c = '<fake work id>'
			LIMIT 1
		].Id;

		Test.startTest();

		//Run class
		HotDocs_Request_Monitoring scheduledClass = new HotDocs_Request_Monitoring();      
		String testSchedule = '0 0 23 * * ?';
        System.schedule('Test Class', testSchedule, scheduledClass);

		Test.stopTest();
	}
    
    @IsTest
	static void page_HotDocsIsdaInterview()
	{
		//Test Data
		Libra_TestDataClass testData = new Libra_TestDataClass();
        
        advpm__Matter__c testMarketTransactionMatter = new advpm__Matter__c(
            Name='Market Transaction Test',
            RecordTypeId = mapMatterRecordTypes.get('Market Transaction').getRecordTypeId(),
            Bank__c = testData.testBankAccount.id,
            Relationship__c = testData.testRelAccount.id,
            Relationship_Type_picklist__c = 'Asset Manager',
            Master_Agreement_Type__c = 'Prime Services Agreement',
            Netting_Complete__c = true);
        Insert testMarketTransactionMatter;
        
        //AGREEMENT
        Agreement__c testIsdaAgreement = new Agreement__c (
            Matter_Deal__c = testMarketTransactionMatter.id,
            Client_Name__c = testData.testAccount.id,
            name = 'Agreement Name',
            Agreement_Description__c = 'Testing',
            ReviewDate__c = system.today(),
            Limit__c = 5,
            Product__c = testData.testProductLevel2.id,
            Master_Agreement_Required_Prior_to_First__c = true,
            recordTypeId = AgreementRecordTypes.get('ISDA Agreement').getRecordTypeId());
        Insert testIsdaAgreement;

		Test.startTest();

		PageReference pageRef = Page.HotDocs_Interview;
		pageRef.getParameters().put('id', testIsdaAgreement.Id);
		Test.setCurrentPage(pageRef);

		HotDocs_Interview controller = new HotDocs_Interview();

		//Set Template ID
		controller.hotDocsTemplateId = '<fake ISDA work id>';

		//Methods.
		controller.actionLaunchInterview(); 
		HotDocs_Interview.createRequest('<fake ISDA work id>',testIsdaAgreement.Id, null); 
        
        HotDocs_Request__c hotdocsRequest = [
			SELECT
				Id,
            Status__c
			FROM HotDocs_Request__c
			WHERE
				Work_Item_ID__c = '<fake ISDA work id>'
			LIMIT 1
		];
        hotdocsRequest.Status__c = 'Completed';
        
        update hotdocsRequest;
        
        //Queue job.
		System.enqueueJob(new HotDocs_Request_Queue(hotdocsRequest.Id));

		Test.stopTest();  
	}
    
     @IsTest
	static void page_HotDocsGmslaInterview()
	{
		//Test Data
		Libra_TestDataClass testData = new Libra_TestDataClass();
        
        advpm__Matter__c testMarketTransactionMatter = new advpm__Matter__c(
            Name='Market Transaction Test',
            RecordTypeId = mapMatterRecordTypes.get('Market Transaction').getRecordTypeId(),
            Bank__c = testData.testBankAccount.id,
            Relationship__c = testData.testRelAccount.id,
            Relationship_Type_picklist__c = 'Asset Manager',
            Master_Agreement_Type__c = 'Prime Services Agreement',
            Netting_Complete__c = true);
        Insert testMarketTransactionMatter;
        
        //AGREEMENT
        Agreement__c testGmslaAgreement = new Agreement__c (
            Matter_Deal__c = testMarketTransactionMatter.id,
            Client_Name__c = testData.testAccount.id,
            name = 'Agreement Name',
            Agreement_Description__c = 'Testing',
            ReviewDate__c = system.today(),
            Limit__c = 5,
            Product__c = testData.testProductLevel2.id,
            Master_Agreement_Required_Prior_to_First__c = true,
            recordTypeId = AgreementRecordTypes.get('GMSLA Agreement').getRecordTypeId());
        Insert testGmslaAgreement;

		Test.startTest();

		PageReference pageRef = Page.HotDocs_Interview;
		pageRef.getParameters().put('id', testGmslaAgreement.Id);
		Test.setCurrentPage(pageRef);

		HotDocs_Interview controller = new HotDocs_Interview();

		//Set Template ID
		controller.hotDocsTemplateId = '<fake GMSLA work id>';

		//Methods.
		controller.actionLaunchInterview(); 
		HotDocs_Interview.createRequest('<fake GMSLA work id>',testGmslaAgreement.Id, null); 
        
         Id hotdocsRequestId = [
			SELECT
				Id
			FROM HotDocs_Request__c
			WHERE
				Work_Item_ID__c = '<fake GMSLA work id>'
			LIMIT 1
		].Id;
        
        //Queue job.
		System.enqueueJob(new HotDocs_Request_Queue(hotdocsRequestId));

		Test.stopTest();  
	}
    
     @IsTest
	static void page_HotDocsGmraInterview()
	{
		//Test Data
		Libra_TestDataClass testData = new Libra_TestDataClass();
        
        advpm__Matter__c testMarketTransactionMatter = new advpm__Matter__c(
            Name='Market Transaction Test',
            RecordTypeId = mapMatterRecordTypes.get('Market Transaction').getRecordTypeId(),
            Bank__c = testData.testBankAccount.id,
            Relationship__c = testData.testRelAccount.id,
            Relationship_Type_picklist__c = 'Asset Manager',
            Master_Agreement_Type__c = 'Prime Services Agreement',
            Netting_Complete__c = true);
        Insert testMarketTransactionMatter;
        
        //AGREEMENT
        Agreement__c testGmraAgreement = new Agreement__c (
            Matter_Deal__c = testMarketTransactionMatter.id,
            Client_Name__c = testData.testAccount.id,
            name = 'Agreement Name',
            Agreement_Description__c = 'Testing',
            ReviewDate__c = system.today(),
            Limit__c = 5,
            Product__c = testData.testProductLevel2.id,
            Master_Agreement_Required_Prior_to_First__c = true,
            recordTypeId = AgreementRecordTypes.get('GMRA Agreement').getRecordTypeId());
        Insert testGmraAgreement;

		Test.startTest();

		PageReference pageRef = Page.HotDocs_Interview;
		pageRef.getParameters().put('id', testGmraAgreement.Id);
		Test.setCurrentPage(pageRef);

		HotDocs_Interview controller = new HotDocs_Interview();

		//Set Template ID
		controller.hotDocsTemplateId = '<fake GMRA work id>';

		//Methods.
		controller.actionLaunchInterview(); 
		HotDocs_Interview.createRequest('<fake GMRA work id>',testGmraAgreement.Id, null); 
        
        Id hotdocsRequestId = [
			SELECT
				Id
			FROM HotDocs_Request__c
			WHERE
				Work_Item_ID__c = '<fake GMRA work id>'
			LIMIT 1
		].Id;
        
        //Queue job.
		System.enqueueJob(new HotDocs_Request_Queue(hotdocsRequestId));

		Test.stopTest();  
	}
    
     @IsTest
	static void page_HotDocsPrimeServicesInterview()
	{
		//Test Data
		Libra_TestDataClass testData = new Libra_TestDataClass();
        
        Test.startTest();
        advpm__Matter__c testMarketTransactionMatter = new advpm__Matter__c(
            Name='Market Transaction Test',
            RecordTypeId = mapMatterRecordTypes.get('Market Transaction').getRecordTypeId(),
            Bank__c = testData.testBankAccount.id,
            Relationship__c = testData.testRelAccount.id,
            Relationship_Type_picklist__c = 'Collective Investment Scheme Manager',
            Master_Agreement_Type__c = 'Prime Services Agreement',
            Prime_Services_Client__c = 'Yes',
            Netting_Complete__c = true);
        Insert testMarketTransactionMatter;

        //AGREEMENT
        Agreement__c testPrimeServicesAgreement = new Agreement__c (
            Matter_Deal__c = testMarketTransactionMatter.id,
            Client_Name__c = testData.testAccount.id,
            name = 'Agreement Name',
            Agreement_Description__c = 'Testing',
            ReviewDate__c = system.today(),
            Limit__c = 5,
            Product__c = testData.testProductLevel2.id,
            Master_Agreement_Required_Prior_to_First__c = true,
            recordTypeId = AgreementRecordTypes.get('Prime Services Agreement').getRecordTypeId());
        //Insert testPrimeServicesAgreement;
        Id agreementInsertId;
        for(Agreement__c eachAgreement : [ SELECT
                                          Id
                                          FROM Agreement__c
                                          WHERE
                                          Matter_Deal__c =: testMarketTransactionMatter.id
                                          AND Id != null
                                          LIMIT 1
                                         ])
        {
            agreementInsertId = eachAgreement.id;
            
            
            
            
            PageReference pageRef = Page.HotDocs_Interview;
            pageRef.getParameters().put('id', agreementInsertId);
            Test.setCurrentPage(pageRef);
            
            HotDocs_Interview controller = new HotDocs_Interview();
            controller.agreement = testPrimeServicesAgreement;
            
            //Set Template ID
            controller.hotDocsTemplateId = '<fake PRIME work id>';
            
            //Methods.
            controller.actionLaunchInterview(); 
            controller.buildPrimeServicesAnswerFile();
            HotDocs_Interview.createRequest('<fake PRIME work id>',agreementInsertId, null); 
            
            Id hotdocsRequestId = [
                SELECT
                Id
                FROM HotDocs_Request__c
                WHERE
                Work_Item_ID__c = '<fake PRIME work id>'
                LIMIT 1
            ].Id;
            
            //Queue job.
            System.enqueueJob(new HotDocs_Request_Queue(hotdocsRequestId));
        }
		Test.stopTest();  
	}
    
     @IsTest
	static void page_HotDocsCsaInterview()
	{
		//Test Data
		Libra_TestDataClass testData = new Libra_TestDataClass();
        
        advpm__Matter__c testMarketTransactionMatter = new advpm__Matter__c(
            Name='Market Transaction Test',
            RecordTypeId = mapMatterRecordTypes.get('Market Transaction').getRecordTypeId(),
            Bank__c = testData.testBankAccount.id,
            Relationship__c = testData.testRelAccount.id,
            Relationship_Type_picklist__c = 'Asset Manager',
            Master_Agreement_Type__c = 'Prime Services Agreement',
            Netting_Complete__c = true);
        Insert testMarketTransactionMatter;

        //AGREEMENT
        Agreement__c testIsdaAgreement = new Agreement__c (
            Matter_Deal__c = testMarketTransactionMatter.id,
            Client_Name__c = testData.testAccount.id,
            name = 'Agreement Name',
            Agreement_Description__c = 'Testing',
            ReviewDate__c = system.today(),
            Limit__c = 5,
            Product__c = testData.testProductLevel2.id,
            Master_Agreement_Required_Prior_to_First__c = true,
            recordTypeId = AgreementRecordTypes.get('ISDA Agreement').getRecordTypeId());
        Insert testIsdaAgreement;
        
        Supporting_Agreement__c testSupportingAgreement = new Supporting_Agreement__c();
        testSupportingAgreement.Master_Agreement_Type__c = 'ISDA Agreement';
        testSupportingAgreement.Collateral_type__c = 'Bilateral';
        testSupportingAgreement.Transaction_Exposure_Calculation_Method__c = 'Method A';
        testSupportingAgreement.Valuation__c = 50;
        testSupportingAgreement.Valuation_Agent__c = 'Bank';
        testSupportingAgreement.Call_Frequency__c = 'Once Off';
        testSupportingAgreement.Supporting_Agreement_Type__c = 'CSA';
        testSupportingAgreement.Agreement__c = testIsdaAgreement.id;
        Insert testSupportingAgreement;

		Test.startTest();

		PageReference pageRef = Page.HotDocs_Interview;
		pageRef.getParameters().put('id', testIsdaAgreement.Id);
        pageRef.getParameters().put('csaId', testSupportingAgreement.id);
		Test.setCurrentPage(pageRef);

		HotDocs_Interview controller = new HotDocs_Interview();

		//Set Template ID
		controller.hotDocsTemplateId = '<fake ISDA work id>';

		//Methods.
		controller.actionLaunchInterview(); 
		HotDocs_Interview.createRequest('<fake ISDA work id>',testIsdaAgreement.Id, testSupportingAgreement.id); 
        
        Id hotdocsRequestId = [
			SELECT
				Id
			FROM HotDocs_Request__c
			WHERE
				Work_Item_ID__c = '<fake ISDA work id>'
			LIMIT 1
		].Id;
        
        //Queue job.
		System.enqueueJob(new HotDocs_Request_Queue(hotdocsRequestId));

		Test.stopTest();  
	}
}