objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Transaction</relationshipLabel>
        <relationshipName>Matters_Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral_Agreement_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Collateral Agreement Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collective_Investment_Scheme_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collective Investment Scheme Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matters/Deals (Name of Collective Investment Scheme)</relationshipLabel>
        <relationshipName>Matters_Deals3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collective_Investment_Scheme_Type__c</fullName>
        <label>Collective Investment Scheme Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Relationship_Type_picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Qualified Investor Hedge Fund</fullName>
                </value>
                <value>
                    <fullName>Retail Hedge Fund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Counterparty_Type__c</fullName>
        <label>Counterparty Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Relationship_Type_picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed Corporation</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>CPF Corporation Template</fullName>
                </value>
                <value>
                    <fullName>En Commandite Partnership</fullName>
                </value>
                <value>
                    <fullName>Long Term Insurer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pension Fund</fullName>
                </value>
                <value>
                    <fullName>Project Finance Linked Hedging</fullName>
                </value>
                <value>
                    <fullName>Short Term Insurer</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GMRA Agreement</fullName>
                </value>
                <value>
                    <fullName>GMSLA Agreement</fullName>
                </value>
                <value>
                    <fullName>ISDA Agreement</fullName>
                </value>
                <value>
                    <fullName>Prime Services Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Netting_Applicable__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This indicates whether Netting will apply on the Agreement</inlineHelpText>
        <label>Netting Applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Netting_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Netting Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Party_B__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Party B</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prime_Services_Client__c</fullName>
        <inlineHelpText>Selecting &apos;Yes&apos; indicates that this client will be signing a master Prime Brokerage Agreement</inlineHelpText>
        <label>Prime Services Client</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Master_Agreement_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <formula>advpm__Primary_Account__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Type_picklist__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>Counterparty</fullName>
                </value>
                <value>
                    <fullName>Collective Investment Scheme Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Transaction Relationship</relationshipLabel>
        <relationshipName>Matters_Deals2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agreement_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <formula>Matter_Deal__r.Bank__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bank</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_Agreement_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Services_Client__c</fullName>
        <formula>TEXT(Matter_Deal__r.Prime_Services_Client__c)</formula>
        <label>Prime Services Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <formula>Matter_Deal__r.Relationship__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship</label>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Agreement_Trade_Instrument__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Trade Instruments</relationshipLabel>
        <relationshipName>Trade_Instruments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trade_Instrument__c</fullName>
        <label>Trade Instrument</label>
        <referenceTo>Trade_Instrument__c</referenceTo>
        <relationshipLabel>Agreement Trade Instruments</relationshipLabel>
        <relationshipName>Agreement_Trade_Instruments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement Trade Instrument</label>
    <nameField>
        <displayFormat>ATI - {00000}</displayFormat>
        <label>Agreement Trade Instrument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Trade Instruments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal_Party__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Deal Parties</relationshipLabel>
        <relationshipName>Deal_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Party_B__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Party B</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deal Parties</relationshipLabel>
        <relationshipName>Deal_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Party</label>
    <nameField>
        <displayFormat>DP-{00000}</displayFormat>
        <label>Deal Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Netting_Group__c.object
<CustomObject>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Netting Groups</relationshipLabel>
        <relationshipName>Netting_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Netting_Type__c</fullName>
        <label>Netting Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Close Out</fullName>
                </value>
                <value>
                    <fullName>Novation</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Netting Group</label>
    <nameField>
        <displayFormat>NG-{0000}</displayFormat>
        <label>Netting Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Netting Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NettingGroupBranch__c.object
<CustomObject>
    <fields>
        <fullName>BranchType__c</fullName>
        <label>Branch Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>Counterparty</fullName>
                </value>
                <value>
                    <fullName>Trade Instrument</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NettingGroup__c</fullName>
        <label>Netting Group</label>
        <referenceTo>Netting_Group__c</referenceTo>
        <relationshipLabel>Netting Group Branches</relationshipLabel>
        <relationshipName>Netting_Group_Branchs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Netting Group Branches</relationshipLabel>
        <relationshipName>Netting_Group_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trade_Instrument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade Instrument</label>
        <referenceTo>Trade_Instrument__c</referenceTo>
        <relationshipLabel>Netting Group Branches</relationshipLabel>
        <relationshipName>Netting_Group_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Netting Group Branch</label>
    <nameField>
        <displayFormat>NGB-{0000}</displayFormat>
        <label>Netting Group Branch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Netting Group Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Agreement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Awaiting Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Executed</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Send to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed/Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Amended</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled/Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Superceded</fullName>
        <isActive>false</isActive>
        <label>Superceded</label>
    </customValue>
    <description>Agreement Management (LEAP)</description>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

globalValueSets/Master_Agreement_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>GMRA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>GMSLA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>ISDA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Prime Services Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Supporting Agreement</fullName>
    </customValue>
    <masterLabel>Master Agreement Type</masterLabel>
</GlobalValueSet>

classes/Matter_Deal_Override_MarketTrans_Cont.cls
/**
* Created by KyleAlexander on 2018/03/14.
* 
* 16/04/2018 - TdB  - Add duplicateCheck() based on Bank, Relationship, Relationship Type and Master Agreement Type
*/

public with sharing class Matter_Deal_Override_MarketTrans_Cont {
    
    public advpm__Matter__c matter {get;set;}
    public Id MatterId {get;set;}
    public Boolean isNewMatter {get;set;}
    public Boolean isEditable {get;set;}
    
    public Matter_Deal_Override_MarketTrans_Cont (ApexPages.StandardController stdController) {
        MatterId = ApexPages.currentPage().getParameters().get('matterId');
        
        if(MatterId != null){
            matter = [select id, name, Bank__c, Relationship__c, Relationship_Type_picklist__c, Counterparty_Type__c,
                      Party_B__c, Master_Agreement_Type__c, Netting_Complete__c, Active__c, Netting_Applicable__c, Prime_Services_Client__c,
                      Collateral_Agreement_Flag__c, Collective_Investment_Scheme_Name__c, Collective_Investment_Scheme_Type__c
                      from advpm__Matter__c where id = :MatterId limit 1];
            isNewMatter = false;
            
            isEditable = true;
            List<Agreement__c> agreementList = [select Id, Agreement_Status__c FROM Agreement__c WHERE Matter_Deal__c = :MatterId];
            for(Agreement__c agreement : agreementList){
                if(agreement.Agreement_Status__c == 'Confirmed/Completed' || agreement.Agreement_Status__c == 'Amended' || agreement.Agreement_Status__c == 'Cancelled/Terminated'){
                    isEditable = false;
                    break;
                }
            }
        }
        else{
            matter = new advpm__Matter__c();
            
            matter.Party_B__c = true;
            
            List<Account> account = [select id, name, SDS__c from Account where SDS__c = '10250696' limit 1];
            
            if(!account.isEmpty())
            {
                matter.Bank__c = account[0].id;
            }
            
            id recId = Schema.SObjectType.advpm__Matter__c.getRecordTypeInfosByName().get('Market Transaction').getRecordTypeId();
            matter.RecordTypeId = recId;
            
            isNewMatter = true;
        }
    }
    
    public PageReference CancelPage() {
        PageReference pf = new PageReference('/' + matter.id);
        return pf;
    }
    
    public PageReference SaveMatter() {
        if(isNewMatter == false){
            if(matter.Netting_Complete__c == true){
                //Get all the Netting Groups
                List<Netting_Group__c> nettingGroups = [select id, name, Netting_Type__c from Netting_Group__c where Matter_Deal__c = :MatterId];
                //Get all netting types and check if all of those netting types have been added to the matter
                Schema.DescribeFieldResult fieldResult = Netting_Group__c.Netting_Type__c.getDescribe();
                List<Schema.PicklistEntry> nettingType = fieldResult.getPicklistValues();
                for(Schema.PicklistEntry nt : nettingType){
                    Boolean notAllAdded = false;
                    for(Netting_Group__c ng : nettingGroups){
                        if(ng.Netting_Type__c == nt.getValue()){
                            notAllAdded = true;
                            break;
                        }
                    }
                    if(notAllAdded == false){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR,'Not all Netting Groups have been added. Please add: ' + nt.getValue()));
                        return null;
                    }
                }
                
                //Get all of the existing netting group branches
                List<NettingGroupBranch__c> nettingGroupBranches = [Select id, Relationship__c, Relationship__r.Name, Trade_Instrument__c, Trade_Instrument__r.Name, NettingGroup__c, BranchType__c from NettingGroupBranch__c];
                
                //Get all the Bank branches
                List<Deal_Party__c> bankBranchList = [SELECT Id, Relationship__r.Name FROM Deal_Party__c WHERE Deal__c =: MatterId AND Relationship_Type__c = :'Bank Branch'];
                advpm__Matter__c matterBank = [SELECT Id, Bank__c, Bank__r.Name FROM advpm__Matter__c WHERE Id =: MatterId LIMIT 1];
                
                //Add all banks and bank branches to list
                List<Id> bankBranches = new List<Id>();
                for(Deal_Party__c dp : bankBranchList)
                {
                    bankBranches.add(dp.Relationship__r.Id);
                }
                bankBranches.add(matterBank.Bank__c);
                
                //Get all the Couterparties, dealParties etc.
                List<Deal_Party__c> counterpartyList = [SELECT Id, Relationship__r.Name FROM Deal_Party__c WHERE Deal__c =: MatterId AND (Relationship_Type__c =: 'Counterparty Branch' OR Relationship_Type__c = 'Qualified Investor Hedge Fund' OR Relationship_Type__c = 'Retail Hedge Fund')];
                List<advpm__Matter__c> matterCP = [SELECT Id, Relationship__c, Relationship_Type_picklist__c, Relationship__r.Name FROM advpm__Matter__c WHERE Id =: MatterId AND Relationship_Type_picklist__c =: 'Counterparty' LIMIT 1];
                List<Deal_Party__c> disclosedPrinciplesList = new List<Deal_Party__c>();
                if(matter.Relationship_Type_picklist__c == 'Asset Manager'){
                    disclosedPrinciplesList = [SELECT Id, Relationship__r.Name FROM Deal_Party__c WHERE Deal__c =: MatterId AND Relationship_Type__c =: 'Disclosed Principal'];
                }
                
                //Add all counterparties etc. to list
                List<Id> counterparties = new List<Id>();
                if(!disclosedPrinciplesList.isEmpty() || disclosedPrinciplesList != null){
                    for(Deal_Party__c disPrinc : disclosedPrinciplesList)
                    {
                        counterparties.add(disPrinc.Relationship__r.Id);
                    }
                }
                for(Deal_Party__c dp : counterpartyList)
                {
                    counterparties.add(dp.Relationship__r.Id);
                }
                if(matterCP.size() > 0)
                {
                    counterparties.add(matterCP[0].Relationship__c);
                }
                
                Set<Id> tradeInstrumentIds = new Set<Id>();
                
                //Get all Trade Instruments
                Map<Id, Agreement__c> agreementList = new Map<Id, Agreement__c>([
                    select
                    Id,
                    Agreement_Status__c
                    FROM Agreement__c
                    WHERE
                    Matter_Deal__c = :MatterId]);
                
                Set<Id> agreementIds = agreementList.keySet();
                
                
                List<Agreement_Trade_Instrument__c> agreementTradeInstruments = [select Agreement__c, Trade_Instrument__c FROM Agreement_Trade_Instrument__c WHERE Agreement__c IN :agreementIds];
                
                for(Agreement_Trade_Instrument__c ati : agreementTradeInstruments)
                {
                    tradeInstrumentIds.add(ati.Trade_Instrument__c);
                }
                
                List<Trade_Instrument__c> ti = [select id, name from Trade_Instrument__c WHERE Id IN :tradeInstrumentIds];
                
                //Add all trade instruments to list
                List<Id> tradeInstrument = new List<Id>();
                for(Trade_Instrument__c trIn : ti)
                {
                    tradeInstrument.add(trIn.Id);
                }
                
                List<NettingGroupBranch__c> tempTICloseOutList = new List<NettingGroupBranch__c>();
                List<NettingGroupBranch__c> tempTINovationList = new List<NettingGroupBranch__c>();
                List<NettingGroupBranch__c> tempTISettlementList = new List<NettingGroupBranch__c>();
                
                //Check that all bank and bank branches, counterparty and counterparty branches and disclosed principals associated with the market transaction have been associated with each netting group
                for(Netting_Group__c ng : nettingGroups){
                    List<NettingGroupBranch__c> tempBankList = new List<NettingGroupBranch__c>();
                    List<NettingGroupBranch__c> tempCoutperartyList = new List<NettingGroupBranch__c>();
                    for(NettingGroupBranch__c ngb : nettingGroupBranches){
                        if(ng.id == ngb.NettingGroup__c){
                            if(ngb.BranchType__c == 'Bank'){
                                tempBankList.add(ngb);
                            }
                            else if(ngb.BranchType__c == 'Counterparty'){
                                tempCoutperartyList.add(ngb);
                            }
                            else if (ngb.BranchType__c == 'Trade Instrument') {
                                if(ng.Netting_Type__c == 'Close Out'){
                                    tempTICloseOutList.add(ngb);
                                }
                                else if(ng.Netting_Type__c == 'Novation'){
                                    tempTINovationList.add(ngb);
                                }
                                else if(ng.Netting_Type__c == 'Settlement') {
                                    tempTISettlementList.add(ngb);
                                }
                            }
                        }
                    }
                    if(tempBankList.size() != bankBranches.size()){
                        String missingNames = getMissingBanksOrCounterparties(bankBranches, tempBankList, false);
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR,'Not all Banks / Bank Branches have been associated with each Netting Group. Please add the following Bank Branch: ' + missingNames.substring(0, missingNames.length() - 2) + ' for Netting Group: ' + ng.Name));
                        return null;
                    }                 
                    
                    if(tempCoutperartyList.size() != counterparties.size()){
                        String missingNames = getMissingBanksOrCounterparties(counterparties, tempCoutperartyList, false);
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR,'Not all Counterparty / Counterparty Branches / Disclosed Principals / Hedge Funds have been associated with each Netting Group. Please add the following Counterparty Branch / Disclosed Principal / Hedge Fund : ' + missingNames.substring(0, missingNames.length() - 2) + ' for Netting Group: ' + ng.Name));
                        return null;
                    }
                    
                }
                //Checks if all trade instruments are added
                if(!tempTICloseOutList.isEmpty()){
                    if(tempTICloseOutList.size() != tradeInstrument.size()) {
                        String missingNames = getMissingBanksOrCounterparties(tradeInstrument, tempTICloseOutList, true);
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, 'Not all Trade Instruments have been associated with the Netting Group of Type: Close Out. Please add the following Trade Instruments: ' + missingNames.substring(0, missingNames.length() - 2)));
                        return null;
                    }
                }
                if(!tempTINovationList.isEmpty()){
                    if(tempTINovationList.size() != tradeInstrument.size()) {
                        String missingNames = getMissingBanksOrCounterparties(tradeInstrument, tempTINovationList, true);
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, 'Not all Trade Instruments have been associated with the Netting Group of Type: Novation. Please add the following Trade Instruments: ' + missingNames.substring(0, missingNames.length() - 2)));
                        return null;
                    }
                }
                if(!tempTISettlementList.isEmpty()){
                    if(tempTISettlementList.size() != tradeInstrument.size()) {
                        String missingNames = getMissingBanksOrCounterparties(tradeInstrument, tempTISettlementList, true);
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, 'Not all Trade Instruments have been associated with the Netting Group of Type: Settlement. Please add the following Trade Instruments: ' + missingNames.substring(0, missingNames.length() - 2)));
                        return null;
                    }
                }
            }
            
            //Check if must set the matter to inactive
            if(matter.Active__c == false){
                id recId = Schema.SObjectType.advpm__Matter__c.getRecordTypeInfosByName().get('Market Transaction (Locked)').getRecordTypeId();
                matter.RecordTypeId = recId;
            }
            
            update matter;
            PageReference pf = new PageReference('/' + matter.id);
            return pf;
        }
        //Netting Complete has not been selected
        else{
            matter.Party_B__c = true;
            matter.Active__c = true;
            try{
                if(matter.Relationship_Type_picklist__c == 'Collective Investment Scheme Manager' && matter.Collective_Investment_Scheme_Name__c == null){
                    if(matter.Collective_Investment_Scheme_Type__c != 'Both' && matter.Collective_Investment_Scheme_Type__c != 'N/A'){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, 'Collective Investment Scheme Name cannot be empty if Collective Investment Scheme Manager is selected as a Relationship Type'));
                        return null;
                    }
                }
                insert matter;
                PageReference pf = new PageReference('/' + matter.id);
                return pf;
            }
            catch (DmlException e){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getDmlMessage(0)));
                return null;
            }
        }
    }
    
    public String getMissingBanksOrCounterparties(List<Id> branchList, List<NettingGroupBranch__c> tempList, Boolean isTradeInstrument){
        Set<Id> missingValues = new Set<Id>(branchList);
        Set<Id> tempSet = new Set<Id>();
        for(NettingGroupBranch__c ngb : tempList)
        {
            if(isTradeInstrument){
                tempSet.add(ngb.Trade_Instrument__c);
            }
            else{
                tempSet.add(ngb.Relationship__r.Id);
            }
        }
        
        missingValues.removeAll(tempSet);
        
        String missingNames = '';
        for(Id mv : missingValues){
            if(isTradeInstrument){
                Trade_Instrument__c tempTI = [select id, name from Trade_Instrument__c where id = :mv];
                missingNames += tempTI.Name + ', ';
            }
            else{
                Deal_Party__c tempBranch = [SELECT Id, Relationship__r.Name FROM Deal_Party__c WHERE Relationship__r.Id = :mv limit 1];
                missingNames += tempBranch.Relationship__r.Name + ', ';
            }
        }
        
        if(missingNames.equals('')){
            missingNames = 'Error';
        }
        
        return missingNames;
    }
    
    public pageReference duplicateCheck()
    {
        List<advpm__Matter__c> marketTransactionDuplicateList = new List<advpm__Matter__c>();
        String matterUrlString = '';
        
        if(!String.isBlank(matter.Relationship__c) && !String.isBlank(matter.Relationship_Type_picklist__c) && !String.isBlank(matter.Master_Agreement_Type__c) && !String.isBlank(matter.Bank__c)) 
        {
            //Get all existing Market Transaction where the Bank, Relationship, Relationship Type and Master Agreement Type is the same
            marketTransactionDuplicateList = [SELECT Id, Name, Bank__c, Relationship__c, Relationship_Type_picklist__c, Master_Agreement_Type__c 
                                              FROM advpm__Matter__c 
                                              WHERE Bank__c = :matter.Bank__c 
                                              AND Relationship__c = :matter.Relationship__c 
                                              AND Relationship_Type_picklist__c = :matter.Relationship_Type_picklist__c
                                              AND Master_Agreement_Type__c = :matter.Master_Agreement_Type__c
                                             ];
        }
        if(!marketTransactionDuplicateList.isEmpty()) 
        {
            for(advpm__Matter__c eachMatter : marketTransactionDuplicateList )
            {
                matterUrlString += '<li  style="margin-left:0px"><a href=' + site.getBaseSecureUrl() + '/' + eachMatter.Id + '>'  + eachMatter.Name + '</a></li>';
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Warning,'Please note that an ' + matter.Master_Agreement_Type__c + ' already exist between the Bank and Counterparty , Duplicate Market Transaction: <ul style="margin-top:5px">' + matterUrlString + '</ul>'));
        }
        
        return null;
    }
    
}