objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Business_Unit_Cluster_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Matters/Deals</relationshipLabel>
        <relationshipName>Matters_Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>Business Unit where query originates from</inlineHelpText>
        <label>Business Unit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claim_By_Against_Barclays__c</fullName>
        <label>Claim By/Against Barclays</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Claim By Barclays</fullName>
                </value>
                <value>
                    <fullName>Claim Against Barclays</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Probable_Approved__c</fullName>
        <label>Probable (Approved)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Probable_For_Approval__c</fullName>
        <label>Probable (For Approval)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reasonably_Possible__c</fullName>
        <label>Reasonably Possible</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Securitization_value__c</fullName>
        <label>Security value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>advpm__Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/advpm__Participant__c.object
<CustomObject>
    <customHelpPage>advpm__HelpParticipant</customHelpPage>
    <fields>
        <fullName>advpm__Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>advpm__Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Business_Unit_Claim__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Business Unit Claims</relationshipLabel>
        <relationshipName>Business_Unit_Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Business Unit Claims</relationshipLabel>
        <relationshipName>Business_Unit_Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portion_of_Claim__c</fullName>
        <label>Portion of Claim (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Business Unit Claim</label>
    <nameField>
        <displayFormat>BUC-{0000}</displayFormat>
        <label>Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Unit Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Matter_Relation__c.object
<CustomObject>
    <fields>
        <fullName>Matter1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter1</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Matter Relations</relationshipLabel>
        <relationshipName>Matter_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Matter Relations (Matter2)</relationshipLabel>
        <relationshipName>Matter_Relations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Matter Relation</label>
    <nameField>
        <label>Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matter Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Matter_Override_Litigation_Controller.cls
public with sharing class Matter_Override_Litigation_Controller {

	public advpm__Matter__c matterRec {get;set;}
    public Boolean showDuplicates {get;set;}
    public String boxFolderId {get;set;}
    public Boolean showBox {get;set;}
    public List<Duplicate> potentialDuplicates {get;set;}
    
    @TestVisible private List<advpm__Participant__c> participants;
    @TestVisible private List<Business_Unit_Claim__c> claims;

    public Matter_Override_Litigation_Controller() {

        Id litigationId = [SELECT Id FROM RecordType WHERE Name = 'Litigation Matter' AND SobjectType = 'advpm__Matter__c' LIMIT 1][0].Id;
        matterRec = new advpm__Matter__c(OwnerId = UserInfo.getUserId(), RecordTypeId = litigationId);

        if(potentialDuplicates == null)
            potentialDuplicates = new List<Duplicate>();

        participants = new List<advpm__Participant__c>();
        claims = new List<Business_Unit_Claim__c>();
        addClaim();
        
        showDuplicates = false;
        showBox = false;
        
    }

    public PageReference save() {

        if(ApexPages.getMessages().isEmpty() == false) {
            return null;
        }

        Decimal totalPercentage = 0;
        Boolean hasUnits = false;

        for(Business_Unit_Claim__c claim: claims) {

            if(claim.Business_Unit__c != null) {

                hasUnits = true;

                if(claim.Portion_of_Claim__c != null)
                    totalPercentage += claim.Portion_of_Claim__c;

            }
            
        }

        if(totalPercentage != 100 && hasUnits) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Claim apportions must add up to 100%'));
            return null;
        }
                
        saveMatter();
        saveClaims();
        saveParticipants();
        saveRelations();

        return null;

    }

    public PageReference done() {

        save();

        if(ApexPages.getMessages().isEmpty() == false) {
            return null;
        }

        PageReference retRef = new PageReference('/' + matterRec.Id);
        retRef.setRedirect(true);

        return retRef;

    }

    private void saveMatter() {

        if(matterRec.advpm__Description__c == null) {

            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Matter Summary is mandatory'));
            return;
        }

        if(matterRec.Name == null) {

            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Matter Name is mandatory'));
            return;
        }

        if(matterRec.Id == null)
            insert matterRec;
         else 
            update matterRec;       

    }

    public PageReference createBox() {

        if(ApexPages.getMessages().isEmpty() == false) {
            return null;
        }

        boxFolderId = BxdMatterDealService.createBoxFolderSync(matterRec.Id);
        showBox = true;
        return null;

    }

    public PageReference cancel() {

        PageReference redirect = new PageReference(ApexPages.currentPage().getParameters().get('retUrl'));        
        
        redirect.setRedirect(true);
        return redirect;

    }

    public List<advpm__Participant__c> getParticipants() {
        return participants;
    }
	
   @TestVisible private void saveParticipants() {

        if(ApexPages.getMessages().isEmpty() == false) {
            return;
        }

        List<advpm__Participant__c> toSave = new List<advpm__Participant__c>();
        Set<Id> userIds = new Set<Id>();

        for(advpm__Participant__c part: participants) {
            if(part.advpm__Staff__c != null) {

                part.advpm__Matter__c = matterRec.Id;
                userIds.add(part.advpm__Staff__c);
                toSave.add(part);

            }
        }

        Map<Id, User> participantUsersMap = new Map<Id, User>([SELECT Id, Profile.Name FROM User WHERE Id IN :userIds]);

        for(advpm__Participant__c part: toSave) {
            if(!participantUsersMap.get(part.advpm__Staff__c).Profile.Name.contains('Litigation')) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'All participants must be Litigation users'));
                part.advpm__Staff__c.addError('User is not a Litigation user');
            }
        }

        if(ApexPages.getMessages().isEmpty()) {
            upsert toSave;
            toSave.clear();
        }

    }

    public PageReference addParticipant() {
        participants.add(new advpm__Participant__c());
        return null;
    }

    //Although the List is unordered and the user may have filled in 
    //from the back of the list because s/he is weird, 
    //this is the most reliable method
    public PageReference removeParticipant() {

        participants.remove(participants.size() - 1);
        return null;

    }

    public List<Business_Unit_Claim__c> getClaims() {
        return claims;
    }

    private void saveClaims() {

        if(ApexPages.getMessages().isEmpty() == false) {
            return;
        }

        List<Business_Unit_Claim__c> toSave = new List<Business_Unit_Claim__c>();        

        for(Business_Unit_Claim__c claim: claims) {
            if(claim.Business_Unit__c != null) {

                claim.Matter__c = matterRec.Id;
                toSave.add(claim);

            }
        }

        if(toSave.size() != 0) {            

            upsert toSave;
            toSave.clear();
                            
        }
        else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Must have business unit'));
        }

    }

    public PageReference addClaim() {
        claims.add(new Business_Unit_Claim__c());
        return null;
    }

    //Although the List is unordered and the user may have filled in 
    //from the back of the list because s/he is weird, 
    //this is the most reliable method. One claim must remain.
    public PageReference removeClaim() {

        Integer endList = claims.size() - 1;

        if(endList > 0)
            claims.remove(endList);

        return null;

    }

    private void saveRelations() {

        if(potentialDuplicates == null)
            return;

        if(ApexPages.getMessages().isEmpty() == false) {
            return;
        }

        List<Matter_Relation__c> toInsert = new List<Matter_Relation__c>();

        for(Duplicate dup: potentialDuplicates) 
            if(dup.isRelated)
                toInsert.add(new Matter_Relation__c(Matter1__c = matterRec.Id, Matter2__c = dup.matter.Id, Name = dup.matter.Name));
        
        Database.SaveResult[] results = Database.Insert(toInsert, false);

        //TODO
        //for(Database.SaveResult res: results)
        //    if(!res.isSuccess())
        //        for(Database.Error err: res.getErrors())
        //            if(!err.getMessage().contains('DUPLICATE_VALUE'))
        //                throw err;

    }

    public class Duplicate {

        public advpm__Matter__c matter {get;set;}
        public Boolean isRelated {get;set;}

        public Duplicate(advpm__Matter__c potentialDuplicate) {
            this.matter = potentialDuplicate;
            this.isRelated = false;
        }

    }

    public PageReference searchDupes() {

        if(String.isBlank(matterRec.Name)){

            showDuplicates = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Potential duplicates cannot be determined without a name!'));
        
        }
        else {

            String likeToken = String.format('%{0}%', new List<String>{matterRec.Name});
            List<advpm__Matter__c> queryResult = [SELECT Id, Name, OwnerId, advpm__Description__c, Business_Unit_Cluster_Segment__c FROM advpm__Matter__c WHERE Name LIKE :likeToken];

            for(advpm__Matter__c res: queryResult) 
                potentialDuplicates.add(new Duplicate(res));

            showDuplicates = true;

        }

        return null;
    }

    public PageReference clearFinancial() {

        matterRec.Reasonably_Possible__c = null;
        matterRec.Probable_For_Approval__c = null;
        matterRec.Securitization_value__c = null;

        return null;

    }

    public PageReference claimTypeChange() {

        if(matterRec.Claim_By_Against_Barclays__c == 'Claim By Barclays') {

            matterRec.Probable_Approved__c = matterRec.Probable_For_Approval__c;
            matterRec.Probable_For_Approval__c = null;

        }
        else if(matterRec.Claim_By_Against_Barclays__c == 'Claim Against Barclays') {

            matterRec.Probable_For_Approval__c = matterRec.Probable_Approved__c;
            matterRec.Probable_Approved__c = null;

        } 

        return null;

    }

}