objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>Business Unit where query originates from</inlineHelpText>
        <label>Business Unit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GMRA Agreement</fullName>
                </value>
                <value>
                    <fullName>GMSLA Agreement</fullName>
                </value>
                <value>
                    <fullName>ISDA Agreement</fullName>
                </value>
                <value>
                    <fullName>Prime Services Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Absa_as_Agent_Principal__c</fullName>
        <label>Absa as Agent / Principal</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>principal/agent</fullName>
                </value>
                <value>
                    <fullName>principal but not as agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Absa_as_Borrower_Lender__c</fullName>
        <label>Absa as Borrower / Lender</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Borrower</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agreement_ID__c</fullName>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Agreement ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agreement_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Break_Clause_days__c</fullName>
        <label>Break Clause (days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ABSA Capital Securities PTY LTD</fullName>
                </value>
                <value>
                    <fullName>CIB</fullName>
                </value>
                <value>
                    <fullName>Prime Services</fullName>
                </value>
                <value>
                    <fullName>Wealth</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cash_Amount__c</fullName>
        <label>Cash Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cash_Amount_counterparty__c</fullName>
        <label>Cash Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Counterparty_as_Borrower_Lender__c</fullName>
        <label>Counterparty as Borrower / Lender</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Borrower</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_of_Issue__c</fullName>
        <label>Country of Issue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cross_Default_Threshold_Re_Absa__c</fullName>
        <label>Cross Default Threshold Re Absa</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cross_Default_Threshold_Re_Counterparty__c</fullName>
        <label>Cross Default Threshold Re Counterparty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Equity_Percentage_Counterparty__c</fullName>
        <label>Equity Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Equity_Percentage__c</fullName>
        <label>Equity Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ExternalAgreementId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalAgreementId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Governing_Law__c</fullName>
        <label>Governing Law</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Australian</fullName>
                </value>
                <value>
                    <fullName>Australian Capital Territory</fullName>
                </value>
                <value>
                    <fullName>Belgium Law (2016 CSA)</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>California - USA</fullName>
                </value>
                <value>
                    <fullName>Canadian</fullName>
                </value>
                <value>
                    <fullName>Delaware - USA</fullName>
                </value>
                <value>
                    <fullName>English Law</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Irish</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Malaysian</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>New South Wales - Australian</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>People&apos;s Republic of China</fullName>
                </value>
                <value>
                    <fullName>Queelsland</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>South African Law</fullName>
                </value>
                <value>
                    <fullName>South Australia</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>State of New York Law</fullName>
                </value>
                <value>
                    <fullName>Swiss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin_Maintenance_Amount_Absa__c</fullName>
        <label>Margin Maintenance Amount - Absa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Net Exposure</fullName>
                </value>
                <value>
                    <fullName>Own Amount</fullName>
                </value>
                <value>
                    <fullName>Zero</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin_Maintenance_Amount_Counterparty__c</fullName>
        <label>Margin Maintenance Amount - Counterparty</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Net Exposure</fullName>
                </value>
                <value>
                    <fullName>Own Amount</fullName>
                </value>
                <value>
                    <fullName>Zero</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin_Maintenance_Own_Amount_Absa__c</fullName>
        <label>Margin Maintenance Own Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Margin_Maintenance_Own_Amount_Counter__c</fullName>
        <label>Margin Maintenance Own Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Name__c</fullName>
        <formula>Matter_Deal__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Agreement Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Required_Prior_to_First__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Master Agreement Required Prior to First</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Start_Date__c</fullName>
        <label>Master Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_Agreement_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Agreement_Version__c</fullName>
        <label>Master Agreement Version</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_Agreement_Version</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Amendment__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreement Amendments</relationshipLabel>
        <relationshipName>Agreeement_Amendments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Amendment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Amendment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Market_Collateral__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Market Collaterals</relationshipLabel>
        <relationshipName>Market_Collaterals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_of_Issue__c</fullName>
        <label>Country of Issue</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Collateral_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <label>Market Collateral</label>
    <nameField>
        <displayFormat>MC-{00000}</displayFormat>
        <label>Market Collateral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Agreement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Awaiting Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Executed</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Send to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed/Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Amended</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled/Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Superceded</fullName>
        <isActive>false</isActive>
        <label>Superceded</label>
    </customValue>
    <description>Agreement Management (LEAP)</description>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Abu Dhabi Global Market</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

globalValueSets/Master_Agreement_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>GMRA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>GMSLA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>ISDA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Prime Services Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Supporting Agreement</fullName>
    </customValue>
    <masterLabel>Master Agreement Type</masterLabel>
</GlobalValueSet>

globalValueSets/Master_Agreement_Version.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1987 ISDA</fullName>
    </customValue>
    <customValue>
        <fullName>1992 GMRA</fullName>
    </customValue>
    <customValue>
        <fullName>1992 ISDA</fullName>
    </customValue>
    <customValue>
        <fullName>1995 GMRA</fullName>
    </customValue>
    <customValue>
        <fullName>2000 GMRA</fullName>
    </customValue>
    <customValue>
        <fullName>2000 GMSLA</fullName>
    </customValue>
    <customValue>
        <fullName>2002 ISDA</fullName>
    </customValue>
    <customValue>
        <fullName>2009 GMSLA</fullName>
    </customValue>
    <customValue>
        <fullName>2010 GMSLA</fullName>
    </customValue>
    <customValue>
        <fullName>2011 GMRA</fullName>
    </customValue>
    <customValue>
        <fullName>2011 GMSLA</fullName>
    </customValue>
    <customValue>
        <fullName>Collective Investment Scheme</fullName>
    </customValue>
    <customValue>
        <fullName>CSA</fullName>
    </customValue>
    <masterLabel>Master Agreement Version</masterLabel>
</GlobalValueSet>

classes/MasterAgreementEdit_Cont.cls
/**
 * Created by Kyle Alexander on 2018/02/20.
 */

public with sharing class MasterAgreementEdit_Cont {
    public Agreement__c agreement {get;set;}

    public Boolean agreementPanel {get;set;}
    public Boolean amendmentPanel {get;set;}
    public Boolean closurePanel {get;set;}

    public Amendment__c amendment {get;set;}
    public String amendmentType {get;set;}
    public String amendmentReason {get;set;}
    public Date amendmentDate {get;set;}
    public String regulationName {get;set;}
    public Boolean amendmentDocument {get;set;}

    public Boolean isdaPanel {get;set;}
    public Boolean gmraPanel {get;set;}
    public Boolean gmslaPanel {get;set;}
    public Boolean primeServPanel {get;set;}

    public String initialAgreementStatus;

    public Boolean collateralPanel {get;set;}
    public Boolean changePanel {get;set;}

    public List<Market_Collateral__c> collateralItems {get; set;}
    public List<Market_Collateral__c> addedCollateral {get; set;}
    public Id addedColId {get; set;}
    
    public Boolean mustShowStatusWarningMessage {get; set;}
    
    public MasterAgreementEdit_Cont (ApexPages.StandardController stdController) {

        Id agreementId = ApexPages.currentPage().getParameters().get('id');
        
        agreement = [Select id, Name, RecordTypeId, Master_Agreement_Type__c, Agreement_ID__c, Master_Agreement_Start_Date__c,
                Master_Agreement_Required_Prior_to_First__c, Break_Clause_days__c, Master_Agreement_Version__c,
                ExternalAgreementId__c, Agreement_Status__c, Master_Agreement_Name__c, Matter_Deal__c, Governing_Law__c,
                Country_of_Issue__c, Cross_Default_Threshold_Re_Absa__c, Cash_Amount__c, Equity_Percentage__c,
                Cross_Default_Threshold_Re_Counterparty__c, Cash_Amount_counterparty__c, Equity_Percentage_Counterparty__c,
                Business_Unit__c, Margin_Maintenance_Amount_Absa__c, Margin_Maintenance_Own_Amount_Absa__c,
                Margin_Maintenance_Amount_Counterparty__c, Margin_Maintenance_Own_Amount_Counter__c,
                Absa_as_Borrower_Lender__c, Absa_as_Agent_Principal__c, Counterparty_as_Borrower_Lender__c,
                Counterparty_as_Agent_Principal__c, Undisclosed__c, Principal_Type__c, Termination_Currency__c, Calculation_Agent__c, Currency_Re_Absa__c,
                Currency_Re_Counterparty__c, Closure_Reason__c, Agreement_Comments__c, Bank_Minimum_Transfer_Amount__c, Counterparty_Minimum_Transfer_Amount__c,
                Bilateral_Unilateral__c, Triparty_Agent__c, Base_Currency__c, Loan_Name__c, Loan_Linked__c, Facility_Loan_Name__c, Transaction_Exposure_Calculation_Method__c, 
                Buy_Sell_Back_Applies__c, Bank__c, Relationship__c
        from Agreement__c where id = :agreementId];

        String name = Agreement__c.sObjectType.getDescribe().getRecordTypeInfosById().get(agreement.RecordTypeId).getName();
        System.debug(name);
        System.debug(agreement);

        //Agreement Status
        initialAgreementStatus = this.agreement.Agreement_Status__c;

        //Amendment
        amendment = new Amendment__c();

        getCategories();

        agreementPanel = true;
        amendmentPanel = false;
        closurePanel = false;
        changePanel = false;

        isdaPanel = false;
        gmraPanel = false;
        gmslaPanel = false;
        primeServPanel = false;
        
        mustShowStatusWarningMessage = false;

        if(agreement.Master_Agreement_Type__c == 'ISDA Agreement'){
            isdaPanel = true;
            advpm__Matter__c m = [select id, Relationship_Type_picklist__c, Netting_Complete__c from advpm__Matter__c where id = :agreement.Matter_Deal__c limit 1];
            if(m.Netting_Complete__c == false && (m.Relationship_Type_picklist__c == 'Collective Investment Scheme Manager' || m.Relationship_Type_picklist__c == 'Asset Manager')){
                mustShowStatusWarningMessage = true;
            }
        }
        else if(agreement.Master_Agreement_Type__c == 'GMRA Agreement'){
            gmraPanel = true;
        }
        else if(agreement.Master_Agreement_Type__c == 'GMSLA Agreement'){
            gmslaPanel = true;
        }
        else if(agreement.Master_Agreement_Type__c == 'Prime Services Agreement'){
            primeServPanel = true;
        }
    }

    public PageReference CancelPage() {
        PageReference pf = new PageReference('/' + agreement.id);
        return pf;
    }

    public PageReference SaveAgreement() {
        Boolean mustBeAmended = false;

        if(!(agreement.Master_Agreement_Required_Prior_to_First__c)){
            if(agreement.Break_Clause_days__c == null){
                apexpages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'If Master Agreement Required Prior to First is selected, you have to enter a value for Break Clause (days)'));
                return null;
            }
        }

        /*Check if it must be ameneded*/
        if(agreement.Agreement_Status__c == 'Amended')
        {
            mustBeAmended = true;
        }
        else if(initialAgreementStatus == 'Confirmed/Completed' || initialAgreementStatus == 'Amended'){
            if(agreement.Agreement_Status__c == 'Confirmed/Completed' || agreement.Agreement_Status__c == 'Amended'){
                mustBeAmended = true;
            }
            else{
                mustBeAmended = false;
            }
        }
        else{
            mustBeAmended = false;
        }

        /*Check if change panel must be shown*/
        if(initialAgreementStatus == 'Cancelled/Terminated'){
            if(agreement.Agreement_Status__c != 'Cancelled/Terminated'){
                agreementPanel = false;
                amendmentPanel = false;

                isdaPanel = false;
                gmraPanel = false;
                gmslaPanel = false;
                collateralPanel = false;
                closurePanel = false;

                changePanel = true;

                return null;
            }
        }
        /*Check if it must be closed*/
        if(agreement.Agreement_Status__c == 'Cancelled/Terminated'){
            agreementPanel = false;
            amendmentPanel = false;

            isdaPanel = false;
            gmraPanel = false;
            gmslaPanel = false;
            collateralPanel = false;

            closurePanel = true;

            return null;
        }
        else{
            if(mustBeAmended){
                agreementPanel = false;
                amendmentPanel = true;

                isdaPanel = false;
                gmraPanel = false;
                gmslaPanel = false;
                collateralPanel = false;

                closurePanel = false;

                return null;
            }
            else{
                try
                {
                    update agreement;
                    PageReference pf = new PageReference('/' + agreement.id);
                    return pf;
                }
                catch(Exception ex){
                    ApexPages.addMessages(ex);
                    return null;
                }

                
            }
        }
    }

    public PageReference CancelAmendment() {
        PageReference pf = new PageReference('/' + agreement.id);
        return pf;
    }

    public PageReference SaveAmendment() {
        amendment.Amendment_Reason__c = amendmentReason;
        amendment.Amendment_Reason_Type__c = amendmentType;
        amendment.Effective_date__c = amendmentDate;
        amendment.Name_of_Regulation__c = regulationName;
        amendment.Agreement__c = agreement.id;

        if (amendmentDocument) {
            amendment.Amendment_Document_Uploaded__c = true;
            agreement.Agreement_Status__c = 'Amended';
        } else {
            amendment.Amendment_Document_Uploaded__c = false;
        }

        try {
            update agreement;
            insert amendment;
        }
        catch(exception ex) {
            ApexPages.addMessages(ex);
            return null;
        }

        PageReference pr = new PageReference('/' + agreement.id);
        pr.setRedirect(true);
        return pr;
    }

    public List<SelectOption> getCategories() {
        List<SelectOption> categories = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Amendment__c.Amendment_Reason_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : ple)
        {
            categories.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return categories;
    }

    public PageReference CancelClosure() {
        PageReference pf = new PageReference('/' + agreement.id);
        return pf;
    }

    public PageReference SaveClosure() {
        try {
            update agreement;
        }
        catch(DMLException e) {
            apexpages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'There was an issue creating the closure please try again or contact a system administrator :' + e.getMessage()));
            return null;
        }

        PageReference pr = new PageReference('/' + agreement.id);
        pr.setRedirect(true);
        return pr;
    }

    public PageReference CancelChange() {
        PageReference pf = new PageReference('/' + agreement.id);
        return pf;
    }
    
    public PageReference SaveChange() {
        try {
            update agreement;
        }
        catch(DMLException e) {
            apexpages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'There was an issue creating the change please try again or contact a system administrator :' + e.getMessage()));
            return null;
        }

        PageReference pr = new PageReference('/' + agreement.id);
        pr.setRedirect(true);
        return pr;
    }
}