objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <inlineHelpText>Legal area you work in</inlineHelpText>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CIB</fullName>
                </value>
                <value>
                    <fullName>RBB</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Africa Docman</fullName>
                    <isActive>false</isActive>
                    <label>Africa Docman</label>
                </value>
                <value>
                    <fullName>Africa Shared Services</fullName>
                    <isActive>false</isActive>
                    <label>Africa Shared Services</label>
                </value>
                <value>
                    <fullName>Debt</fullName>
                    <isActive>false</isActive>
                    <label>Debt</label>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                    <isActive>false</isActive>
                    <label>Distribution</label>
                </value>
                <value>
                    <fullName>Global Markets</fullName>
                    <isActive>false</isActive>
                    <label>Global Markets</label>
                </value>
                <value>
                    <fullName>HOTH</fullName>
                    <isActive>false</isActive>
                    <label>HOTH</label>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                    <isActive>false</isActive>
                    <label>Infrastructure</label>
                </value>
                <value>
                    <fullName>Investment Banking</fullName>
                    <isActive>false</isActive>
                    <label>Investment Banking</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>WIMI</fullName>
                    <isActive>false</isActive>
                    <label>WIMI</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Specify start date of the Deal/Transation</description>
        <inlineHelpText>Specify Transaction/Deal start date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>advpm__Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matters</relationshipLabel>
        <relationshipName>Matters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>advpm__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Discharged</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>In Appeal</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Matured</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>advpm__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bilateral</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Corporate Transaction</fullName>
                </value>
                <value>
                    <fullName>Criminal</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Government Affairs</fullName>
                </value>
                <value>
                    <fullName>IP</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Personal Injury</fullName>
                </value>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Syndicated</fullName>
                </value>
                <value>
                    <fullName>Taxation</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <label>Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Matter_Spend_Document__c.object
<CustomObject>
    <fields>
        <fullName>BU_Corporate_Code__c</fullName>
        <label>BU Corporate Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GL_Account__c</fullName>
        <label>GL Account</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>On/Off Panel Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matter Spend Documents</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Matter Spend Document</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Queried</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved For Payment</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount_Excl_VAT__c</fullName>
        <description>value of items that are non VAT exempt (where VAT applies)</description>
        <inlineHelpText>value of items that are non VAT exempt (where VAT applies)</inlineHelpText>
        <label>Total Amount (Incl. VAT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Non_VATable__c</fullName>
        <description>Total value of items that are VAT exempt.</description>
        <inlineHelpText>Total value of items that are VAT exempt.</inlineHelpText>
        <label>Total Amount (Excl. VAT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Matter Spend Document</label>
    <nameField>
        <displayFormat>MSD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matter Spend Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Matter_Spend_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Document_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Exported</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Matter Spend Schedule</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Schedule #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matter Spend Schedules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product_Level_2__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Level 2</relationshipLabel>
        <relationshipName>Product_Level_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Level 2</label>
    <nameField>
        <label>Level 2 Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Level 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BxdMatterSpend_test.cls
/**
 * 
 * 26/02/2018 - TdB	- Change Financial_Year_End__c from Date to a picklist 
 * 
 * */
@Istest
public class BxdMatterSpend_test {  
    public static Map <String, Schema.RecordTypeInfo> mapAccountRecordTypes = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
    public static Map <String, Schema.RecordTypeInfo> mapMatterRecordTypes = advpm__Matter__c.sObjectType.getDescribe().getRecordTypeInfosByName();  
    public static Account 				    TestAccount;
    public static advpm__Matter__c 		    TestMatter;
    public static DateTime todaysDate_nextMonth = System.now().addMonths(1);
    
    public static testmethod void testSpendDocumentFolderCreation(){
        setup();
        test.StartTest();
        Matter_Spend_Document__c TestSpendDocument = new Matter_Spend_Document__c(
            Matter__c = TestMatter.Id,
            Law_Firm__c = TestAccount.Id,
            Total_Amount_Excl_VAT__c = 100,
            Total_Amount_Non_VATable__c = 50,
            GL_Account__c = '123',
            BU_Corporate_Code__c = '123'
        );
        insert TestSpendDocument;
        test.StopTest();   
    }
   
    public static void setup(){
        //USER RECORD
        User TestUser = createUser('Barclays Standard User','AdvoUser@fakeddomain11235z.co.za');
        insert TestUser;
        
        //ACCOUNT
        TestAccount = new Account
        (
            Name = 'The name for testing '+ generateRandomString(6), 
            Type = 'Client',
            Financial_Year_End_Month__c = todaysDate_nextMonth.format('MMMM'),
            RecordTypeId = mapAccountRecordTypes.get('On/Off Panel Law Firm').getRecordTypeId() //Added
        );
        Insert TestAccount; 
        //PRODUCT
        Product2 TestProduct2 = new Product2
        (
            Name = 'Corporate Finance',
            ProductCode = 'Pro-X',
            isActive = true
        );
        insert TestProduct2;
        
        //PRODUCT LEVEL 2 
        Product_Level_2__c TestProductLevel2 =  new Product_Level_2__c
        (
            Name = 'SUB100',
            Active__c = true,
            Product__c = TestProduct2.id
        );
        insert TestProductLevel2;
        //MATTER
        TestMatter = new advpm__Matter__c
        (
            advpm__Primary_Account__c = TestAccount.id,
            Name = 'Test',
            Standard__c = true,
            advpm__Status__c = 'Open',
            advpm__Type__c='Syndicated',
            Start_Date__c = date.today(),
            RecordTypeId = mapMatterRecordTypes.get('Deal').getRecordTypeId(),
            Division__c = 'CIB',
            Coverage_Area__c = 'Corporate Banking',
            Product_Area__c = 'Corporate Finance',
            Product2__c = TestProductLevel2.Id,
            OwnerId = TestUser.Id
        );
        insert TestMatter;
    }
    
        //New user
    public static User createUser(string profile, string username)
    {
        username = Math.random()+ username;
        user newUser;
        try 
        {
            Profile userProfile = [select Name from Profile where Name = :profile];
            
            newUser = new User(Alias = 'test',
                   Email = 'one@test.sbsa.co.za',
                   Emailencodingkey = 'UTF-8',
                   Lastname = profile + ' User',
                   Languagelocalekey = 'en_US',
                   City = 'Johannesburg',
                   Country = 'South Africa',
                   Division__c = 'Barclays',
                   BRID__c = String.valueOf(Math.random()).left(9),
                   Localesidkey = 'en_US',
                   Profileid = userProfile.Id,
                   Timezonesidkey = 'America/Los_Angeles',
                   Username = username,
                   Can_Approve_Spend_Schedules__c = true
           );
        } 
        catch(Exception e) 
        {
            system.assertEquals('List has no rows for assignment to SObject Profile', e.getMessage());
        }
        return newUser;
    } 
    
    public static testmethod void testCreatePermission(){
        setup();
        
        Matter_Spend_Schedule__c schedule = new Matter_Spend_Schedule__c(
            Status__c = 'Approved'
        );
        insert schedule;
        
        Matter_Spend_Document__c TestSpendDocument = new Matter_Spend_Document__c(
            Matter__c = TestMatter.Id,
            Law_Firm__c = TestAccount.Id,
            Total_Amount_Excl_VAT__c = 100,
            Total_Amount_Non_VATable__c = 50,
            GL_Account__c = '123',
            BU_Corporate_Code__c = '123',
            Matter_Spend_Schedule__c = schedule.Id
        );
        insert TestSpendDocument;
        test.StartTest();
        BxdMatterSpendScheduleService scr = new BxdMatterSpendScheduleService();
        scr.createBoxFolderSync(TestSpendDocument.Id);
        BxdMatterSpendScheduleService.createViewerPermission(schedule);
        test.StopTest(); 
        
    }
    
    public static testmethod void testUpdateRemoveFromSchedule(){
        setup();
        
        Matter_Spend_Schedule__c schedule = new Matter_Spend_Schedule__c(
            Status__c = 'Approved'
        );
        insert schedule;
        
        Matter_Spend_Document__c TestSpendDocument = new Matter_Spend_Document__c(
            Matter__c = TestMatter.Id,
            Law_Firm__c = TestAccount.Id,
            Total_Amount_Excl_VAT__c = 100,
            Total_Amount_Non_VATable__c = 50,
            GL_Account__c = '123',
            BU_Corporate_Code__c = '123',
            Matter_Spend_Schedule__c = schedule.Id
        );
        insert TestSpendDocument;
        test.StartTest();
        TestSpendDocument.Matter_Spend_Schedule__c = null;
        Update TestSpendDocument;
        test.StopTest(); 
        
    }
    
    public static testmethod void testUpdateAddToSchedule(){
        setup();
        Matter_Spend_Document__c TestSpendDocument = new Matter_Spend_Document__c(
            Matter__c = TestMatter.Id,
            Law_Firm__c = TestAccount.Id,
            Total_Amount_Excl_VAT__c = 100,
            Total_Amount_Non_VATable__c = 50,
            GL_Account__c = '123',
            BU_Corporate_Code__c = '123'
        );
        insert TestSpendDocument;
        test.StartTest();
        Matter_Spend_Schedule__c schedule = new Matter_Spend_Schedule__c(
            Status__c = 'Approved'
        );
        insert schedule;
        
        TestSpendDocument.Matter_Spend_Schedule__c = schedule.Id;
        Update TestSpendDocument;
        test.StopTest(); 
        
    }
    
    public static testmethod void testBoxLink(){
        setup();
        
        Matter_Spend_Schedule__c schedule = new Matter_Spend_Schedule__c(
            Status__c = 'Approved'
        );
        insert schedule;
        
        test.StartTest();
        BxdMatterSpendScheduleService.getBoxFolderLink(schedule);
        test.StopTest(); 
        
    }
    
    //Generate String
    public static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'; 
        String randStr = '';
        while (randStr.length() < len) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length()); 
            randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }
}