objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Netting_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Netting Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <formula>advpm__Primary_Account__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship Type</label>
        <type>Text</type>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <label>Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agreement_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <formula>TEXT(Matter_Deal__r.Relationship_Type_picklist__c)</formula>
        <label>Relationship Type</label>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Amendment__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreement Amendments</relationshipLabel>
        <relationshipName>Agreeement_Amendments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amendment_Document_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amendment Document Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amendment_Reason_Type__c</fullName>
        <label>Amendment Reason Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Amendment_Reason_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amendment_Reason__c</fullName>
        <description>Field used to prompt user to complete field when &apos;other&apos; is selected on amendment reason type</description>
        <label>Amendment Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_date__c</fullName>
        <label>Effective date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Amendments</relationshipLabel>
        <relationshipName>Amendments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_of_Regulation__c</fullName>
        <label>Name of Regulation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Amendment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Amendment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal_Party__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Deal Parties</relationshipLabel>
        <relationshipName>Deal_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party Guarantor</fullName>
                </value>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>Bank Branch</fullName>
                </value>
                <value>
                    <fullName>Collective Investment Scheme Manager</fullName>
                </value>
                <value>
                    <fullName>Counterparty</fullName>
                </value>
                <value>
                    <fullName>Counterparty Branch</fullName>
                </value>
                <value>
                    <fullName>Cross Guarantor</fullName>
                </value>
                <value>
                    <fullName>Custodian</fullName>
                </value>
                <value>
                    <fullName>Disclosed Principal</fullName>
                </value>
                <value>
                    <fullName>Qualified Investor Hedge Fund</fullName>
                </value>
                <value>
                    <fullName>Retail Hedge Fund</fullName>
                </value>
                <value>
                    <fullName>Security Provider</fullName>
                </value>
                <value>
                    <fullName>Specified Entity Bank</fullName>
                </value>
                <value>
                    <fullName>Specified Entity Counterparty</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal Party</label>
    <nameField>
        <displayFormat>DP-{00000}</displayFormat>
        <label>Deal Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Agreement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Awaiting Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Executed</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Send to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed/Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Amended</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled/Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Superceded</fullName>
        <isActive>false</isActive>
        <label>Superceded</label>
    </customValue>
    <description>Agreement Management (LEAP)</description>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

globalValueSets/Amendment_Reason_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Regulatory compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Amendment Reason Type</masterLabel>
</GlobalValueSet>

classes/dealPartyOverride_Cont.cls
public with sharing class dealPartyOverride_Cont {

    public advpm__Matter__c matter {get;set;}
    public Id MatterId {get;set;}
    public Deal_Party__c dealParty {get;set;}
    
    public Amendment__c amendment {get;set;}
    public String amendmentType {get;set;}
    public String amendmentReason {get;set;}
    public Date amendmentDate {get;set;}
    public String regulationName {get;set;}
    public Boolean amendmentDocument {get;set;}
    
    public Boolean mustBeAmended {get;set;}
    public Boolean dealPartyPanel {get;set;}
    public Boolean amendmentPanel {get;set;}
    
    public Boolean isLibraDeal {get;set;}

    public dealPartyOverride_Cont (ApexPages.StandardController stdController) {
        MatterId = ApexPages.currentPage().getParameters().get('matterId');
        id tmgRecordId = Schema.SObjectType.Deal_Party__c.getRecordTypeInfosByName().get('TMG Deal Party').getRecordTypeId();
        id libraRecordId = Schema.SObjectType.Deal_Party__c.getRecordTypeInfosByName().get('CNSG Deal Party').getRecordTypeId();

        if(MatterId != null){
            matter = [select id, name, RecordTypeId, Netting_Complete__c from advpm__Matter__c where id = :MatterId limit 1];
            
            dealParty = new Deal_Party__c();
            dealParty.Deal__c = matter.id;
            
            //Check if the Matter is a Libra Matter or if it is a TMG Matter
            if(matter.RecordTypeId == Schema.SObjectType.advpm__Matter__c.getRecordTypeInfosByName().get('Deal').getRecordTypeId()){
                isLibraDeal = false;
                dealParty.RecordTypeId = tmgRecordId;
            }
            else{
                isLibraDeal = true;
                dealParty.RecordTypeId = libraRecordId;
            }
            
            if(matter.Netting_Complete__c){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.WARNING,'If a Bank Branch, Counterparty Branch, Retail Hedge Fund, Qualified Investor Hedge Fund or Disclosed Principal is added, it will make Netting Incomplete.'));
            }
            
            if(isLibraDeal){
                amendment = new Amendment__c();
            
                mustBeAmended = false;
                dealPartyPanel = true;
                amendmentPanel = false;
                
                List<Agreement__c> agreements = [SELECT id, Agreement_Status__c from Agreement__c where Matter_Deal__c = :MatterId];
                for(Agreement__c agreement : agreements){
                    if(agreement.Agreement_Status__c == 'Confirmed/Completed' || agreement.Agreement_Status__c == 'Amended'){
                        mustBeAmended = true;
                        break;
                    }
                }      
            }
            else{
                mustBeAmended = false;
                dealPartyPanel = false;
                amendmentPanel = false;
            }
		}
    }

    public PageReference cancel() {
        PageReference pf = new PageReference('/' + matter.id);
        return pf;
    }

    public PageReference save() {
        if(mustBeAmended) {
            dealPartyPanel = false;
            amendmentPanel = true;
            
            return null;
        }
        else{
            try{
                saveDealParty();
                PageReference pf = new PageReference('/' + matter.id);
        		return pf; 
            }
            catch (DmlException e){
            	ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getDmlMessage(0)));
            	return null;
        	}
        }
    }
    
    public PageReference saveTmgDealParty() {
        try{
            //Set record type to tmg specific one
            id tmgRecordId = Schema.SObjectType.Deal_Party__c.getRecordTypeInfosByName().get('TMG Deal Party').getRecordTypeId();
            dealParty.RecordTypeId = tmgRecordId;
            
            insert dealParty;
            
            PageReference pf = new PageReference('/' + matter.id);
        	return pf;
        }
        catch (DmlException e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getDmlMessage(0)));
            return null;
        }
    }
    
    public PageReference saveDealParty() {
        //Set record type to libra specific one
        id libraRecordId = Schema.SObjectType.Deal_Party__c.getRecordTypeInfosByName().get('CNSG Deal Party').getRecordTypeId();
        dealParty.RecordTypeId = libraRecordId;
        
        insert dealParty;
        if(dealParty.Relationship_Type__c == 'Counterparty Branch' || 
               dealParty.Relationship_Type__c == 'Bank Branch' || 
               dealParty.Relationship_Type__c == 'Disclosed Principal' || 
               dealParty.Relationship_Type__c == 'Retail Hedge Fund' || 
               dealParty.Relationship_Type__c == 'Qualified Investor Hedge Fund'){
            matter.Netting_Complete__c = false;
            update matter;
        }
        return null;
    }
    
    public PageReference SaveAmendment() {
        amendment.Amendment_Reason__c = amendmentReason;
        amendment.Amendment_Reason_Type__c = amendmentType;
        amendment.Effective_date__c = amendmentDate;
        amendment.Name_of_Regulation__c = regulationName;
        amendment.Matter__c = MatterId;

        amendment.Amendment_Document_Uploaded__c = amendmentDocument ? true : false;

        try {
            insert amendment;
            saveDealParty();
        }
        catch(exception e) {
            ApexPages.addMessages(e);
            return null;
        }

        PageReference pf = new PageReference('/' + matter.id);
        return pf;
    }
    
    public List<SelectOption> getCategories() {
        List<SelectOption> categories = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Amendment__c.Amendment_Reason_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : ple)
        {
            categories.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return categories;
    }
}