objects/advpm__Participant__c.object
<CustomObject>
    <customHelpPage>advpm__HelpParticipant</customHelpPage>
    <label>Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Collateral_Monitoring__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Deal__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Matter_Deal__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Collateral Monitoring</relationshipLabel>
        <relationshipName>Collateral_Monitoring</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Collateral Monitoring</relationshipLabel>
        <relationshipName>Collateral_Monitoring</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collateral Monitoring</label>
    <nameField>
        <label>Collateral Monitoring Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Monitoring</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Collateral_Valuation__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <description>Used to schedule Collateral Valuations</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Agreement__c.Matter_Deal__c</field>
                <operation>equals</operation>
                <valueField>$Source.Deal__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Collateral Valuations</relationshipLabel>
        <relationshipName>Collateral_Valuations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Collateral Valuations</relationshipLabel>
        <relationshipName>Collateral_Valuations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collateral Valuation</label>
    <nameField>
        <label>Collateral Valuation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Valuations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Drawdown__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <description>SFA-286 to record client drawdowns as they occur</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <formula>Agreement__r.Matter_Deal__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal</label>
        <type>Text</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <label>Drawdown Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <recordTypes>
        <fullName>Drawdown</fullName>
        <active>true</active>
        <label>Drawdown</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Fit_To_Lend_Checklist__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipName>Fit_to_Lend</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fit To Lend Checklist</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Fit to Lend No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fit To Lend Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Margin_Ratchet__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Margin Ratchets</relationshipLabel>
        <relationshipName>Margin_Ratchets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Margin Ratchets</relationshipLabel>
        <relationshipName>Margin_Ratchets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Margin Ratchet</label>
    <nameField>
        <label>Margin Ratchet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margin Ratchets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Notification_Participant__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Collateral_Monitoring__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral Monitoring</label>
        <referenceTo>Collateral_Monitoring__c</referenceTo>
        <relationshipLabel>Notification Participants</relationshipLabel>
        <relationshipName>Notification_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral_Valuation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral Valuation</label>
        <referenceTo>Collateral_Valuation__c</referenceTo>
        <relationshipLabel>Notification Participants</relationshipLabel>
        <relationshipName>Notification_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Drawdown__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Drawdown</label>
        <referenceTo>Drawdown__c</referenceTo>
        <relationshipLabel>Notification Participants</relationshipLabel>
        <relationshipName>Notification_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fit_To_Lend_Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fit To Lend Checklist</label>
        <referenceTo>Fit_To_Lend_Checklist__c</referenceTo>
        <relationshipLabel>Notification Participants</relationshipLabel>
        <relationshipName>Notification_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Margin_Ratchet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Margin Ratchet</label>
        <referenceTo>Margin_Ratchet__c</referenceTo>
        <relationshipLabel>Notification Participants</relationshipLabel>
        <relationshipName>Notification_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>advpm__Participant__c</referenceTo>
        <relationshipLabel>Notification Participants</relationshipLabel>
        <relationshipName>Notification_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trigger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trigger</label>
        <referenceTo>Trigger__c</referenceTo>
        <relationshipLabel>Notification Participants</relationshipLabel>
        <relationshipName>Notification_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Notification Participant</label>
    <nameField>
        <displayFormat>NP-{00000}</displayFormat>
        <label>Notification Participants #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Participants</pluralLabel>
    <recordTypes>
        <fullName>Drawdown</fullName>
        <active>true</active>
        <label>Drawdown</label>
    </recordTypes>
    <recordTypes>
        <fullName>Trigger</fullName>
        <active>true</active>
        <label>Trigger</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trigger__c.object
<CustomObject>
    <customHelpPage>SPV</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Deal__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Matter_Deal__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Triggers</relationshipLabel>
        <relationshipName>Triggers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Triggers</relationshipLabel>
        <relationshipName>Triggers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Trigger</label>
    <nameField>
        <label>Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Notification_Participants_Bulk.cls
/**
*** CHANGE LOG ***
 
 16/11/2017 - TdB    - Created Class.
 22/02/2018 - TdB    - Add DrawDown and Fit to Lend functionality

**/ 

public class Notification_Participants_Bulk {
    
    public List<sObject_Scheduling_Occurences.ParticipantWrapper> participantsWrapper { get; set; }
    public List<Notification_Participant__c> existingNotificationParticipants { get; set; }
    public List<advpm__Participant__c> existingParticipants { get; set; }
    public List<sObject> objectParentRecord { get; set; }
    public Set<Id> existingParticipantsSet { get; set; }
    public Map<Id, Id> participantNotificationParticipants { get; set; }
    public Boolean showError { get; set; }
    public Id currentObjectId;
    public String currentObjectName; 
    public Id parentObjectId;
    
    public Notification_Participants_Bulk()
    {
        //Empty wrappers
        participantsWrapper = new  List<sObject_Scheduling_Occurences.ParticipantWrapper>();
        existingNotificationParticipants = new List<Notification_Participant__c>();
        existingParticipants = new  List<advpm__Participant__c>();
        objectParentRecord = new List<sObject>();
        existingParticipantsSet = new Set<Id>();
        participantNotificationParticipants = new Map<Id, Id>();
        
        //Get Record Id from URL
        if(ApexPages.currentPage().getParameters().get('sObjectId') != null)
        {
            currentObjectId = Id.valueOf(ApexPages.currentPage().getParameters().get('sObjectId'));
        }
        
        //Get Object API Name based on Id
        currentObjectName = currentObjectId.getSObjectType().getDescribe().getName();
        
        //Margin Ratchet
        if(currentObjectName  == 'Margin_Ratchet__c')
        {
            //Get Margin Ratchet Record (sObject)
            objectParentRecord = [SELECT Id, Agreement__c, Agreement__r.Matter_Deal__c  FROM Margin_Ratchet__c WHERE Id = :currentObjectId limit 1];
            //Get existing Notification Participants
            existingNotificationParticipants = [SELECT Id, Margin_Ratchet__c,Participant__c FROM Notification_Participant__c WHERE Margin_Ratchet__c = : currentObjectId];
        }
        //Collateral Vaulation
        else if(currentObjectName  == 'Collateral_Valuation__c')
        {
            //Get Collateral Valuation Record (sObject)
            objectParentRecord = [SELECT Id, Agreement__c, Agreement__r.Matter_Deal__c  FROM Collateral_Valuation__c WHERE Id = :currentObjectId limit 1];
            //Get existing Notification Participants
            existingNotificationParticipants = [SELECT Id, Collateral_Valuation__c,Participant__c FROM Notification_Participant__c WHERE Collateral_Valuation__c = : currentObjectId];
        }   
        //Collateral Monitoring
        else if(currentObjectName  == 'Collateral_Monitoring__c')
        {
            //Get Margin Collateral Monitoring (sObject)
            objectParentRecord = [SELECT Id, Agreement__c, Agreement__r.Matter_Deal__c  FROM Collateral_Monitoring__c WHERE Id = :currentObjectId limit 1];
            //Get existing Notification Participants
            existingNotificationParticipants = [SELECT Id, Collateral_Monitoring__c,Participant__c FROM Notification_Participant__c WHERE Collateral_Monitoring__c = : currentObjectId];
        }
        //Trigger
        else if(currentObjectName  == 'Trigger__c')
        {
            //Get Trigger Record (sObject)
            objectParentRecord = [SELECT Id, Agreement__c, Agreement__r.Matter_Deal__c  FROM Trigger__c WHERE Id = :currentObjectId limit 1];
            //Get existing Notification Participants
            existingNotificationParticipants = [SELECT Id, Trigger__c,Participant__c FROM Notification_Participant__c WHERE Trigger__c = : currentObjectId];
        }
        //DrawDown
        else if(currentObjectName  == 'Drawdown__c')
        {
            //Get Trigger Record (sObject)
            objectParentRecord = [SELECT Id, Agreement__c, Agreement__r.Matter_Deal__c  FROM Drawdown__c WHERE Id = :currentObjectId limit 1];
            //Get existing Notification Participants
            existingNotificationParticipants = [SELECT Id, Trigger__c,Participant__c FROM Notification_Participant__c WHERE Drawdown__c = : currentObjectId];
        }
        //Fit to Lend
        else if(currentObjectName  == 'Fit_To_Lend_Checklist__c')
        {
            //Get Trigger Record (sObject)
            objectParentRecord = [SELECT Id, Deal__c  FROM Fit_To_Lend_Checklist__c WHERE Id = :currentObjectId limit 1];
            //Get existing Notification Participants
            existingNotificationParticipants = [SELECT Id, Trigger__c,Participant__c FROM Notification_Participant__c WHERE Fit_To_Lend_Checklist__c = : currentObjectId];
        }
                
        if(currentObjectName  != 'Fit_To_Lend_Checklist__c' && objectParentRecord.size() > 0 && (Id)objectParentRecord[0].get('Agreement__c') != null )
        {
            //Call class with method to get list of Participants
            sObject_Scheduling_Occurences.getParticipantsList((Id)objectParentRecord[0].getSObject('Agreement__r').get('Matter_Deal__c'));
            //Get Participants linked to Agreement
            existingParticipants = sObject_Scheduling_Occurences.participants;
        }
        else if(currentObjectName  == 'Fit_To_Lend_Checklist__c' && objectParentRecord.size() > 0 && (Id)objectParentRecord[0].get('Deal__c') != null )
        {
            //Call class with method to get list of Participants
            sObject_Scheduling_Occurences.getParticipantsList((Id)objectParentRecord[0].get('Deal__c'));
            //Get Participants linked to Agreement
            existingParticipants = sObject_Scheduling_Occurences.participants;
        }
        
        if(!existingNotificationParticipants.isEmpty())
        {
            //Build a set of existing Notification Participants
            for(Notification_Participant__c eachNotificationParticipant : existingNotificationParticipants)
            {
                if(!existingParticipantsSet.contains(eachNotificationParticipant.Participant__c))
                {
                    existingParticipantsSet.add(eachNotificationParticipant.Participant__c);  
                } 
                
                //Add to map for use later to track deselected.
                participantNotificationParticipants.put(eachNotificationParticipant.Participant__c, eachNotificationParticipant.Id);
            } 
        }
        
        initialiseWrapperList();
    }
    
    public void initialiseWrapperList()
    {
        System.debug('### initialiseWrapperList : ' + existingParticipants);
        //Loop through Participants Wrapper, check if Participant already created as a Notification Participant and flag as True
        for(advpm__Participant__c eachParticipant : existingParticipants)
        {
            sObject_Scheduling_Occurences.participantWrapper wrapperItem = new sObject_Scheduling_Occurences.participantWrapper();
            wrapperItem.participant = eachParticipant;
            
            if(existingParticipantsSet.contains(eachParticipant.Id))
            {
                wrapperItem.selected = true;   
            }
            
            //Add to main wrapper list.
            participantsWrapper.add(wrapperItem);
        }
    }
    
    public PageReference saveRecord() 
    {
     	System.debug('### saveRecord : ' + existingParticipants);   
        List<Notification_Participant__c> notificationParticipantInsert = new List<Notification_Participant__c>();
        List<Notification_Participant__c> notificationParticipantDelete = new List<Notification_Participant__c>();
        Map <String, Schema.RecordTypeInfo> NOTI_PARTICIPANT_TYPES = Notification_Participant__c.sObjectType.getDescribe().getRecordTypeInfosByName(); 
        
        //Reset error message.
        showError = true;
        
        //Loop through wrapper list.
        for(sObject_Scheduling_Occurences.participantWrapper eachWrapper : participantsWrapper)
        {
            //If selected
            if(eachWrapper.selected)
            {
                //One is selected at least.
                showError = false;
                
                if(!existingParticipantsSet.contains(eachWrapper.participant.Id))
                {
                    //New Notification participant
                    Notification_Participant__c notificationParticipantItem = new Notification_Participant__c();
                    
                    //Set Record Type and sObject
                    //Margin Ratchet
                    if(currentObjectName  == 'Margin_Ratchet__c')
                    {
                        notificationParticipantItem.Margin_Ratchet__c = currentObjectId;
                        notificationParticipantItem.RecordTypeId = NOTI_PARTICIPANT_TYPES.get('Margin Ratchet').getRecordTypeId();
                    }
                    //Collateral Valuation
                    else if (currentObjectName  == 'Collateral_Valuation__c')
                    {
                        notificationParticipantItem.Collateral_Valuation__c = currentObjectId;
                        notificationParticipantItem.RecordTypeId = NOTI_PARTICIPANT_TYPES.get('Collateral Valuation').getRecordTypeId();
                    }
                    //Collateral Monitoring
                    else if (currentObjectName  == 'Collateral_Monitoring__c')
                    {
                        notificationParticipantItem.Collateral_Monitoring__c = currentObjectId;
                        notificationParticipantItem.RecordTypeId = NOTI_PARTICIPANT_TYPES.get('Collateral Monitoring').getRecordTypeId();
                    }
                    //Trigger
                    else if (currentObjectName  == 'Trigger__c')
                    {
                        notificationParticipantItem.Trigger__c = currentObjectId;
                        notificationParticipantItem.RecordTypeId = NOTI_PARTICIPANT_TYPES.get('Trigger').getRecordTypeId();
                    }
                    //DrawDown
                    else if (currentObjectName  == 'Drawdown__c')
                    {
                        notificationParticipantItem.Drawdown__c = currentObjectId;
                        notificationParticipantItem.RecordTypeId = NOTI_PARTICIPANT_TYPES.get('Drawdown').getRecordTypeId();
                    }
                    //Fit to Lend
                    else if (currentObjectName  == 'Fit_To_Lend_Checklist__c')
                    {
                        notificationParticipantItem.Fit_To_Lend_Checklist__c = currentObjectId;
                        notificationParticipantItem.RecordTypeId = NOTI_PARTICIPANT_TYPES.get('Fit To Lend Checklist').getRecordTypeId();
                    }
                    
                    notificationParticipantItem.Participant__c = eachWrapper.participant.Id;
                    
                    //Add to list.
                    notificationParticipantInsert.add(notificationParticipantItem);
                }
            }
            //If deselected
            else
            {
                if(existingParticipantsSet.contains(eachWrapper.participant.Id))
                {
                    //Id of participant to delete.
                    Id participantNotificationId = (Id)participantNotificationParticipants.get(eachWrapper.participant.Id);
                    
                    //Notification participant to delete.
                    Notification_Participant__c notificationParticipantToDelete = new Notification_Participant__c(Id = participantNotificationId); 
                    
                    //Add to delete list.
                    notificationParticipantDelete.add(notificationParticipantToDelete);
                }
            }
        }
        
        //Execute changes.
        try 
        {
            //Insert new records.
            if(!notificationParticipantInsert.isEmpty())
            {
                insert notificationParticipantInsert;
            }
            
            //Delete deselected records.
            if(!notificationParticipantDelete.isEmpty())
            {
                delete notificationParticipantDelete;
            }
            
            //New Page Setup
            PageReference standardPage = new PageReference('/'+ currentObjectId); 
            standardPage.setRedirect(true);
            
            //Redirect.
            return standardPage;
        }
        catch(Exception e)
        {
            //Error Message
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR,'Error: '+e.getMessage()));
        }
        return null;
    }
}