objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <formula>advpm__Primary_Account__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship Type</label>
        <type>Text</type>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <recordTypes>
        <fullName>Deal</fullName>
        <active>true</active>
        <label>Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agreement_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <formula>TEXT(Matter_Deal__r.Relationship_Type_picklist__c)</formula>
        <label>Relationship Type</label>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Amendment__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreement Amendments</relationshipLabel>
        <relationshipName>Agreeement_Amendments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amendment_Document_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amendment Document Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amendment_Reason_Type__c</fullName>
        <label>Amendment Reason Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Amendment_Reason_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amendment_Reason__c</fullName>
        <description>Field used to prompt user to complete field when &apos;other&apos; is selected on amendment reason type</description>
        <label>Amendment Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_date__c</fullName>
        <label>Effective date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Name_of_Regulation__c</fullName>
        <label>Name of Regulation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supporting_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supporting Agreement</label>
        <referenceTo>Supporting_Agreement__c</referenceTo>
        <relationshipLabel>Amendments</relationshipLabel>
        <relationshipName>Amendments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Amendment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Amendment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal_Party__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Deal Parties</relationshipLabel>
        <relationshipName>Deal_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship_SDS_ID__c</fullName>
        <formula>Relationship__r.SDS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship SDS ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party Guarantor</fullName>
                </value>
                <value>
                    <fullName>Asset Manager</fullName>
                </value>
                <value>
                    <fullName>Bank Branch</fullName>
                </value>
                <value>
                    <fullName>Collective Investment Scheme Manager</fullName>
                </value>
                <value>
                    <fullName>Counterparty</fullName>
                </value>
                <value>
                    <fullName>Counterparty Branch</fullName>
                </value>
                <value>
                    <fullName>Cross Guarantor</fullName>
                </value>
                <value>
                    <fullName>Custodian</fullName>
                </value>
                <value>
                    <fullName>Disclosed Principal</fullName>
                </value>
                <value>
                    <fullName>Qualified Investor Hedge Fund</fullName>
                </value>
                <value>
                    <fullName>Retail Hedge Fund</fullName>
                </value>
                <value>
                    <fullName>Security Provider</fullName>
                </value>
                <value>
                    <fullName>Specified Entity Bank</fullName>
                </value>
                <value>
                    <fullName>Specified Entity Counterparty</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supporting Agreement</label>
        <referenceTo>Supporting_Agreement__c</referenceTo>
        <relationshipLabel>Deal Parties</relationshipLabel>
        <relationshipName>Deal_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Party</label>
    <nameField>
        <displayFormat>DP-{00000}</displayFormat>
        <label>Deal Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Supporting_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Supporting Agreements</relationshipLabel>
        <relationshipName>Supporting_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supporting_Agreement_Type__c</fullName>
        <label>Supporting Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Master_Agreement_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>2005 Master Give-up Agreement</fullName>
                </value>
                <value>
                    <fullName>ACS Terms of Business</fullName>
                </value>
                <value>
                    <fullName>Collateral Management Agency Agreement</fullName>
                </value>
                <value>
                    <fullName>Collateral Management Agreement</fullName>
                </value>
                <value>
                    <fullName>Credit Support Document</fullName>
                </value>
                <value>
                    <fullName>CSA</fullName>
                </value>
                <value>
                    <fullName>CSA (New York Law)</fullName>
                </value>
                <value>
                    <fullName>CSD</fullName>
                </value>
                <value>
                    <fullName>Global Netting Agreement</fullName>
                </value>
                <value>
                    <fullName>IM CSA</fullName>
                </value>
                <value>
                    <fullName>International Futures Terms of Business</fullName>
                </value>
                <value>
                    <fullName>IRC Client Agreement</fullName>
                </value>
                <value>
                    <fullName>ISDA Collateral Transfer Agreement / Euroclear Security</fullName>
                </value>
                <value>
                    <fullName>JSE IRC</fullName>
                </value>
                <value>
                    <fullName>JSE SAFEX</fullName>
                </value>
                <value>
                    <fullName>JSE Tripartite</fullName>
                </value>
                <value>
                    <fullName>JSE Yield X</fullName>
                </value>
                <value>
                    <fullName>Master Confirmation Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>SAFEX Clearing Agreement</fullName>
                </value>
                <value>
                    <fullName>SAFEX Client Agreement</fullName>
                </value>
                <value>
                    <fullName>SE Client Agreement</fullName>
                </value>
                <value>
                    <fullName>Service Level Agreement</fullName>
                </value>
                <value>
                    <fullName>Structured Deposit Master Agreement and Confirmation</fullName>
                </value>
                <value>
                    <fullName>Terms Of Business</fullName>
                </value>
                <value>
                    <fullName>Tri-Party CSA</fullName>
                </value>
                <value>
                    <fullName>VM CSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supporting Agreement</label>
    <nameField>
        <displayFormat>SA-{0}</displayFormat>
        <label>Supporting Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supporting Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Agreement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Awaiting Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Executed</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Send to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed/Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Amended</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled/Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Superceded</fullName>
        <isActive>false</isActive>
        <label>Superceded</label>
    </customValue>
    <description>Agreement Management (LEAP)</description>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

globalValueSets/Amendment_Reason_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Regulatory compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Amendment Reason Type</masterLabel>
</GlobalValueSet>

classes/SupportingAgreementDealsRelatedList_Cont.cls
/**
 * Created by KyleAlexander on 2018/03/05.
 */

public with sharing class SupportingAgreementDealsRelatedList_Cont {

    public Supporting_Agreement__c supportingAgreement {get;set;}
    public Id supportingAgreementId {get;set;}
    public List<Deal_Party__c> dealParties {get;set;}
    public List<Deal_Party__c> addedDealParties {get;set;}
    public id dealId {get;set;}
    public Boolean changesMade {get;set;}
    public Boolean mustBeAmended {get;set;}

    public Amendment__c amendment {get;set;}
    public String amendmentType {get;set;}
    public String amendmentReason {get;set;}
    public Date amendmentDate {get;set;}
    public String regulationName {get;set;}
    public Boolean amendmentDocument {get;set;}

    public Agreement__c agreement {get;set;}

    public Boolean dealsPanel {get;set;}
    public Boolean amendmentPanel {get;set;}

    public SupportingAgreementDealsRelatedList_Cont(ApexPages.StandardController controller) {
        changesMade = false;
        addedDealParties = new List<Deal_Party__c>();
        dealParties = new List<Deal_Party__c>();
        populateDealsList();

        amendment = new Amendment__c();

        getCategories();

        dealsPanel = true;
        amendmentPanel = false;
    }

    public void populateDealsList(){
        supportingAgreementId = ApexPages.currentPage().getParameters().get('id');
        supportingAgreement = [select id, Agreement__c, Supporting_Agreement_Type__c from Supporting_Agreement__c where id = :supportingAgreementId limit 1];

        //Gets all added deal parties for this supporting agreement
        addedDealParties = [select name, Relationship_SDS_ID__c, Relationship_Type__c, id, Deal__c, Supporting_Agreement__c from Deal_Party__c where Supporting_Agreement__c = :supportingAgreementId];

        //It should show only supporting agreements of type CSA and CSD
        if(supportingAgreement.Supporting_Agreement_Type__c == 'CSA' || supportingAgreement.Supporting_Agreement_Type__c == 'CSD'){
            //Since the deal parties are on the matter level, we need to get the agreement from the supporting agreement and then the matter from that (MATTER -> AGREEMENT -> SUPPORTING AGREEMENT)
            agreement = [select id, Matter_Deal__c, Agreement_Status__c from Agreement__c where id = :supportingAgreement.Agreement__c limit 1];

            if(agreement.Agreement_Status__c == 'Confirmed/Completed' || agreement.Agreement_Status__c == 'Amended') {
                mustBeAmended = true;
            }
            else{
                mustBeAmended = false;
            }

            advpm__Matter__c matter = [select id from advpm__Matter__c where id = :agreement.Matter_Deal__c limit 1];

            //Gets all the deals on that specific Matter where the relationship type for the deal has been set to 'Disclosed principal'
            List<Deal_Party__c> allDeals = [select name, Relationship_SDS_ID__c, Relationship_Type__c, id, Deal__c, Supporting_Agreement__c from Deal_Party__c where Deal__c = :matter.id and Relationship_Type__c = 'Disclosed Principal'];

            //If there are deal parties that have been added then check if the added deals don't contain the current instance of all of the deals and then add it to the deal parties for the users to add
            //This checks for duplicates and doesn't add them if they've already been added
            //Else add all the deals to the deal parties list so that the users can add them
            if(!addedDealParties.isEmpty()) {
                if (!allDeals.isEmpty()) {
                    for (Integer i = 0; i < allDeals.size(); i++) {
                        if (!addedDealParties.contains(allDeals.get(i))) {
                            dealParties.add(allDeals.get(i));
                        }
                    }
                }
            }
            else{
                dealParties.addAll(allDeals);
            }
        }
    }

    public void updateDealParties(){
        List<Deal_Party__c> existingDealParties = [select name, Relationship_SDS_ID__c, Relationship_Type__c, id, Deal__c, Supporting_Agreement__c from Deal_Party__c where Supporting_Agreement__c = :supportingAgreementId];

        for (Deal_Party__c adp : addedDealParties) {
            if (!existingDealParties.contains(adp)) {
                //Add the supporting agreement to the deal and update it
                adp.Supporting_Agreement__c = supportingAgreementId;
                update adp;
            }
        }

        for (Deal_Party__c dp : dealParties) {
            if (existingDealParties.contains(dp)) {
                //Get the deal party to remove and set the deal parties supporting agreement to null
                dp.Supporting_Agreement__c = null;
                update dp;
            }
        }
    }

    public PageReference submitChanges(){
        if(mustBeAmended) {
            dealsPanel = false;
            amendmentPanel = true;
        }
        else{
            updateDealParties();
        }

        return null;
    }

    public void addDeal(){
        changesMade = true;

        //Gets the current instance of the deal party, passed by it's dealId from the vf page
        Deal_Party__c dealParty = [select name, Relationship_SDS_ID__c, Relationship_Type__c, id, Deal__c, Supporting_Agreement__c from Deal_Party__c where id = :dealId limit 1];
        //Add it to the added list
        addedDealParties.add(dealParty);

        //Get the deal to be added's index in the list and remove it from the deal parties list
        //This is so the users can't add it again
        Integer count = 0;
        for(Deal_Party__c dParty : dealParties){
            if(dParty.id == dealParty.id){
                break;
            }
            count++;
        }
        if(dealParties.size() > 0){
            try{
                dealParties.remove(count);
            }
            catch(Exception e){
                System.debug('Error removing deal party: ' + e.getMessage());
            }
        }
    }

    public void removeDeal(){
        changesMade = true;

        //Gets the current instance of the deal party, passed by it's dealId from the vf page
        Deal_Party__c dealParty = [select name, Relationship_SDS_ID__c, Relationship_Type__c, id, Deal__c, Supporting_Agreement__c from Deal_Party__c where id = :dealId limit 1];

        //Get the deal to be added's index in the list and remove it from the added parties list
        //This is so the users can't remove it again
        Integer count = 0;
        for(Deal_Party__c dParty : addedDealParties){
            if(dParty.id == dealParty.id){
                break;
            }
            count++;
        }
        addedDealParties.remove(count);
        //It is then added back to the deal party list so a user can add it again later if they choose to
        dealParties.add(dealParty);
    }

    public PageReference CancelAmendment() {
        PageReference pf = new PageReference('/' + supportingAgreementId);
        return pf;
    }

    public PageReference SaveAmendment() {
        amendment.Amendment_Reason__c = amendmentReason;
        amendment.Amendment_Reason_Type__c = amendmentType;
        amendment.Effective_date__c = amendmentDate;
        amendment.Name_of_Regulation__c = regulationName;
        amendment.Supporting_Agreement__c = supportingAgreementId;

        if (amendmentDocument) {
            amendment.Amendment_Document_Uploaded__c = true;
        } else {
            amendment.Amendment_Document_Uploaded__c = false;
        }

        try {
            updateDealParties();
            insert amendment;
        }
        catch(exception e) {
            ApexPages.addMessages(e);
            return null;
        }

        dealsPanel = true;
        amendmentPanel = false;

        changesMade = false;

        return null;
    }

    public List<SelectOption> getCategories() {
        List<SelectOption> categories = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Amendment__c.Amendment_Reason_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : ple)
        {
            categories.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return categories;
    }
}