objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                    <default>true</default>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Attainable_litigation_objective__c</fullName>
        <label>Attainable litigation objective</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Cluster_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Matters/Deals</relationshipLabel>
        <relationshipName>Matters_Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Matter_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Categories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Claim_By_Against_Barclays__c</fullName>
        <label>Claim By/Against Barclays</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Claim By Barclays</fullName>
                </value>
                <value>
                    <fullName>Claim Against Barclays</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Branch_code__c</fullName>
        <label>Client/Branch code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Centre__c</fullName>
        <label>Cost Centre</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Costs_Actually_Recovered__c</fullName>
        <label>Costs Actually Recovered</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Costs_Awarded_Against_Barclays__c</fullName>
        <label>Costs Awarded Against Barclays</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_account_number_policy_number__c</fullName>
        <label>Customer account number/policy number/</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Closure__c</fullName>
        <label>Date of Closure</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disposition_Description__c</fullName>
        <label>Disposition Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Disposition_Type__c</fullName>
        <label>Disposition Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Disposition_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financial_Value_Unknown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Financial Value Unknown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <description>The country in which the matter resides</description>
        <inlineHelpText>The country in which the matter resides</inlineHelpText>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Lawyer_Office__c</fullName>
        <description>Location</description>
        <inlineHelpText>Location of Lead Lawyer</inlineHelpText>
        <label>Lead Lawyer Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cape Town</fullName>
                </value>
                <value>
                    <fullName>Durban</fullName>
                </value>
                <value>
                    <fullName>Johannesburg</fullName>
                    <default>true</default>
                    <label>Johannesburg</label>
                </value>
                <value>
                    <fullName>Port Elizabeth</fullName>
                </value>
                <value>
                    <fullName>Pretoria</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Litigation_Status__c</fullName>
        <label>Litigation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Litigation_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matter_Type__c</fullName>
        <label>Matter Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Matter_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matter_Value__c</fullName>
        <label>Total Claim Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Negative_Outcome_Before_All_Costs__c</fullName>
        <label>Negative Outcome Before All Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Positive_Outcome_Before_All_Costs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Positive Outcome Before All Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_current_status__c</fullName>
        <label>Previous Status</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Probable_For_Approval__c</fullName>
        <label>Probable (For Approval)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reasonably_Possible__c</fullName>
        <label>Reasonably Possible</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reputational_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reputational Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Securitization_value__c</fullName>
        <label>Security value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Claim_Percentage__c</fullName>
        <description>Used for validation, must always add up to 100</description>
        <label>Total Claim Percentage</label>
        <summarizedField>Business_Unit_Claim__c.Portion_of_Claim__c</summarizedField>
        <summaryForeignKey>Business_Unit_Claim__c.Matter__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>advpm__Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>advpm__Engagement_Date__c</fullName>
        <label>Engagement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>advpm__Legal_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legal Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>advpm__Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matters</relationshipLabel>
        <relationshipName>Matters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>advpm__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Matters</relationshipLabel>
        <relationshipName>Matters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>advpm__Projected_Date_Of_Closure__c</fullName>
        <label>Projected Date Of Closure</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>advpm__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Discharged</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>In Appeal</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Matured</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Jurisdiction__c.object
<CustomObject>
    <fields>
        <fullName>Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Jurisdictions</relationshipLabel>
        <relationshipName>Jurisdictions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Jurisdiction</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jurisdiction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jurisdictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Matter_Content__c.object
<CustomObject>
    <fields>
        <fullName>Box_Parent_Id__c</fullName>
        <label>Box Parent Id</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Box_Url__c</fullName>
        <label>Box Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Box_id__c</fullName>
        <label>Box id</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Matter Content</relationshipLabel>
        <relationshipName>Matter_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_Id__c</fullName>
        <label>Content Id</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Name__c</fullName>
        <label>Content Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Source__c</fullName>
        <label>Document Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Box</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Matter Content</relationshipLabel>
        <relationshipName>Matter_Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Matter Content</label>
    <nameField>
        <displayFormat>MC {00000}</displayFormat>
        <label>Matter Content No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matter Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Categories.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ABC</fullName>
    </customValue>
    <customValue>
        <fullName>Action Lines</fullName>
    </customValue>
    <customValue>
        <fullName>AML</fullName>
    </customValue>
    <customValue>
        <fullName>Banking Ombudsman</fullName>
    </customValue>
    <customValue>
        <fullName>Benchmarks</fullName>
    </customValue>
    <customValue>
        <fullName>CEO’s Office</fullName>
    </customValue>
    <customValue>
        <fullName>Class Action</fullName>
    </customValue>
    <customValue>
        <fullName>Competition / Antitrust</fullName>
    </customValue>
    <customValue>
        <fullName>Compliance with orders made by the Court</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Statutory Rights</fullName>
    </customValue>
    <customValue>
        <fullName>Contentious IP</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Disputes (other)</fullName>
    </customValue>
    <customValue>
        <fullName>Court Proceedings</fullName>
    </customValue>
    <customValue>
        <fullName>Court Proceedings Filed</fullName>
    </customValue>
    <customValue>
        <fullName>Customers</fullName>
    </customValue>
    <customValue>
        <fullName>Cybercrime</fullName>
    </customValue>
    <customValue>
        <fullName>Data Protection</fullName>
    </customValue>
    <customValue>
        <fullName>Debt Recovery</fullName>
    </customValue>
    <customValue>
        <fullName>Delict</fullName>
    </customValue>
    <customValue>
        <fullName>Employment Related Matters</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Crime</fullName>
    </customValue>
    <customValue>
        <fullName>Fraud</fullName>
    </customValue>
    <customValue>
        <fullName>Inappropriate Use of Information</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect Payments / Transfer of Funds</fullName>
    </customValue>
    <customValue>
        <fullName>Insolvency bankruptcy / Business rescue</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Investigation</fullName>
    </customValue>
    <customValue>
        <fullName>Market Misconduct</fullName>
    </customValue>
    <customValue>
        <fullName>Mis-Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Misuse of Confidential Information/IP</fullName>
    </customValue>
    <customValue>
        <fullName>Mortgage Related Activity</fullName>
    </customValue>
    <description>Litigation subcategories to Matter type</description>
    <masterLabel>Categories</masterLabel>
</GlobalValueSet>

globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Abu Dhabi Global Market</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

globalValueSets/Disposition_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Absolution</fullName>
    </customValue>
    <customValue>
        <fullName>Appellate Decision Against</fullName>
    </customValue>
    <customValue>
        <fullName>Appellate Decision For</fullName>
    </customValue>
    <customValue>
        <fullName>Arbitration Resulting in Award Against</fullName>
    </customValue>
    <customValue>
        <fullName>Arbitration Resulting in Award For</fullName>
    </customValue>
    <customValue>
        <fullName>Business Rescue</fullName>
    </customValue>
    <customValue>
        <fullName>Business Rescue / Liquidation (Finalised)</fullName>
    </customValue>
    <customValue>
        <fullName>Court Finding Against</fullName>
    </customValue>
    <customValue>
        <fullName>Court Finding For</fullName>
    </customValue>
    <customValue>
        <fullName>Default Judgement</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Duplicate</fullName>
    </customValue>
    <customValue>
        <fullName>Finding by Regulator Against</fullName>
    </customValue>
    <customValue>
        <fullName>Finding by Regulator For</fullName>
    </customValue>
    <customValue>
        <fullName>Investigation Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Liquidation</fullName>
    </customValue>
    <customValue>
        <fullName>Settlement</fullName>
    </customValue>
    <customValue>
        <fullName>Settlement with Regulator (No Penalty)</fullName>
    </customValue>
    <customValue>
        <fullName>Settlement with Regulator (Penalty)</fullName>
    </customValue>
    <customValue>
        <fullName>Summary Judgement</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Matter Settled</fullName>
        <isActive>false</isActive>
        <label>Matter Settled</label>
    </customValue>
    <description>Litigation field</description>
    <masterLabel>Disposition Type</masterLabel>
</GlobalValueSet>

globalValueSets/Litigation_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Pre Action Correspondence</fullName>
    </customValue>
    <customValue>
        <fullName>Arbitration / ADR</fullName>
    </customValue>
    <customValue>
        <fullName>Court Proceedings</fullName>
    </customValue>
    <customValue>
        <fullName>Enforcement Proceeedings</fullName>
    </customValue>
    <customValue>
        <fullName>Court Proceedings Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
        <isActive>false</isActive>
        <label>Not Applicable</label>
    </customValue>
    <description>The Litigation Status field is a mandatory field that identifies the current litigation status of the Dispute Matter which should be updated during the lifecycle of the matter.</description>
    <masterLabel>Litigation Status</masterLabel>
</GlobalValueSet>

globalValueSets/Matter_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Litigation</fullName>
    </customValue>
    <customValue>
        <fullName>Investigation</fullName>
    </customValue>
    <customValue>
        <fullName>Investigation | Other</fullName>
        <isActive>false</isActive>
        <label>Investigation | Other</label>
    </customValue>
    <customValue>
        <fullName>Investigation Market Misconduct</fullName>
        <isActive>false</isActive>
        <label>Investigation Market Misconduct</label>
    </customValue>
    <customValue>
        <fullName>Investigation | Financial Crime</fullName>
        <isActive>false</isActive>
        <label>Investigation | Financial Crime</label>
    </customValue>
    <customValue>
        <fullName>Investigation | Systems and Controls</fullName>
        <isActive>false</isActive>
        <label>Investigation | Systems and Controls</label>
    </customValue>
    <description>Litigation Matters</description>
    <masterLabel>Matter Type</masterLabel>
</GlobalValueSet>

classes/MatterHandler_CaseConvert.cls
/**
 * Author: Sean Parker
*/
Public class MatterHandler_CaseConvert   {

public String MatterId;
public Case MatterCase  { get; set;}
public List<TagSelect> lstTagSelect  { get; set; }
public String VFtag;
public Boolean AddMatter { get; set; }
public List<BoxFiles> LstBoxFiles { get; set; }
public static Boolean convertedMatter;
public String callSuccessFunction { get; set; }

public MatterHandler_CaseConvert(){
    
    String[] lstTag;
    String tags;
    
    //Assign matter id based on page param.
    if(apexpages.currentpage().getparameters().get('Id') !=null){
        MatterId = apexpages.currentpage().getparameters().get('Id');
    }
    
    //New Case
    MatterCase = new Case();      

    //Fetch all "matter content" records for this matter.
    List<Matter_Content__c> lst_Content = new List<Matter_Content__c>([
        Select id,
          Matter__c,
          Content_Id__c,
          Case__c 
        from Matter_Content__c 
        Where Matter__c =: MatterId
    ]);
}

public void filesfromBox() {

    Id matterId = MatterId;
    List<BxdKnowledgeItem> items;
    LstBoxFiles = new List<BoxFiles>();
    
    //Retrieve existing files for matters box folder contents.
    if(!Test.isRunningTest()){
       items = BxdKnowledgeService.getBoxFolderFiles(matterId);
    }
    //Create and add a blank box knowledge item?
    else{
       BxdKnowledgeItem i = new BxdKnowledgeItem('name','description','url','id','parent', null);
       items = new List<BxdKnowledgeItem>(); 
       items.Add(i);
    }
    
    //Iterate over box knowledge folder items and add to list.
    for(BxdKnowledgeItem i:items){
      BoxFiles BoxFile = new BoxFiles();
      BoxFile.fileName  = i.name;
      BoxFile.fileDescription = i.description;
      BoxFile.fileUrl = i.url;
      BoxFile.fileBoxId = i.id;
      BoxFile.fileBoxParent = i.parent;
      BoxFile.Selectfile = false;
      LstBoxFiles.Add(BoxFile);
    }
}    

public PageReference ConvertMatterToCase() {
  
    convertedMatter = true;    
    
    //Set matter on new case.
    MatterCase.Matter__c = MatterId;
    
    //Set case owner to knowledge queue.
    QueueSobject[] QueueID = [SELECT CreatedById,Id,QueueId,SobjectType,queue.Name FROM QueueSobject where queue.Name='Knowledge Request Queue' limit 1];
    MatterCase.OwnerId=QueueID[0].QueueId;
    
    //Set case record type to knowledge request.
    RecordType rt = [Select id From RecordType where Name= 'Knowledge Request' limit 1];
    MatterCase.RecordTypeid = rt.id;    

    //Set the initial case status.
    MatterCase.Status = 'KM In Progress';

    //Insert the new case.
    Insert MatterCase;
      
    //Query all matter content records associated with matter.
    List<Matter_Content__c> lst_Content = new List<Matter_Content__c>([Select id,Matter__c,Case__c from Matter_Content__c Where Matter__c =: MatterId ]);

    //Associate matter content records with the case.
    for(Matter_Content__c c:lst_Content) {
        c.Case__c = MatterCase.id;
    }
       

    lst_Content = new  List<Matter_Content__c>();
    
    //Iterate over box files.
    for(BoxFiles b:LstBoxFiles){
        
        //Select in list in VF page UI.
        if(b.Selectfile) {

            //Build up new matter content item.
            Matter_Content__c Content = new Matter_Content__c();
            Content.Document_Source__c = 'Box';
            Content.Box_Url__c = b.fileUrl;
            Content.Content_Name__c = b.fileName;
            Content.Description__c = b.fileDescription;
            Content.Case__c = MatterCase.id; 
            Content.Box_id__c = b.fileBoxid;
            Content.Box_Parent_Id__c =  b.fileBoxParent;      

            //Add to the matter content list.
            lst_Content.Add(Content);
        }  
    }    

    //Insert box linked matter content.
    insert lst_Content; 
       
    advpm__Matter__c Matter;

    //Requery a milliion field on the matter for PDF inclusion.
    Matter = [Select recordTypeid, recordType.Name,Name,Reputational_Risk__c,advpm__Engagement_Date__c,Cost_Centre__c,
                            Jurisdiction__c,Customer_account_number_policy_number__c,Litigation_Status__c,Client_Branch_code__c,
                            advpm__Description__c,Total_Claim_Percentage__c,Matter_Type__c,Category__c,advpm__Legal_Hold__c,
                            Claim_By_Against_Barclays__c,Reasonably_Possible__c,Approval_Status__c,Probable_For_Approval__c,
                            Financial_Value_Unknown__c,Matter_Value__c,Attainable_litigation_objective__c,Securitization_value__c,
                            Current_Status__c,Notes__c,Previous_current_status__c,Disposition_Type__c,advpm__Projected_Date_Of_Closure__c,
                            Disposition_Description__c,Positive_Outcome_Before_All_Costs__c,Negative_Outcome_Before_All_Costs__c,Costs_Awarded_Against_Barclays__c,
                            Costs_Actually_Recovered__c, Lead_Lawyer_Office__c, Business_Unit_Cluster_Segment__r.Name,Business_Unit_Cluster_Segment__c,advpm__Status__c,
                            Date_of_Closure__c,advpm__Primary_Account__c,advpm__Primary_Contact__c,Owner.Name                           
                             From advpm__Matter__c Where Id=:MatterId limit 1];

       
    if(Test.isRunningTest()){ 
        AddMatter = true;
    }

    //Query return a matter.
    if(AddMatter) {

        PageReference pdf;
        
        if(MatterId != null){                  
            pdf =  Page.MatterToCaseConvertPDF;
        }
        
        //Set page params for PDF generating page.
        pdf.getParameters().put('id',MatterId); 
        pdf.getParameters().put('RecordType',(String) Matter.recordTypeid); 
        pdf.setRedirect(true); 
        
        Blob body; 

        if(Test.isRunningTest()) {
            body = Blob.valueOf('body');
        }
        else
        {   
            //Fetch PDF data from VF Page.
            body = pdf.getContentAsPDF();
        }
        
        //New attachment record.
        Attachment attach = new Attachment();
        attach.Body = body;
        attach.Name = Matter.Name+'.pdf';
        attach.IsPrivate = false;
        attach.ParentId = MatterCase.Id;
        
        //Insert attachement and associate with case. 
        insert attach;
      }

    PageReference pageRef;

    //Get current users profile
    Id userProfId = UserInfo.getProfileId();
    String userProfile = [select Name from profile where id = :userProfId limit 1].Name;

    //Create box items via redirect page.
    pageRef = new PageReference('/apex/CaseRedirectForBox?id='+MatterCase.Id+'&matterId='+MatterId);
    pageRef.setRedirect(true);
    return pageRef;
}
 
public PageReference SubmitCaseToBox() {
            
    String CaseId;

    String matterId = ApexPages.currentPage().getParameters().get('matterId');

    //If there is a case id in the URL params.
    if(apexpages.currentpage().getparameters().get('Id') !=null) {
        
        //Get passed in case id.
        CaseId = apexpages.currentpage().getparameters().get('Id');

        //Get a single attachment that is on the case.
        Attachment[] attach = [Select Body,Name,ParentId From Attachment Where ParentId =: CaseId limit 1];
        
        //Get all matter content assocaite with the case.
        List<Matter_Content__c> lst_Content = new List<Matter_Content__c>([
            SELECT 
                id,
                Box_id__c,
                Box_Parent_Id__c,
                Content_Name__c,
                Description__c,
                Box_Url__c,
                Matter__c,
                Case__c 
            FROM Matter_Content__c 
            WHERE 
                Case__c =: CaseId 
        ]);
        
        List<BxdKnowledgeItem> lstitems = new List<BxdKnowledgeItem>();
        
        //Build up list of knowledge box items on matter content.
        for(Matter_Content__c c : lst_Content) {
           BxdKnowledgeItem items = new  BxdKnowledgeItem(c.Box_id__c, c.Content_Name__c , c.Description__c, c.Box_Url__c,c.Box_Parent_Id__c, null);
           lstitems.Add(items);
        }

        Boolean b;

        if(attach.size() > 0) {
            b =   BxdKnowledgeService.createBoxCaseFolder(CaseId,lstitems,attach[0].Body,attach[0].Name);
        }
        else {
            Blob body;
            body = Blob.valueOf('Null'); 
            b =   BxdKnowledgeService.createBoxCaseFolder(CaseId,lstitems,null,'');
        }
    }

    //Redirect back to matter.
    PageReference pageRef;
    pageRef = new PageReference('/'+matterId);
    return pageRef;
}


    //Wrapper class for selected tags?
    public class TagSelect {        
        public String tags { get; set; }
    }

    //Box file wrapper.
    public class BoxFiles {

        public String fileName { get; set; }
        public String fileDescription { get; set; }
        public String fileUrl { get; set; }
        public String fileBoxid { get; set; }
        public String fileBoxParent { get; set; }
        public Boolean Selectfile { get; set; }
    }

    //Page action to cancel and return to the matter.
    public Pagereference Cancel() {
        PageReference pageRef = new PageReference('/'+MatterId);
        return pageRef;
    }
}