objects/advpm__Matter__c.object
<CustomObject>
    <customHelpPage>advpm__HelpMatter</customHelpPage>
    <label>Matter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NettingGroupBranch__c.object
<CustomObject>
    <fields>
        <fullName>BranchType__c</fullName>
        <label>Branch Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>Counterparty</fullName>
                </value>
                <value>
                    <fullName>Trade Instrument</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NettingGroup__c</fullName>
        <label>Netting Group</label>
        <referenceTo>Netting_Group__c</referenceTo>
        <relationshipLabel>Netting Group Branches</relationshipLabel>
        <relationshipName>Netting_Group_Branchs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trade_Instrument__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade Instrument</label>
        <referenceTo>Trade_Instrument__c</referenceTo>
        <relationshipLabel>Netting Group Branches</relationshipLabel>
        <relationshipName>Netting_Group_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Netting Group Branch</label>
    <nameField>
        <displayFormat>NGB-{0000}</displayFormat>
        <label>Netting Group Branch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Netting Group Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Trade_Instrument__c.object
<CustomObject>
    <label>Trade Instrument</label>
    <nameField>
        <label>Trade Instrument Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Instruments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Matter_Deal_Override_MarketTrans_test.cls
@Istest
public class Matter_Deal_Override_MarketTrans_test {
    
    public static testMethod void testMarketTransCreate() {
        Test.startTest();
        Libra_TestDataClass libraTestData = new Libra_TestDataClass();

        advpm__Matter__c matter = libraTestData.testMarketTransactionMatter;
        
        Test.setCurrentPageReference(new PageReference('Page.Matter_Deal_Override_MarketTransaction'));
        System.currentPageReference().getParameters().put('matterId', matter.id);

        ApexPages.StandardController sc = new ApexPages.StandardController(matter);
        Matter_Deal_Override_MarketTrans_Cont testMarketTrans = new Matter_Deal_Override_MarketTrans_Cont(sc);
        
        testMarketTrans.CancelPage();
        testMarketTrans.SaveMatter();
		testMarketTrans.duplicateCheck(); 
        
        System.currentPageReference().getParameters().put('matterId', null);
        sc = new ApexPages.StandardController(matter);
        testMarketTrans = new Matter_Deal_Override_MarketTrans_Cont(sc);
        testMarketTrans.SaveMatter();
        
        System.currentPageReference().getParameters().put('matterId', matter.id);
        sc = new ApexPages.StandardController(matter);
        testMarketTrans = new Matter_Deal_Override_MarketTrans_Cont(sc);
        
        libraTestData.testNettingGroup.Netting_Type__c = 'Novation';
        update libraTestData.testNettingGroup;
        
        NettingGroupBranch__c testNettingGroupBranchTI = new NettingGroupBranch__c();
        testNettingGroupBranchTI.NettingGroup__c = libraTestData.testNettingGroup.id;
        testNettingGroupBranchTI.BranchType__c = 'Trade Instrument';
        testNettingGroupBranchTI.Trade_Instrument__c = libraTestData.testTradeInstrument.id;
        insert testNettingGroupBranchTI;
        
        testMarketTrans.SaveMatter();
        
        libraTestData.testNettingGroup.Netting_Type__c = 'Settlement';
        update libraTestData.testNettingGroup;
        
        testNettingGroupBranchTI = new NettingGroupBranch__c();
        testNettingGroupBranchTI.NettingGroup__c = libraTestData.testNettingGroup.id;
        testNettingGroupBranchTI.BranchType__c = 'Trade Instrument';
        testNettingGroupBranchTI.Trade_Instrument__c = libraTestData.testTradeInstrument.id;
        insert testNettingGroupBranchTI;
        
        testMarketTrans.SaveMatter();     
        
        Test.stopTest();
    }
    
    public static testMethod void testMarketTransTI(){
        Test.startTest();
        Libra_TestDataClass libraTestData = new Libra_TestDataClass();

        advpm__Matter__c matter = libraTestData.testMarketTransactionMatter;
        
        Test.setCurrentPageReference(new PageReference('Page.Matter_Deal_Override_MarketTransaction'));
        System.currentPageReference().getParameters().put('matterId', matter.id);

        ApexPages.StandardController sc = new ApexPages.StandardController(matter);
        Matter_Deal_Override_MarketTrans_Cont testMarketTrans = new Matter_Deal_Override_MarketTrans_Cont(sc);
        delete libraTestData.testNettingGroupBranchCP;
        NettingGroupBranch__c testNettingGroupBranchTI = new NettingGroupBranch__c();
        testNettingGroupBranchTI.NettingGroup__c = libraTestData.testNettingGroup.id;
        testNettingGroupBranchTI.BranchType__c = 'Trade Instrument';
        testNettingGroupBranchTI.Trade_Instrument__c = libraTestData.testTradeInstrument.id;
        insert testNettingGroupBranchTI;
        testMarketTrans.SaveMatter();
        
        libraTestData.testNettingGroup.Netting_Type__c = 'Settlement';
        update libraTestData.testNettingGroup;
        testMarketTrans.SaveMatter();
        
        libraTestData.testNettingGroup.Netting_Type__c = 'Novation';
        update libraTestData.testNettingGroup;
        testMarketTrans.SaveMatter();
        
        Test.stopTest();
    }
}