objects/Agency_Transfer__c.object
<CustomObject>
    <customHelpPage>Agency</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agency Transfers</relationshipLabel>
        <relationshipName>Transfer_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Facility_Tranche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility Tranche</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Facility_Tranche__c.Facility__c</field>
                <operation>equals</operation>
                <valueField>$Source.Facility__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Facility_Tranche__c</referenceTo>
        <relationshipLabel>Agency Transfers</relationshipLabel>
        <relationshipName>Agency_Transfers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Facility__c.Agreement__c</field>
                <operation>equals</operation>
                <valueField>$Source.Agreement__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Agency Transfers</relationshipLabel>
        <relationshipName>Agency_Transfers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Transfer</label>
    <nameField>
        <displayFormat>TRANS-{0}</displayFormat>
        <label>Transfer #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Transfers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Collateral_Monitoring__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Deal__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Matter_Deal__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Collateral Monitoring</relationshipLabel>
        <relationshipName>Collateral_Monitoring</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Collateral Monitoring</relationshipLabel>
        <relationshipName>Collateral_Monitoring</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Collateral Monitoring</label>
    <nameField>
        <label>Collateral Monitoring Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Monitoring</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Collateral_Valuation__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <description>Used to schedule Collateral Valuations</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Agreement__c.Matter_Deal__c</field>
                <operation>equals</operation>
                <valueField>$Source.Deal__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Collateral Valuations</relationshipLabel>
        <relationshipName>Collateral_Valuations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Collateral Valuations</relationshipLabel>
        <relationshipName>Collateral_Valuations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Collateral Valuation</label>
    <nameField>
        <label>Collateral Valuation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Valuations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Condition__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only select Agreements that are linked to the selected Deal</errorMessage>
            <filterItems>
                <field>$Source.Matter__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Matter_Deal__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Conditions</relationshipLabel>
        <relationshipName>Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Condition_Occurrence__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <formula>Condition__r.Agreement__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agreement</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <referenceTo>Condition__c</referenceTo>
        <relationshipName>Conditions_Due</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Condition Occurrence</label>
    <nameField>
        <label>Condition Occurrence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Occurrences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Drawdown__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <description>SFA-286 to record client drawdowns as they occur</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Facility__c.Agreement__c</field>
                <operation>equals</operation>
                <valueField>$Source.Agreement__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <label>Drawdown Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Facility__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Facility_Tranche__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; + Facility__r.Agreement__r.Id ,  Facility__r.Agreement__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agreement</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Facility Tranches</relationshipLabel>
        <relationshipName>Facility_Tranches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Facility Tranche</label>
    <nameField>
        <label>Facility Tranche Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Tranches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Margin_Ratchet__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Margin Ratchets</relationshipLabel>
        <relationshipName>Margin_Ratchets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Margin Ratchets</relationshipLabel>
        <relationshipName>Margin_Ratchets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Margin Ratchet</label>
    <nameField>
        <label>Margin Ratchet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margin Ratchets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SPV_Items__c.object
<CustomObject>
    <customHelpPage>SPV</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>SPV Items</relationshipLabel>
        <relationshipName>SPV_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SPV Item</label>
    <nameField>
        <label>SPV Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPV Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Trigger__c.object
<CustomObject>
    <customHelpPage>SPV</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Deal__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Matter_Deal__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Triggers</relationshipLabel>
        <relationshipName>Triggers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Trigger</label>
    <nameField>
        <label>Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BxdDocumentTreeView.cls
public class BxdDocumentTreeView {   
    private static FolderHandler folderHandler = new FolderHandler();
    private final static String BOX_FILE_URL = 'https://account.box.com/file/';
    private final static String BOX_RESTRICTED_SCOPE = 'base_explorer item_preview';
    private final static String BOX_RESTRICTED_TYPE = 'folder';
    public Id BxdOwnerId {get; set;}
    public String folderId {get;set;}
    public String accessToken {get;set;}
    public String fileBaseURL {get; private set;}
    
    public BxdDocumentTreeView() {
        BxdOwnerId = ApexPages.currentPage().getParameters().get('Id');
        fileBaseURL = BOX_FILE_URL;
        System.debug('TreeView OWNER ' + BxdOwnerId);
        if (BxdOwnerId != null) {
            //Box FOLDER and TOKEN
            folderId = folderHandler.getBoxFolderIdByRecordIdForCustomUI(getParentTree(BxdOwnerId));
            accessToken = folderHandler.downscopeBoxToken(folderHandler.getBoxApi().getAccessToken(), BOX_RESTRICTED_SCOPE, folderId, BOX_RESTRICTED_TYPE);
        }
    }
    
    private Id getParentTree(Id recordId) {
        Schema.SObjectType ObjType =  recordId.getSobjectType();
        Schema.DescribeSObjectResult ObjTypeDesc = ObjType.getDescribe();
        System.debug('***Tree View Parent Object Name '+ObjTypeDesc.getName());
        
        if (ObjTypeDesc.getName() == 'Account') {
            return recordId;
        }  
        
        if (ObjTypeDesc.getName() == 'advpm__Matter__c') {
            return recordId;
        } 
        
        if (ObjTypeDesc.getName() == 'Agreement__c')
        {
            return getAgreementParent(recordId);
        }
        if (ObjTypeDesc.getName() == 'Condition__c')
        {
            
        }
        if (ObjTypeDesc.getName() == 'Condition_Occurrence__c')
        {
            
        }  
        if (ObjTypeDesc.getName() == 'Collateral__c')
        {
            
        }  
        if (ObjTypeDesc.getName() == 'DrawDown__c')
        {
            
        } 
        if (ObjTypeDesc.getName() == 'Facility__c')
        {
            
        } 
        if (ObjTypeDesc.getName() == 'Facility_Tranche__c')
        {
            
        }
        if (ObjTypeDesc.getName() == 'SPV_Items__c')
        {
            
        }
        if (ObjTypeDesc.getName() == 'Agency_Transfer__c')
        {
            
        }
        if (ObjTypeDesc.getName() == 'Collateral_Valuation__c')
        {
            
        }
        if (ObjTypeDesc.getName() == 'Collateral_Monitoring__c')
        {
            
        }
        if (ObjTypeDesc.getName() == 'Watcher__c')
        {
            
        }
        if (ObjTypeDesc.getName() == 'Trigger__c')
        {
            
        }
        if (ObjTypeDesc.getName() == 'Margin_Ratchet__c')
        {
            
        }
        
        return recordId;
    }
    
    private Id getAgreementParent(Id recordId) {
        Agreement__c agreement = [SELECT Id, Name, Matter_Deal__c, RecordTypeId FROM Agreement__c where id =: recordId LIMIT 1];
        return agreement.Matter_Deal__c;
    }
    
    private class FolderHandler extends BxdFolderHandler {
        private FolderHandler() {           
            super(true, null);
        }
    }
}