objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Agreement_Party__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreement Parties</relationshipLabel>
        <relationshipName>Agreement_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Party_Type__c</fullName>
        <formula>TEXT(Deal_Party__r.Party_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Party Type</label>
        <type>Text</type>
    </fields>
    <label>Agreement Party</label>
    <nameField>
        <label>Agreement Party</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Facility__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Facility_Party__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement Party</label>
        <referenceTo>Agreement_Party__c</referenceTo>
        <relationshipLabel>Facility Parties</relationshipLabel>
        <relationshipName>Facility_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Facility Parties</relationshipLabel>
        <relationshipName>Facility_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Party_Type__c</fullName>
        <formula>Agreement_Party__r.Party_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Party Type</label>
        <type>Text</type>
    </fields>
    <label>Facility Party</label>
    <nameField>
        <label>Facility Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Facility_Tranche__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; + Facility__r.Agreement__r.Id ,  Facility__r.Agreement__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agreement</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Facility Tranches</relationshipLabel>
        <relationshipName>Facility_Tranches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Facility Tranche</label>
    <nameField>
        <label>Facility Tranche Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Tranches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Margin_Ratchet__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Margin Ratchets</relationshipLabel>
        <relationshipName>Margin_Ratchets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Tranche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility Tranche</label>
        <referenceTo>Facility_Tranche__c</referenceTo>
        <relationshipLabel>Margin Ratchets</relationshipLabel>
        <relationshipName>Margin_Ratchets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Margin Ratchets</relationshipLabel>
        <relationshipName>Margin_Ratchets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Margin Ratchet</label>
    <nameField>
        <label>Margin Ratchet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margin Ratchets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Relationship_Parties__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement Party</label>
        <referenceTo>Agreement_Party__c</referenceTo>
        <relationshipName>Margin_Ratchet_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility Party</label>
        <referenceTo>Facility_Party__c</referenceTo>
        <relationshipName>Margin_Ratchet_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Margin_Ratchet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Margin Ratchet</label>
        <referenceTo>Margin_Ratchet__c</referenceTo>
        <relationshipName>Margin_Ratchet_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tranche_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tranche Party</label>
        <referenceTo>Tranche_Party__c</referenceTo>
        <relationshipName>Margin_Ratchet_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Party</label>
    <nameField>
        <displayFormat>RP - {0000000}</displayFormat>
        <label>Relationship Parties Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tranche_Party__c.object
<CustomObject>
    <fields>
        <fullName>Facility_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility Party</label>
        <referenceTo>Facility_Party__c</referenceTo>
        <relationshipLabel>Tranche Parties</relationshipLabel>
        <relationshipName>Tranche_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Tranche__c</fullName>
        <label>Facility Tranche</label>
        <referenceTo>Facility_Tranche__c</referenceTo>
        <relationshipLabel>Tranche Parties</relationshipLabel>
        <relationshipName>Tranche_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Party_Type__c</fullName>
        <formula>Facility_Party__r.Party_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Party Type</label>
        <type>Text</type>
    </fields>
    <label>Tranche Party</label>
    <nameField>
        <label>Tranche Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tranche Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Relationship_Parties_Bulk.cls
/**
*** CHANGE LOG ***

29/11/2017 - TdB    - Created Class.

**/ 
public class Relationship_Parties_Bulk {
    
    public List<sObject_Scheduling_Occurences.RelationshipPartiesWrapper> relationshipParties_Wrapper { get; set; }
    public List<Relationship_Parties__c> existingRelationshipParties { get; set; }
    public List<sObject> existingParties { get; set; }
    public List<sObject> objectParentRecord { get; set; }
    public Set<Id> existingRelationshipSet { get; set; }
    public Map<Id, Id> partiesRelationshipParties { get; set; }
    public Boolean showError { get; set; }
    public Id currentObjectId;
    public String currentObjectName; 
   // public Id parentObjectId;
    
    public Relationship_Parties_Bulk()
    {
        relationshipParties_Wrapper = new List<sObject_Scheduling_Occurences.RelationshipPartiesWrapper> ();
        existingRelationshipParties = new List<Relationship_Parties__c> ();
        existingParties = new List<sObject>();
        objectParentRecord = new List<sObject>();
        existingRelationshipSet = new Set<Id> ();
        partiesRelationshipParties = new Map<Id, Id>();
        
        //Get Record Id from URL
        if(ApexPages.currentPage().getParameters().get('sObjectId') != null)
        {
            currentObjectId = Id.valueOf(ApexPages.currentPage().getParameters().get('sObjectId'));
        }
        
        //Get Object API Name based on Id
        currentObjectName = currentObjectId.getSObjectType().getDescribe().getName();
        
        //Margin Ratchet
        if(currentObjectName  == 'Margin_Ratchet__c')
        {
            //Get Margin Ratchet Record (sObject)
            objectParentRecord = [SELECT Id, Facility_Tranche__c, Facility__c, Agreement__c  FROM Margin_Ratchet__c WHERE Id = :currentObjectId limit 1];
            //Get existing Notification financialCovenants
            existingRelationshipParties = [SELECT Id, Agreement_Party__c, Facility_Party__c, Margin_Ratchet__c, Tranche_Party__c  FROM Relationship_Parties__c WHERE Margin_Ratchet__c = : currentObjectId];
            
                        
            if(objectParentRecord.size() > 0)
            {
                if((Id)objectParentRecord[0].get('Facility_Tranche__c') != null)
                {
                    sObject_Scheduling_Occurences.getRelationshipPartiesList((Id)objectParentRecord[0].get('Facility_Tranche__c'), 'Tranche');
                    existingParties = sObject_Scheduling_Occurences.tranchePartiesList;
                }
                else if ((Id)objectParentRecord[0].get('Facility__c') != null)
                {
                    sObject_Scheduling_Occurences.getRelationshipPartiesList((Id)objectParentRecord[0].get('Facility__c'), 'Facility');
                    existingParties = sObject_Scheduling_Occurences.facilityPartiesList;
                }
                else
                {
                    sObject_Scheduling_Occurences.getRelationshipPartiesList((Id)objectParentRecord[0].get('Agreement__c'), 'Agreement');
                    existingParties = sObject_Scheduling_Occurences.agreementPartiesList;
                }
            }
        }   
        
        if(!existingRelationshipParties.isEmpty())
        {
            //Build a set of existing Relationship Parties
            for(Relationship_Parties__c eachRelationshipParties : existingRelationshipParties)
            {
                if((Id)objectParentRecord[0].get('Facility_Tranche__c') != null)
                {
                    if(!existingRelationshipSet.contains(eachRelationshipParties.Tranche_Party__c))
                    {
                    	existingRelationshipSet.add(eachRelationshipParties.Tranche_Party__c);  
                    } 
                    partiesRelationshipParties.put(eachRelationshipParties.Tranche_Party__c, eachRelationshipParties.Id);
                }
                else if((Id)objectParentRecord[0].get('Facility__c') != null)
                {
                    if(!existingRelationshipSet.contains(eachRelationshipParties.Facility_Party__c))
                    {
                    	existingRelationshipSet.add(eachRelationshipParties.Facility_Party__c);  
                    } 
                    partiesRelationshipParties.put(eachRelationshipParties.Facility_Party__c, eachRelationshipParties.Id);
                }
                else if((Id)objectParentRecord[0].get('Agreement__c') != null)
                {
                    if(!existingRelationshipSet.contains(eachRelationshipParties.Agreement_Party__c))
                    {
                    	existingRelationshipSet.add(eachRelationshipParties.Agreement_Party__c);  
                    } 
                    partiesRelationshipParties.put(eachRelationshipParties.Agreement_Party__c, eachRelationshipParties.Id);
                } 
            } 
        }
        initialiseWrapperList();
    }
    
    public void initialiseWrapperList()
    {
        //Loop through financialCovenants Wrapper, check if financialCovenant already created as a Notification financialCovenant and flag as True
        for(sObject eachParty : existingParties)
        {
            sObject_Scheduling_Occurences.RelationshipPartiesWrapper wrapperItem = new sObject_Scheduling_Occurences.RelationshipPartiesWrapper();
            wrapperItem.partyName = (String)eachParty.get('Name');
            wrapperItem.partyType = (String)eachParty.get('Party_Type__c');
            wrapperItem.partyId = (Id)eachParty.get('Id');
            
            if(existingRelationshipSet.contains(eachParty.Id))
            {
                wrapperItem.selected = true;   
            }
            
            //Add to main wrapper list.
            relationshipParties_Wrapper.add(wrapperItem);
        }
    }
    
    public PageReference saveRecord() 
    {
        
        List<Relationship_Parties__c> relationshipPartiesInsert = new List<Relationship_Parties__c>();
        List<Relationship_Parties__c> relationshipPartiesDelete = new List<Relationship_Parties__c>();

        //Reset error message.
        showError = true;
        
        //Loop through wrapper list.
        for(sObject_Scheduling_Occurences.RelationshipPartiesWrapper eachWrapper : relationshipParties_Wrapper)
        {
            //If selected
            if(eachWrapper.selected)
            {
                //One is selected at least.
                showError = false;
                
                if(!existingRelationshipSet.contains(eachWrapper.PartyId))
                {
                    //New Notification financialCovenant
                    Relationship_Parties__c relationshipPartyItem = new Relationship_Parties__c();
                    relationshipPartyItem.Margin_Ratchet__c = currentObjectId;
					if((Id)objectParentRecord[0].get('Facility_Tranche__c') != null)
                    {
                        relationshipPartyItem.Tranche_Party__c = eachWrapper.PartyId;
                    }
                    else if((Id)objectParentRecord[0].get('Facility__c') != null)
                    {
                        relationshipPartyItem.Facility_Party__c = eachWrapper.PartyId;
                    }
                    else if((Id)objectParentRecord[0].get('Agreement__c') != null)
                    {
                        relationshipPartyItem.Agreement_Party__c = eachWrapper.PartyId;
                    }
                    
                    //Add to list.
                    relationshipPartiesInsert.add(relationshipPartyItem);
                }
            }
            //If deselected
            else
            {
                if(existingRelationshipSet.contains(eachWrapper.PartyId))
                {
                    //Id of financialCovenant to delete.
                    Id relationshipPartyToDeleteId = (Id)partiesRelationshipParties.get(eachWrapper.PartyId);
                    
                    //Notification financialCovenant to delete.
                    Relationship_Parties__c realtionshipPartyItemToDelete = new Relationship_Parties__c(Id = relationshipPartyToDeleteId); 
                    
                    //Add to delete list.
                    relationshipPartiesDelete.add(realtionshipPartyItemToDelete);
                }
            }
        }
        
        
        //Execute changes.
        try 
        {
            //Insert new records.
            if(!relationshipPartiesInsert.isEmpty())
            {
                insert relationshipPartiesInsert;
            }
            
            //Delete deselected records.
            if(!relationshipPartiesDelete.isEmpty())
            {
                delete relationshipPartiesDelete;
            }
            
            //New Page Setup
            PageReference standardPage = new PageReference('/'+ currentObjectId); 
            standardPage.setRedirect(true);

            //Redirect.
            return standardPage;
        }
        catch(Exception e)
        {
            //Error Message
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR,'Error: '+e.getMessage()));
        }
          return null;
    }
}