objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.TMG_Product_Level_3__c</field>
                <operation>equals</operation>
                <valueField>Product_Agreement__c.TMG_Product_Level_3__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product_Agreement__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facility_Limit__c</fullName>
        <description>Facility limit to determine each Lender&apos;s portion</description>
        <label>Facility Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <description>Facility limit to determine each Lender&apos;s portion</description>
        <label>Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signature_Date__c</fullName>
        <label>Signature Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TMG_Product_Level_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement Product Grouping</label>
        <referenceTo>TMG_Product_Level_3__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TMG_Product_Level_3__c.object
<CustomObject>
    <label>Agreement Group 3</label>
    <nameField>
        <label>TMG Product Level 3 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Group 3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Agreement_Override_Test.cls
/**
 _____ _                 _ _____           _ _   _         
/  __ \ |               | /  ___|         (_) | | |        
| /  \/ | ___  _   _  __| \ `--. _ __ ___  _| |_| |__  ___ 
| |   | |/ _ \| | | |/ _` |`--. \ '_ ` _ \| | __| '_ \/ __|
| \__/\ | (_) | |_| | (_| /\__/ / | | | | | | |_| | | \__ \
 \____/_|\___/ \__,_|\__,_\____/|_| |_| |_|_|\__|_| |_|___/
 
 *** CHANGE LOG ***
 
 31/10/2017 - PG    - Created Class. 
 09/11/2017 - TdB   - API Name change. Facility_Limit__c  to Limit__c on Agreements Object

**/ 
@IsTest
public class Agreement_Override_Test 
{   
    @IsTest
    public static void testOverrideEdit() 
    {
        CloudSmiths_TestDataClass testData = new CloudSmiths_TestDataClass();

        Test.startTest();

        PageReference pageRef = Page.Agreement_Override;
        Test.setCurrentPage(pageRef);

        //Controller + Extension
        ApexPages.StandardController sc = new ApexPages.standardController(testData.TestAgreement);
        Agreement_Override ec = new Agreement_Override(sc); 

        //Methods
        ec.actionHandleEntry();
        ec.populateProductAgreementTypes();
        ec.updateSelectedProduct();
        ec.getAgreementTypesList();
        ec.actionSave();

        Test.stopTest();
    }

    @IsTest
    public static void testOverrideNew() 
    {
        CloudSmiths_TestDataClass testData = new CloudSmiths_TestDataClass();

        //New Agreement
        Agreement__c newAgreement = new Agreement__c
        (
            Matter_Deal__c =  testData.TestMatter.id,
            Name = 'Test',
            Agreement_Type__c =    testData.TestProductAgreement.id,
            TMG_Product_Level_3__c = testData.TestProductLevel3.id,
            Signature_Date__c = Date.today().addDays(5),
            Effective_Date__c = Date.today().addDays(5),
            Limit__c = 10000
        );

        Test.startTest();

        PageReference pageRef = Page.Agreement_Override;
        Test.setCurrentPage(pageRef);

        //Controller + Extension
        ApexPages.StandardController sc = new ApexPages.standardController(newAgreement);
        Agreement_Override ec = new Agreement_Override(sc); 

        //Methods
        ec.actionHandleEntry();
        ec.populateProductAgreementTypes();
        ec.updateSelectedProduct();
        ec.getAgreementTypesList();
        ec.actionSave();

        Test.stopTest(); 
    }
}