objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agreement_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Agreement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Awaiting Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Executed</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Send to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed/Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Amended</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled/Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Superceded</fullName>
        <isActive>false</isActive>
        <label>Superceded</label>
    </customValue>
    <description>Agreement Management (LEAP)</description>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

classes/Libra_Restful_Deal_Party_Test.cls
@IsTest
public class Libra_Restful_Deal_Party_Test {
    
     static testmethod void myUnitTestPositive()
    {
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/deal-party/';       
        
        String dealPartyId = [select Matter_Deal__c from Agreement__c where Agreement_Status__c= 'Amended' limit 1].Matter_Deal__c;
        
        Libra_Restul_Functions.DealPartyWrapper dealParty = new Libra_Restul_Functions.DealPartyWrapper();
        dealParty.dealPartyId = dealPartyId;
        req.requestBody = Blob.valueof(JSON.serialize(dealParty));
        RestContext.request = req; 
        RestContext.response= res;
        
        test.startTest();
        Libra_Restful_Deal_Party.getDealParty();
        test.stopTest();
    }
    
    static testmethod void myUnitTestNegative()
    {
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.addHeader('httpMethod', 'POST');
        req.requestUri = '/services/apexrest/master/';       
        
        
        Libra_Restul_Functions.DealPartyWrapper dealParty = new Libra_Restul_Functions.DealPartyWrapper();
        dealParty.dealPartyId = 'Invalid ID';
        req.requestBody = Blob.valueof(JSON.serialize(dealParty));
        RestContext.request = req; 
        RestContext.response= res;
        
        test.startTest();
        Libra_Restful_Deal_Party.getDealParty();
        test.stopTest();
    }
    
    @TestSetup static void setupData()
    {
        Libra_TestDataClass data =  new Libra_TestDataClass();
        
        List<Agreement__c> Agreementlist = [Select id,Agreement_Status__c from Agreement__c limit 1];
        if(Agreementlist.size()>0)
        {
            Agreementlist[0].Agreement_Status__c ='Amended';
        }
        
        update Agreementlist;
    }

}