objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Description__c</fullName>
        <label>Agreement Description</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <formula>Matter_Deal__r.Relationship__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship</label>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Agreement_Party__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreement Parties</relationshipLabel>
        <relationshipName>Agreement_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Conditions_Monitored_By__c</fullName>
        <formula>Deal_Party__r.Conditions_Monitored_By__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Conditions Monitored By</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Party__c</fullName>
        <label>Deal Party</label>
        <referenceTo>Deal_Party__c</referenceTo>
        <relationshipLabel>Agreement Parties</relationshipLabel>
        <relationshipName>Agreement_Parties</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Party_Type__c</fullName>
        <formula>TEXT(Deal_Party__r.Party_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Party Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <formula>Deal_Party__r.Relationship__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship</label>
        <type>Text</type>
    </fields>
    <label>Agreement Party</label>
    <nameField>
        <label>Agreement Party</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Condition__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only select Agreements that are linked to the selected Deal</errorMessage>
            <filterItems>
                <field>$Source.Matter__c</field>
                <operation>equals</operation>
                <valueField>Agreement__c.Matter_Deal__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Conditions</relationshipLabel>
        <relationshipName>Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <formula>Matter__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Conditions</relationshipLabel>
        <relationshipName>MatterConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <formula>Matter__r.advpm__Primary_Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Counterparty</inlineHelpText>
        <label>Relationship</label>
        <type>Text</type>
    </fields>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Condition_Party__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Party__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agreement Party</label>
        <referenceTo>Agreement_Party__c</referenceTo>
        <relationshipLabel>Condition Parties</relationshipLabel>
        <relationshipName>Condition_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <referenceTo>Condition__c</referenceTo>
        <relationshipLabel>Condition Parties</relationshipLabel>
        <relationshipName>Condition_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Party_Type__c</fullName>
        <formula>TEXT(Agreement_Party__r.Deal_Party__r.Party_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Party Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <formula>Agreement_Party__r.Deal_Party__r.Relationship__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship</label>
        <type>Text</type>
    </fields>
    <label>Condition Party</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condition Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal_Party__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Conditions_Monitored_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conditions Monitored By</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Deal__c</field>
                <operation>equals</operation>
                <valueField>advpm__Participant__c.advpm__Matter__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>advpm__Participant__c</referenceTo>
        <relationshipLabel>Deal Parties</relationshipLabel>
        <relationshipName>Deal_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Deal Parties</relationshipLabel>
        <relationshipName>Deal_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Party_Type__c</fullName>
        <label>Party Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Borrower</fullName>
                </value>
                <value>
                    <fullName>Carrier</fullName>
                </value>
                <value>
                    <fullName>Collateral Manager</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>ECA</fullName>
                </value>
                <value>
                    <fullName>Forward Sale Purchaser</fullName>
                </value>
                <value>
                    <fullName>Guarantor</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Rating Agency</fullName>
                </value>
                <value>
                    <fullName>Relevant Party</fullName>
                </value>
                <value>
                    <fullName>Seller</fullName>
                </value>
                <value>
                    <fullName>Storage Operator</fullName>
                </value>
                <value>
                    <fullName>Trustee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deal Parties</relationshipLabel>
        <relationshipName>Deal_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Party</label>
    <nameField>
        <displayFormat>DP-{00000}</displayFormat>
        <label>Deal Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Condition_Party_Override.cls
/**
 _____ _                 _ _____           _ _   _         
/  __ \ |               | /  ___|         (_) | | |        
| /  \/ | ___  _   _  __| \ `--. _ __ ___  _| |_| |__  ___ 
| |   | |/ _ \| | | |/ _` |`--. \ '_ ` _ \| | __| '_ \/ __|
| \__/\ | (_) | |_| | (_| /\__/ / | | | | | | |_| | | \__ \
 \____/_|\___/ \__,_|\__,_\____/|_| |_| |_|_|\__|_| |_|___/
 
 *** CHANGE LOG ***
 
 26/06/2017 - PG    - Created Class. 
 04/07/2017 - PG    - Modify class to handle GC's creates at Deal level.  Provisions a container Agreement and Agreement Parties.
                    - Moved most logic away from Constructor to initialiseData methods.  Needed DML.
 15/09/2017 - PG    - Ported overall class to use "Condition__c" instead of "Condition_Party__c" instead.
 29/09/2017 - PG    - Added "CONDITION_TYPES" and updated code to use it instead.  
 02/11/2017 - PG    - Removed Standard controller logic and use param instead.
                    - Added actionCancel method. 

**/ 
public class Condition_Party_Override
{
    /**
    * Variables
    **/
    public static final Map<String, RecordTypeInfo> CONDITION_TYPES = new Map<String, RecordTypeInfo>(Condition__c.sObjectType.getDescribe().getRecordTypeInfosByName());
    public List<Agreement_Party__c> agreementParties { get; set; }
    public List<Condition_Party__c> conditionParties { get; set; }
    public Set<Id> existingAgreementParties { get; set; }
    public Map<Id, Id> agreementPartyMap { get; set; }
    public List<PartyWrapper> partyWrappers { get; set; }
    public Condition__c conditionRecord { get; set; }
    public Agreement__c agreementRecord { get; set; }
    public Id agreementId { get; set; }
    public String param1 { get; set; }
    
    /**
     * CONSTRUCTOR
    **/
    public Condition_Party_Override()
    {
        System.debug('## Condition_Party_Override');
        
        //Blank vars.
        agreementParties = new List<Agreement_Party__c>();
        conditionParties = new List<Condition_Party__c>();
        existingAgreementParties = new Set<Id>();
        agreementPartyMap = new Map<Id, Id>();
        partyWrappers = new List<PartyWrapper>();
        param1 = ApexPages.currentPage().getParameters().get('id');
    }
    
    /**
     * action - initialiseData - The main page logic on how to handle the Condition Party.
    **/
    public PageReference initialiseData()
    {
        //Get condition
        conditionRecord = [
            SELECT
                Id,
                RecordTypeId,
                Agreement__c,
                Matter__c
            FROM Condition__c
            WHERE
                Id = :param1
            LIMIT 1
        ];

        //Get all the existing conditions parties for the condition.
        conditionParties = [
            SELECT
                Id,
                Agreement_Party__c,
                Condition__c
            FROM Condition_Party__c
            WHERE
                Condition__c = :conditionRecord.Id
        ];
        
        //If this is a governance check, that is linked to the Deal and not linked to an Agreement i.e. Directly on Deal.
        if(conditionRecord.RecordTypeId == CONDITION_TYPES.get('Governance Check').getRecordTypeId() && conditionRecord.Matter__c != null && conditionRecord.Agreement__c == null)
        {
            System.debug('## Condition_Party_Override : GC IF ');
            
            //Blank list.
            List<Agreement__c> agreements = new List<Agreement__c>();
            
            //See if there is an existing system generated agreemnet on the Deal for Governance Checks.
            agreements = [
                SELECT
                    Id,
                    Name,
                    Matter_Deal__c
                FROM Agreement__c
                WHERE 
                    Name = 'Internal Deal Governance Checks'
                    AND Matter_Deal__c = :conditionRecord.Matter__c
                LIMIT 1
            ];
            
            //Agreement exists.
            if(agreements.size() > 0)
            {
                //Assign Id.
                agreementId = agreements[0].Id;  
                
            }
            //Agreement does not exist.
            else
            {
                //Create a new agreement.
                agreementRecord = new Agreement__c();
                agreementRecord.Name = 'Internal Deal Governance Checks';
                agreementRecord.Matter_Deal__c = conditionRecord.Matter__c; 
                agreementRecord.Agreement_Description__c = 'System Generated - Purpose: Deal Level Govenance Checks.';
                
                //insert agreement.
                insert agreementRecord;
                
                //Update id to be inserted agreement record.
                agreementId = agreementRecord.Id;
                
                //Get all deal parties and insert them by default.
                List<Deal_Party__c> dealParties = [
                    SELECT
                        Id,
                        Deal__c,
                        Conditions_Monitored_By__c,
                        Relationship__c,
                        Party_Type__c
                    FROM Deal_Party__c
                    WHERE
                        Deal__c = :conditionRecord.Matter__c
                ]; 
                
                //Anything to process
                if(dealParties.size() > 0)
                {
                    //Empty list.
                    List<Agreement_Party__c> agreementParties = new List<Agreement_Party__c>();
                    
                    //Loop through deal parties and build agreement parties.
                    for(Deal_Party__c dealParty : dealParties)
                    {
                        //New agreement party object.
                        Agreement_Party__c agreementParty = new Agreement_Party__c();
                        agreementParty.Deal_Party__c = dealParty.Id;
                        agreementParty.Agreement__c = agreementId;
                        
                        //Add to list.
                        agreementParties.add(agreementParty);
                    }
                    
                    //Anything to process.
                    if(!agreementParties.isEmpty())
                    {
                        //Insert parties.
                        insert agreementParties;
                    }
                }
            }
            
        }
        else
        {
            //Get this id of the associated conditions agreement. 
            agreementId = conditionRecord.Agreement__c;
        }
        
        //Get all the agreement parties for the conditions agreement.
        agreementParties = [
            SELECT
                Id,
                Name,
                Agreement__c,
                Relationship__c,
                Party_Type__c,
                Conditions_Monitored_By__c
            FROM Agreement_Party__c
            WHERE 
                Agreement__c = :agreementId
        ];
        
        //There are no deal parties defined.
        if(agreementParties.isEmpty())
        {
            //Error Message
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.INFO,'There are no parties specified on the associated agreement.'));
        }
        
        //Any existing condition parties?
        if(!conditionParties.isEmpty()) 
        {            
            for(Condition_Party__c conditionParty : conditionParties)
            {                
                if(!existingAgreementParties.contains(conditionParty.Agreement_Party__c))
                {
                    existingAgreementParties.add(conditionParty.Agreement_Party__c);
                }
                
                //Add to map for use later to track deselected.
                agreementPartyMap.put(conditionParty.Agreement_Party__c, conditionParty.Id); 
            }
        }
        
        //Build Initial Wrapper List.
        initialiseWrapperList(); 
        
        return null;
    }
    
    /**
     * action - initialiseWrapperList - Builds the initial wrapper list.
    **/
    public void initialiseWrapperList()
    {
        System.debug('## initialiseWrapperList');
        System.debug('## initialiseWrapperList : agreementParties : '+agreementParties);
        
        //Loop through agreement parties.
        for(Agreement_Party__c agreementParty : agreementParties)
        {
            PartyWrapper wrapperItem = new PartyWrapper();
            wrapperItem.party = agreementParty;
            
            if(existingAgreementParties.contains(agreementParty.Id))
            {
                wrapperItem.selected = true;   
            }
            
            //Add to main wrapper list.
            partyWrappers.add(wrapperItem);
        }
    }
    
    /**
     * action - initialiseWrapperList - Builds the initial wrapper list. 
    **/
    public PageReference saveRecord() 
    {
        System.debug('### Condition_Party_Override : saveRecord');

        //Blank variables.
        List<Condition_Party__c> conditionPartiesInsert = new List<Condition_Party__c>();
        List<Condition_Party__c> conditionPartiesDelete = new List<Condition_Party__c>();
        
        //Loop through wrapper list.
        for(PartyWrapper partyWrapper : partyWrappers)
        {
            //If selected
            if(partyWrapper.selected == true)
            {
                if(!existingAgreementParties.contains(partyWrapper.party.Id))
                {
                    //New Agreement Party
                    Condition_Party__c conditionParty = new Condition_Party__c();
                    conditionParty.Condition__c = conditionRecord.Id;
                    conditionParty.Agreement_Party__c = partyWrapper.party.Id;
                    
                    //Add to list.
                    conditionPartiesInsert.add(conditionParty);
                }
            }
            //If deselected
            else
            {
                if(existingAgreementParties.contains(partyWrapper.party.Id))
                {
                    //Id of party to delete.
                    Id conditionPartyId = agreementPartyMap.get(partyWrapper.party.Id);
                    
                    //Agreemnet party to delete.
                    Condition_Party__c conditionPartyToDelete = new Condition_Party__c(Id = conditionPartyId); 
                    
                    //Add to delete list.
                    conditionPartiesDelete.add(conditionPartyToDelete);
                }
            }
        }
        
        //Execute changes.
        try 
        {
            //Insert new records.
            if(!conditionPartiesInsert.isEmpty())
            {
                insert conditionPartiesInsert;
            }

            //Delete deselected records.
            if(!conditionPartiesDelete.isEmpty())
            {
                delete conditionPartiesDelete;
            }
            
            //New Page Setup
            PageReference standardPage = new PageReference('/'+conditionRecord.Id); 
            standardPage.setRedirect(true);

            //Redirect.
            return standardPage;
        }
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR,'Error: '+e.getMessage()));
        }
        
        //Default.
        return null;
    }

    /**
    * actionCancel
    **/
    public PageReference actionCancel() 
    { 
        PageReference page = new PageReference('/'+param1);
        page.setRedirect(true);
        return page;
    }
    
    /**
     * Wrapper Class
    **/
    public class PartyWrapper 
    {
        public Agreement_Party__c party { get; set; }
        public Boolean selected { get; set; }
        
        public PartyWrapper() 
        {
            this.selected = false; 
        } 
    }
}