objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agreement_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Agreement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Awaiting Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Executed</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Send to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed/Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Amended</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled/Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Superceded</fullName>
        <isActive>false</isActive>
        <label>Superceded</label>
    </customValue>
    <description>Agreement Management (LEAP)</description>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

classes/Libra_Restful_Get_All_Test.cls
/*=============================================
*@CreatedDate :2018-07-25
*@CreatedBy : Mthandeni Gumede	
*@Description : Test Class for Libra_Restful_Get_All
===============================================*/
@isTest
private class Libra_Restful_Get_All_Test {
    
    static testMethod void TestPost_Postive() {
      
            
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = 'services/apexrest/all';
        req.httpMethod = 'POST';
        

        
        RestContext.request = req;
        RestContext.response= res;
        
       
               
        Test.startTest();
        Libra_Restful_Get_All.getAll();
        Test.stopTest();
    }
    
     static testMethod void TestPost_Negtive() {
   
        List<Agreement__c> Agreementlist = [Select id,Agreement_Status__c from Agreement__c where Agreement_Status__c ='Amended' limit 1];
        if(Agreementlist.size()>0)
        {
            Agreementlist[0].Agreement_Status__c ='';
        }
   
        update Agreementlist;
    
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = 'services/apexrest/all';
        req.httpMethod = 'POST';
        

        
        RestContext.request = req;
        RestContext.response= res;
        
       
               
        Test.startTest();
        Libra_Restful_Get_All.getAll();
        Test.stopTest();
    }
    
    
      @TestSetup static void setupData()
    {
        Libra_TestDataClass data =  new Libra_TestDataClass();
        
        List<Agreement__c> Agreementlist = [Select id,Agreement_Status__c from Agreement__c limit 1];
        if(Agreementlist.size()>0)
        {
            Agreementlist[0].Agreement_Status__c ='Amended';
        }
   
        update Agreementlist;
    }
    
}