objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Facility_Limit__c</fullName>
        <description>Facility limit to determine each Lender&apos;s portion</description>
        <label>Facility Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <description>Facility limit to determine each Lender&apos;s portion</description>
        <label>Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <formula>Matter_Deal__r.Relationship__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship</label>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Agreement_Party__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Agreement Parties</relationshipLabel>
        <relationshipName>Agreement_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deal_Party__c</fullName>
        <label>Deal Party</label>
        <referenceTo>Deal_Party__c</referenceTo>
        <relationshipLabel>Agreement Parties</relationshipLabel>
        <relationshipName>Agreement_Parties</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lender_Amount__c</fullName>
        <label>Lender Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lender_Percentage__c</fullName>
        <label>Lender Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <formula>Deal_Party__r.Relationship__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship</label>
        <type>Text</type>
    </fields>
    <label>Agreement Party</label>
    <nameField>
        <label>Agreement Party</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal_Party__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deal Parties</relationshipLabel>
        <relationshipName>Deal_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal Party</label>
    <nameField>
        <displayFormat>DP-{00000}</displayFormat>
        <label>Deal Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Agreement_Party_Helper.cls
/**
 _____ _                 _ _____           _ _   _         
/  __ \ |               | /  ___|         (_) | | |        
| /  \/ | ___  _   _  __| \ `--. _ __ ___  _| |_| |__  ___ 
| |   | |/ _ \| | | |/ _` |`--. \ '_ ` _ \| | __| '_ \/ __|
| \__/\ | (_) | |_| | (_| /\__/ / | | | | | | |_| | | \__ \
 \____/_|\___/ \__,_|\__,_\____/|_| |_| |_|_|\__|_| |_|___/
 
 *** CHANGE LOG ***
 
 18/06/2017 - PG    - Created Trigger. 
 24/08/2017 - PG    - Added "beforeUpdate" method.
                    - Added "calculateLimits" methods to update the percentage and amounts.
 09/11/2017 - TdB   - API Name change. Facility_Limit__c  to Limit__c on Agreements Object
 14/11/2017 - TdB   - Make sure that lowest Parent Limit (Agreement/Facility/Tranche) is not exceeded when creating a Drawdown
 12/12/2017 - PG    - Updated calculateLimits method to handle null values.
 21/02/2018 - TdB   - Set lender portion to 0 if Agreement limit is 0
 12/03/2018 - TdB   - Agreement Limit optional (prevent Users from creating Drawdown and Agency with no Agreement Limit) 
**/ 
public class Agreement_Party_Helper {
    
    /**
    * beforeInsert trigger handler.
    **/
    public static void beforeInsert(List<Agreement_Party__c> inputNewList) 
    {
        //Blank Variables
        Set<Id> dealPartyIds = new Set<Id>();
        Map<Id, Deal_Party__c>  dealParties = new Map<Id, Deal_Party__c>();

        //Loop; through agreements.
        for(Agreement_Party__c agreementParty : inputNewList)
        {
            dealPartyIds.add(agreementParty.Deal_Party__c);
        }

        //Get all the relevant deal parties.
        dealParties = new Map<Id, Deal_Party__c>([
            SELECT 
                Id,
                Relationship__c,
                Relationship__r.Name
            FROM Deal_Party__c
            WHERE
                Id IN :dealPartyIds
        ]); 

        //Update the agreement party record name.
        for(Agreement_Party__c agreementParty : inputNewList)
        {
            agreementParty.Name = dealParties.get(agreementParty.Deal_Party__c).Relationship__r.Name; 
        }
    }

    /**
    * beforeUpdate trigger handler.
    **/
    public static void beforeUpdate(List<Agreement_Party__c> inputNewList, Map<Id, Agreement_Party__c> inputOldMap)
    {
        calculateLimits(inputNewList, inputOldMap);
    }

    /**
    * calculateLimits - Sets the percentage or amount.  Depending on the what was modified.
    **/
    public static void calculateLimits(List<Agreement_Party__c> inputNewList, Map<Id, Agreement_Party__c> inputOldMap)
    {
        //Blank vars.
        Set<Id> agreementIds = new Set<Id>();
        Map<Id, Agreement__c> agreements = new Map<Id, Agreement__c>();

        //Loop through agreement parties.
        for(Agreement_Party__c agreementParty : inputNewList)
        {   
            //Add to set.
            agreementIds.add(agreementParty.Agreement__c);
        }

        //Have agreements to get.
        if(!agreementIds.isEmpty())
        {
            //Get agreements with there Parties.
            agreements = new Map<Id, Agreement__c>([
                SELECT
                    Id,
                    Limit__c,
                    (
                        SELECT
                            Id,
                            Agreement__c,
                            Lender_Percentage__c,
                            Lender_Amount__c
                        FROM Agreement_Parties__r
                    )
                FROM Agreement__c
                WHERE
                    Id IN :agreementIds 
            ]);
        }

        //Loop through agreement parties again to set the values for update.
        for(Agreement_Party__c agreementParty : inputNewList)
        {   
            //Agreements facility limit.
            Decimal agreementFacilityLimit = agreements.get(agreementParty.Agreement__c).Limit__c;

            /*if(agreementFacilityLimit == null)
            {
                agreementParty.addError('Please ensure there is a "Limit" specified on the Agreement.');
                continue;
            }*/


            //Amount was updated, calculate new percentage.
            if(agreementParty.Lender_Amount__c != inputOldMap.get(agreementParty.Id).Lender_Amount__c && agreementParty.Lender_Amount__c != null && agreementFacilityLimit != 0 && agreementFacilityLimit != null)
            {
                agreementParty.Lender_Percentage__c = (agreementParty.Lender_Amount__c != null) ? (agreementParty.Lender_Amount__c / agreementFacilityLimit) * 100 : 0;
            }
            else if(agreementParty.Lender_Amount__c != inputOldMap.get(agreementParty.Id).Lender_Amount__c && agreementParty.Lender_Amount__c != null && agreementFacilityLimit == 0)
            {
                agreementParty.Lender_Percentage__c = 0;
            }
            else if(agreementFacilityLimit == null)
            {
                agreementParty.Lender_Percentage__c = null;
            }

            //Amount was updated, calculate new percentage.
            if(agreementParty.Lender_Percentage__c != inputOldMap.get(agreementParty.Id).Lender_Percentage__c && agreementParty.Lender_Percentage__c != null && agreementFacilityLimit != 0 && agreementFacilityLimit != null)
            {
                agreementParty.Lender_Amount__c = (agreementParty.Lender_Percentage__c != null) ? agreementFacilityLimit * (agreementParty.Lender_Percentage__c / 100) : 0;
            }
            else  if(agreementParty.Lender_Percentage__c != inputOldMap.get(agreementParty.Id).Lender_Percentage__c && agreementParty.Lender_Percentage__c != null && agreementFacilityLimit == 0)
            {
                agreementParty.Lender_Amount__c = 0;
            }
            else if(agreementFacilityLimit == null)
            {
                agreementParty.Lender_Amount__c = null;
            }
        }
    }
}