objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Description__c</fullName>
        <label>Agreement Description</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Counterparty/Client</inlineHelpText>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter/Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewDate__c</fullName>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AgreementHandler.cls
Public Class AgreementHandler{


Public String AgreementId;

Public  Agreement__c Agreement {get;set;}
Public Case newCase {get;set;}

Public AgreementHandler(){

    AgreementId = ApexPages.currentPage().getParameters().get('id');
    Agreement = [Select id, Matter_Deal__c,Client_Name__c,name,Agreement_Description__c,ReviewDate__c from Agreement__c where id =: AgreementId];
      
      
      
      
       RecordType rt = [Select id From RecordType where Name= 'Knowledge Request' limit 1];
     
      newCase = new Case();
      newCase.RecordTypeid = rt.id;
      newCase.SuggestedTags__c = 'Executed Agreement';
      newCase.Status = 'New';
      newCase.Subject = Agreement.Name;
      
      
      newCase.Matter__c = Agreement.Matter_Deal__c;
      newCase.AccountId = Agreement.Client_Name__c;
      newCase.Subject = Agreement.name;
      newCase.Description = Agreement.Agreement_Description__c;
        newCase.Previous_Review_Date__c = Agreement.ReviewDate__c;

}


Public pagereference ConvertAgreementtoCase(){   
      Insert newCase;
    
      return new pagereference('/'+newCase.id);
}

Public pagereference Cancel(){   
     
    
      return new pagereference('/'+Agreement.id);
}




}