objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System field used to identify which Agreement Template was used to generated the agreement.</description>
        <inlineHelpText>System field used to identify which Agreement Template was used to generated the agreement.</inlineHelpText>
        <label>Agreement Template</label>
        <referenceTo>Agreement_Template__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_Agreement_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Agreement_Template__c.object
<CustomObject>
    <label>Agreement Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BoxDocument__c.object
<CustomObject>
    <description>Managing box interactions to through a UI similar to standard attachments</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipName>BoxDocuments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_Type__c</fullName>
        <label>Owner Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                </value>
                <value>
                    <fullName>Condition</fullName>
                </value>
                <value>
                    <fullName>Matter</fullName>
                </value>
                <value>
                    <fullName>Condition_Occurrence</fullName>
                    <label>Condition Occurrence</label>
                </value>
                <value>
                    <fullName>Collateral</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PII__c</fullName>
        <inlineHelpText>Document uploaded contains personal identifiable informaiton</inlineHelpText>
        <label>Personally Identifiable Information</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Box Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HotDocs_Request__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>HotDocs Requests</relationshipLabel>
        <relationshipName>HotDocs_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attempts__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Attempts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_ID__c</fullName>
        <inlineHelpText>Salesforce Job Queue Id</inlineHelpText>
        <label>Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Attempt__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Last Attempt</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supporting Agreement</label>
        <referenceTo>Supporting_Agreement__c</referenceTo>
        <relationshipLabel>HotDocs Requests</relationshipLabel>
        <relationshipName>HotDocs_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Item_ID__c</fullName>
        <label>Work Item ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HotDocs Request</label>
    <nameField>
        <displayFormat>HR-{0}</displayFormat>
        <label>Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HotDocs Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HotDocs_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>Box_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Box Document</label>
        <referenceTo>BoxDocument__c</referenceTo>
        <relationshipLabel>HotDocs Request Items</relationshipLabel>
        <relationshipName>HotDocs_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HotDocs_Request__c</fullName>
        <label>HotDocs Request</label>
        <referenceTo>HotDocs_Request__c</referenceTo>
        <relationshipLabel>HotDocs Request Items</relationshipLabel>
        <relationshipName>HotDocs_Request_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <label>Item ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Answer File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>HotDocs Request Item</label>
    <nameField>
        <displayFormat>HRI-{0}</displayFormat>
        <label>Request Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HotDocs Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Supporting_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement Template</label>
        <referenceTo>Agreement_Template__c</referenceTo>
        <relationshipLabel>Supporting Agreements</relationshipLabel>
        <relationshipName>Supporting_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Supporting Agreements</relationshipLabel>
        <relationshipName>Supporting_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Agreement_Type__c</fullName>
        <label>Master Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GMRA Agreement</fullName>
                </value>
                <value>
                    <fullName>GMSLA Agreement</fullName>
                </value>
                <value>
                    <fullName>ISDA Agreement</fullName>
                </value>
                <value>
                    <fullName>Prime Services Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supporting Agreement</label>
    <nameField>
        <displayFormat>SA-{0}</displayFormat>
        <label>Supporting Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supporting Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Master_Agreement_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>GMRA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>GMSLA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>ISDA Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Prime Services Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Supporting Agreement</fullName>
    </customValue>
    <masterLabel>Master Agreement Type</masterLabel>
</GlobalValueSet>

classes/HotDocs_Request_Queue.cls
/**
 _____ _                 _ _____           _ _   _         
/  __ \ |               | /  ___|         (_) | | |        
| /  \/ | ___  _   _  __| \ `--. _ __ ___  _| |_| |__  ___ 
| |   | |/ _ \| | | |/ _` |`--. \ '_ ` _ \| | __| '_ \/ __|
| \__/\ | (_) | |_| | (_| /\__/ / | | | | | | |_| | | \__ \
 \____/_|\___/ \__,_|\__,_\____/|_| |_| |_|_|\__|_| |_|___/
 
 *** CHANGE LOG ***
 
 10/11/2017 - PG    - Created Class. 
 23/11/2017 - PG 	- Added Handling to upload to box.com.
 17/01/2017 - PG 	- Moved Answer file processing to after request item upserts.
 13/03/2018 - PG 	- Updated to use metadata type.

**/
public class HotDocs_Request_Queue implements Queueable, Database.AllowsCallouts 
{
	private HotDocs_Request__c hotDocsRequest { get; set; }
	private HotDocs_API api { get; set; }
	private Map<String, HotDocs_Request_Item__c> existingRequestItems { get; set; }
	private Map<String, String> existingBoxDocuments { get; set; }
	private Boolean hasAnswerFile { get; set; }
    public static Map <String, Schema.RecordTypeInfo> agreementTemplateRecordTypes = Agreement_Template__c.sObjectType.getDescribe().getRecordTypeInfosByName(); 
	
	public HotDocs_Request_Queue(String iHotDocsRequestId)  
	{
		//Blank vars.
		Set<String> jobNames = new Set<String>();		
		existingRequestItems = new Map<String, HotDocs_Request_Item__c>(); 
		existingBoxDocuments = new Map<String, String>();
		hasAnswerFile = false;

		try
		{
	    	//Instantiate API
	    	api = new HotDocs_API();	

	    	//Load hotdocs request and existing items.
			hotDocsRequest = [
				SELECT
					Id, 
					Work_Item_ID__c,
                	Supporting_Agreement__c,
                	Supporting_Agreement__r.Agreement_Template__r.RecordTypeId,
					Agreement__c,
                    Agreement__r.Agreement_Template__r.RecordTypeId,
                    Agreement__r.Master_Agreement_Type__c,
					Attempts__c, 
					(
						SELECT
							Id,
							Type__c,
							Item_ID__c,
							Status__c,
							Box_Document__c
						FROM HotDocs_Request_Items__r 
					)
				FROM HotDocs_Request__c
				WHERE
					Id = :iHotDocsRequestId 
			];

			//Get all existing hotdocs request items for Agreement.
			List<HotDocs_Request_Item__c> agreementRequestItems = new List<HotDocs_Request_Item__c>([
				SELECT
					Id,
					HotDocs_Request__r.Agreement__c,
					Box_Document__c,
					Box_Document__r.Name
				FROM HotDocs_Request_Item__c
				WHERE
					HotDocs_Request__r.Agreement__c = :hotDocsRequest.Agreement__c
					AND Box_Document__c != null
			]);

			//Build up a map of existing document name to box document id.
			for(HotDocs_Request_Item__c requestItem : agreementRequestItems)
			{
				existingBoxDocuments.put(requestItem.Box_Document__r.Name, requestItem.Box_Document__c);
			}

			//Build up a map for easy reference of existing items.
			for(HotDocs_Request_Item__c requestItem : hotDocsRequest.HotDocs_Request_Items__r)
			{
			 	if(requestItem.Type__c == 'Document')
			 	{
			 		existingRequestItems.put(requestItem.Item_ID__c, requestItem);
			 	}

			 	if(requestItem.Type__c == 'Answer File')
			 	{
			 		hasAnswerFile = true;
			 	}
			}

			//Ensure our monitoring job is scheduled.
			List<CronTrigger> cronJobs = new List<CronTrigger>([
				SELECT
					Id,
					CronJobDetail.Name
				FROM CronTrigger
				WHERE
					CronJobDetail.Name LIKE '%HotDocs Request Monitoring%' 
			]);

			//Build set for existing schedule reference.
			for(CronTrigger cronJob : cronJobs)
			{
				jobNames.add(cronJob.CronJobDetail.Name);
			}

			//Monitoring is active and needs to be scheduled every 15 mins.
			if(api.SETTINGS.Enable_Monitoring__c == true && cronJobs.size() != 4) 
			{
				if(!jobNames.contains('HotDocs Request Monitoring - 0'))
				{
					System.schedule('HotDocs Request Monitoring - 0', '0 0 * * * ? ', new HotDocs_Request_Monitoring());
				}

				if(!jobNames.contains('HotDocs Request Monitoring - 15'))
				{
					System.schedule('HotDocs Request Monitoring - 15', '0 15 * * * ? ', new HotDocs_Request_Monitoring());
				} 

				if(!jobNames.contains('HotDocs Request Monitoring - 30'))
				{
					System.schedule('HotDocs Request Monitoring - 30', '0 30 * * * ? ', new HotDocs_Request_Monitoring());
				} 

				if(!jobNames.contains('HotDocs Request Monitoring - 45'))
				{
					System.schedule('HotDocs Request Monitoring - 45', '0 45 * * * ? ', new HotDocs_Request_Monitoring());
				} 
			}
		}
		catch(Exception e)
		{
			DebugLog.create( new DebugLog.Error(e, 'HotDocs_Request_Queue', 'constructor', 'HotDocs Request ID: '+iHotDocsRequestId) );    
		}
	}

	public void execute(QueueableContext context)
	{
		System.debug('### HotDocs_Request_Queue : execute');

		//Blank vars.
		List<HotDocs_Request_Item__c> requestItems = new List<HotDocs_Request_Item__c>();		
		Map<String, HotDocs_Document> retrievedDocumentsMetadata = new Map<String, HotDocs_Document>();		
		List<BoxDocument__c> newBoxDocuments = new List<BoxDocument__c>();
		Map<String, BoxDocument__c> newRequestBoxDocuments = new Map<String, BoxDocument__c>();
		Set<Id> boxDocumentIds = new Set<Id>();
		String answerXML = '';

		try
		{
			System.debug('### HotDocs_Request_Queue : execute : try ');

			//Fetch work item metadata.
			HotDocs_WorkItem workItem = api.getWorkItemMetadata(hotDocsRequest.Work_Item_ID__c);

			System.debug('### HotDocs_Request_Queue : execute : try : AFTER');

			//Loop over work item documents.
			for(HotDocs_WorkItem.AssembledDocuments assembledDocument : workItem.PrimaryTemplate.AssembledDocuments)
			{	
				//Retrieve document meta data from HotDocs.
				HotDocs_Document documentMeta = api.getDocumentMetadata(hotDocsRequest.Work_Item_ID__c, assembledDocument.DocumentId);
				retrievedDocumentsMetadata.put(assembledDocument.DocumentId, documentMeta);

				//If this is NOT an existing document item.
				if(!existingRequestItems.containsKey(assembledDocument.DocumentId))
				{
					//New Document Request Item.
					HotDocs_Request_Item__c requestItem = new HotDocs_Request_Item__c(
						Item_ID__c = assembledDocument.DocumentId, 
						HotDocs_Request__c = hotDocsRequest.Id, 
						Type__c = 'Document',
						Status__c = 'Queued' 
					);

					//If there is an existing box document with this file name associate the box document.
					if(existingBoxDocuments.containsKey(documentMeta.Title+documentMeta.FileExtension))
					{
						requestItem.Box_Document__c = existingBoxDocuments.get(documentMeta.Title+documentMeta.FileExtension);
					}

					//Add to insert list.
					requestItems.add(requestItem);
				}

				//Existing request item
				if(existingRequestItems.containsKey(assembledDocument.DocumentId))
				{
					//It is not completed yet.
					if(existingRequestItems.get(assembledDocument.DocumentId).Status__c != 'Completed')
					{
						//Add existing list for processing.
						requestItems.add(existingRequestItems.get(assembledDocument.DocumentId));
					}
				}
			}

			//Needed to add answer file if needed.
			Integer answerIndex = requestItems.size();					

			//New answer request item.
			if(hasAnswerFile == false)
			{
				//Fetch answer file content.
				answerXML = api.getAnswerSetXmlFile(workItem.AnswerSetId);

				HotDocs_Request_Item__c answerItem = new HotDocs_Request_Item__c(
					Item_ID__c = workItem.AnswerSetId, 
					HotDocs_Request__c = hotDocsRequest.Id, 
					Type__c = 'Answer File',
					Status__c = 'Completed'
				);			

				//Add to list.
				requestItems.add(answerItem); 
			}

			//Upsert Request Items.
			upsert requestItems;

			//Have we set to store answer file?
			if(api.SETTINGS.Keep_Answer_File__c == true && hasAnswerFile == false) 
			{
				Attachment attachment = new Attachment();
				attachment.Body = Blob.valueOf(answerXML); 
  				attachment.Name = 'Received-AnswerFile.xml';
  				attachment.ParentId = requestItems[answerIndex].Id; 
  				insert attachment;
			}

			//Process after request items, so we can see the XML file if processing fails.
			if(hasAnswerFile == false)
			{
				//Process AnswerXML
				//Libra 
				if(hotDocsRequest.Supporting_Agreement__r.Agreement_Template__r.RecordTypeId == agreementTemplateRecordTypes.get('Agreement Template - Master').getRecordTypeId())
                {
                    //CSA
                    if(hotDocsRequest.Supporting_Agreement__c != null)
                    {
                        HotDocs_Helper.processCsaAnswerXML(hotDocsRequest.Supporting_Agreement__c, answerXML);
                    }
                }
				else if(hotDocsRequest.Agreement__r.Agreement_Template__r.RecordTypeId == agreementTemplateRecordTypes.get('Agreement Template - Master').getRecordTypeId())
                {
                     //Prime Services
                    if(hotDocsRequest.Agreement__r.Master_Agreement_Type__c == 'Prime Services Agreement')
                    {
                        HotDocs_Helper.processPrimeServicesAnswerXML(hotDocsRequest.Agreement__c, answerXML);
                    }
                    //GMSLA
                    else if(hotDocsRequest.Agreement__r.Master_Agreement_Type__c == 'GMSLA Agreement')
                    {
                        HotDocs_Helper.processGmslaAnswerXML(hotDocsRequest.Agreement__c, answerXML);
                    }
                    //GMRA
                    else if(hotDocsRequest.Agreement__r.Master_Agreement_Type__c == 'GMRA Agreement')
                    {
                        HotDocs_Helper.processGmraAnswerXML(hotDocsRequest.Agreement__c, answerXML);
                    }
                    //ISDA
                    else if(hotDocsRequest.Agreement__r.Master_Agreement_Type__c == 'ISDA Agreement')
                    {
                        HotDocs_Helper.processIsdaAnswerXML(hotDocsRequest.Agreement__c, answerXML);
                    }
                }
                //TMG and LEAP
                else
                {
                    HotDocs_Helper.processAnswerXML(hotDocsRequest.Agreement__c, answerXML);
                }
				
			}

			//Loop over request items for box document processing.
			for(HotDocs_Request_Item__c requestItem : requestItems)
			{
				if(requestItem.Type__c == 'Document')
				{
					if(requestItem.Box_Document__c == null)
					{
						//New Box Document
						BoxDocument__c boxDocument = new BoxDocument__c(
							Name = retrievedDocumentsMetadata.get(requestItem.Item_ID__c).Title + retrievedDocumentsMetadata.get(requestItem.Item_ID__c).FileExtension,
							Agreement__c = hotDocsRequest.Agreement__c,
							PII__c = 'Yes',
							Owner_Type__c = 'Agreement__c'
						);

						//Add to insert list.
						newBoxDocuments.add(boxDocument);

						//Add to reference map for after insert linking.
						newRequestBoxDocuments.put(requestItem.Id, boxDocument);			
					}
					else
					{
						//Add to set for processing.
						boxDocumentIds.add(requestItem.Box_Document__c);  
					}
				}
			}

			//Any new box documents to insert?
			if(!newBoxDocuments.isEmpty())
			{
				insert newBoxDocuments;
			}

			//Update the box document reference on each item.
			for(HotDocs_Request_Item__c requestItem : requestItems)
			{
				//Needs to be associated to box document?
				if(requestItem.Box_Document__c == null && requestItem.Type__c == 'Document' && newRequestBoxDocuments.containsKey(requestItem.Id))
				{
					//Set box id on request.
					requestItem.Box_Document__c = newRequestBoxDocuments.get(requestItem.Id).Id;
					
					//Add to set for processing.
					boxDocumentIds.add(requestItem.Box_Document__c); 
				}
			}

			//Update request items with Box Ids.
			update requestItems;

			//finally call box to upload files.
			for(HotDocs_Request_Item__c requestItem : requestItems)
			{	
				if(requestItem.Type__c == 'Document' && requestItem.Box_Document__c != null)
				{
					//Future call out.
					HotDocs_Helper.retrieveDocument(requestItem.Id);
				}
			}
		}
		catch(Exception e)
		{
			//Mark request as 'Failed'
			hotDocsRequest.Status__c = 'Failed'; 

			//Log Error.
			DebugLog.create( new DebugLog.Error(e, 'HotDocs_Request_Queue', 'execute', 'HotDocs Request ID: '+hotDocsRequest.Id) );
		}
		finally
		{
			//Update the request.
			hotDocsRequest.Job_ID__c = context.getJobId();
			hotDocsRequest.Attempts__c = hotDocsRequest.Attempts__c + 1;
			hotDocsRequest.Last_Attempt__c = DateTime.now();
			update hotDocsRequest;
		}
	}
}