objects/Agreement__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agreement_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Agreement</fullName>
        <active>true</active>
        <label>Agreement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Supporting_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Agreement__c</referenceTo>
        <relationshipLabel>Supporting Agreements</relationshipLabel>
        <relationshipName>Supporting_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supporting Agreement</label>
    <nameField>
        <displayFormat>SA-{0}</displayFormat>
        <label>Supporting Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supporting Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Agreement_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Awaiting Feedback</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Executed</fullName>
    </customValue>
    <customValue>
        <fullName>Extension</fullName>
    </customValue>
    <customValue>
        <fullName>Live</fullName>
    </customValue>
    <customValue>
        <fullName>Send to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Undergoing Execution</fullName>
    </customValue>
    <customValue>
        <fullName>Under Negotiation</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Process</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed/Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Amended</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled/Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Superceded</fullName>
        <isActive>false</isActive>
        <label>Superceded</label>
    </customValue>
    <description>Agreement Management (LEAP)</description>
    <masterLabel>Agreement Status</masterLabel>
</GlobalValueSet>

classes/Libra_Inbound_Restful_S_Agreement.cls
@RestResource(urlMapping='/supporting-agreement/*')
global class Libra_Inbound_Restful_S_Agreement {

      @HttpPost
    global static void getSupportingAgreement()
    {
          String requestBody = RestContext.request.requestBody.toString();
        try
        {
            List<Supporting_Agreement__c> supportingAgreementList;
            if(String.isNotBlank(requestBody))
            {
                Libra_Restul_Functions.AgreementWrapper supportingAgreement =(Libra_Restul_Functions.AgreementWrapper)JSON.deserialize(requestBody,Libra_Restul_Functions.AgreementWrapper.class);
                
                if(String.isNotBlank(supportingAgreement.agreementId))
                {
                    String additionalClause = ' Agreement__r.Agreement_Status__c IN (\'Confirmed/Completed\',\'Amended\')';
                    supportingAgreementList = Libra_Restul_Functions.getSObjectById(supportingAgreement.agreementId,Libra_Restful_Constants.SupportingAgreementColumns,Libra_Restful_Constants.SupportingAgreementObject,additionalClause);
                    
                    if(supportingAgreementList!=null && supportingAgreementList.size()>0)
                    {
                        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(new LibraRestfulModel.SupportingAgreement(supportingAgreementList[0])));
                    }
                    else
                    {
                        RestContext.response.responseBody = Blob.valueOf(Libra_Restful_Constants.NotFound);
                        RestContext.response.statusCode =Libra_Restful_Constants.statusCodeNotFound;
                    }
                }
            }
            
            
        }
        catch(StringException eex)
        {
            RestContext.response.responseBody = Blob.valueOf(Libra_Restful_Constants.NotFound);
            RestContext.response.statusCode =Libra_Restful_Constants.statusCodeNotFound;
        }catch(QueryException qe)
        {
            RestContext.response.responseBody = Blob.valueOf(qe.getMessage());
            RestContext.response.statusCode =400;
        }
    }
}