objects/Annual_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Pricing</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Letter Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Annual Pricings</relationshipLabel>
        <relationshipName>Annual_Pricings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Template</label>
        <referenceTo>Pricing_Template__c</referenceTo>
        <relationshipLabel>Annual Pricings</relationshipLabel>
        <relationshipName>Annual_Pricings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Annual Pricing</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Annual Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Pricings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Annual_Pricing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Pricing__c</fullName>
        <label>Annual Pricing</label>
        <referenceTo>Annual_Pricing__c</referenceTo>
        <relationshipLabel>Annual Pricing Items</relationshipLabel>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending 1st line Approval</fullName>
                </value>
                <value>
                    <fullName>Pending 2nd line Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Final_Price__c</fullName>
        <label>Final Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Deal_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Deal Product</label>
        <referenceTo>Pricing_Deal_Product__c</referenceTo>
        <relationshipLabel>Annual Pricing Items</relationshipLabel>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Pricing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Standard Pricing</label>
        <referenceTo>Standard_Pricing__c</referenceTo>
        <relationshipLabel>Annual Pricing Items</relationshipLabel>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Annual Pricing Item</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>Annual Pricing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Pricing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pricing_Deal_Product__c.object
<CustomObject>
    <label>Pricing Deal Product</label>
    <nameField>
        <label>Pricing Deal Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Deal Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Pricing_Template__c.object
<CustomObject>
    <label>Pricing Template</label>
    <nameField>
        <label>Pricing Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Standard_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Deal_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Deal Product</label>
        <referenceTo>Pricing_Deal_Product__c</referenceTo>
        <relationshipLabel>Standard Pricings</relationshipLabel>
        <relationshipName>Standard_Pricings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Template__c</fullName>
        <label>Pricing Template</label>
        <referenceTo>Pricing_Template__c</referenceTo>
        <relationshipLabel>Standard Pricings</relationshipLabel>
        <relationshipName>Standard_Pricings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Standard Pricing</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Standard Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Pricings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ZZTEST_APT_AnnualPricingItemTrigger.cls
@isTest
private class ZZTEST_APT_AnnualPricingItemTrigger
{
	public static testMethod void testSetDefaultFinalPrice(){
		Integer BATCH_SIZE = 200;
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
		//ZZTEST_F_PricingGroup pricingGroupFactory = ZZTEST_DataFactoryFacade.pricingGroup;
		ZZTEST_F_PricingDealProduct pricingDealProductFactory = ZZTEST_DataFactoryFacade.pricingDealProduct;
		ZZTEST_F_PricingTemplate pricingTemplateFactory = ZZTEST_DataFactoryFacade.pricingTemplate;

        Account account = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);
        List<Pricing_Deal_Product__c> pricingDealProducts = new List<Pricing_Deal_Product__c>();
        for(Integer i=0; i<BATCH_SIZE; i++){
        	Pricing_Deal_Product__c pricingDealProduct = pricingDealProductFactory.getProduct(ZZTEST_F_PricingDealProduct.PricingDealProductRecordType.DEFAULT_PRICING_DEAL_PRODUCT, dataContainer);
        	pricingDealProducts.add(pricingDealProduct);
        }
        insert pricingDealProducts;

        Pricing_Template__c pricingTemplate = pricingTemplateFactory.getInsertedProduct(ZZTEST_F_PricingTemplate.PricingTemplateRecordType.DEFAULT_PRICING_TEMPLATE, dataContainer);
        List<Standard_Pricing__c> standardPricings = new List<Standard_Pricing__c>();
        for(Pricing_Deal_Product__c pricingDealProduct : pricingDealProducts){
        	standardPricings.add(new Standard_Pricing__c(Pricing_Template__c=pricingTemplate.Id, Pricing_Deal_Product__c=pricingDealProduct.Id, Price__c='1000'));
        }
        insert standardPricings;

        Annual_Pricing__c annualPricing = new Annual_Pricing__c();
        annualPricing.Organisation__c = account.Id;
        annualPricing.Pricing_Template__c = pricingTemplate.Id;
        //annualPricing.Approval_Status__c = APT_AnnualPricingUtils.STATUS_STANDARD_PRICING;
        annualPricing.Approval_Status__c = APT_AnnualPricingUtils.STATUS_NOT_SUBMITTED;
        insert annualPricing;

        List<Annual_Pricing_Item__c> annualPricingItems = new List<Annual_Pricing_Item__c>();
        for(Standard_Pricing__c standardPricing : standardPricings){
        	Annual_Pricing_Item__c annualPricingItem = new Annual_Pricing_Item__c();
        	annualPricingItem.Annual_Pricing__c = annualPricing.Id;
        	annualPricingItem.Pricing_Deal_Product__c = standardPricing.Pricing_Deal_Product__c;
        	annualPricingItem.Standard_Pricing__c = standardPricing.Id;
        	annualPricingItems.add(annualPricingItem);
        }
        insert annualPricingItems;

        Test.startTest();

		for(Annual_Pricing_Item__c api : [SELECT Id, Final_Price__c FROM Annual_Pricing_Item__c WHERE Annual_Pricing__c = :annualPricing.Id]){
			System.assertEquals(api.Final_Price__c, '1000');
		}

        Test.stopTest();
	}

	public static testMethod void testUpdateApprovalStatus(){
		Integer BATCH_SIZE = 200;
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
		//ZZTEST_F_PricingGroup pricingGroupFactory = ZZTEST_DataFactoryFacade.pricingGroup;
		ZZTEST_F_PricingDealProduct pricingDealProductFactory = ZZTEST_DataFactoryFacade.pricingDealProduct;
		ZZTEST_F_PricingTemplate pricingTemplateFactory = ZZTEST_DataFactoryFacade.pricingTemplate;

        Account account = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);
        List<Pricing_Deal_Product__c> pricingDealProducts = new List<Pricing_Deal_Product__c>();
        for(Integer i=0; i<BATCH_SIZE; i++){
        	Pricing_Deal_Product__c pricingDealProduct = pricingDealProductFactory.getProduct(ZZTEST_F_PricingDealProduct.PricingDealProductRecordType.DEFAULT_PRICING_DEAL_PRODUCT, dataContainer);
        	pricingDealProducts.add(pricingDealProduct);
        }
        insert pricingDealProducts;

        Pricing_Template__c pricingTemplate = pricingTemplateFactory.getInsertedProduct(ZZTEST_F_PricingTemplate.PricingTemplateRecordType.DEFAULT_PRICING_TEMPLATE, dataContainer);
        List<Standard_Pricing__c> standardPricings = new List<Standard_Pricing__c>();
        for(Pricing_Deal_Product__c pricingDealProduct : pricingDealProducts){
        	standardPricings.add(new Standard_Pricing__c(Pricing_Template__c=pricingTemplate.Id, Pricing_Deal_Product__c=pricingDealProduct.Id, Price__c='1000'));
        }
        insert standardPricings;

        Annual_Pricing__c annualPricing = new Annual_Pricing__c();
        annualPricing.Organisation__c = account.Id;
        annualPricing.Pricing_Template__c = pricingTemplate.Id;
        //annualPricing.Approval_Status__c = APT_AnnualPricingUtils.STATUS_NOT_SUBMITTED;
        annualPricing.Approval_Status__c = APT_AnnualPricingUtils.STATUS_STANDARD_PRICING;
        insert annualPricing;

        List<Annual_Pricing_Item__c> annualPricingItems = new List<Annual_Pricing_Item__c>();
        for(Standard_Pricing__c standardPricing : standardPricings){
        	Annual_Pricing_Item__c annualPricingItem = new Annual_Pricing_Item__c();
        	annualPricingItem.Annual_Pricing__c = annualPricing.Id;
        	annualPricingItem.Pricing_Deal_Product__c = standardPricing.Pricing_Deal_Product__c;
        	annualPricingItem.Standard_Pricing__c = standardPricing.Id;
        	annualPricingItems.add(annualPricingItem);
        }
        insert annualPricingItems;

        Test.startTest();

        for(Annual_Pricing_Item__c api : annualPricingItems){
        	api.Approval_Status__c = APT_AnnualPricingUtils.STATUS_PENDING_FIRST_APPROVAL;
        }
		update annualPricingItems;

		Annual_Pricing__c annualPricingPending = [SELECT Id, Approval_Status__c FROM Annual_Pricing__c WHERE Id = :annualPricing.Id LIMIT 1];
		System.assertEquals(annualPricingPending.Approval_Status__c, APT_AnnualPricingUtils.STATUS_PENDING);

		for(Annual_Pricing_Item__c api : annualPricingItems){
        	api.Approval_Status__c = APT_AnnualPricingUtils.STATUS_REJECTED;
        }
		update annualPricingItems;

		Annual_Pricing__c annualPricingRejected = [SELECT Id, Approval_Status__c FROM Annual_Pricing__c WHERE Id = :annualPricing.Id LIMIT 1];
		System.assertEquals(annualPricingRejected.Approval_Status__c, APT_AnnualPricingUtils.STATUS_REJECTED);

        Test.stopTest();
	}
}