objects/Annual_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Pricing</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Letter Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Template</label>
        <referenceTo>Pricing_Template__c</referenceTo>
        <relationshipLabel>Annual Pricings</relationshipLabel>
        <relationshipName>Annual_Pricings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Annual Pricing</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Annual Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Pricings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Annual_Pricing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Pricing__c</fullName>
        <label>Annual Pricing</label>
        <referenceTo>Annual_Pricing__c</referenceTo>
        <relationshipLabel>Annual Pricing Items</relationshipLabel>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending 1st line Approval</fullName>
                </value>
                <value>
                    <fullName>Pending 2nd line Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Final_Price__c</fullName>
        <label>Final Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Deal_Product_Name__c</fullName>
        <formula>Pricing_Deal_Product__r.Pricing_Deal_Product_Name__c</formula>
        <label>Pricing Deal Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Deal_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Deal Product</label>
        <referenceTo>Pricing_Deal_Product__c</referenceTo>
        <relationshipLabel>Annual Pricing Items</relationshipLabel>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Group__c</fullName>
        <formula>Pricing_Deal_Product__r.Pricing_Group__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT(Pricing_Deal_Product__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(Pricing_Deal_Product__r.Product_Type__c)</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Price__c</fullName>
        <formula>Standard_Pricing__r.Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Standard Price</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Pricing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Standard Pricing</label>
        <referenceTo>Standard_Pricing__c</referenceTo>
        <relationshipLabel>Annual Pricing Items</relationshipLabel>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_VAT_Inclusive__c</fullName>
        <formula>Pricing_Deal_Product__r.Pricing_Group__r.VAT_Inclusive__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VAT Inclusive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Icon__c</fullName>
        <formula>IF(Approval_Required__c, 
  CASE(Approval_Status__c, 
    &apos;Approved&apos;, IMAGE(&quot;/resource/IMG_Status_Approved&quot;, &quot;Green&quot;, 16, 16), 
    &apos;Rejected&apos;, IMAGE(&quot;/resource/IMG_Status_Rejected&quot;, &quot;Red&quot;, 16, 16),
    IMAGE(&quot;/resource/IMG_Status_Pending&quot;, &quot;Yellow&quot;, 16, 16)
  ), 
  &apos;&apos;
)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isLocked</label>
        <type>Checkbox</type>
    </fields>
    <label>Annual Pricing Item</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>Annual Pricing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Pricing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pricing_Deal_Product__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Deal_Product_Name__c</fullName>
        <description>Name of the Pricing Deal Product (the standard object name is limited to 80 characters)</description>
        <label>Pricing Deal Product Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Group</label>
        <referenceTo>Pricing_Group__c</referenceTo>
        <relationshipLabel>Pricing Deal Products</relationshipLabel>
        <relationshipName>Pricing_Deal_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Absa Online</fullName>
                </value>
                <value>
                    <fullName>Administration Fees</fullName>
                </value>
                <value>
                    <fullName>B.NET fees</fullName>
                </value>
                <value>
                    <fullName>Bank Drafts Issued</fullName>
                </value>
                <value>
                    <fullName>Bank Drafts Purchased</fullName>
                </value>
                <value>
                    <fullName>Barclays.Net</fullName>
                </value>
                <value>
                    <fullName>Barclays Dot Net B.Net</fullName>
                </value>
                <value>
                    <fullName>BII International (ICM \C2B</fullName>
                </value>
                <value>
                    <fullName>BII International (Trade Finance)</fullName>
                </value>
                <value>
                    <fullName>Bills</fullName>
                </value>
                <value>
                    <fullName>Bills for Collection Inwards (Imports)</fullName>
                </value>
                <value>
                    <fullName>Bills for collection Outward (Exports)</fullName>
                </value>
                <value>
                    <fullName>Business Integrator &gt; Attorney Management System</fullName>
                </value>
                <value>
                    <fullName>Business Integrator &gt; Card Online Solution</fullName>
                </value>
                <value>
                    <fullName>Business Integrator &gt; Card Online Solution : Co-branded Cards</fullName>
                </value>
                <value>
                    <fullName>Business Integrator &gt; General Fees</fullName>
                </value>
                <value>
                    <fullName>Business Integrator &gt; Host to Host</fullName>
                </value>
                <value>
                    <fullName>Business Integrator &gt; Information Products</fullName>
                </value>
                <value>
                    <fullName>Business Integrator &gt; Maintenance, Support &amp; Training Fees</fullName>
                </value>
                <value>
                    <fullName>Business Integrator &gt; Online High Volume Fee Structure: &gt; 300 Transactions Per Month</fullName>
                </value>
                <value>
                    <fullName>Business Integrator &gt;Online Low Volume Fee Structure: &lt; 300 Transactions Per Month</fullName>
                </value>
                <value>
                    <fullName>Business Integrator - Cash Focus</fullName>
                </value>
                <value>
                    <fullName>Business Integrator - Cash Focus - HIGH VOLUME PACKAGE</fullName>
                </value>
                <value>
                    <fullName>Business Integrator - Cash Focus - STANDARD PACKAGE</fullName>
                </value>
                <value>
                    <fullName>Business Integrator - Core</fullName>
                </value>
                <value>
                    <fullName>Business Integrator Host to Host - Fee Structure &lt; 10 000 transactions</fullName>
                </value>
                <value>
                    <fullName>Business Integrator Host to Host - Fee Structure &gt; 100 000 Transactions</fullName>
                </value>
                <value>
                    <fullName>Business Integrator Host to Host - Fee Structure &gt; 10 000 - 50 000 transactions</fullName>
                </value>
                <value>
                    <fullName>Business Integrator Host to Host - Fee Structure &gt; 50 000 -100 000 transactions</fullName>
                </value>
                <value>
                    <fullName>Business Integrator - Mailbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Deal Product</label>
    <nameField>
        <label>Pricing Deal Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Deal Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Pricing_Template__c.object
<CustomObject>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Pricing Template</label>
    <nameField>
        <label>Pricing Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Standard_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Deal_Product_Name__c</fullName>
        <formula>Pricing_Deal_Product__r.Pricing_Deal_Product_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing Deal Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Deal_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Deal Product</label>
        <referenceTo>Pricing_Deal_Product__c</referenceTo>
        <relationshipLabel>Standard Pricings</relationshipLabel>
        <relationshipName>Standard_Pricings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Group__c</fullName>
        <formula>Pricing_Deal_Product__r.Pricing_Group__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Template__c</fullName>
        <label>Pricing Template</label>
        <referenceTo>Pricing_Template__c</referenceTo>
        <relationshipLabel>Standard Pricings</relationshipLabel>
        <relationshipName>Standard_Pricings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT(Pricing_Deal_Product__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <label>Standard Pricing</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Standard Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Pricings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/APT_AnnualPricingUtils.cls
/**
* @Author		Marta Malinowska
* Company:		Deloitte
* @Description:	This class is used as a help class for classes APT_ViewAnnualPricingController, APT_ApprovalRequestController 
*				and triggers APT_AnnualPricingItemTrigger, APT_StandardPricingTrigger.
* @Date:		09/2015
* @ConstructorParam:	None
* @TestClass:	ZZTEST_APT_PricingLetterController
* History
* <Date>      <Authors Name>     <Brief Description of Change>
*------------------------------------------------------------*/
public class APT_AnnualPricingUtils {
	public static String STATUS_NOT_SUBMITTED = 'Not Submitted';
    public static String STATUS_STANDARD_PRICING = 'Standard Pricing';
	public static String STATUS_PENDING = 'Pending';
	public static String STATUS_APPROVED = 'Approved';
	public static String STATUS_REJECTED = 'Rejected';
	public static String STATUS_PENDING_FIRST_APPROVAL = 'Pending 1st line Approval';
	public static String STATUS_PENDING_SECOND_APPROVAL = 'Pending 2nd line Approval';
    private static final String EDIT = 'edit';

	public APT_AnnualPricingUtils() {}

	/**
	* @Author:		Marta Malinowska
	* @Company:		Deloitte
	* @Description:	This method is used to set Final Price by default to equal to Standard Price.
	* @param 		The list of Annual Pricing Items to process
	* @Returns:		None
	* History
	* <Date>      <Authors Name>     <Brief Description of Change>
	*------------------------------------------------------------*/
	public static void copyStandardPrice(List<Annual_Pricing_Item__c> annualPricingItems){
		Set<Id> standardPricingIds = new Set<Id>();
		for(Annual_Pricing_Item__c api : annualPricingItems){
			if(api.Standard_Pricing__c != null){
				standardPricingIds.add(api.Standard_Pricing__c);
			}
		}

		Map<Id, Standard_Pricing__c> mapStandardPricings = new Map<Id, Standard_Pricing__c>([SELECT Id, Price__c FROM Standard_Pricing__c WHERE Id IN :standardPricingIds]);
		for(Annual_Pricing_Item__c api : annualPricingItems){
			if(api.Standard_Pricing__c != null && mapStandardPricings.containsKey(api.Standard_Pricing__c)){
				api.Final_Price__c =  mapStandardPricings.get(api.Standard_Pricing__c).Price__c;
			}
		}
	}

	/**
	* @Author:		Marta Malinowska
	* @Company:		Deloitte
	* @Description:	This method is used to update the status of Annual Pricing.
	* @param 		The list of Annual Pricing Items before update and after update.
	* @Returns:		None
	* History
	* <Date>      <Authors Name>     <Brief Description of Change>
	*------------------------------------------------------------*/
	public static void updateApprovalStatus(Map<Id, Annual_Pricing_Item__c> newAnnualPricingItems, Map<Id, Annual_Pricing_Item__c> oldAnnualPricingItems){
		Set<Id> annualPricingIds = new Set<Id>();
		for(Id apiId : newAnnualPricingItems.keySet()){
			if(oldAnnualPricingItems.get(apiId).Approval_Status__c != newAnnualPricingItems.get(apiId).Approval_Status__c){
				annualPricingIds.add(newAnnualPricingItems.get(apiId).Annual_Pricing__c);
			}
		}

		List<Annual_Pricing__c> annualPricingToUpd = new List<Annual_Pricing__c>();
		for(Annual_Pricing__c ap : [SELECT Id, Approval_Status__c, (SELECT Id, Approval_Status__c FROM Annual_Pricing_Items__r)
									FROM Annual_Pricing__c WHERE Id IN :annualPricingIds]){
			Boolean isPending = false;
			Boolean isApproved = true;
			Boolean isRejected = false;
			for(Annual_Pricing_Item__c api : ap.Annual_Pricing_Items__r){
				if(api.Approval_Status__c != STATUS_APPROVED){
					isApproved = false;
					if(api.Approval_Status__c == STATUS_PENDING_FIRST_APPROVAL || api.Approval_Status__c == STATUS_PENDING_SECOND_APPROVAL){
						isPending = true;
					} else if(api.Approval_Status__c == STATUS_REJECTED){
						isPending = false;
						isRejected = true;
						break;
					} 
				}
			}
			if(isPending){
				ap.Approval_Status__c = STATUS_PENDING;
				annualPricingToUpd.add(ap);
			}
			if(isApproved){
				ap.Approval_Status__c = STATUS_APPROVED;
				annualPricingToUpd.add(ap);
			}
			if(isRejected){
				ap.Approval_Status__c = STATUS_REJECTED;
				annualPricingToUpd.add(ap);
			} 
		}

		update annualPricingToUpd;
	}

	/**
	* @Author:		Marta Malinowska
	* @Company:		Deloitte
	* @Description:	This method is used to check if Pricing Template is locked and add error message for Standard Pricings.
	* @param 		The list of Standard Pricings.
	* @Returns:		None
	* History
	* <Date>      <Authors Name>     <Brief Description of Change>
	*------------------------------------------------------------*/
	public static void validateStandardPricingBeforeInsert(List<Standard_Pricing__c> standardPricings){
		Map<Id, Pricing_Template__c> mapPricingTemplates = getPricingTemplatesMap(standardPricings);
		for(Standard_Pricing__c stdPricing : standardPricings){
			if(mapPricingTemplates.containsKey(stdPricing.Pricing_Template__c) && mapPricingTemplates.get(stdPricing.Pricing_Template__c).Locked__c == true){
				stdPricing.addError(Label.errMsg_NotAllowedToAddStandardPricing);
			}
		}
	}

	/**
	* @Author:		Marta Malinowska
	* @Company:		Deloitte
	* @Description:	This method is used to check if Pricing Template is locked and add error message for Standard Pricings to prevent update.
	* @param 		The list of Standard Pricings.
	* @Returns:		None
	* History
	* <Date>      <Authors Name>     <Brief Description of Change>
	*------------------------------------------------------------*/
	public static void validateStandardPricingBeforeUpdate(List<Standard_Pricing__c> standardPricings){
		Map<Id, Pricing_Template__c> mapPricingTemplates = getPricingTemplatesMap(standardPricings);
		for(Standard_Pricing__c stdPricing : standardPricings){
			if(mapPricingTemplates.containsKey(stdPricing.Pricing_Template__c) && mapPricingTemplates.get(stdPricing.Pricing_Template__c).Locked__c == true){
				stdPricing.addError(Label.errMsg_NotAllowedToChangeStandardPricing);
			}
		}
	}

	/**
	* @Author:		Marta Malinowska
	* @Company:		Deloitte
	* @Description:	This method is used to check if Pricing Template is locked and add error message for Standard Pricings to prevent delete.
	* @param 		The list of Standard Pricings.
	* @Returns:		None
	* History
	* <Date>      <Authors Name>     <Brief Description of Change>
	*------------------------------------------------------------*/
	public static void validateStandardPricingBeforeDelete(List<Standard_Pricing__c> standardPricings){
		Map<Id, Pricing_Template__c> mapPricingTemplates = getPricingTemplatesMap(standardPricings);
		for(Standard_Pricing__c stdPricing : standardPricings){
			if(mapPricingTemplates.containsKey(stdPricing.Pricing_Template__c) && mapPricingTemplates.get(stdPricing.Pricing_Template__c).Locked__c == true){
				stdPricing.addError(Label.errMsg_NotAllowedToDeleteStandardPricing);
			}
		}
	}

	/**
	* @Author:		Marta Malinowska
	* @Company:		Deloitte
	* @Description:	This method is used to query Pricing Templates.
	* @param 		The list of Standard Pricings.
	* @Returns:		Map of Pricing Templates
	* History
	* <Date>      <Authors Name>     <Brief Description of Change>
	*------------------------------------------------------------*/
	public static Map<Id, Pricing_Template__c> getPricingTemplatesMap(List<Standard_Pricing__c> standardPricings){
		Set<Id> pricingTemplateIds = new Set<Id>();
		for(Standard_Pricing__c stdPricing : standardPricings){
			pricingTemplateIds.add(stdPricing.Pricing_Template__c);
		}
		return new Map<Id, Pricing_Template__c>([SELECT Id, Locked__c FROM Pricing_Template__c WHERE Id IN :pricingTemplateIds]);
	}

	/**
	* @Author:		Marta Malinowska
	* @Company:		Deloitte
	* @Description:	This method is used to create a list of Annual Pricing Items that will be displayed on View Annual Pricing page.
	* @param 		The list of Annual Pricing.
	* @Returns:		List of Pricing Group Wrapper that includes all Related Annual Pricing Items.
	* History
	* <Date>      <Authors Name>     <Brief Description of Change>
	*------------------------------------------------------------*/
	public static List<PricingGroupWrapper> getAnnualPricingItemsGroupedByPricingGroups(Annual_Pricing__c annualPricing){
		Map<Id, Annual_Pricing_Item__c> mapAnnualPricingItems = new Map<Id, Annual_Pricing_Item__c>();
		Map<Id, Standard_Pricing__c> mapStandardPricings = new Map<Id, Standard_Pricing__c>();
		Map<Id, Pricing_Deal_Product__c> mapPricingDealProducts = new Map<Id, Pricing_Deal_Product__c>();

		Set<Id> pricingGroupIds = new Set<Id>();
		Set<Id> pricingDealProductIds = new Set<Id>();
		for(Annual_Pricing_Item__c annualPricingItem : [SELECT Id, Name, Pricing_Deal_Product__r.Pricing_Group__c, Pricing_Deal_Product__c, 
														Standard_Price__c, Standard_VAT_Inclusive__c, Final_Price__c, 
														Approval_Required__c, Status_Icon__c, isLocked__c
														FROM Annual_Pricing_Item__c  
														WHERE Annual_Pricing__c = :annualPricing.Id]){
			mapAnnualPricingItems.put(annualPricingItem.Pricing_Deal_Product__c, annualPricingItem);
			pricingGroupIds.add(annualPricingItem.Pricing_Deal_Product__r.Pricing_Group__c);
			pricingDealProductIds.add(annualPricingItem.Pricing_Deal_Product__c);
		}

		List<PricingGroupWrapper> pricingGroups = new List<PricingGroupWrapper>();
		for(Pricing_Group__c pricingGroup : [SELECT Id, Name, OwnerId,
																(SELECT Id, Pricing_Deal_Product_Name__c, Product_Category__c, Product_Type__c
																	FROM Pricing_Deal_Products__r WHERE Id IN :pricingDealProductIds
																	ORDER BY Report_Sequence__c) 
															FROM Pricing_Group__c WHERE Id IN :pricingGroupIds 
															ORDER BY Report_Sequence__c]){
			List<AnnualPricingItemWrapper> annualPricingItems = new List<AnnualPricingItemWrapper>();
			for(Pricing_Deal_Product__c pricingDealProduct : pricingGroup.Pricing_Deal_Products__r){
				Annual_Pricing_Item__c annualPricingItem = mapAnnualPricingItems.get(pricingDealProduct.Id);
				annualPricingItems.add(new AnnualPricingItemWrapper(pricingDealProduct, annualPricingItem));
			}
			pricingGroups.add(new PricingGroupWrapper(pricingGroup, annualPricingItems));
		}

		return pricingGroups;
	}

	/**
	* @Author:		Marta Malinowska
	* @Company:		Deloitte
	* @Description:	This method is used to create a list of Annual Pricing Items that will be displayed on Approval Request page.
	* @param 		The list of Annual Pricing.
	* @Returns:		List of Pricing Group Wrapper that includes list of Annual Pricing Items required approval.
	* History
	* <Date>      <Authors Name>     <Brief Description of Change>
	*------------------------------------------------------------*/
	public static List<PricingGroupWrapper> getAnnualPricingItemsForApproval(Annual_Pricing__c annualPricing){
		Map<Id, Annual_Pricing_Item__c> mapAnnualPricingItems = new Map<Id, Annual_Pricing_Item__c>();
		Map<Id, Standard_Pricing__c> mapStandardPricings = new Map<Id, Standard_Pricing__c>();
		Map<Id, Pricing_Deal_Product__c> mapPricingDealProducts = new Map<Id, Pricing_Deal_Product__c>();

		Set<Id> pricingGroupIds = new Set<Id>();
		Set<Id> pricingDealProductIds = new Set<Id>();
		for(Annual_Pricing_Item__c annualPricingItem : [SELECT Id, Pricing_Deal_Product__r.Pricing_Group__c, Pricing_Deal_Product__c, 
														Standard_Price__c, Standard_VAT_Inclusive__c, Final_Price__c, Request_Comments__c,
														Approval_Required__c, Status_Icon__c, isLocked__c
														FROM Annual_Pricing_Item__c  
														WHERE Annual_Pricing__c = :annualPricing.Id 
														AND Approval_Required__c = true AND isLocked__c = false]){
			mapAnnualPricingItems.put(annualPricingItem.Pricing_Deal_Product__c, annualPricingItem);
			pricingGroupIds.add(annualPricingItem.Pricing_Deal_Product__r.Pricing_Group__c);
			pricingDealProductIds.add(annualPricingItem.Pricing_Deal_Product__c);
		}

		List<PricingGroupWrapper> pricingGroups = new List<PricingGroupWrapper>();
		for(Pricing_Group__c pricingGroup : [SELECT Id, Name, OwnerId,
																(SELECT Id, Pricing_Deal_Product_Name__c, Product_Category__c, Product_Type__c
																	FROM Pricing_Deal_Products__r WHERE Id IN :pricingDealProductIds
																	ORDER BY Report_Sequence__c) 
															FROM Pricing_Group__c WHERE Id IN :pricingGroupIds 
															ORDER BY Report_Sequence__c]){
			List<AnnualPricingItemWrapper> annualPricingItems = new List<AnnualPricingItemWrapper>();
			for(Pricing_Deal_Product__c pricingDealProduct : pricingGroup.Pricing_Deal_Products__r){
				Annual_Pricing_Item__c annualPricingItem = mapAnnualPricingItems.get(pricingDealProduct.Id);
				annualPricingItems.add(new AnnualPricingItemWrapper(pricingDealProduct, annualPricingItem));
			}
			pricingGroups.add(new PricingGroupWrapper(pricingGroup, annualPricingItems));
		}

		return pricingGroups;
	}

	/**
	* @Author:		Marta Malinowska
	* @Company:		Deloitte
	* @Description:	This method is used to check if approval is required 
	*				and determines if the button "Submit for Approval" will be displayed on View Annual Pricing page.
	* @param 		The list of Pricing Group Wrapper that include Annual Pricing Items.
	* @Returns:		true if at least one of Annual Pricing Items require approval
	*				false if there is no Annual Pricing Item that requires approval
	* History
	* <Date>      <Authors Name>     <Brief Description of Change>
	*------------------------------------------------------------*/
	public static Boolean getIsApprovalRequired(List<PricingGroupWrapper> pricingGroups){
		Boolean isApprovalRequired = false;
		for(PricingGroupWrapper pg : pricingGroups){
			for(AnnualPricingItemWrapper api : pg.annualPricingItems){
				if(api.annualPricingItem.Approval_Required__c == true){
					isApprovalRequired = true;
					break;
				}
			}
		}

		return isApprovalRequired;
	}

	public class PricingGroupWrapper {
		public Pricing_Group__c pricingGroup { get; set; }
		public List<AnnualPricingItemWrapper> annualPricingItems { get; set; }

		public PricingGroupWrapper(Pricing_Group__c pricingGroup, List<AnnualPricingItemWrapper> annualPricingItems){
			this.pricingGroup = pricingGroup;
			this.annualPricingItems = annualPricingItems;
		}
	}

	public class AnnualPricingItemWrapper {
		public Pricing_Deal_Product__c pricingDealProduct { get; set; }
		public Annual_Pricing_Item__c annualPricingItem { get; set; }

		public AnnualPricingItemWrapper(Pricing_Deal_Product__c pricingDealProduct, Annual_Pricing_Item__c annualPricingItem){
			this.pricingDealProduct = pricingDealProduct;
			this.annualPricingItem = annualPricingItem;
		}
	}
    
    
    public static Annual_Pricing__Share createSharingInstance(String planId, String userId) {
        
        Annual_Pricing__Share shRec = new Annual_Pricing__Share();
        shRec.AccessLevel = EDIT;
        shRec.RowCause = Schema.Annual_Pricing__Share.RowCause.Manual;
        
        try {
            shRec.ParentId = planId;
            shRec.UserOrGroupId = userId;
        } catch (StringException e) {
            system.debug(e);
            return null;
        }
        
        return shRec;
    }
}