objects/Annual_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Pricing</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Letter Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Annual Pricings</relationshipLabel>
        <relationshipName>Annual_Pricings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Template</label>
        <referenceTo>Pricing_Template__c</referenceTo>
        <relationshipLabel>Annual Pricings</relationshipLabel>
        <relationshipName>Annual_Pricings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Annual Pricing</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Annual Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Pricings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Annual_Pricing_Approver__c.object
<CustomObject>
    <fields>
        <fullName>First_Line_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Line Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Annual_Pricing_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Second_Line_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Line Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Annual_Pricing_Approvers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Annual Pricing Approver</label>
    <nameField>
        <displayFormat>APA-{00000}</displayFormat>
        <label>Annual Pricing Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Pricing Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Annual_Pricing_Item__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Pricing__c</fullName>
        <label>Annual Pricing</label>
        <referenceTo>Annual_Pricing__c</referenceTo>
        <relationshipLabel>Annual Pricing Items</relationshipLabel>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending 1st line Approval</fullName>
                </value>
                <value>
                    <fullName>Pending 2nd line Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Final_Price__c</fullName>
        <label>Final Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Line_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Line Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Deal_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Deal Product</label>
        <referenceTo>Pricing_Deal_Product__c</referenceTo>
        <relationshipLabel>Annual Pricing Items</relationshipLabel>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Group__c</fullName>
        <formula>Pricing_Deal_Product__r.Pricing_Group__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Second_Line_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Line Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Annual_Pricing_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Pricing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Standard Pricing</label>
        <referenceTo>Standard_Pricing__c</referenceTo>
        <relationshipLabel>Annual Pricing Items</relationshipLabel>
        <relationshipName>Annual_Pricing_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Annual Pricing Item</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>Annual Pricing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Pricing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pricing_Deal_Product__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Group</label>
        <referenceTo>Pricing_Group__c</referenceTo>
        <relationshipLabel>Pricing Deal Products</relationshipLabel>
        <relationshipName>Pricing_Deal_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Pricing Deal Product</label>
    <nameField>
        <label>Pricing Deal Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Deal Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Pricing_Group__c.object
<CustomObject>
    <label>Pricing Group</label>
    <nameField>
        <label>Pricing Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Pricing_Template__c.object
<CustomObject>
    <label>Pricing Template</label>
    <nameField>
        <label>Pricing Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Standard_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Deal_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pricing Deal Product</label>
        <referenceTo>Pricing_Deal_Product__c</referenceTo>
        <relationshipLabel>Standard Pricings</relationshipLabel>
        <relationshipName>Standard_Pricings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Group__c</fullName>
        <formula>Pricing_Deal_Product__r.Pricing_Group__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Template__c</fullName>
        <label>Pricing Template</label>
        <referenceTo>Pricing_Template__c</referenceTo>
        <relationshipLabel>Standard Pricings</relationshipLabel>
        <relationshipName>Standard_Pricings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Standard Pricing</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Standard Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Pricings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ZZTEST_APT_ApprovalRequestController.cls
/**
* @Author   Marta Malinowska
* @Company: Deloitte
* @Description Unit Tests for APT_ApprovalRequestController
*              Tests executed:
*               1 - testSubmitForApproval()
*                   Test that all Annual Pricing Items submitted for approval have change the status for "Pending First Approval".
*/
@isTest
private class ZZTEST_APT_ApprovalRequestController {
	public static testMethod void testSubmitForApproval(){
		Integer GROUP_ITEMS_SIZE = 30;
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
		ZZTEST_F_PricingGroup pricingGroupFactory = ZZTEST_DataFactoryFacade.pricingGroup;
		ZZTEST_F_PricingDealProduct pricingDealProductFactory = ZZTEST_DataFactoryFacade.pricingDealProduct;
		ZZTEST_F_PricingTemplate pricingTemplateFactory = ZZTEST_DataFactoryFacade.pricingTemplate;

        Account account = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);
        Pricing_Group__c pricingGroup1 = pricingGroupFactory.getProduct(ZZTEST_F_PricingGroup.PricingGroupRecordType.DEFAULT_PRICING_GROUP, dataContainer);
        Pricing_Group__c pricingGroup2 = pricingGroupFactory.getProduct(ZZTEST_F_PricingGroup.PricingGroupRecordType.DEFAULT_PRICING_GROUP, dataContainer);
        List<Pricing_Group__c> pricingGroups = new List<Pricing_Group__c>{pricingGroup1, pricingGroup2};
        insert pricingGroups;
        List<Pricing_Deal_Product__c> pricingDealProducts = new List<Pricing_Deal_Product__c>();
        for(Integer i=0; i<GROUP_ITEMS_SIZE; i++){
        	Pricing_Deal_Product__c pricingDealProduct1 = pricingDealProductFactory.getProduct(ZZTEST_F_PricingDealProduct.PricingDealProductRecordType.DEFAULT_PRICING_DEAL_PRODUCT, dataContainer);
        	Pricing_Deal_Product__c pricingDealProduct2 = pricingDealProductFactory.getProduct(ZZTEST_F_PricingDealProduct.PricingDealProductRecordType.DEFAULT_PRICING_DEAL_PRODUCT, dataContainer);
        	pricingDealProduct1.Pricing_Group__c = pricingGroup1.Id;
        	pricingDealProduct2.Pricing_Group__c = pricingGroup2.Id;
        	pricingDealProducts.add(pricingDealProduct1);
        	pricingDealProducts.add(pricingDealProduct2);
        }
        insert pricingDealProducts;
        Pricing_Template__c pricingTemplate = pricingTemplateFactory.getInsertedProduct(ZZTEST_F_PricingTemplate.PricingTemplateRecordType.DEFAULT_PRICING_TEMPLATE, dataContainer);
        List<Standard_Pricing__c> standardPricings = new List<Standard_Pricing__c>();
        for(Pricing_Deal_Product__c pricingDealProduct : pricingDealProducts){
        	standardPricings.add(new Standard_Pricing__c(Pricing_Template__c=pricingTemplate.Id, Pricing_Deal_Product__c=pricingDealProduct.Id, Price__c='1000'));
        }
        insert standardPricings;

        Annual_Pricing__c annualPricing = new Annual_Pricing__c();
        annualPricing.Organisation__c = account.Id;
        annualPricing.Pricing_Template__c = pricingTemplate.Id;
       // annualPricing.Approval_Status__c = APT_AnnualPricingUtils.STATUS_NOT_SUBMITTED;
        annualPricing.Approval_Status__c = APT_AnnualPricingUtils.STATUS_STANDARD_PRICING;
        insert annualPricing;

        List<Annual_Pricing_Item__c> annualPricingItems = new List<Annual_Pricing_Item__c>();
        for(Standard_Pricing__c standardPricing : standardPricings){
        	Annual_Pricing_Item__c annualPricingItem = new Annual_Pricing_Item__c();
        	annualPricingItem.Annual_Pricing__c = annualPricing.Id;
        	annualPricingItem.Pricing_Deal_Product__c = standardPricing.Pricing_Deal_Product__c;
        	annualPricingItem.Standard_Pricing__c = standardPricing.Id;
        	annualPricingItem.Final_Price__c = '2000';
        	annualPricingItem.Approval_Required__c = true;
        	annualPricingItems.add(annualPricingItem);
        }
        insert annualPricingItems;

        Test.startTest();

		PageReference APT_ApprovalRequest = Page.APT_ApprovalRequest;
        Test.setCurrentPage(APT_ApprovalRequest);

    	Apexpages.Standardcontroller stc = new ApexPages.StandardController(annualPricing);
        APT_ApprovalRequestController controller = new APT_ApprovalRequestController(stc);
		
		controller.submit();
		System.assertEquals(ApexPages.getMessages()[0].getDetail(), Label.errMsg_ApproverRequired);

		controller.selectedApprover =UserInfo.getUserId();
        controller.setSecondApprover();
		controller.submit();

		Annual_Pricing__c annualPricingAfterUpd = [SELECT Id, Approval_Status__c FROM Annual_Pricing__c WHERE Id = :annualPricing.Id];
		System.assertEquals(annualPricingAfterUpd.Approval_Status__c, APT_AnnualPricingUtils.STATUS_PENDING);

		for(Annual_Pricing_Item__c annualPricingItem : [SELECT Id, Approval_Status__c FROM Annual_Pricing_Item__c WHERE Annual_Pricing__c = :annualPricing.Id]){
			System.assertEquals(annualPricingItem.Approval_Status__c, APT_AnnualPricingUtils.STATUS_PENDING_FIRST_APPROVAL);
		}

        Test.stopTest();
	}
    
    @TestSetup static void setupTestData()
    {
        Annual_Pricing_Approver__c APA = new Annual_Pricing_Approver__c(First_line_Approver__c = UserInfo.getUserId(),Second_line_Approver__c=UserInfo.getUserId());
        insert APA;
    }
}