objects/Attendee__c.object
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>AT{000000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Meeting__c.object
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Meeting_Attendee__c.object
<CustomObject>
    <description>This object is used to manage meeting attendees.</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Meeting_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipName>Meeting_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>MT{00000}</displayFormat>
        <label>Meeting Attendees Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ZZTEST_MeetingPrintViewController.cls
/**
* @Author   Dino Scarcella
* @Company: Absa Capital
* @Description Unit Tests for MeetingPrintViewController
*              Tests executed:
*               1 - testGeneratePDF()
*                   Test Generation of the PDF
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* ----------------------------------------------------------------------------*/
@isTest
private class ZZTEST_MeetingPrintViewController {
	public static testMethod void testGeneratePDF() {
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_Meeting meetingFactory = ZZTEST_DataFactoryFacade.meeting;

        Meeting__c meeting = meetingFactory.getInsertedProduct(ZZTEST_F_Meeting.MeetingRecordType.DEFAULT_MEETING, dataContainer);
        List<Meeting_Attendee__c> meetingAttendees = new List<Meeting_Attendee__c>();
        meetingAttendees.add(new Meeting_Attendee__c(Meeting__c=meeting.Id, Attendee__c=UserInfo.getUserId()));
        insert meetingAttendees;
        
        Document doc_done = new Document(Name='Icon Done', AuthorId = UserInfo.getUserId(), FolderId = UserInfo.getUserId());
        insert doc_done;
        Document doc_error = new Document(Name='Icon Error', AuthorId = UserInfo.getUserId(), FolderId = UserInfo.getUserId());
        insert doc_error;
        Document doc_warning = new Document(Name='Icon Warning', AuthorId = UserInfo.getUserId(), FolderId = UserInfo.getUserId());
        insert doc_warning;
        
        //Start Test
        Test.startTest();

    	PageReference MeetingPrintView = Page.MeetingPrintView;
        Test.setCurrentPage(MeetingPrintView);

        ApexPages.currentPage().getParameters().put('id', meeting.Id);
        Apexpages.Standardcontroller stc = new ApexPages.StandardController(meeting);
        MeetingPrintViewController controller = new MeetingPrintViewController(stc);
        
        System.assert(controller.Meeting != NULL);
        
        //Stop Test
        Test.stopTest();
    }
}