objects/Barclays_SA__Cat_Content_Junction__c.object
<CustomObject>
    <description>Acts as &quot;junction&quot; object, linking a Content Document to a  Category</description>
    <fields>
        <fullName>Barclays_SA__Category__c</fullName>
        <label>Category</label>
        <referenceTo>Barclays_SA__Category__c</referenceTo>
        <relationshipName>Cat_Content_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Barclays_SA__ContentId__c</fullName>
        <label>ContentId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Category Content Junction</label>
    <nameField>
        <displayFormat>CCJ-{00000}</displayFormat>
        <label>Cat-Content-Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Content Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Barclays_SA__Category__c.object
<CustomObject>
    <fields>
        <fullName>Barclays_SA__Is_Top_Level__c</fullName>
        <formula>IF( ISBLANK(Barclays_SA__Parent_Category__c), 1, 0)</formula>
        <label>Is Top Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Barclays_SA__Parent_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Category</label>
        <referenceTo>Barclays_SA__Category__c</referenceTo>
        <relationshipLabel>Sub Categories</relationshipLabel>
        <relationshipName>SubCategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ProductInfoFilesController.cls
/**
* @Author:          Dino Scarcella
* @Company:         Absa Capital
* @Description:     SFAFRICA-570 - VF page for SF1 to list Product collateral files. This allows
*					users to view all documents from the Salesforce1 App
* History
* <Date>      <Authors Name>     <Brief Description of Change>
*------------------------------------------------------------*/

public with sharing class ProductInfoFilesController {
	// Property method to build the dropdown that shows the Top Level Product Categories
    public List<SelectOption> TopLevelCategories {
        get
        {
            List<SelectOption> top_level_categories = new List<SelectOption>();
            for (Barclays_SA__Category__c cat : [SELECT Id, Name FROM Barclays_SA__Category__c WHERE Barclays_SA__Is_Top_Level__c = 1 ORDER BY Name]) {
            	SelectOption option = new SelectOption(cat.Id,cat.Name);
                top_level_categories.add(option);
            }
            return top_level_categories;
        }
    }
    
    // Property method to build the dropdown that shows the Product Sub Categories
    public List<SelectOption> SubCategories {
        get
        {
        	List<SelectOption> sub_categories = new List<SelectOption>();
            for (Barclays_SA__Category__c cat : [SELECT Id, Name FROM Barclays_SA__Category__c 
            										WHERE Barclays_SA__Is_Top_Level__c = 0 
            										AND Barclays_SA__Parent_Category__c =: SelectedTopLevelCategory ORDER BY Name]) {
            	SelectOption option = new SelectOption(cat.Id,cat.Name);
                sub_categories.add(option);
            }
            SelectedSubCategory = '--SELECT--';
            return sub_categories;
        }
    }
    
    // Property methods to keep track of what we have selected
    public String SelectedTopLevelCategory { get;set; }
    public String SelectedSubCategory {	get;set; }
    public List<ContentWorkspaceDoc> Files { get;set; }
    public Set<String> DocumentIDs { get;set; }
    
    public PageReference getFiles() {
    		Set<Id> categoryids = new Set<Id>();
    		if ((SelectedTopLevelCategory!=null && SelectedTopLevelCategory!='--SELECT--') && (SelectedSubCategory==null || SelectedSubCategory=='--SELECT--')) 
    			categoryids.add(SelectedTopLevelCategory);
    		if (SelectedSubCategory!=null && SelectedSubCategory!='--SELECT--') categoryids.add(SelectedSubCategory);
    		if (SelectedTopLevelCategory==null || SelectedTopLevelCategory=='--SELECT--') {
    			SelectedSubCategory = '--SELECT--';
    			Files = null;
    			return null;
    		}
    	
    		Set<String> ContentIds = new Set<String>();
    		for (Barclays_SA__Cat_Content_Junction__c junction : [
    			SELECT Barclays_SA__ContentId__c FROM Barclays_SA__Cat_Content_Junction__c 
    			WHERE Barclays_SA__Category__c IN : categoryids
    			AND IsDeleted = false
    		]) ContentIds.add(junction.Barclays_SA__ContentId__c);
    	
    		Files = [SELECT ContentDocumentID, ContentDocument.ContentModifiedDate
						FROM ContentWorkspaceDoc WHERE ContentDocumentId 
						IN : ContentIds 
						ORDER BY ContentDocument.Title];
        
        	DocumentIDs = new Set<String>();
    		for(ContentWorkspaceDoc cwd : Files) {
    			DocumentIDs.add(cwd.ContentDocumentID);
    		}
        
			return null;
    }
}