objects/box__FRUP__c.object
<CustomObject>
    <fields>
        <fullName>box__Box_user__c</fullName>
        <externalId>true</externalId>
        <label>Box user</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>box__Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>box__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FRUP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FRUP</label>
    <nameField>
        <displayFormat>FRUP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRUP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Box_Folder_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Custom__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Custom Link</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_Collaboration_Id__c</fullName>
        <label>External Collaboration Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Level__c</fullName>
        <label>Folder Level</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Folder_Name__c</fullName>
        <label>Folder Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Type__c</fullName>
        <label>Folder Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                </value>
                <value>
                    <fullName>Agreement Agency Transfer</fullName>
                </value>
                <value>
                    <fullName>Agreement Legal</fullName>
                </value>
                <value>
                    <fullName>Collateral</fullName>
                </value>
                <value>
                    <fullName>Condition Precedent</fullName>
                </value>
                <value>
                    <fullName>Deal</fullName>
                </value>
                <value>
                    <fullName>Default Legal Matter type</fullName>
                </value>
                <value>
                    <fullName>Drawdown</fullName>
                </value>
                <value>
                    <fullName>Drawdown ReadOnly</fullName>
                </value>
                <value>
                    <fullName>Facility</fullName>
                </value>
                <value>
                    <fullName>Facility Agency Transfer</fullName>
                </value>
                <value>
                    <fullName>Financial Covenant</fullName>
                </value>
                <value>
                    <fullName>General Undertaking</fullName>
                </value>
                <value>
                    <fullName>Governance Check</fullName>
                </value>
                <value>
                    <fullName>Information Undertaking</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Legal (Off Panel)</fullName>
                </value>
                <value>
                    <fullName>Legal Quote</fullName>
                </value>
                <value>
                    <fullName>Legal Quote (Locked)</fullName>
                </value>
                <value>
                    <fullName>Legal Request</fullName>
                </value>
                <value>
                    <fullName>Litigation (Off Panel)</fullName>
                </value>
                <value>
                    <fullName>Litigation Matter</fullName>
                </value>
                <value>
                    <fullName>Litigation Quote</fullName>
                </value>
                <value>
                    <fullName>Litigation Quote (Locked)</fullName>
                </value>
                <value>
                    <fullName>Litigation Request</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
                <value>
                    <fullName>Off Panel Quote</fullName>
                </value>
                <value>
                    <fullName>Off Panel Quote (Locked)</fullName>
                </value>
                <value>
                    <fullName>Read Only Agreement</fullName>
                </value>
                <value>
                    <fullName>Read-Only Legal Hold (Legal RT)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Hold_Policy_Id__c</fullName>
        <label>Legal Hold Policy Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Hold_Policy_Name__c</fullName>
        <label>Legal Hold Policy Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Record_Type__c</fullName>
        <label>Group Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deal</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Litigation Matter</fullName>
                </value>
                <value>
                    <fullName>Default Legal Matter type</fullName>
                </value>
                <value>
                    <fullName>Legal Quote</fullName>
                </value>
                <value>
                    <fullName>Litigation Quote</fullName>
                </value>
                <value>
                    <fullName>Legal RT</fullName>
                </value>
                <value>
                    <fullName>Litigation RT</fullName>
                </value>
                <value>
                    <fullName>Collaterals</fullName>
                </value>
                <value>
                    <fullName>Knowledge Management</fullName>
                </value>
                <value>
                    <fullName>Market Transaction</fullName>
                </value>
                <value>
                    <fullName>Market Transaction - Prime Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Lookup__c</fullName>
        <label>Parent Lookup</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Matter_Deal__c</fullName>
                </value>
                <value>
                    <fullName>Agreement__c</fullName>
                </value>
                <value>
                    <fullName>Matter__c</fullName>
                </value>
                <value>
                    <fullName>Legal_Quote_Request__c</fullName>
                </value>
                <value>
                    <fullName>Condition__c</fullName>
                </value>
                <value>
                    <fullName>Facility__c</fullName>
                </value>
                <value>
                    <fullName>Facility_Tranche__c</fullName>
                </value>
                <value>
                    <fullName>Collateral_Valuation__c</fullName>
                </value>
                <value>
                    <fullName>Collateral__c</fullName>
                </value>
                <value>
                    <fullName>Collateral_Monitoring__c</fullName>
                </value>
                <value>
                    <fullName>Margin_Ratchet__c</fullName>
                </value>
                <value>
                    <fullName>Trigger__c</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Static_Folder__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Static Folder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Webhook_Triggers__c</fullName>
        <label>Webhook Triggers</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FILE.UPLOADED</fullName>
                </value>
                <value>
                    <fullName>FILE.PREVIEWED</fullName>
                </value>
                <value>
                    <fullName>FILE.DOWNLOADED</fullName>
                </value>
                <value>
                    <fullName>FILE.TRASHED</fullName>
                </value>
                <value>
                    <fullName>FILE.DELETED</fullName>
                </value>
                <value>
                    <fullName>FILE.RESTORED</fullName>
                </value>
                <value>
                    <fullName>FILE.COPIED</fullName>
                </value>
                <value>
                    <fullName>FILE.MOVED</fullName>
                </value>
                <value>
                    <fullName>FILE.LOCKED</fullName>
                </value>
                <value>
                    <fullName>FILE.UNLOCKED</fullName>
                </value>
                <value>
                    <fullName>METADATA_INSTANCE.CREATED</fullName>
                </value>
                <value>
                    <fullName>METADATA_INSTANCE.UPDATED</fullName>
                </value>
                <value>
                    <fullName>METADATA_INSTANCE.DELETED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Webhook_URL__c</fullName>
        <description>The url that box will use to send webhook notifications/triggers</description>
        <label>Webhook URL</label>
        <type>Url</type>
    </fields>
    <label>Box Folder Structure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Folder Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BxdFolderStructureHelper.cls
public virtual class BxdFolderStructureHelper {

    public BxdFolderStructureHelper() {}
        
    /**
    * getFolderStructure - used to query Box_Folder_Structure__c to find folder structure based on recordTypeName passed as an argument
	**/
    public Box_Folder_Structure__c getFolderStructure(String recordTypeName) {
        Box_Folder_Structure__c queryHelper;
        try
        {
            queryHelper = [select ID, Custom__c, Folder_Level__c, Folder_Name__c, Folder_Type__c, Main_Record_Type__c, Legal_Hold_Policy_Id__c, Legal_Hold_Policy_Name__c, Static_Folder__c, Webhook_Triggers__c, Webhook_URL__c, Parent_Lookup__c, External_Collaboration_Id__c from Box_Folder_Structure__c where Folder_Type__c includes (:recordTypeName) ORDER BY Folder_Level__c ASC LIMIT 1];
        }
        catch (Exception e)
        {
            system.debug('Box Integration: Cannot find record type name for ' + recordTypeName + ' on Box Folder Structure: '+e);
        }   
        return queryHelper;
    }
    
    /**
    * getFolderStructure - used to query Box_Folder_Structure__c to find folder structure based on recordTypeName, requires two arguments
	**/
    public Box_Folder_Structure__c getFolderStructure(SObjectType sObjectType, Id recordTypeId){
        Box_Folder_Structure__c queryHelper;
        try
        {
            String recordTypeName = sObjectType.getDescribe().getRecordTypeInfosById().get(recordTypeId).getName();
            return queryHelper =[select ID, Custom__c, Folder_Level__c, Folder_Name__c, Folder_Type__c, Main_Record_Type__c, Legal_Hold_Policy_Id__c, Legal_Hold_Policy_Name__c, Static_Folder__c, Webhook_Triggers__c, Webhook_URL__c, Parent_Lookup__c, External_Collaboration_Id__c from Box_Folder_Structure__c where Folder_Type__c includes (:recordTypeName) ORDER BY Folder_Level__c ASC LIMIT 1];
        }
        catch (Exception e)
        {
            system.debug('Box Integration: Cannot find record type name for ' + sObjectType.getDescribe().getName() + ' on Box Folder Structure: '+e);
        }
        
        return null;
    }
    
 	/**
    * getFolderStructure - used to query Box_Folder_Structure__c to find static folder structure based on recordTypeName
	**/
    public Box_Folder_Structure__c getFolderStructure(SObjectType sObjectType, Id recordTypeId, Boolean staticFolder, Boolean customLink){
        Box_Folder_Structure__c queryHelper;
        try
        {
            String recordTypeName = sObjectType.getDescribe().getRecordTypeInfosById().get(recordTypeId).getName();
            return queryHelper =[select ID, Custom__c, Folder_Level__c, Folder_Name__c, Folder_Type__c, Main_Record_Type__c, Legal_Hold_Policy_Id__c, Legal_Hold_Policy_Name__c, Static_Folder__c, Webhook_Triggers__c, Webhook_URL__c, Parent_Lookup__c, External_Collaboration_Id__c from Box_Folder_Structure__c where Folder_Type__c includes (:recordTypeName) AND Static_Folder__c =: staticFolder AND Custom__c =: customLink ORDER BY Folder_Level__c ASC LIMIT 1];  
        }
        catch (Exception e)
        {
            system.debug('Box Integration: Cannot find record type name for ' + sObjectType.getDescribe().getName() + ' on Box Folder Structure: '+e);
        }
        
        return null;
    }
    
    /**
    * getFolderStructures - used to query Box_Folder_Structure__c to find a list of static folder structures based on recordTypeName
	**/
    public List<Box_Folder_Structure__c> getFolderStructures(SObjectType sObjectType, Id recordTypeId, Boolean staticFolder){
        List<Box_Folder_Structure__c> queryHelper;
        try
        {
            String recordTypeName = sObjectType.getDescribe().getRecordTypeInfosById().get(recordTypeId).getName();
            return queryHelper =[select ID, Custom__c, Folder_Level__c, Folder_Name__c, Folder_Type__c, Main_Record_Type__c, Legal_Hold_Policy_Id__c, Legal_Hold_Policy_Name__c, Static_Folder__c, Webhook_Triggers__c, Webhook_URL__c, Parent_Lookup__c, External_Collaboration_Id__c from Box_Folder_Structure__c where Folder_Type__c includes (:recordTypeName) AND Static_Folder__c =: staticFolder ORDER BY Folder_Level__c ASC];
            
        }
        catch (Exception e)
        {
            system.debug('Box Integration: Cannot find record type name for ' + sObjectType.getDescribe().getName() + ' on Box Folder Structure: '+e);
        }
        
        return new List<Box_Folder_Structure__c>();
    }
    
    /**
    * getRecordValue - used to manipulate a record to get a value of a specific field
	**/
    public String getRecordValue(SObject record, String fieldName){
        String value;
        try
        {
            value = String.valueOf(record.get(fieldName));
        }
        catch (Exception e)
        {
            system.debug('Failed to get record value for field '+fieldName);
        }
        return value;
    }
    
    /**
    * getRecordTypeName - used to find the record type name using the record type id parameter to query the database
	**/
    public String getRecordTypeName(String recordTypeId){
        try
        {
            RecordType recordType = [SELECT Name FROM RecordType WHERE Id=:recordTypeId LIMIT 1];
            if(recordType != null){
                return recordType.Name;
            }
        }
        catch (Exception e)
        {
            system.debug('Failed to get record type name: '+e);
        }
        
        return '';
    }
    
    /**
    * getFolderStructure - used to query Box_Folder_Structure__c to find folder structure based on recordTypeName passed as an argument
	**/
    public box__FRUP__c getBoxUser(Id salesforceUser) {
        box__FRUP__c frup;
        try
        {
            frup = [SELECT ID, box__Box_user__c, CreatedDate, box__Object_Name__c FROM box__FRUP__c WHERE box__Salesforce_User__c =: salesforceUser AND box__Box_user__c != null ORDER BY CreatedDate DESC LIMIT 1];
        }
        catch (Exception e)
        {
            system.debug('Box Integration: Cannot find a Box user associate with Salesforce user: ' + salesforceUser + ' on FRUP: ' + e);
        }   
        return frup;
    }
    
    /**
    * getTokenExchangeDataString - this method takes in a map, then generate a string as in url param form
	**/
    public String getTokenExchangeDataString(Map<String, String> params) {
        BxdStringBuilder result = new BxdStringBuilder();
        boolean first = true;
        for(String key : params.keySet()) {
            if (first) {
                first = false;
            } else {
                result.append('&');
            }                
            result.append(key);
            result.append('=');
            result.append(params.get(key));
        }    
        return result.build();
    }
    
    /**
    * parseToolkitRole - parse a role string into Box Toolkit Collaboration Role
	**/
    public box.Toolkit.CollaborationType parseToolkitRole(String value) {
        if (value == 'VIEWER_UPLOADER') {
            return box.Toolkit.CollaborationType.VIEWERUPLOADER;
        } else if (value == 'PREVIEWER_UPLOADER') {
            return box.Toolkit.CollaborationType.PREVIEWERUPLOADER;
        } else if (value == 'VIEWER') {
            return box.Toolkit.CollaborationType.VIEWER;
        } else if (value == 'PREVIEWER') {
            return box.Toolkit.CollaborationType.PREVIEWER;
        }
        
        return null;
    }
    
    /**
    * parseRole - parse a role string into Box SDK Collaboration Role
	**/
    public BoxCollaboration.Role parseRole(String value) {
        if (value == 'VIEWER_UPLOADER') {
            return BoxCollaboration.Role.VIEWER_UPLOADER;
        } else if (value == 'PREVIEWER_UPLOADER') {
            return BoxCollaboration.Role.PREVIEWER_UPLOADER;
        } else if (value == 'VIEWER') {
            return BoxCollaboration.Role.VIEWER;
        } else if (value == 'PREVIEWER') {
            return BoxCollaboration.Role.PREVIEWER;
        }
        
        return null;
    }
}