objects/BoxDocument__c.object
<CustomObject>
    <description>Managing box interactions to through a UI similar to standard attachments</description>
    <fields>
        <fullName>Box_Location__c</fullName>
        <description>Location URL on BOX.com</description>
        <label>Box Location</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Condition_Occurrence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Occurrence</label>
        <referenceTo>Condition_Occurrence__c</referenceTo>
        <relationshipName>BoxDocuments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PII__c</fullName>
        <inlineHelpText>Document uploaded contains personal identifiable informaiton</inlineHelpText>
        <label>Personally Identifiable Information</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Upload_Date__c</fullName>
        <label>Upload Date</label>
        <type>DateTime</type>
    </fields>
    <label>Box Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Condition_Occurrence__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Condition Occurrence</label>
    <nameField>
        <label>Condition Occurrence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Occurrences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Condition_Occurrence_Override_Test.cls
@isTest(SeeAllData=false)
public class Condition_Occurrence_Override_Test {

	public static testMethod void testController() 
	{	
		//Setup data data
		BXDtesclassdata.setupFolder();
		Cloudsmiths_TestDataClass  testDataClass = new Cloudsmiths_TestDataClass(); 

		ApexPages.StandardController sc = new ApexPages.standardController(testDataClass.TestConditionOccurrence);
		Condition_Occurrence_Override test = new Condition_Occurrence_Override(sc);
        
        //Insert Box Documents
        BoxDocument__c testBoxDocument = new BoxDocument__c(
            Box_Location__c = 'https://test.com',
            Condition_Occurrence__c = testDataClass.TestConditionOccurrence.id,
            Upload_Date__c = System.today(),
        	PII__c = 'Yes');
		insert testBoxDocument;
        
        Condition_Occurrence__c updateConditionOccurence = new Condition_Occurrence__c();
        
        updateConditionOccurence.id = testDataClass.TestConditionOccurrence.id;
        updateConditionOccurence.Comments__c = 'Testing 123';
        Update updateConditionOccurence;

		//Methods
		test.actionViewRoute();
		test.actionEditRoute();
	}
}