objects/Budget_Revenue__c.object
<CustomObject>
    <fields>
        <fullName>Actual_RoRWA__c</fullName>
        <label>Actual RoRWA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Client_Plan__c</fullName>
        <label>Client Plan</label>
        <referenceTo>Client_Plan__c</referenceTo>
        <relationshipName>Budget_Revenue</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Client Plan Budget &amp; Revenue</label>
    <nameField>
        <displayFormat>BR{00000}</displayFormat>
        <label>Budget &amp; Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Budgets &amp; Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plans</relationshipLabel>
        <relationshipName>ClientPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Plan</label>
    <nameField>
        <displayFormat>PL{00000}</displayFormat>
        <label>Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Client_Plan_Borrowers_Guarantors__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plan Borrowers Guarantors</relationshipLabel>
        <relationshipName>Client_Plan_Borrowers_Guarantors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Borrower</fullName>
                </value>
                <value>
                    <fullName>Guarantor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Client Plan Borrowers Guarantors</label>
    <nameField>
        <label>Client Plan Borrowers Guarantors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Plan Borrowers Guarantors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Plan_Facility__c.object
<CustomObject>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plan Facilities</relationshipLabel>
        <relationshipName>Client_Plan_Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_Of_Facility__c</fullName>
        <label>Type Of Facility</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABSA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Plan Facility</label>
    <nameField>
        <displayFormat>CPF-{000000}</displayFormat>
        <label>Client Plan  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Client_Plan_Revenue_By_Product__c.object
<CustomObject>
    <fields>
        <fullName>Client_Plan__c</fullName>
        <label>Client Plan</label>
        <referenceTo>Client_Plan__c</referenceTo>
        <relationshipName>Revenue_By_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Plan Revenue By Product</label>
    <nameField>
        <label>Revenue By Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Plan Revenue By Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Plan_Security__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plan Securities</relationshipLabel>
        <relationshipName>Client_Plan_Securities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Security_Description__c</fullName>
        <label>Security Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Client Plan Security</label>
    <nameField>
        <displayFormat>CPS-{0000}</displayFormat>
        <label>Client Plan Security Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country_Presence__c.object
<CustomObject>
    <fields>
        <fullName>Banking_Country__c</fullName>
        <label>Banking Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Plan__c</fullName>
        <label>Client Plan</label>
        <referenceTo>Client_Plan__c</referenceTo>
        <relationshipLabel>Country Presence</relationshipLabel>
        <relationshipName>Country_Presents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Country Presence</label>
    <nameField>
        <displayFormat>CP{00000}</displayFormat>
        <label>Country Presence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Presence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Information__c.object
<CustomObject>
    <fields>
        <fullName>EBITDA__c</fullName>
        <label>EBITDA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Asset_Value__c</fullName>
        <label>Net Asset Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Financial_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Plan Financial Information</label>
    <nameField>
        <displayFormat>FI{00000}</displayFormat>
        <label>Financial Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Financial Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/JLOC__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>JLOC</relationshipLabel>
        <relationshipName>JLOC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_and_Returns_Document_ID__c</fullName>
        <label>Pricing and Returns Document ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bilateral</fullName>
                </value>
                <value>
                    <fullName>Syndication/Club</fullName>
                </value>
                <value>
                    <fullName>Underwrite-Best Efforts</fullName>
                </value>
                <value>
                    <fullName>Underwrite</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>JLOC</label>
    <nameField>
        <displayFormat>JLOC-{000000}</displayFormat>
        <label>JLOC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JLOC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>JLOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>JLOC</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only JLOC from current Organisation can be selected.</errorMessage>
            <filterItems>
                <field>JLOC__c.Organisation__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>JLOC__c.Organisation__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>JLOC__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityTeamMember.object
<CustomObject>
    <fields>
        <fullName>I_confirm_team_member_has_been_cleared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I confirm team member has been cleared</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/ZZTEST_JLOC_PrintViewController.cls
/**
* @Author   Marta Malinowska
* @Company: Deloitte
* @Description Unit Tests for JLOC_PrintViewController
*              Tests executed:
*               1 - testJlocPrintView()
*                   Test that JLOC Print View can be generated.
*               2 - testJlocPrintViewWithDealTeamAndProducts()
*                   Test that Deal Team and Products lists are displayed on JLOC Print View.
*               3 - testGetRadioOptions()
*                   Tests getter of radio options.
*/
@isTest
public class ZZTEST_JLOC_PrintViewController {
	public static testMethod void testJlocPrintView() {
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_JLOC jlocFactory = ZZTEST_DataFactoryFacade.jloc;

		JLOC__c jloc = new JLOC__c();

		Test.startTest();

        
		PageReference JLOC_PrintView = Page.JLOC_PrintView;
        JLOC_PrintView.getParameters().put('status','Submitted to Secretary');
        Test.setCurrentPage(JLOC_PrintView);

    	Apexpages.Standardcontroller stc = new ApexPages.StandardController(jloc);
        JLOC_PrintViewController controller = new JLOC_PrintViewController(stc);	

        System.assertEquals(controller.jlocDealTeam.size(), 0);
        System.assertEquals(controller.jlocProposedProducts.size(), 0);

        Test.stopTest();
	}

	public static testMethod void testJlocPrintViewWithDealTeamAndNoProducts() {
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_JLOC jlocFactory = ZZTEST_DataFactoryFacade.jloc;
		ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
		ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;

		User stdUser = userFactory.getBarclaysStandardUser();

		//Give this user JLOC permissions
        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'JLOC'];
        INSERT new PermissionSetAssignment(AssigneeId = stdUser.id, PermissionSetId = ps.Id);

		System.runAs(stdUser) {
			JLOC__c jloc = jlocFactory.getInsertedProduct(ZZTEST_F_JLOC.JlocRecordType.DEFAULT_JLOC, dataContainer);
			Opportunity opp = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
			opp.JLOC__c = jloc.Id;
			INSERT opp;

			jloc.Opportunity__c = opp.Id;
			UPDATE jloc;

			OpportunityTeamMember otm = new OpportunityTeamMember();
			otm.OpportunityId = opp.Id;
			otm.UserId = stdUser.Id;
			otm.I_confirm_team_member_has_been_cleared__c = true;
			INSERT otm;

			Test.startTest();

			PageReference JLOC_PrintView = Page.JLOC_PrintView;
	        Test.setCurrentPage(JLOC_PrintView);

	    	Apexpages.Standardcontroller stc = new ApexPages.StandardController(jloc);
	        JLOC_PrintViewController controller = new JLOC_PrintViewController(stc);	

	        //Verify we have 2 people on the deal team (1 real user and 1 empty record)
	        System.assertEquals(2, controller.jlocDealTeam.size());

	        //Verify we have no products on the JLOC (nothing on the Opportunity)
	        System.assertEquals(0, controller.jlocProposedProducts.size());

	        Test.stopTest();
	    }
	}

	public static testMethod void testJlocPrintViewWithClientPlan() {
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_JLOC jlocFactory = ZZTEST_DataFactoryFacade.jloc;
		ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
		ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;

		User stdUser = userFactory.getBarclaysStandardUser();

		//Give this user JLOC permissions
        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'JLOC'];
        INSERT new PermissionSetAssignment(AssigneeId = stdUser.id, PermissionSetId = ps.Id);

		System.runAs(stdUser) {
			JLOC__c jloc = jlocFactory.getInsertedProduct(ZZTEST_F_JLOC.JlocRecordType.DEFAULT_JLOC, dataContainer);
			Opportunity opp = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
			opp.JLOC__c = jloc.Id;
			INSERT opp;

			jloc.Opportunity__c = opp.Id;
			jloc.Pricing_and_Returns_Document_ID__c = '0000000000';
			UPDATE jloc;

			//Create CLientPlan test data
			Client_Plan__c cp = new Client_Plan__c();
			cp.Relationship__c = opp.AccountId;
			INSERT cp;

			Client_Plan_Borrowers_Guarantors__c borrower = new Client_Plan_Borrowers_Guarantors__c();
			borrower.Relationship__c = opp.AccountId;
			borrower.Type__c = 'Borrower';
			borrower.Value__c = 'A';
			INSERT borrower;

			Client_Plan_Borrowers_Guarantors__c guarantor = new Client_Plan_Borrowers_Guarantors__c();
			guarantor.Relationship__c = opp.AccountId;
			guarantor.Type__c = 'Guarantor';
			guarantor.Value__c = 'B';
			INSERT guarantor;

			Financial_Information__c finInfo = new Financial_Information__c();
			finInfo.Relationship__c = opp.AccountId;
			finInfo.Year__c = '2016';
			finInfo.Net_Asset_Value__c = 1;
			finInfo.EBITDA__c = 2;
			INSERT finInfo;

			Budget_Revenue__c budRev = new Budget_Revenue__c();
			budRev.Client_Plan__c = cp.Id;
			budRev.Actual_RoRWA__c = 10.0;
			INSERT budRev;

			Client_Plan_Facility__c cpFac = new Client_Plan_Facility__c();
			cpFac.Relationship__c = opp.AccountId;
			cpFac.Type_Of_Facility__c = 'OTHER';
            cpFac.Limit__c = 2000;
			INSERT cpFac;

			Country_Presence__c pres = new Country_Presence__c();
			pres.Client_Plan__c = cp.Id;
			pres.Banking_Country__c = 'South Africa';
			INSERT pres;

			Client_Plan_Security__c sec = new Client_Plan_Security__c();
			sec.Relationship__c = opp.AccountId;
			sec.Security_Description__c = 'XXX';
			sec.Value__c = 100000;
			INSERT sec;

			Client_Plan_Revenue_By_Product__c revByProduct = new Client_Plan_Revenue_By_Product__c();
			revByProduct.Client_Plan__c = cp.Id;
			INSERT revByProduct;

			Test.startTest();

			PageReference JLOC_PrintView = Page.JLOC_PrintView;
	        Test.setCurrentPage(JLOC_PrintView);

	    	Apexpages.Standardcontroller stc = new ApexPages.StandardController(jloc);
	        JLOC_PrintViewController controller = new JLOC_PrintViewController(stc);	

	        Test.stopTest();

	        //Verify we have a RevByProduct var which means we processed everything
	        System.assertEquals(true, controller.jlocRevByProduct != null, 'We should have a Client_Plan_Revenue_By_Product__c reference');
	    }
	}
}