objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Business_Unit_Claim__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Business Unit Claims</relationshipLabel>
        <relationshipName>Business_Unit_Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Business Unit Claims</relationshipLabel>
        <relationshipName>Business_Unit_Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portion_of_Claim__c</fullName>
        <label>Portion of Claim (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Business Unit Claim</label>
    <nameField>
        <displayFormat>BUC-{0000}</displayFormat>
        <label>Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Unit Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MatterPortionClaimOverride_Cont_test.cls
@Istest
public class MatterPortionClaimOverride_Cont_test {
    public static testMethod void testAddPortion() {
        Cloudsmiths_TestDataClass cloudsmiths_TestDataClass = new Cloudsmiths_TestDataClass();
       	
        Test.startTest();
        
        Test.setCurrentPageReference(new PageReference('Page.MatterPortionClaimOverride'));
		System.currentPageReference().getParameters().put('id', cloudsmiths_TestDataClass.TestMatter.id);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(cloudsmiths_TestDataClass.TestMatter);
        MatterPortionClaimOverride_Cont testPortionClaim = new MatterPortionClaimOverride_Cont(sc);
        
        Business_Unit_Claim__c bu = new Business_Unit_Claim__c();
        bu.Matter__c = cloudsmiths_TestDataClass.TestMatter.id;
        bu.Business_Unit__c = cloudsmiths_TestDataClass.TestBusinessUnit.id;
        bu.Portion_of_Claim__c = 80;
        
        insert bu;
        
        Business_Unit_Claim__c abu = new Business_Unit_Claim__c();
        abu.Matter__c = cloudsmiths_TestDataClass.TestMatter.id;
        abu.Business_Unit__c = cloudsmiths_TestDataClass.TestBusinessUnit.id;
        abu.Portion_of_Claim__c = 20;
        
        testPortionClaim.addedBusinessUnitClaims.add(bu);
        testPortionClaim.addBusinessUnitClaims = abu;
            
        testPortionClaim.save();
        testPortionClaim.addClaimButton();
        
        testPortionClaim.claimId = bu.id;
        testPortionClaim.removeClaim();
        
        Business_Unit_Claim__c bu2 = new Business_Unit_Claim__c();
        bu2.Matter__c = cloudsmiths_TestDataClass.TestMatter.id;
        bu2.Business_Unit__c = cloudsmiths_TestDataClass.TestBusinessUnit.id;
        bu2.Portion_of_Claim__c = 80;
        testPortionClaim.addedBusinessUnitClaims.add(bu2);

        testPortionClaim.updateClaims();
        
        Test.stopTest();
    }
}