objects/Business_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Cluster_Function__c</fullName>
        <label>Cluster/Function</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Business_Unit_Claim__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Business Unit Claims</relationshipLabel>
        <relationshipName>Business_Unit_Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cluster_Function__c</fullName>
        <formula>Business_Unit__r.Cluster_Function__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster/Function</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Business Unit Claims</relationshipLabel>
        <relationshipName>Business_Unit_Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portion_of_Claim__c</fullName>
        <label>Portion of Claim (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <formula>Business_Unit__r.Segment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Segment</label>
        <type>Text</type>
    </fields>
    <label>Business Unit Claim</label>
    <nameField>
        <displayFormat>BUC-{0000}</displayFormat>
        <label>Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Unit Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MatterPortionClaimOverride_Cont.cls
public class MatterPortionClaimOverride_Cont {

    public List<Business_Unit_Claim__c> addedBusinessUnitClaims { get; set; }
    public Id MatterId { get; set; }
    public Id claimId { get; set; }
    public Business_Unit_Claim__c addBusinessUnitClaims { get; set; }
    public Boolean showClaimButton { get; set; }
    public Decimal claimTotal { get; set; }

    public MatterPortionClaimOverride_Cont(ApexPages.StandardController stdController) {
        MatterId = ApexPages.currentPage().getParameters().get('id');
        addedBusinessUnitClaims = [select id, Cluster_Function__c, Segment__c, Business_Unit__c, Portion_of_Claim__c, Matter__c from Business_Unit_Claim__c where Matter__c = :MatterId];
        showClaimButton = true;
    }

    public Decimal CheckClaimTotal() {
        Decimal count = 0;
        for (Business_Unit_Claim__c bu : addedBusinessUnitClaims) {
            count += bu.Portion_of_Claim__c;
        }
        claimTotal = count;
        return count;
    }

    public PageReference save() {
        Decimal newTotalClaim = CheckClaimTotal() + addBusinessUnitClaims.Portion_of_Claim__c;
        if (newTotalClaim == 100) {
            addBusinessUnitClaims.Matter__c = MatterId;
            insert addBusinessUnitClaims;
            addedBusinessUnitClaims.add(addBusinessUnitClaims);
            showClaimButton = true;

            try {
                update addedBusinessUnitClaims;
            } catch (Exception e) {
                apexpages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Error adding business units: ' + e));
            }
        } else {
            apexpages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Total Portions of Claim must add up to 100. Please amend the Added Claims before a new Business Unit'));
        }
        return null;
    }

    public PageReference removeClaim() {
        Business_Unit_Claim__c busUnit = [select id, Cluster_Function__c, Segment__c, Business_Unit__c, Portion_of_Claim__c, Matter__c from Business_Unit_Claim__c where id = :claimId];

        Integer count = 0;
        for (Business_Unit_Claim__c bu : addedBusinessUnitClaims) {
            if (bu.id == busUnit.id) {
                break;
            }
            count++;
        }
        delete busUnit;
        addedBusinessUnitClaims.remove(count);

        //Adding rest of portions to claims
        Decimal newTotal = 100 - CheckClaimTotal();
        Integer numBusUnits = 0;
        for (Business_Unit_Claim__c bu : addedBusinessUnitClaims) {
            numBusUnits++;
        }

        Decimal amountToAddToEachClaim = newTotal / numBusUnits;
        for (Business_Unit_Claim__c bu : addedBusinessUnitClaims) {
            bu.Portion_of_Claim__c += amountToAddToEachClaim;
        }

        update addedBusinessUnitClaims;

        return null;
    }

    public PageReference addClaimButton() {
        addBusinessUnitClaims = new Business_Unit_Claim__c();
        showClaimButton = false;
        return null;
    }

    public PageReference updateClaims() {
        Decimal totalClaim = CheckClaimTotal();
        if (totalClaim == 100) {
            update addedBusinessUnitClaims;
        } else {
            apexpages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Total Portions of Claim must add up to 100'));
        }
        return null;
    }
}