objects/Call_Report__c.object
<CustomObject>
    <fields>
        <fullName>Client_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You can link an existing Client Plan to retrieve some fields for the Briefing Note (Company overview, opportunities, ...)</inlineHelpText>
        <label>Client Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Client_Plan__c.Relationship__c</field>
                <operation>equals</operation>
                <valueField>$Source.Relationship__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Client_Plan__c</referenceTo>
        <relationshipLabel>Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Only Relationship Groups or Prospect Relationships can be related to a Call Report</inlineHelpText>
        <label>Relationship</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 OR 5) AND 2) OR ((3 OR 5) AND 4) OR ((5 OR 6) AND 7)</booleanFilter>
            <errorMessage>Call Reports can only be recorded against a Relationship Group or Prospects</errorMessage>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Barclays Standard User, ABSA META User,User, Standard User ( Lightning ), Banking User (Custom), Standard User (Banking - Private), Standard User ( Lightning ), Standard User (Markets), Standard User (Research), ,Standard User (WIMI), Standard User (RoA)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Relationship Group, Prospect</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Barclays Wealth Advisor, Standard User (Wealth Advisory)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client - Individual, Client - Legal Entity, Prospect - Individual, Prospect - Legal Entity, Relationship Group, Client, Prospect, Client - Individual, Client - Legal Entity, Prospect - Individual, Prospect - Legal Entity</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Barclays Private Side User,Barclays Administrator, Delegated Admins, System Administrator, Barclays Business Owner, Standard User ( Private Lightning )</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Standard User (WIMI), Standard User (Retail Distribution)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>EDC Client,</value>
            </filterItems>
            <infoMessage>Call Reports can only be recorded against a Relationship Group</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Call Report</label>
    <nameField>
        <displayFormat>CR{000000}</displayFormat>
        <label>Call Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Client_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plans</relationshipLabel>
        <relationshipName>ClientPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Plan</label>
    <nameField>
        <displayFormat>PL{00000}</displayFormat>
        <label>Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Meeting_Attendee__c.object
<CustomObject>
    <description>This object is used to manage meeting attendees.</description>
    <fields>
        <fullName>Present__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Present</label>
        <type>Checkbox</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>MT{00000}</displayFormat>
        <label>Meeting Attendees Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Call_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <description>Determines the segment to which the opportunity belongs in order to apply sharing rules</description>
        <inlineHelpText>Determines the segment to which the opportunity belongs in order to apply sharing rules</inlineHelpText>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ProjectName__c.object
<CustomObject>
    <description>Object used to hold all potential private side opportunity names when user clicks new opportunity on a client</description>
    <fields>
        <fullName>Reserved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to store if a user has reserved this project name and is about to save an opportunity with this name</description>
        <label>Reserved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Used__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to determine if a user has saved an opportunity with this name</description>
        <label>Used</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Name</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountHelperController.cls
/*================================================
@Author : Mabhedle Tonga 
@Description : Helper class that holds generic functions that an be used across the salesforcs Org
@Created Date : 2017/12/14
@Test Class : AccountHelperController_Test
==================================================
@Modification Description : Changed account holder name from Africa RD Holder to Coverage Unmanaged
@Modification Date : 2018/02/19
@Modified By : Mabhedle Tonga 
==================================================*/
public with sharing class AccountHelperController 
{
	@AuraEnabled
    public static boolean isAFricaRDOwned(String accountId)
    {
        Account currentAccount = [Select Owner.Name,Segment__c from Account where ID=:accountID limit 1];
        
        if(currentAccount.Owner.Name.EqualsIgnoreCase(Label.lbl_Coverage_Unmanaged)&& !currentAccount.Segment__c.equalsIgnoreCase('Business Banking'))
        {
            return false;
        }
        else
        {
            return true;
        }
    }
    
    @AuraEnabled
    public static string getNewName() {
        Set<String> newOppNames = new Set<String>();
        List<ProjectName__c> newProjectNames = [SELECT Id, Name FROM ProjectName__c WHERE Reserved__c = false AND Used__c = false ORDER BY CreatedDate LIMIT 20000];
        for(ProjectName__c projectname : newProjectNames)
        	newOppNames.add('Project ' + projectname.Name);

        List<AggregateResult> namecountslist = [SELECT Name, COUNT(Id) CountOpp 
                                                FROM Opportunity 
                                                WHERE RecordTypeId =: OpportunityTrigger_Helper.getOpportunityRT(OpportunityTrigger_Helper.OpportunityRT.PrivateOpp)
                                                AND Name =: newOppNames
                                                GROUP BY Name];
		Map<String, Integer> namecountsmap = new Map<String, Integer>();
        for(AggregateResult namecount : namecountslist) namecountsmap.put(((String)namecount.get('Name')).toLowerCase(), (Integer)namecount.get('CountOpp'));
        
        String NameFound = '';
        List<ProjectName__c> projectNamesToUpdate = new List<ProjectName__c>();
        //Run through the Project Names randomly until you find something not used or you have gone through the entire list
        while (newProjectNames.size() > 0 && NameFound == '') {
        	Integer randomIndex = (Math.random() * (newProjectNames.size() - 1)).intValue();
            if (!namecountsmap.containsKey('project ' + newProjectNames[randomIndex].Name.toLowerCase())) {
                projectNamesToUpdate.add(new ProjectName__c(Id = newProjectNames[randomIndex].Id, Reserved__c = true));
                NameFound = 'Project ' + newProjectNames[randomIndex].Name;
            } else {
                projectNamesToUpdate.add(new ProjectName__c(Id = newProjectNames[randomIndex].Id, Used__c = true));
                newProjectNames.remove(randomIndex);
            }
		}
        
        try {
            if (projectNamesToUpdate.size() > 0) update projectNamesToUpdate;
        } catch(Exception e) {
            System.debug('We were not able to update Project Names:' + e);
        }
        
        return NameFound;
    }
    
    @AuraEnabled
    public static String createClientPlan(String accountId)
    {
        Client_Plan__c clientPlan = new Client_Plan__c();
        
        clientPlan.Relationship__c = accountId;
        Database.SaveResult result = Database.insert(clientPlan, false);
        
        if(!result.isSuccess())
        {
            Database.Error error = result.getErrors().get(0);
            return 'false';
        }
        else
        {
            return  [Select ID from Client_Plan__c where Relationship__c =:accountId limit 1].ID;
        }
    }
    
    @AuraEnabled        
    public static List<String> fetchRecordTypeValues(){
        List<Schema.RecordTypeInfo> recordtypes = Call_Report__c.SObjectType.getDescribe().getRecordTypeInfos();    
        Map<String, String> recordtypemap = new Map<String, String>();
        if(!Test.isRunningTest())
        {
            recordtypemap.put('None','None');
        }
        
        for(RecordTypeInfo rt : recordtypes){
            if(rt.isAvailable()){
                if(rt.getName() != 'Master')
                    recordtypemap.put(rt.getRecordTypeId(), rt.getName());
            }
        }        
        return recordtypemap.values();
    }
    
    @AuraEnabled
    public static Id getRecTypeId(String recordTypeLabel){
        Id recid = Schema.SObjectType.Call_Report__c.getRecordTypeInfosByName().get(recordTypeLabel).getRecordTypeId();        
        return recid;
    }
    
    @AuraEnabled
    public static String updateAttendeePresent(String attendeeId){
        Meeting_Attendee__c ma = new Meeting_Attendee__c();
        ma.Id = attendeeId;
        ma.Present__c = true;
        
        Database.SaveResult result = Database.update(ma, false);
        if(!result.isSuccess())
            return 'There was an issue updating this record.';
        else
            return attendeeId;
    }
}