objects/Case_Checklist_Question__c.object
<CustomObject>
    <description>RN - CloudSmiths - Object stores all the questions per heading for a specific checklist template</description>
    <fields>
        <fullName>Question__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Case Checklist Question</label>
    <nameField>
        <displayFormat>CHKQ-{000000000}</displayFormat>
        <label>CSC Checklist Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Checklist Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case_Checklist_Template__c.object
<CustomObject>
    <description>RN - CloudSmiths - Define a checklist template for each business area</description>
    <fields>
        <fullName>BusinessArea__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Business Area ( HUB )</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RSC</fullName>
                </value>
                <value>
                    <fullName>RSCS</fullName>
                </value>
                <value>
                    <fullName>EBSH CSC Pretoria</fullName>
                </value>
                <value>
                    <fullName>EBSS CSC Pretoria</fullName>
                </value>
                <value>
                    <fullName>POB JHB</fullName>
                </value>
                <value>
                    <fullName>RBB South Africa</fullName>
                </value>
                <value>
                    <fullName>Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>RSC - Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>RSC - Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>EBSS</fullName>
                </value>
                <value>
                    <fullName>EBSH</fullName>
                </value>
                <value>
                    <fullName>RSC - Corporate CPT</fullName>
                </value>
                <value>
                    <fullName>POB</fullName>
                </value>
                <value>
                    <fullName>Migration</fullName>
                </value>
                <value>
                    <fullName>RSCS - Bank Confirmations</fullName>
                </value>
                <value>
                    <fullName>RSC - Commercial CPT</fullName>
                </value>
                <value>
                    <fullName>RSCS - Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>RSCS - Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>RSCS - Corporate CPT</fullName>
                </value>
                <value>
                    <fullName>RSCS - Commercial CPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Checklist Template</label>
    <nameField>
        <displayFormat>CHKT-{000000}</displayFormat>
        <label>CSC Checklist Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case_QA__c.object
<CustomObject>
    <description>RN - CloudSmiths - QA record saved by an agent against a specific case. VF page renders QA questions dynamically from the case QA template record for a specific business area. Updates are saved as metadata to this record and rendered by a VF page</description>
    <fields>
        <fullName>QATemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RN - CloudSmiths</description>
        <label>QA Template</label>
        <referenceTo>Case_QA_Template__c</referenceTo>
        <relationshipLabel>Case QA&apos;s</relationshipLabel>
        <relationshipName>QAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case QA</label>
    <nameField>
        <displayFormat>QA-{000000000}</displayFormat>
        <label>Case QA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case QA&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case_QA_Question__c.object
<CustomObject>
    <description>RN - CloudSmiths - QA questions with weightings related to a specific QA template</description>
    <fields>
        <fullName>QATemplate__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>QA Template</label>
        <referenceTo>Case_QA_Template__c</referenceTo>
        <relationshipLabel>QA Questions</relationshipLabel>
        <relationshipName>QA_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case QA Question</label>
    <nameField>
        <displayFormat>QAQ-{000000000}</displayFormat>
        <label>Case QA Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case QA Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case_QA_Template__c.object
<CustomObject>
    <description>RN - CloudSmiths - Template object for all CSC Case QA forms</description>
    <fields>
        <fullName>BusinessArea__c</fullName>
        <label>Business Area ( HUB )</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>EBSH</fullName>
                </value>
                <value>
                    <fullName>EBSH CSC Pretoria</fullName>
                </value>
                <value>
                    <fullName>EBSS</fullName>
                </value>
                <value>
                    <fullName>EBSS CSC Pretoria</fullName>
                </value>
                <value>
                    <fullName>POB</fullName>
                </value>
                <value>
                    <fullName>POB JHB</fullName>
                </value>
                <value>
                    <fullName>RBB South Africa</fullName>
                </value>
                <value>
                    <fullName>RSC</fullName>
                </value>
                <value>
                    <fullName>RSCC</fullName>
                </value>
                <value>
                    <fullName>RSC - Commercial CPT</fullName>
                </value>
                <value>
                    <fullName>RSC - Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>RSC - Corporate CPT</fullName>
                </value>
                <value>
                    <fullName>RSC - Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>TCS</fullName>
                </value>
                <value>
                    <fullName>RSCS - Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>RSCS - Corporate CPT</fullName>
                </value>
                <value>
                    <fullName>RSCS - Bank Confirmations</fullName>
                </value>
                <value>
                    <fullName>RSC – Enterprise PTA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QAName__c</fullName>
        <description>RN - CloudSmiths - Name of the QA template</description>
        <label>QA Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Case QA Template</label>
    <nameField>
        <displayFormat>QAT-{000000}</displayFormat>
        <label>Case QA Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case QA Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Service_Mapping__c.object
<CustomObject>
    <description>Object to Capture Service Process and Resulting Service Category, Sub-Category and Type Applicable Information to Render on Cases Page</description>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <label>Business Hours</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Hours</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Department</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>RN : CloudSmiths
The date when this service mapping with SLA is effective from</description>
        <inlineHelpText>The date when this service mapping with SLA is effective from</inlineHelpText>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_SLA_Time_Measure__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Email SLA Time Measure</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Time_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_SLA_Units__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Email SLA Units</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Department__c</fullName>
        <label>Full Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Absa Electronic Banking Helpdesk</fullName>
                </value>
                <value>
                    <fullName>Absa Electronic Banking Service Support</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Support Corporate Cape Town</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Commercial Cape Town</fullName>
                </value>
                <value>
                    <fullName>Trade Client Service Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Enterprise Pretoria</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Commercial Pretoria</fullName>
                </value>
                <value>
                    <fullName>Channel Specialist</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Corporate Cape Town</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Support Corporate Pretoria</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Corporate Pretoria</fullName>
                </value>
                <value>
                    <fullName>Product On-boarding</fullName>
                </value>
                <value>
                    <fullName>Digital Ops Support</fullName>
                </value>
                <value>
                    <fullName>Botswana CCC SA</fullName>
                </value>
                <value>
                    <fullName>Payments Operations</fullName>
                </value>
                <value>
                    <fullName>Transfer Inwards</fullName>
                </value>
                <value>
                    <fullName>Structured Commodity Finance</fullName>
                </value>
                <value>
                    <fullName>Structured Trade Finance</fullName>
                </value>
                <value>
                    <fullName>RBB Cash Operations</fullName>
                </value>
                <value>
                    <fullName>Open Account - Middle Office</fullName>
                </value>
                <value>
                    <fullName>Functions Technology</fullName>
                </value>
                <value>
                    <fullName>Salesforce Africa</fullName>
                </value>
                <value>
                    <fullName>Trade Operations</fullName>
                </value>
                <value>
                    <fullName>CIB Financial Crime Compliance</fullName>
                </value>
                <value>
                    <fullName>Future clearing</fullName>
                    <label>Futures clearing</label>
                </value>
                <value>
                    <fullName>SA Migrations</fullName>
                </value>
                <value>
                    <fullName>Wholesale Client Service Centre</fullName>
                </value>
                <value>
                    <fullName>inward payments Client service and support</fullName>
                </value>
                <value>
                    <fullName>Cash Send</fullName>
                </value>
                <value>
                    <fullName>Refresh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>RN : CloudSmiths</description>
        <inlineHelpText>Please use the Queue API name</inlineHelpText>
        <label>Queue Name (API Name)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Queue</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Team</valueSetName>
        </valueSet>
    </fields>
    <label>Service Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Business_Hours.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Monday to Friday 06:00 - 19:00</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 07:30 - 17:00</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 08:00 - 16:30</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 07:00 - 16:30</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 08:00 - 18:00</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday     08:00 - 17:00</fullName>
    </customValue>
    <masterLabel>Business Hours</masterLabel>
</GlobalValueSet>

globalValueSets/Department.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>EBSS</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Commercial PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Commercial CPT</fullName>
    </customValue>
    <customValue>
        <fullName>TCSM</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate CPT &amp; PTA</fullName>
    </customValue>
    <customValue>
        <fullName>POB</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Enterprise PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>DOS</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH ROA</fullName>
    </customValue>
    <customValue>
        <fullName>Investigations</fullName>
    </customValue>
    <customValue>
        <fullName>ITC</fullName>
    </customValue>
    <customValue>
        <fullName>TRI</fullName>
    </customValue>
    <customValue>
        <fullName>SCF</fullName>
    </customValue>
    <customValue>
        <fullName>STF</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Operations</fullName>
    </customValue>
    <customValue>
        <fullName>OA - MO</fullName>
    </customValue>
    <customValue>
        <fullName>F-Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>BGI</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Crime Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Future Clearing</fullName>
    </customValue>
    <customValue>
        <fullName>SA Migrations - JHB</fullName>
    </customValue>
    <masterLabel>Department</masterLabel>
</GlobalValueSet>

globalValueSets/Queue.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Banking Advisory Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Breaks</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Send</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Bloem</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare DBN</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Goodwood</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Kempton</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Klerksdorp</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Ormonde</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare PE</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare PTA</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Vaal</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Witbank</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement DBN</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement JHB</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement PE</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Finance Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Client</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Csctradesupport</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - DebiCheck</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - General</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - NovoFX</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - 2nd Line</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - Absa Electronic Banking</fullName>
    </customValue>
    <masterLabel>Queue</masterLabel>
</GlobalValueSet>

globalValueSets/SLA_Time_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <customValue>
        <fullName>Hour(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Day(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Week(s)</fullName>
    </customValue>
    <masterLabel>SLA Time Measure</masterLabel>
</GlobalValueSet>

globalValueSets/SLA_Unit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <masterLabel>SLA Unit</masterLabel>
</GlobalValueSet>

globalValueSets/Team.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2nd Line</fullName>
    </customValue>
    <customValue>
        <fullName>Absa Electronic Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Absa Global</fullName>
    </customValue>
    <customValue>
        <fullName>Activations</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net Amendments</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net CSC Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net Processing</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net Rest of Africa</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net SA</fullName>
    </customValue>
    <customValue>
        <fullName>Billing &amp; Limits</fullName>
    </customValue>
    <customValue>
        <fullName>C2B</fullName>
    </customValue>
    <customValue>
        <fullName>CSC Documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Diamond</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Certificates</fullName>
    </customValue>
    <customValue>
        <fullName>EBSS Approvals</fullName>
    </customValue>
    <customValue>
        <fullName>EFX Support</fullName>
    </customValue>
    <customValue>
        <fullName>Magtapes</fullName>
    </customValue>
    <customValue>
        <fullName>New Registrations</fullName>
    </customValue>
    <customValue>
        <fullName>Passwords</fullName>
    </customValue>
    <customValue>
        <fullName>Sweeping</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>TCSM</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Product On-boarding</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Ops Support</fullName>
    </customValue>
    <customValue>
        <fullName>NovoFX</fullName>
    </customValue>
    <masterLabel>Team</masterLabel>
</GlobalValueSet>

classes/LscCaseQaFormController_Test.cls
@isTest
public class LscCaseQaFormController_Test {
    
  @isTest
    static void LscCaseQaFormController_Postive_test()
    { 
        case testCase = new case();
        
        testCase.Queue__c = 'EBSH - Absa Electronic Banking';
        testCase.Subject = 'Support test ';
        testCase.Origin = 'Email';
        testCase.Status = 'New';
        testCase.Priority = 'High';  
        testCase.Department__c = 'EBSH';
        testCase.Full_Department__c = 'Absa Electronic Banking Helpdesk';
        
        insert testCase;
        
        Group testq = new Group();
        testq.Name = 'testq';
        testq.Type = 'Queue'; 
        insert testq;
        
        Service_Mapping__c testMapping = new Service_Mapping__c
            (
                Queue_Name__c = 'testq', 
                queue__c = 'EBSH - Absa Electronic Banking',
                Team__c= 'Absa Electronic Banking',
                Department__c ='EBSH', 
                Business_Hours__c= '	Monday to Friday 06:00 - 19:00', 
                Full_Department__c = 'Absa Electronic Banking Helpdesk',
                Effective_Date__c = date.today(),
                Email_SLA_Time_Measure__c = 'Hour', 
                Email_SLA_Units__c = '1'
                
            );
        insert testMapping;
        
        
        Case_QA_Template__c QATemplate = new Case_QA_Template__c
          (
        
        	QAName__c ='EBSH',
            BusinessArea__c ='EBSH'
        
           );
                  
        insert QATemplate;
         
 
        
        Case_QA_Question__c CaseQA = new Case_QA_Question__c
            (
          	
            QATemplate__c = QATemplate.id,
            Heading__c = 'Test',
            QAQuestion__c = 'Test',
            Weighting__c = 12
        
        );
        
         insert CaseQA;
     
        
        Case_QA__c TestQustions = new Case_QA__c
        (
            
             RelatedCase__c= testCase.id,
             submittedBy__c = UserInfo.getUserId(),
             QATemplate__c = QATemplate.id,
             SavedResults__c = 'test|test'
     
        );
            insert TestQustions;
                system.debug(QATemplate.id+' Test 11111111111111111111111111111111111111111111111111111111111111111111111111111111111');
        
         LscCaseQaFormController.getCaseQaRecords(testCase.id,QATemplate.id);
         LscCaseQaFormController.fetchAgentRecords('test', 'Account');
        
        /* String CaseID =String.valueOf(testCase.id);
        String TemplateID =String.valueOf(testTemplate.id);
        String SavedResults =String.valueOf(testChecklist.id);
        
        lscCaseQAExt.updateCaseChecklistRecord(CaseID, TemplateID, SavedResults, CaseID);
        lscCaseQAExtFormSelection(); */
    }

     

/* @isTest
    static void LscCaseQaFormController_Postive(){
        
         case testCase = new case();
        
        testCase.Queue__c = 'EBSH - Absa Electronic Banking';
        testCase.Subject = 'Support test ';
        testCase.Origin = 'Email';
        testCase.Status = 'New';
        testCase.Priority = 'High';  
        testcase.Department__c = 'EBSH';
        testCase.Full_Department__c = 'Absa Electronic Banking Helpdesk';
        
        insert testCase;
        
        Group testq = new Group();
        testq.Name = 'testq';
        testq.Type = 'Queue'; 
        insert testq;
        
        Service_Mapping__c testMapping = new Service_Mapping__c
            (
                Queue_Name__c = 'testq', 
                queue__c = 'EBSH - Absa Electronic Banking',
                Team__c= 'Absa Electronic Banking',
                Department__c ='EBSH', 
                Business_Hours__c= '	Monday to Friday 06:00 - 19:00', 
                Full_Department__c = 'Absa Electronic Banking Helpdesk',
                Effective_Date__c = date.today(),
                Email_SLA_Time_Measure__c = 'Hour', 
                Email_SLA_Units__c = '1'
                
            );
        insert testMapping;
        
        Case_Checklist_Template__c testTemplate = new Case_Checklist_Template__c
            (
                BusinessArea__c = 'RSCS',
                ChecklistName__c = 'test'
            );
        insert testTemplate;
        
        Case_Checklist_Question__c testQuestion = new Case_Checklist_Question__c
            (
                
             Checklist_Template__c = testTemplate.id,
             Heading__c = 'Test',
             Question__c= 'What is the test?'
                
            );
        insert testQuestion;
        
        Case_Checklist__c testChecklist = new Case_Checklist__c
            (
                
                ChecklistTemplate__c =testTemplate.id,
                RelatedCase__c = testCase.id,
                SubmittedBy__c =  UserInfo.getUserId()
               // SavedResults__c = 'This is a test'
                
            );
        
        insert testChecklist;
            
             
         LscCaseQaFormController.getCaseQaRecords(testCase.id,testTemplate.id);
         //LscCaseQaFormController.updateCaseChecklistRecord(testCase);
         LscCaseQaFormController.fetchAgentRecords('test', 'Account');
   
    
    } */
    

}