objects/Case_QA__c.object
<CustomObject>
    <description>RN - CloudSmiths - QA record saved by an agent against a specific case. VF page renders QA questions dynamically from the case QA template record for a specific business area. Updates are saved as metadata to this record and rendered by a VF page</description>
    <fields>
        <fullName>AgentName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_QA_s1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AgentScorePer__c</fullName>
        <formula>IF( FailedAuditRequirement__c , 0 , ( AgentScore__c / WeightingTotal__c ))</formula>
        <label>Agent Score %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AgentScore__c</fullName>
        <label>Agent Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QATemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RN - CloudSmiths</description>
        <label>QA Template</label>
        <referenceTo>Case_QA_Template__c</referenceTo>
        <relationshipLabel>Case QA&apos;s</relationshipLabel>
        <relationshipName>QAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case QA&apos;s</relationshipLabel>
        <relationshipName>QAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SavedResults__c</fullName>
        <description>RN - CloudSmiths - Saved results as metadata to be rendered by VF</description>
        <label>Saved Results</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SubmittedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_QA_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WeightingTotal__c</fullName>
        <label>Weighting Total</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case QA</label>
    <nameField>
        <displayFormat>QA-{000000000}</displayFormat>
        <label>Case QA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case QA&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case_QA_Question__c.object
<CustomObject>
    <description>RN - CloudSmiths - QA questions with weightings related to a specific QA template</description>
    <fields>
        <fullName>Heading__c</fullName>
        <description>RN - CloudSmiths - QA question heading</description>
        <label>Heading</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsAuditRequirement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>RN - CloudSmiths 
Audit critical question</description>
        <inlineHelpText>Check this if this question is an audit critical question. Should an agent score zero (0) for this question the complete QA evaluation for that agent will fail.</inlineHelpText>
        <label>Is Audit Requirement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QAQuestion__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QATemplate__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>QA Template</label>
        <referenceTo>Case_QA_Template__c</referenceTo>
        <relationshipLabel>QA Questions</relationshipLabel>
        <relationshipName>QA_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weighting__c</fullName>
        <defaultValue>0</defaultValue>
        <description>RN - CloudSmiths - The weighting of the specific question</description>
        <inlineHelpText>The weighting of the specific question</inlineHelpText>
        <label>Weighting</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case QA Question</label>
    <nameField>
        <displayFormat>QAQ-{000000000}</displayFormat>
        <label>Case QA Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case QA Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case_QA_Template__c.object
<CustomObject>
    <description>RN - CloudSmiths - Template object for all CSC Case QA forms</description>
    <fields>
        <fullName>BusinessArea__c</fullName>
        <label>Business Area ( HUB )</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>EBSH</fullName>
                </value>
                <value>
                    <fullName>EBSH CSC Pretoria</fullName>
                </value>
                <value>
                    <fullName>EBSS</fullName>
                </value>
                <value>
                    <fullName>EBSS CSC Pretoria</fullName>
                </value>
                <value>
                    <fullName>POB</fullName>
                </value>
                <value>
                    <fullName>POB JHB</fullName>
                </value>
                <value>
                    <fullName>RBB South Africa</fullName>
                </value>
                <value>
                    <fullName>RSC</fullName>
                </value>
                <value>
                    <fullName>RSCC</fullName>
                </value>
                <value>
                    <fullName>RSC - Commercial CPT</fullName>
                </value>
                <value>
                    <fullName>RSC - Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>RSC - Corporate CPT</fullName>
                </value>
                <value>
                    <fullName>RSC - Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>TCS</fullName>
                </value>
                <value>
                    <fullName>RSCS - Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>RSCS - Corporate CPT</fullName>
                </value>
                <value>
                    <fullName>RSCS - Bank Confirmations</fullName>
                </value>
                <value>
                    <fullName>RSC – Enterprise PTA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QAName__c</fullName>
        <description>RN - CloudSmiths - Name of the QA template</description>
        <label>QA Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WeightingTotal__c</fullName>
        <label>Weighting Total</label>
        <summarizedField>Case_QA_Question__c.Weighting__c</summarizedField>
        <summaryForeignKey>Case_QA_Question__c.QATemplate__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Case QA Template</label>
    <nameField>
        <displayFormat>QAT-{000000}</displayFormat>
        <label>Case QA Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case QA Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Case_QA_Form_Controller.cls
/**
* 2017-08-17 - Rudolf Niehaus - CloudSmiths
* Controller for the visualforce page Case_QA_Form 
* The controller and page dynamically renders a qa form based on the 
* managers selection from a console Case quick action. The blue print for the form is stored in a 
* custom object and unique per business area
* 2017-08-24 - Rudolf Niehau - Remove peer review from the VF page and std page layouts, but keep the code
                               in this controller. I have a feeling CSC is going to use this in future again.
**/
public class Case_QA_Form_Controller {
    
    private list<Case_QA_Template__c> qaBluePrint;
    public String wtotal {get;set;}
    public String templateId {get;set;}
    public String agentId {get;set;}
    public String agentName {get;set;}
    public String caseId {get;set;}
    public String metaData {get;set;}
    public String qaId {get;set;}
    public list<FormStructure> wFormStructure {get;set;}
    public Decimal agentTotal {get;set;}
    public Decimal peerTotal {get;set;}
    public boolean makeReadOnly {get;set;}
    public String currentAgentName {get;set;}
    private String qaMode = '';
    
    public Case_QA_Form_Controller(){
        

         map<String,String> selectionMap = new map<String,String>();
         makeReadOnly = false;
         currentAgentName = 'No Agent';        
         //get page parameters
        if(ApexPages.currentPage().getParameters().get('Id') != null){
            caseId = ApexPages.currentPage().getParameters().get('Id');
        }
        if(ApexPages.currentPage().getParameters().get('templateId') != null){
            templateId = ApexPages.currentPage().getParameters().get('templateId');
        }
        if(ApexPages.currentPage().getParameters().get('readOnly') != null){
            String x = ApexPages.currentPage().getParameters().get('readOnly');
            if(x=='1'){
                makeReadOnly=true;
            }
            
        }
        //
        if(ApexPages.currentPage().getParameters().get('qaMode') != null){
            templateId = ApexPages.currentPage().getParameters().get('qaMode');
        }
        //check if there is an existing checklist saved for this template for this case
        list<Case_QA__c> currentQA = [Select Id, WeightingTotal__c, SavedResults__c, RelatedCase__c, QATemplate__c,
                                      AgentScorePer__c, AgentScore__c, AgentName__c,AgentName__r.Name  
                                      From Case_QA__c 
                                      Where QATemplate__c = :templateId and RelatedCase__c = :caseId 
                                      and SubmittedBy__c = :UserInfo.getUserId()];
        if(currentQA.size() > 0){
            
            qaId = currentQA[0].Id;
            currentAgentName = currentQA[0].AgentName__r.Name;
            
            //get metadata
            if(String.isNotBlank(currentQA[0].SavedResults__c)){
                
                list<String> allSaved = currentQA[0].SavedResults__c.split(';');
           
                for(String selection :allSaved){
                   
                    list<String> res = selection.split('\\|');
                    
                    selectionMap.put(res[0],res[1]);
                    
                }
            }
        }else{
            qaId = '';
        }
        
        //get the QA blue print
        qaBluePrint = [Select Id, QAName__c, BusinessArea__c, WeightingTotal__c, 
                     (Select Id, Weighting__c, QAQuestion__c, Heading__c, IsAuditRequirement__c From QA_Questions__r order by Heading__c asc) 
                     From Case_QA_Template__c  
                     Where Id = :templateId limit 1];
        
        if(qaBluePrint.size() > 0){
            wtotal = String.valueOf(qaBluePrint[0].WeightingTotal__c);
            String headingX = '';
            String headingY = '';
            headingX.hashCode();
            list<String> questions = new list<String>();
            list<FormSelection> wFormSelection = new list<FormSelection>();
            wFormStructure = new list<FormStructure>();
            
            //build the heading with related questions map
            FormSelection fs;
           
            for(Case_QA_Question__c q :qaBluePrint[0].QA_Questions__r){

                headingX = q.Heading__c;
               
                if(selectionMap.containsKey(q.Id)){
                    fs = new FormSelection(q, q.Id, selectionMap.get(q.Id), q.IsAuditRequirement__c);
                }else{             
                    fs = new FormSelection(q, q.Id, 'Yes', q.IsAuditRequirement__c);
                }
     
                if(headingX == headingY || headingY == ''){
                    wFormSelection.add(fs);                  
                }else{
                    
                    list<FormSelection> wNewFormSelection = new list<FormSelection>(wFormSelection);
                    FormStructure fstr = new FormStructure(headingY,wNewFormSelection);
                    wFormStructure.add(fstr);

                    wFormSelection.clear();
                    wFormSelection.add(fs);
                }
                
                headingY = q.Heading__c;
            }
            
            //add last list of questions to the wrapper after we have exite the loop
            FormStructure fstr = new FormStructure(headingY, wFormSelection);
            wFormStructure.add(fstr);
            
            //default calculation to 100%
            calculateQA();
            
        }else{
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'There is no QA template configure with this Id : ' + templateId));
        }    
    }
    
    public void calculateQA(){
        
        Integer totalAgentScore = 0;

        for(FormStructure fs :wFormStructure){
            for(FormSelection s :fs.questions){
                
                if(s.IsCheckedYes == 'checked'){
                    totalAgentScore+= Integer.valueOf(s.question.Weighting__c); 
                }   
            }
        }
        if(qaBluePrint[0].WeightingTotal__c > 0){
            agentTotal = ( totalAgentScore / qaBluePrint[0].WeightingTotal__c ) * 100;
        }else{
            agentTotal = 0;
        }
        

        //return null;
    }
    
    //NESTED CLASSES
    //Case_QA_Template__c wrapper class to keep track of values entered
    public class FormStructure{
        
        public String heading {get;set;}
        public list<FormSelection> questions {get;set;}

        public FormStructure(String heading, list<FormSelection> questions){
            this.heading = heading;
            this.questions = questions;
        }
    }
    
    public class FormSelection{
        
        public Case_QA_Question__c question {get;set;}
        public String questionId {get;set;}
        public Boolean isAuditQuestion {get;set;}
        public String IsChecked {get;set;}
        public String IsCheckedYes {get;set;}
        public String IsCheckedNo {get;set;}
        public String IsCheckedNA {get;set;}
        
        public FormSelection(Case_QA_Question__c question, String questionId, String IsChecked, Boolean isAudit ){
            this.question = question;
            this.questionId = questionId;
            this.isAuditQuestion = isAudit;
            
            if(IsChecked == 'Yes'){
                this.IsCheckedYes = 'checked';
            }else if(IsChecked == 'No'){
                this.IsCheckedNo = 'checked';
            }else if(IsChecked == 'NA'){
                this.IsCheckedNA = 'checked';
            }else{
                this.IsCheckedYes = '';
                this.IsCheckedNo = '';
                this.IsCheckedNA = '';
            }
        }
    }   
}