objects/Case_Checklist__c.object
<CustomObject>
    <description>RN - CloudSmiths - Checklist record saved by an agent against a specific case. VF page renders checklist questions dynamically from the case checklist template record for a specific business area. Updates are saved as metadata to this record and rendered by a VF page</description>
    <fields>
        <fullName>ChecklistTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RN - CloudSmiths</description>
        <label>Checklist Template</label>
        <referenceTo>Case_Checklist_Template__c</referenceTo>
        <relationshipLabel>Case Checklists</relationshipLabel>
        <relationshipName>Case_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RN - CloudSmiths</description>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Checklists</relationshipLabel>
        <relationshipName>Case_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SavedResults__c</fullName>
        <description>RN - CloudSmiths - The checklist saved results as metadata. This will be rendered by a VF page when a user wants to view the saved results</description>
        <label>Saved Results</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SubmittedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RN - CloudSmiths</description>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Checklist</label>
    <nameField>
        <displayFormat>CHK-{000000000}</displayFormat>
        <label>Case Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case_Checklist_Question__c.object
<CustomObject>
    <description>RN - CloudSmiths - Object stores all the questions per heading for a specific checklist template</description>
    <fields>
        <fullName>Checklist_Template__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Checklist Template</label>
        <referenceTo>Case_Checklist_Template__c</referenceTo>
        <relationshipLabel>Case Checklist Questions</relationshipLabel>
        <relationshipName>Case_Checklist_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Heading__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Heading</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Case Checklist Question</label>
    <nameField>
        <displayFormat>CHKQ-{000000000}</displayFormat>
        <label>CSC Checklist Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Checklist Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case_Checklist_Template__c.object
<CustomObject>
    <description>RN - CloudSmiths - Define a checklist template for each business area</description>
    <fields>
        <fullName>BusinessArea__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Business Area ( HUB )</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RSC</fullName>
                </value>
                <value>
                    <fullName>RSCS</fullName>
                </value>
                <value>
                    <fullName>EBSH CSC Pretoria</fullName>
                </value>
                <value>
                    <fullName>EBSS CSC Pretoria</fullName>
                </value>
                <value>
                    <fullName>POB JHB</fullName>
                </value>
                <value>
                    <fullName>RBB South Africa</fullName>
                </value>
                <value>
                    <fullName>Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>RSC - Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>RSC - Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>EBSS</fullName>
                </value>
                <value>
                    <fullName>EBSH</fullName>
                </value>
                <value>
                    <fullName>RSC - Corporate CPT</fullName>
                </value>
                <value>
                    <fullName>POB</fullName>
                </value>
                <value>
                    <fullName>Migration</fullName>
                </value>
                <value>
                    <fullName>RSCS - Bank Confirmations</fullName>
                </value>
                <value>
                    <fullName>RSC - Commercial CPT</fullName>
                </value>
                <value>
                    <fullName>RSCS - Corporate PTA</fullName>
                </value>
                <value>
                    <fullName>RSCS - Commercial PTA</fullName>
                </value>
                <value>
                    <fullName>RSCS - Corporate CPT</fullName>
                </value>
                <value>
                    <fullName>RSCS - Commercial CPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChecklistName__c</fullName>
        <description>RN - CloudSmiths</description>
        <inlineHelpText>Please enter the name of the checklist for this business area. This name will be visible to support agents</inlineHelpText>
        <label>Checklist Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Case Checklist Template</label>
    <nameField>
        <displayFormat>CHKT-{000000}</displayFormat>
        <label>CSC Checklist Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Mapping__c.object
<CustomObject>
    <description>Object to Capture Service Process and Resulting Service Category, Sub-Category and Type Applicable Information to Render on Cases Page</description>
    <label>Service Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Hub__c</fullName>
        <label>Hub</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Case_Checklist_Form_Controller_Test.cls
/**
* 2017-09-01 - Rudolf Niehaus - CloudSmiths
*============================================
* 2017-06-27 Mabhedle Tonga - Updated running user hub to use RCS Corporate PTA
=============================================
**/
@isTest(seeAllData=true)
public class Case_Checklist_Form_Controller_Test {
    
    static testMethod void Checklist_Form_Controller_Test(){
        
        CSC_TestDataFactory.testDataSize = 1;
         
        User currentUser  = new User(ID = UserInfo.getUserId(),Hub__c = 'RSC - Corporate PTA');
        update currentUser;
        //create some service mapping data
        Service_Mapping__c sm = CSC_TestDataFactory.getServiceMapRecord();
        insert sm;
        
        list<Case> caseInsertList = CSC_TestDataFactory.getTestCaseList( 'CSC Emails' , UserInfo.getUserId() );
        insert caseInsertList;
        Case_Checklist_Template__c temp = new Case_Checklist_Template__c();
        temp.ChecklistName__c = 'Checklis';
        temp.BusinessArea__c = 'EBSS CSC Pretoria';
        insert temp;
        
        Case_Checklist_Question__c q = new Case_Checklist_Question__c();
        q.Checklist_Template__c = temp.Id;
        q.Heading__c = 'test heading';
        q.Question__c = 'test question a';
        insert q;
        
            Case_Checklist__c currentChkList = new Case_Checklist__c();
            currentChkList.SubmittedBy__c = UserInfo.getUserId();
            currentChkList.RelatedCase__c = caseInsertList[0].Id;
            currentChkList.ChecklistTemplate__c = temp.Id;
            insert currentChkList;         
            
            currentChkList.SavedResults__c = q.Id + '|No;';
            update currentChkList;
      
        Test.startTest();

        PageReference pageRef = Page.Case_Checklist_Form;
        Test.setCurrentPage(pageRef);     
        ApexPages.currentPage().getParameters().put('Id', caseInsertList[0].Id);
        ApexPages.currentPage().getParameters().put('templateId', temp.Id);
        ApexPages.currentPage().getParameters().put('readOnly', '1');
        ApexPages.currentPage().getParameters().put('recId', null);
        
        Case_Checklist_Form_Controller theCont = new Case_Checklist_Form_Controller();
        theCont.updateChecklist();
        
        Test.stopTest();
        
    }

}