objects/Case_Checklist__c.object
<CustomObject>
    <description>RN - CloudSmiths - Checklist record saved by an agent against a specific case. VF page renders checklist questions dynamically from the case checklist template record for a specific business area. Updates are saved as metadata to this record and rendered by a VF page</description>
    <fields>
        <fullName>ChecklistTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RN - CloudSmiths</description>
        <label>Checklist Template</label>
        <referenceTo>Case_Checklist_Template__c</referenceTo>
        <relationshipLabel>Case Checklists</relationshipLabel>
        <relationshipName>Case_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>RN - CloudSmiths</description>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Checklists</relationshipLabel>
        <relationshipName>Case_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SavedResults__c</fullName>
        <description>RN - CloudSmiths - The checklist saved results as metadata. This will be rendered by a VF page when a user wants to view the saved results</description>
        <label>Saved Results</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Case Checklist</label>
    <nameField>
        <displayFormat>CHK-{000000000}</displayFormat>
        <label>Case Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case_Checklist_Question__c.object
<CustomObject>
    <description>RN - CloudSmiths - Object stores all the questions per heading for a specific checklist template</description>
    <fields>
        <fullName>Checklist_Template__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Checklist Template</label>
        <referenceTo>Case_Checklist_Template__c</referenceTo>
        <relationshipLabel>Case Checklist Questions</relationshipLabel>
        <relationshipName>Case_Checklist_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Heading__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Heading</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Case Checklist Question</label>
    <nameField>
        <displayFormat>CHKQ-{000000000}</displayFormat>
        <label>CSC Checklist Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Checklist Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case_QA_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case_QA_Answers</relationshipLabel>
        <relationshipName>Case_QA_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TemplateID__c</fullName>
        <label>TemplateID</label>
        <type>TextArea</type>
    </fields>
    <label>Case_QA_Answer</label>
    <nameField>
        <displayFormat>CASQA-A-{000000000}</displayFormat>
        <label>Case_QA_Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case_QA_Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CSC_Migration_Team__mdt.object
<CustomObject>
    <label>CSC Migration Team</label>
    <pluralLabel>CSC Migration Team</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Hub__c</fullName>
        <label>Hub</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CaseChecklistTriggerhandler_Functions.cls
/*====================================================
@CreatedDate : 2018-06-13
@CreatedBy : Mabhedle Tonga 
@Description : 
=====================================================*/
public class CaseChecklistTriggerhandler_Functions {
    
    public static void addToQuestionAnswer(List<Case_Checklist__c> ccList)
    {
        List<Case_QA_Answer__c> caseQAAnswerList = new List<Case_QA_Answer__c>();
        map<ID,Case_Checklist_Question__c> questionMap = getQuestions();
        Set<ID> TemplateIDSet = new Set<ID>();
        Set<ID> caseIDSet = new Set<ID>();
        
        for(Case_Checklist__c case_CheckList : ccList)
        {
            caseIDSet.add(case_CheckList.RelatedCase__c);
            TemplateIDSet.add(case_CheckList.ChecklistTemplate__c);
            if(String.isNotBlank(case_CheckList.SavedResults__c))
            {
                List<String> questionAnswerlist = case_CheckList.SavedResults__c.split(';');
                for(String questionAnswer : questionAnswerlist)
                {
                    List<String> questionAnswerArray = questionAnswer.split('\\|');
                    if(questionMap.containskey((ID)questionAnswerArray[0].trim()))
                    {
                        if(questionAnswerArray.size()==2)
                        {
                            caseQAAnswerList.add(new Case_QA_Answer__c(Case__c=case_CheckList.RelatedCase__c,Question__c = questionMap.get(questionAnswerArray[0]).Question__c,
                                                                       Answer__c = questionAnswerArray[1],TemplateID__c = questionMap.get(questionAnswerArray[0]).Checklist_Template__c));                            
                        }
                        if(questionAnswerArray.size()==3)
                        {
                            caseQAAnswerList.add(new Case_QA_Answer__c(Case__c=case_CheckList.RelatedCase__c,Question__c = questionMap.get(questionAnswerArray[0]).Question__c,
                                                                       Answer__c = questionAnswerArray[1],TemplateID__c = questionMap.get(questionAnswerArray[0]).Checklist_Template__c,
                                                                      Action_Date__c = Date.valueOf(questionAnswerArray[2])));
                        }
                    }
                }
                
                
            }
        }
        
        if(TemplateIDSet.size()>0)
        {
            delete [Select ID from Case_QA_Answer__c where TemplateID__c IN: TemplateIDSet AND Case__c IN:caseIDSet];
        }
        if(caseQAAnswerList.size()>0)
            insert caseQAAnswerList;
    }
    private static map<ID,Case_Checklist_Question__c> getQuestions()
    {
        return  new Map<ID,Case_Checklist_Question__c>([Select ID,Heading__c,Name,Question__c,Checklist_Template__c From Case_Checklist_Question__c limit 50000]);
    }
    public static User getUserById(ID userId)
    {
        return [Select ID,Hub__c from User Where ID=:userId];
    }
    
    public static Set<String> getValidHubs()
    {
        
        List<CSC_Migration_Team__mdt> CSCMigrationTeams = [Select MasterLabel from CSC_Migration_Team__mdt];
        Set<String> teamName = new Set<String>();
        
        for(CSC_Migration_Team__mdt cscMT : CSCMigrationTeams)
        {
            teamName.add(cscMT.MasterLabel);
        }
        
        return teamName;
    }
    
}