objects/Client_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plans</relationshipLabel>
        <relationshipName>ClientPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Plan</label>
    <nameField>
        <displayFormat>PL{00000}</displayFormat>
        <label>Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ZZTEST_ClientPlanSummaryPrintView.cls
@isTest
private class ZZTEST_ClientPlanSummaryPrintView {
	
	@isTest static void testSummaryPrint() {
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
		Account acc1 = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);

		Client_Plan__c cp = new Client_Plan__c();
		cp.Relationship__c = acc1.Id;
		INSERT cp;

		PageReference pr = Page.ClientPlanSummaryPrintView;
		pr.getParameters().put('id', cp.Id);
		Test.setCurrentPage(pr);

		Test.startTest();
		ClientPlanSummaryPrintViewController ctrl = new ClientPlanSummaryPrintViewController(new ApexPages.StandardController(cp));
		Test.stopTest();
	}
}