objects/Client_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plans</relationshipLabel>
        <relationshipName>ClientPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Plan</label>
    <nameField>
        <displayFormat>PL{00000}</displayFormat>
        <label>Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Client_Plan_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Client_Plan__c</fullName>
        <label>Client Plan</label>
        <referenceTo>Client_Plan__c</referenceTo>
        <relationshipLabel>Client Plan Relationships</relationshipLabel>
        <relationshipName>Client_Plan_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client_Strength__c</fullName>
        <label>Client Strength</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Weak</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5 - Strong</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client Plan Relationships (Contact)</relationshipLabel>
        <relationshipName>Account_Plan_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reports_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reports to</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Account_Plan_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Plan Relationship</label>
    <nameField>
        <displayFormat>APR{00000}</displayFormat>
        <label>Client Plan Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Plan_Relationship_Item__c.object
<CustomObject>
    <fields>
        <fullName>Barclays_Contact_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Barclays Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Client_Plan_Relationship_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Plan_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Plan Relationship</label>
        <referenceTo>Client_Plan_Relationship__c</referenceTo>
        <relationshipLabel>Client Plan Relationship Items</relationshipLabel>
        <relationshipName>Client_Plan_Relationship_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Influence__c</fullName>
        <label>Influence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strength_of_Relationship__c</fullName>
        <label>Strength of Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Introduction required</fullName>
                </value>
                <value>
                    <fullName>Good relationship, met a few times</fullName>
                </value>
                <value>
                    <fullName>Strong relationship, able to influence</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Plan Relationship Item</label>
    <nameField>
        <displayFormat>CPRI{00000}</displayFormat>
        <label>Client Plan Relationship Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Relationship Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClientPlanStakeholdersController.cls
/**
* @Author       Marta Malinowska
* @Company:     Deloitte
* @Description: Controller class for ClientPlanStakeholders VF page.
* @Date:        10/2015
* @ConstructorParam:      None
* @TestClass:   ZZTEST_ClientPlanStakeholdersController
* History
* <Date>      <Authors Name>     <Brief Description of Change>
*------------------------------------------------------------*/
public without sharing class ClientPlanStakeholdersController  extends ClientPlanUtils{

    public String planId;
    
    public Client_Plan__c plan { get; set; }
    
    public Boolean planLoaded {get;set;}

    public String contactId {get;set;}
    
    public Map<Id, Client_Plan_Relationship__c> contactsMap {get;set;}
    
    private List<Client_Plan_Relationship__c> cprsToDelete;

    private List<Client_Plan_Relationship_Item__c> cprisToDelete;

    public ClientPlanStakeholdersController() {
        super(ApexPages.currentPage().getParameters().get('planId'),'planId');
        planId = ApexPages.currentPage().getParameters().get('planId');
        if (!String.isEmpty(planId)) {
            queryPlan();
        } else {
            planLoaded = false;
        }
    }
    
    /**
      * @Author:          Marta Malinowska
      * @Company:         Deloitte
      * @Description:     remove contact and its subordinates from stakeholders hierarchy
      * @param            None
      * @Returns:         PageReference
      * History
      * <Date>      <Authors Name>     <Brief Description of Change>
      *------------------------------------------------------------*/
    public PageReference remove() {
        prepareContactsMap();
        cprsToDelete = new List<Client_Plan_Relationship__c>();
        cprisToDelete = new List<Client_Plan_Relationship_Item__c>();
        if(!contactsMap.containsKey(contactId)){
            return null;
        }
        cprsToDelete.add(contactsMap.get(contactId));
        cprisToDelete.addAll(contactsMap.get(contactId).Client_Plan_Relationship_Items__r);
        removeSubordinates(contactId);
        
        delete cprisToDelete;
        delete cprsToDelete;
        
        return null;
    }
    
    /**
      * @Author:          Marta Malinowska
      * @Company:         Deloitte
      * @Description:     remove contact's subordinates from stakeholders hierarchy
      * @param            Id of Contact
      * @Returns:         None
      * History
      * <Date>      <Authors Name>     <Brief Description of Change>
      *------------------------------------------------------------*/
    private void removeSubordinates(Id contactId) {
        for(Client_Plan_Relationship__c cpr : contactsMap.values()) {
            if(cpr.Reports_to__c == contactId) {
                cprsToDelete.add(contactsMap.get(cpr.Contact__c));
                cprisToDelete.addAll(contactsMap.get(cpr.Contact__c).Client_Plan_Relationship_Items__r);
                removeSubordinates(cpr.Contact__c);
            }
        }
    }
    
    /**
      * @Author:          Marta Malinowska
      * @Company:         Deloitte
      * @Description:     query Client Plan record
      * @param            None
      * @Returns:         None
      * History
      * <Date>      <Authors Name>     <Brief Description of Change>
      *------------------------------------------------------------*/
    private void queryPlan() {
        List<Client_Plan__c> plans = [SELECT Id, Relationship__c FROM Client_Plan__c WHERE Id = :planId];
        
        if (plans.isEmpty()) {
            planLoaded = false;
        } else {
            planLoaded = true;
            plan = plans[0];
        }
    }

    /**
      * @Author:          Marta Malinowska
      * @Company:         Deloitte
      * @Description:     prepare map of Client Plan Relationship
      * @param            None
      * @Returns:         None
      * History
      * <Date>      <Authors Name>     <Brief Description of Change>
      *------------------------------------------------------------*/
    private void prepareContactsMap() {
        contactsMap = new Map<Id, Client_Plan_Relationship__c>();
        for(Client_Plan_Relationship__c cpr : [SELECT Id, Contact__c, Contact__r.Name, Contact__r.Job_Role__c, Reports_To__c, Client_Strength__c,
                                                    (SELECT Id, Barclays_Contact_User__c, Influence__c, Primary_Contact__c, Strength_of_Relationship__c 
                                                    FROM Client_Plan_Relationship_Items__r)
                                                FROM Client_Plan_Relationship__c
                                                WHERE Client_Plan__c = :planId]){
            contactsMap.put(cpr.Contact__c, cpr);
        }
    }

}