objects/Client_Plan__c.object
<CustomObject>
    <fields>
        <fullName>FAIS_Status__c</fullName>
        <label>FAIS Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Applicable</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financial_Year_End__c</fullName>
        <label>Financial Year End</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Review_Date__c</fullName>
        <label>Last Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_Audited_Financial_Statement__c</fullName>
        <description>Date of latest audited financial statement on file</description>
        <label>Latest Audited Financial Statement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plans</relationshipLabel>
        <relationshipName>ClientPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Plan</label>
    <nameField>
        <displayFormat>PL{00000}</displayFormat>
        <label>Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Client_Plan_Facility__c.object
<CustomObject>
    <fields>
        <fullName>Bank__c</fullName>
        <label>Bank</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Level_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Level 3</label>
        <referenceTo>Product_Level_3__c</referenceTo>
        <relationshipLabel>Client Plan Facilities</relationshipLabel>
        <relationshipName>Client_Plan_Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plan Facilities</relationshipLabel>
        <relationshipName>Client_Plan_Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_Of_Facility__c</fullName>
        <label>Type Of Facility</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABSA</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utilisation__c</fullName>
        <label>Utilisation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Client Plan Facility</label>
    <nameField>
        <displayFormat>CPF-{000000}</displayFormat>
        <label>Client Plan  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Client_Plan_Security__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plan Securities</relationshipLabel>
        <relationshipName>Client_Plan_Securities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Security_Description__c</fullName>
        <label>Security Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Client Plan Security</label>
    <nameField>
        <displayFormat>CPS-{0000}</displayFormat>
        <label>Client Plan Security Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Financial_Information__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Generated_by_Operations__c</fullName>
        <label>Cash Generated by Operations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Ratio__c</fullName>
        <label>Current Ratio</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Debt_Equity__c</fullName>
        <label>Debt Equity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EBITDA__c</fullName>
        <label>EBITDA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EBIT__c</fullName>
        <label>EBIT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EPS__c</fullName>
        <label>EPS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Cover_Ratio__c</fullName>
        <label>Interest Cover Ratio</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <description>For unaudited or interim results the month is also specified. Can only be inserted on current year.</description>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <isActive>false</isActive>
                    <label>1</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <isActive>false</isActive>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <isActive>false</isActive>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <isActive>false</isActive>
                    <label>12</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <isActive>false</isActive>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <isActive>false</isActive>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <isActive>false</isActive>
                    <label>4</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <isActive>false</isActive>
                    <label>5</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <isActive>false</isActive>
                    <label>6</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <isActive>false</isActive>
                    <label>7</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <isActive>false</isActive>
                    <label>8</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <isActive>false</isActive>
                    <label>9</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Net_Asset_Value__c</fullName>
        <label>Net Asset Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ROA__c</fullName>
        <label>ROA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ROE__c</fullName>
        <label>ROE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Financial_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Assets__c</fullName>
        <label>Total Assets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Interest_Bearing_Debt__c</fullName>
        <label>Total Interest Bearing Debt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Turnover__c</fullName>
        <label>Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client Plan Financial Information</label>
    <nameField>
        <displayFormat>FI{00000}</displayFormat>
        <label>Financial Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Financial Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Level_3__c.object
<CustomObject>
    <label>Product Level 3</label>
    <nameField>
        <label>Level 3 Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Level 3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ZZTEST_ClientFinancialsController.cls
/**
* @Author:        Marek Cech
* @Company:       Deloitte
* @Description:   Unit Tests for ClientFinancialsController
*                 Tests executed:
*                 1 - testQueryPlan()
*                   Tests querying of client plan
*                 2 - testQueryPlanWithWrongId()
*                   Tests querying of client plan with errors
*                 3 - testSave()
*                   Tests saving
*                 4 - testSaveFinValueErrors()
*                   Tests errors handling of financial info records saving
*                 5 - testSaveFinValueAndQuery()
*                   Tests financial info records saving and querying
*                 6 - testGetFAISOptions()
*                   Tests preparation of FAIS select options
*                 7 - testGetFiscalMonthOptions()
*                   Tests preparation of fiscal year select options
*                 8 - testPrepareTimestampFromDate()
*                   Tests method converting date to timestamp
*                 9 - testErrorMessages()
*                   Tests of methods handling error messaged
*                 10 - testDeleteFinValue()
*                   Test deleting of the financial information
*                 11 - testEditFinInfo()
*                   test editing of all fields in the financial information
*                 12 - test testAddFinInfo()
*                   test adding new finacial information + testing retreiving of actual year data
*                 13 - test testEditFacilityAndQuery()
*                   test editing Absa facility and query them back
*                 14 - testAddFacilityAndQuery()
*                   test adding Absa Facility and querry them back
*				  15 - testDeleteSecurity()
*					test Deleting a security
*				  16 - testDeleteFacility()
*					test Deleting a facility
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* 22.2.2016     Svata Sejkora   Modified and added maethods to test new fucntionalities (edit: testSave, add: testDeleteFinValue, testEditFinInfo, testAddFinInfo, testEditFacilityAndQuery,  testAddFacilityAndQuery)
* ----------------------------------------------------------------------------*/
@isTest
public class ZZTEST_ClientFinancialsController {
    
    @testSetup static void setup() {
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
        ZZTEST_F_Product productFactory = ZZTEST_DataFactoryFacade.product;
        Account acc1 = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);
        Product2 prod = productFactory.getInsertedProduct(ZZTEST_F_Product.ProductRecordType.DEFAULT_PRODUCT, dataContainer);
        
        Client_Plan__c ap = new Client_Plan__c();
        ap.Relationship__c = acc1.Id;
        insert ap;
        
    }
    
    static testMethod void testQueryPlan() {
        Client_Plan__c plan = [SELECT Id FROM Client_Plan__c LIMIT 1];
        
       
        
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        
        System.assertNotEquals(null, ctrl.plan);
        System.assertEquals(plan.Id, ctrl.plan.Id);
        System.assertEquals(true, ctrl.planLoaded);
    }
    
    static testMethod void testQueryPlanWithWrongId() {
        Client_Plan__c plan = [SELECT Id FROM Client_Plan__c LIMIT 1];
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', 'asdfasdf');
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        
        System.assertEquals(null, ctrl.plan);
        System.assertEquals(false, ctrl.planLoaded);
    }
    
    static testMethod void testSave() {
        Client_Plan__c plan = [SELECT Id FROM Client_Plan__c LIMIT 1];
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        ctrl.dateOfLatestAFS = DateTime.now().getTime();
        ctrl.lastReviewDate = DateTime.now().getTime();
        
        PageReference result = ctrl.save();
        System.assertEquals(null, result);
        
        plan = [SELECT Id, Latest_Audited_Financial_Statement__c, Last_Review_Date__c FROM Client_Plan__c LIMIT 1];
        System.assertEquals(Date.today(), plan.Latest_Audited_Financial_Statement__c);
        System.assertEquals(Date.today(), plan.Last_Review_Date__c);
    }
    
    static testMethod void testSaveFinValueErrors() {
        Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];
    
        Financial_Information__c fi = new Financial_Information__c();
        fi.Relationship__c = plan.Relationship__c;
        fi.Year__c = String.valueOf(Date.today().year());
        insert fi;
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        ctrl.recordId = fi.Id;
        ctrl.finFieldName = 'asdf';
        
        PageReference result = ctrl.saveFinValue();
        System.assertEquals(null, result);
        System.assertEquals(Label.errMsg_ErrorDuringSaving, ctrl.getErrorMessage());
    }

    static testMethod void testSaveFinValueAndQuery() {
        Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];
    
        Financial_Information__c fi = new Financial_Information__c();
        fi.Relationship__c = plan.Relationship__c;
        fi.Year__c = String.valueOf(Date.today().year());
        insert fi;
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        ctrl.recordId = fi.Id;
        ctrl.finFieldName = 'Total_Assets__c';
        ctrl.finValue = '250';
        
        PageReference result = ctrl.saveFinValue();
        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
        
        List<Financial_Information__c> fis = [SELECT Id, Total_Assets__c FROM Financial_Information__c];
        System.assertEquals(1, fis.size());
        System.assertEquals(fi.Id, fis[0].Id);
        System.assertEquals(250, fis[0].Total_Assets__c);
    }
    
    static testMethod void testGetFAISOptions() {
        Schema.DescribeFieldResult f = Client_Plan__c.FAIS_Status__c.getDescribe();
        List<Schema.PicklistEntry> p = f.getPicklistValues();
        
        List<SelectOption> expected = new List<SelectOption>();
        for (Schema.PicklistEntry e: p) {
            expected.add(new SelectOption(e.getLabel(), e.getValue()));
        }
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        
        List<SelectOption> result = ctrl.getFAISOptions();
        System.assertNotEquals(null, result);
        System.assertEquals(expected.size(), result.size());
        
        for (Integer i = 0; i < expected.size(); i++) {
            System.assertEquals(expected[i].getLabel(), result[i].getLabel());
            System.assertEquals(expected[i].getValue(), result[i].getValue());
        }
    }
    
    static testMethod void testGetFiscalMonthOptions() {
        Schema.DescribeFieldResult f = Client_Plan__c.Financial_Year_End__c.getDescribe();
        List<Schema.PicklistEntry> p = f.getPicklistValues();
        
        List<SelectOption> expected = new List<SelectOption>();
        for (Schema.PicklistEntry e: p) {
            expected.add(new SelectOption(e.getLabel(), e.getValue()));
        }
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        
        List<SelectOption> result = ctrl.getFiscalMonthOptions();
        System.assertNotEquals(null, result);
        System.assertEquals(expected.size(), result.size());
        
        for (Integer i = 0; i < expected.size(); i++) {
            System.assertEquals(expected[i].getLabel(), result[i].getLabel());
            System.assertEquals(expected[i].getValue(), result[i].getValue());
        }
    }
    
    static testMethod void testPrepareTimestampFromDate() {
        ClientFinancialsController ctrl = new ClientFinancialsController();
        Long result = ctrl.prepareTimestampFromDate(null);
        System.assertEquals(0l, result);
        
        Date today = Date.today();
        Long expected = DateTime.newInstance(today.year(), today.month(), today.day()).getTime();
        result = ctrl.prepareTimestampFromDate(today);
        System.assertEquals(expected, result);
    }
    
    static testMethod void testErrorMessages() {
        Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', 'asdfasdf');
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        
        System.assertEquals(null, ctrl.errorMessage);
        
        String expected = 'This is an error message';
        ctrl.setErrorMessage(expected);
        System.assertEquals(expected, ctrl.errorMessage);
        
        String result = ctrl.getErrorMessage();
        System.assertEquals(expected, result);
        System.assertEquals(null, ctrl.errorMessage);
        
        System.assertEquals(null, ctrl.getErrorMessage());
    }
    
    static testMethod void testDeleteFinValue() {
        Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];
    
        Financial_Information__c fi = new Financial_Information__c();
        fi.Relationship__c = plan.Relationship__c;
        fi.Year__c = String.valueOf(Date.today().year());
        insert fi;
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        ctrl.recordId = fi.Id;
        
        PageReference result = ctrl.deleteFinInfo();
        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
        
        List<Financial_Information__c> fis = [SELECT Id FROM Financial_Information__c];
        System.assertEquals(0, fis.size());
    }
    
    static testMethod void testGetYearOptions() {
        Schema.DescribeFieldResult f = Financial_Information__c.Year__c.getDescribe();
        List<Schema.PicklistEntry> p = f.getPicklistValues();
        
        List<SelectOption> expected = new List<SelectOption>();
        for (Schema.PicklistEntry e: p) {
            expected.add(new SelectOption(e.getLabel(), e.getValue()));
        }
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        
        List<SelectOption> result = ctrl.getYearOptions();
        System.assertNotEquals(null, result);
        System.assertEquals(expected.size(), result.size());
        
        for (Integer i = 0; i < expected.size(); i++) {
            System.assertEquals(expected[i].getLabel(), result[i].getLabel());
            System.assertEquals(expected[i].getValue(), result[i].getValue());
        }
    }
    
    static testMethod void testGetMonthOptions() {
        Schema.DescribeFieldResult f = Financial_Information__c.Month__c.getDescribe();
        List<Schema.PicklistEntry> p = f.getPicklistValues();
        
        List<SelectOption> expected = new List<SelectOption>();
        for (Schema.PicklistEntry e: p) {
            expected.add(new SelectOption(e.getLabel(), e.getValue()));
        }
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        
        List<SelectOption> result = ctrl.getMonthOptions();
        System.assertNotEquals(null, result);
        System.assertEquals(expected.size(), result.size());
        
        for (Integer i = 0; i < expected.size(); i++) {
            System.assertEquals(expected[i].getLabel(), result[i].getLabel());
            System.assertEquals(expected[i].getValue(), result[i].getValue());
        }
    }
    
    static testMethod void testEditFinInfo() {
        Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];
    
        Financial_Information__c fi = new Financial_Information__c();
        fi.Relationship__c = plan.Relationship__c;
        fi.Year__c = String.valueOf(Date.today().year());
        insert fi;
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        ctrl.recordId = fi.Id;
        ctrl.yearValue = String.valueOf(Date.today().year());
        ctrl.netAssetValue = 23000000;
        ctrl.turnover = 23000000;
        ctrl.totalAssets = 50000000;
        //ctrl.interestBearingDebt = 456000;
        ctrl.cashGenByOperations = 566700;
        ctrl.ebitda = 23333333;
        ctrl.ebit = 2333333;
        ctrl.roe = 23;
        ctrl.roa = 23;
        ctrl.debtEquity = 7890987;
        ctrl.currentRatio = '1:1';
        ctrl.eps = 80000;
        ctrl.interestCoverRatio = '2:2';
        
        PageReference result = ctrl.modifyYear();
        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
              
        List<Financial_Information__c> fis = [SELECT Id, Total_Assets__c, Net_Asset_Value__c, Turnover__c, Total_Interest_Bearing_Debt__c, Cash_Generated_by_Operations__c, EBITDA__c,
                                                EBIT__c, ROE__c, ROA__c, Debt_Equity__c, Current_Ratio__c, EPS__c, Interest_Cover_Ratio__c
                                              FROM Financial_Information__c];

        System.assertEquals(1, fis.size());
        System.assertEquals(fi.Id, fis[0].Id);
        System.assertEquals(50000000, fis[0].Total_Assets__c);
        System.assertEquals(23000000, fis[0].Net_Asset_Value__c);
        System.assertEquals(23000000, fis[0].Turnover__c);
        System.assertEquals(566700, fis[0].Cash_Generated_by_Operations__c);
        System.assertEquals(23333333, fis[0].EBITDA__c);
        System.assertEquals(2333333, fis[0].EBIT__c);
        System.assertEquals(23, fis[0].ROE__c);
        System.assertEquals(23, fis[0].ROA__c);
        System.assertEquals(7890987, fis[0].Debt_Equity__c);
        System.assertEquals('1:1', fis[0].Current_Ratio__c);
        System.assertEquals(80000, fis[0].EPS__c);
        System.assertEquals('2:2', fis[0].Interest_Cover_Ratio__c);
    }
    
    static testMethod void testAddFinInfo() {
        Client_Plan__c plan = [SELECT Id FROM Client_Plan__c LIMIT 1];
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        ctrl.recordId = '';
        ctrl.yearValue = String.valueOf(Date.today().year());
        ctrl.netAssetValue = 23000000;
        ctrl.turnover = 23000000;
        ctrl.totalAssets = 50000000;
        //ctrl.interestBearingDebt = 456000;
        ctrl.cashGenByOperations = 566700;
        ctrl.ebitda = 23333333;
        ctrl.ebit = 2333333;
        ctrl.roe = 23;
        ctrl.roa = 23;
        ctrl.debtEquity = 7890987;
        ctrl.currentRatio = '1:1';
        ctrl.eps = 80000;
        ctrl.interestCoverRatio = '2:2';

        
        PageReference result = ctrl.modifyYear();       
        String existingYear = ctrl.getExistingYearOptions();        

        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
        
        List<Financial_Information__c> fis = [SELECT Id, Total_Assets__c, Net_Asset_Value__c, Turnover__c, Total_Interest_Bearing_Debt__c, Cash_Generated_by_Operations__c, EBITDA__c,
                                                EBIT__c, ROE__c, ROA__c, Debt_Equity__c, Current_Ratio__c, EPS__c, Interest_Cover_Ratio__c
                                              FROM Financial_Information__c];

        System.assertEquals(1, fis.size());
        System.assertEquals(50000000, fis[0].Total_Assets__c);
        System.assertEquals(23000000, fis[0].Net_Asset_Value__c);
        System.assertEquals(23000000, fis[0].Turnover__c);
        System.assertEquals(566700, fis[0].Cash_Generated_by_Operations__c);
        System.assertEquals(23333333, fis[0].EBITDA__c);
        System.assertEquals(2333333, fis[0].EBIT__c);
        System.assertEquals(23, fis[0].ROE__c);
        System.assertEquals(23, fis[0].ROA__c);
        System.assertEquals(7890987, fis[0].Debt_Equity__c);
        System.assertEquals('1:1', fis[0].Current_Ratio__c);
        System.assertEquals(80000, fis[0].EPS__c);
        System.assertEquals('2:2', fis[0].Interest_Cover_Ratio__c);

        List<String> years = (List<String>)JSON.deserialize(existingYear, List<String>.Class);

        System.assertEquals(years[0], String.valueOf(Date.today().year()));
    }
    
    static testMethod void testEditFacilityAndQuery() {
        Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];

        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_Product_Level_3 productLvl3Factory = ZZTEST_DataFactoryFacade.productLvl3;
        Product_Level_3__c productLvl31 = productLvl3Factory.getInsertedProduct(ZZTEST_F_Product_Level_3.ProductLevel3RecordType.DEFAULT_PRODUCT, 
            dataContainer);
    
        Client_Plan_Facility__c fac = new Client_Plan_Facility__c();
            fac.Relationship__c = plan.Relationship__c;
            fac.Type_Of_Facility__c = 'ABSA';
        insert fac;
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();

        ctrl.facilityId = fac.Id;
        ctrl.bank = '';
        ctrl.utilisation = 345000000;
        ctrl.productLvl3 = productLvl31.Id;
        ctrl.facLimit = 200000000;

        PageReference result = ctrl.modifyFacility();
        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
        
        List<Client_Plan_Facility__c> faci = [
            SELECT Id, Type_Of_Facility__c, Bank__c, Utilisation__c, Product_Level_3__c, Limit__c 
            FROM Client_Plan_Facility__c
        ];

        System.assertEquals(1, faci.size());
        System.assertEquals('ABSA', faci[0].Type_Of_Facility__c);
        System.assertEquals(null, faci[0].Bank__c);
        System.assertEquals(345000000, faci[0].Utilisation__c);
        System.assertEquals(productLvl31.Id, faci[0].Product_Level_3__c);
        System.assertEquals(200000000, faci[0].Limit__c);
    }

    static testMethod void testAddFacilityAndQuery() {
        Client_Plan__c plan = [SELECT Id FROM Client_Plan__c LIMIT 1];

        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_Product_Level_3 productLvl3Factory = ZZTEST_DataFactoryFacade.productLvl3;
        Product_Level_3__c productLvl31 = productLvl3Factory.getInsertedProduct(ZZTEST_F_Product_Level_3.ProductLevel3RecordType.DEFAULT_PRODUCT, 
            dataContainer);
          
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();

        ctrl.facType = 'ABSA';
        ctrl.bank = '';
        ctrl.utilisation = 345000000;
        ctrl.productLvl3 = productLvl31.Id;
        ctrl.facLimit = 200000000;

        PageReference result = ctrl.modifyFacility();
        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
        
        List<Client_Plan_Facility__c> faci = [
            SELECT Id, Type_Of_Facility__c, Bank__c, Utilisation__c, Product_Level_3__c, Limit__c 
            FROM Client_Plan_Facility__c
        ];

        System.assertEquals(1, faci.size());
        System.assertEquals('ABSA', faci[0].Type_Of_Facility__c);
        System.assertEquals(null, faci[0].Bank__c);
        System.assertEquals(345000000, faci[0].Utilisation__c);
        System.assertEquals(productLvl31.Id, faci[0].Product_Level_3__c);
        System.assertEquals(200000000, faci[0].Limit__c);
    }

    static testMethod void testEditSecurityAndQuery() {
        Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];
    
        Client_Plan_Security__c sec = new Client_Plan_Security__c();
            sec.Relationship__c = plan.Relationship__c;
            sec.Security_Description__c = 'Wub WUb';
            sec.Value__c = 200000;
        insert sec;
        
        PageReference pr = Page.ClientFinancials;
            pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();

            ctrl.absaSecId = sec.Id;
            ctrl.value = 345000000;
            ctrl.clientSecurity = 'Wub WUb';

            PageReference result = ctrl.modifySecurity();
        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
        
        List<Client_Plan_Security__c> seci = [SELECT Id, Security_Description__c, Value__c FROM Client_Plan_Security__c];

        System.assertEquals(1, seci.size());
        System.assertEquals('Wub WUb', seci[0].Security_Description__c);
        System.assertEquals(345000000, seci[0].Value__c);
    }

    static testMethod void testAddSecurityAndQuery() {
        Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];

        Client_Plan_Security__c clientPlanSecurity = new Client_Plan_Security__c(Relationship__c = plan.Relationship__c,
                                                                                 Security_Description__c='jabababa',
                                                                                 value__c=345000000);
        insert clientPlanSecurity;
        
        Client_Plan_Security__c clientPlanSecurity2 = new Client_Plan_Security__c(Relationship__c = plan.Relationship__c,
                                                                                 Security_Description__c='jabababa',
                                                                                 value__c=345000000);
        insert clientPlanSecurity2;
        
        PageReference pr = Page.ClientFinancials;
            pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        
            ctrl.value = 345000000;
            ctrl.clientSecurity = 'jabababa';

            PageReference result = ctrl.modifySecurity();
        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
        
        List<Client_Plan_Security__c> seci = [SELECT Id, Security_Description__c, Value__c FROM Client_Plan_Security__c];

        System.assertEquals(3, seci.size());
        System.assertEquals('jabababa', seci[0].Security_Description__c);
        System.assertEquals(345000000, seci[0].Value__c);
    }
    
    static testMethod void testDeleteSecurity() {
        Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];
    
        Client_Plan_Security__c sec = new Client_Plan_Security__c();
        sec.Relationship__c = plan.Relationship__c;
        sec.Security_Description__c = 'Wub WUb';
        sec.Value__c = 200000;
        insert sec;
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        ctrl.absaSecId = sec.Id;
        
        List<Client_Plan_Security__c> cps = [SELECT Id FROM Client_Plan_Security__c];
        System.assertEquals(1, cps.size());
        
        PageReference result = ctrl.deleteSecurity();
        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
        
        cps = [SELECT Id FROM Client_Plan_Security__c];
        System.assertEquals(0, cps.size());
    }
    
    static testMethod void testDeleteFacility() {
		Client_Plan__c plan = [SELECT Id, Relationship__c FROM Client_Plan__c LIMIT 1];
    
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_Product_Level_3 productLvl3Factory = ZZTEST_DataFactoryFacade.productLvl3;
        Product_Level_3__c productLvl31 = productLvl3Factory.getInsertedProduct(ZZTEST_F_Product_Level_3.ProductLevel3RecordType.DEFAULT_PRODUCT, 
            dataContainer);
        
        Client_Plan_Facility__c facility = new Client_Plan_Facility__c();
        facility.Type_Of_Facility__c = 'OTHER';
        facility.Relationship__c = plan.Relationship__c;
        facility.Bank__c = 'Test Bank';
        facility.Country__c = 'South Africa';
        facility.Product_Level_3__c = productLvl31.Id;
        facility.Limit__c = 123456;
        insert facility;
        
        PageReference pr = Page.ClientFinancials;
        pr.getParameters().put('planId', plan.Id);
        Test.setCurrentPage(pr);
        
        ClientFinancialsController ctrl = new ClientFinancialsController();
        ctrl.facilityId = facility.Id;
        
        List<Client_Plan_Facility__c> cpf = [SELECT Id FROM Client_Plan_Facility__c];
        System.assertEquals(1, cpf.size());
        
        PageReference result = ctrl.deleteFacility();
        System.assertEquals(null, result);
        System.assertEquals(null, ctrl.getErrorMessage());
        
        cpf = [SELECT Id FROM Client_Plan_Facility__c];
        System.assertEquals(0, cpf.size());    
    }
}