objects/Client_Plan_Relationship__c.object
<CustomObject>
    <label>Client Plan Relationship</label>
    <nameField>
        <displayFormat>APR{00000}</displayFormat>
        <label>Client Plan Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Client_Plan_Relationship_Item__c.object
<CustomObject>
    <fields>
        <fullName>Barclays_Contact_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Barclays Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Client_Plan_Relationship_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Plan_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Plan Relationship</label>
        <referenceTo>Client_Plan_Relationship__c</referenceTo>
        <relationshipLabel>Client Plan Relationship Items</relationshipLabel>
        <relationshipName>Client_Plan_Relationship_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>Client Plan Relationship Item</label>
    <nameField>
        <displayFormat>CPRI{00000}</displayFormat>
        <label>Client Plan Relationship Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plan Relationship Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClientPlanRelationshipItemTrigger_Helper.cls
/**
* @Author       Marek Cech
* @Company:     Deloitte
* @Description: Helper class for ClientPlanRelationshipItemTrigger
* @Date:        10/2015
* @ConstructorParam:      None
* @TestClass:   ZZTEST_ClientPlanRelatItemTrigger_Helper
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* 2018-02-06  Dino Scarcella	 Check if contact has duplicate Barclays Contacts
*------------------------------------------------------------*/
public class ClientPlanRelationshipItemTrigger_Helper {

    /**
      * @Author:          Marek Cech
      * @Company:         Deloitte
      * @Description:     checks if every contact has only one barclays contact marked as primary
      * @Params:          newList
      * @Returns:         void
      * History
      * <Date>      <Authors Name>     <Brief Description of Change>
      *------------------------------------------------------------*/
    public static void checkPrimaryUniqueness(List<Client_Plan_Relationship_Item__c> newList) {
        
        Set<Id> relIds = new Set<Id>();
        Set<Id> itemIds = new Set<Id>();
        for (Client_Plan_Relationship_Item__c i: newList) {
            relIds.add(i.Client_Plan_Relationship__c);
            itemIds.add(i.Id);
        }
        
        List<Client_Plan_Relationship_Item__c> existingItems = [
                SELECT Id, Primary_Contact__c, Client_Plan_Relationship__c, Barclays_Contact_User__c
                FROM Client_Plan_Relationship_Item__c
                WHERE Client_Plan_Relationship__c IN :relIds AND Id NOT IN :itemIds];
                
        //key = relationship id
        //value = primary item
        Map<Id, Client_Plan_Relationship_Item__c> primaryItems = new Map<Id, Client_Plan_Relationship_Item__c>();
        Map<String, Client_Plan_Relationship_Item__c> uniqueContactItems = new Map<String, Client_Plan_Relationship_Item__c>();
        
        for (Client_Plan_Relationship_Item__c i: existingItems) {
            if (i.Primary_Contact__c) {
                primaryItems.put(i.Client_Plan_Relationship__c, i);
            }
            if (i.Client_Plan_Relationship__c != NULL 
                && i.Barclays_Contact_User__c != NULL
                && !uniqueContactItems.containsKey(String.valueOf(i.Client_Plan_Relationship__c)+String.valueOf(i.Barclays_Contact_User__c))) {
            	uniqueContactItems.put(String.valueOf(i.Client_Plan_Relationship__c)+String.valueOf(i.Barclays_Contact_User__c), i);   
            }
        }
        
        for (Client_Plan_Relationship_Item__c i: newList) {
            // Check Primary Uniqueness
            if (i.Primary_Contact__c) { 
                if (!primaryItems.containsKey(i.Client_Plan_Relationship__c)) {
                    primaryItems.put(i.Client_Plan_Relationship__c, i);
                } else {
                    i.Primary_Contact__c.addError(Label.errMsg_OneContactMax);
                }
            }
            // Check Unique Barclays Contact per Contact
            if (
                i.Client_Plan_Relationship__c != NULL 
                && i.Barclays_Contact_User__c != NULL 
                && !uniqueContactItems.containsKey(String.valueOf(i.Client_Plan_Relationship__c)+String.valueOf(i.Barclays_Contact_User__c))
               ) 
            {
            		uniqueContactItems.put(String.valueOf(i.Client_Plan_Relationship__c)+String.valueOf(i.Barclays_Contact_User__c), i);
            } else if (
                i.Client_Plan_Relationship__c != NULL 
                && i.Barclays_Contact_User__c != NULL 
                && uniqueContactItems.containsKey(String.valueOf(i.Client_Plan_Relationship__c)+String.valueOf(i.Barclays_Contact_User__c))
               ) 
            {
            	i.Barclays_Contact_User__c.addError(Label.errMsg_SameContact); 
            }
        }
    }
}