objects/Client_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Plans</relationshipLabel>
        <relationshipName>ClientPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Plan</label>
    <nameField>
        <displayFormat>PL{00000}</displayFormat>
        <label>Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Client_Plan_Strategy__c.object
<CustomObject>
    <fields>
        <fullName>Client_Plan__c</fullName>
        <label>Client Plan</label>
        <referenceTo>Client_Plan__c</referenceTo>
        <relationshipLabel>Client Plan Strategies</relationshipLabel>
        <relationshipName>Client_Plan_Strategies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Plan Strategy</label>
    <nameField>
        <label>Client Plan Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Plan Strategies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Plan_Strategy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Plan Strategy</label>
        <referenceTo>Client_Plan_Strategy__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Potential_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Client_Plan_Strategy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Plan Strategy</label>
        <referenceTo>Client_Plan_Strategy__c</referenceTo>
        <relationshipName>Unqualified_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Plan__c</fullName>
        <label>Client Plan</label>
        <referenceTo>Client_Plan__c</referenceTo>
        <relationshipName>Unqualified_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date (Expected Revenue Flow Start)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsConverted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsConverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Unqualified_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <label>Probability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Potential Opportunity Identified</fullName>
                    <default>true</default>
                    <label>Potential Opportunity Identified</label>
                </value>
                <value>
                    <fullName>Potential Opportunity Engaged</fullName>
                </value>
                <value>
                    <fullName>Potential Opportunity Convert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cross Sell</fullName>
                </value>
                <value>
                    <fullName>New to Bank</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Potential Opportunity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potential Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClientPlanUtilsMobile.cls
/**
* @Author       Marek Cech
* @Company:     Deloitte
* @Description: Util class for mobile version of client plan
* @Date:        03/2016
* @ConstructorParam:      None
* @TestClass:   ZZTEST_ClientPlanUtilsMobile
* History
* <Date>      <Authors Name>     <Brief Description of Change>
*------------------------------------------------------------*/
public class ClientPlanUtilsMobile {

  /**
      * @Author:          Marek Cech
      * @Company:         Deloitte
      * @Description:     converts potential opportunity to opportunity
      * @Params:          String optyId - Id of potential opportunity to convert
      * @Returns:         Boolean - true if an error occured, false otherwise
      * History
      * <Date>      <Authors Name>     <Brief Description of Change>
      *------------------------------------------------------------*/
  public static Boolean convertUnqOpty(String optyId) {

    List<Potential_Opportunity__c> optys = [
      SELECT Id, Client_Plan__r.Relationship__c, Name, Close_Date__c, Product__c, Stage__c, Probability__c, 
        Type__c, Client_Plan_Strategy__c
            FROM Potential_Opportunity__c
            WHERE Id = :optyId
        ];

        if (optys.isEmpty()) {
          return true;
        }

        Potential_Opportunity__c uo = optys[0];

        Boolean isConvertible = checkUnqOptyConvertibility(uo);
        if (!isConvertible) {
            return true;
        }

        Opportunity opp = new Opportunity();
        opp.Name = uo.Name;
        opp.CloseDate = uo.Close_Date__c;
        opp.Type = uo.Type__c;
        opp.StageName = 'Opportunity Identified';
        opp.AccountId = uo.Client_Plan__r.Relationship__c;
        opp.Client_Plan_Strategy__c = uo.Client_Plan_Strategy__c;

        Savepoint sp = Database.setSavepoint();
        try {
            insert opp;
        } catch (DmlException e) {
            System.debug(e);
            return true;
        }

        uo.IsConverted__c = true;
        uo.Opportunity__c = opp.Id;
        try {
            update uo;
        } catch (DmlException e) {
            System.debug(e);
            Database.rollback(sp);
            return true;
        }

        return false;
  }

  /**
      * @Author:          Marek Cech
      * @Company:         Deloitte
      * @Description:     tests whether potential opportunity in param can be converted
      * @Params:          Potential_Opportunity__c uo - opportunity to be tested
      * @Returns:         Boolean - true if opty can be converted, false otherwise
      * History
      * <Date>      <Authors Name>     <Brief Description of Change>
      *------------------------------------------------------------*/
  @testVisible
    private static Boolean checkUnqOptyConvertibility(Potential_Opportunity__c uo) {
        if (uo.Name == null || uo.Name == '') {
            return false;
        } else if (uo.Close_Date__c == null) {
            return false;
        } else {
            return true;
        }
    }

}