objects/Client_On_Boarding__c.object
<CustomObject>
    <fields>
        <fullName>Case_Category__c</fullName>
        <label>Case Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>DAY 1 TEMPLATE</fullName>
                </value>
                <value>
                    <fullName>Exemption 4</fullName>
                </value>
                <value>
                    <fullName>Client Introductory Certificate (CIC)</fullName>
                </value>
                <value>
                    <fullName>Syndicated Loan</fullName>
                </value>
                <value>
                    <fullName>Group Introductory Certificate</fullName>
                </value>
                <value>
                    <fullName>New Product</fullName>
                </value>
                <value>
                    <fullName>Additional product</fullName>
                </value>
                <value>
                    <fullName>Refresh FICA documents/ Trigger event</fullName>
                </value>
                <value>
                    <fullName>Closure of account</fullName>
                </value>
                <value>
                    <fullName>Migration in</fullName>
                </value>
                <value>
                    <fullName>Migration out</fullName>
                </value>
                <value>
                    <fullName>Update Resolution</fullName>
                </value>
                <value>
                    <fullName>Update Product mandate</fullName>
                </value>
                <value>
                    <fullName>Annual Refresh</fullName>
                </value>
                <value>
                    <fullName>PEP</fullName>
                </value>
                <value>
                    <fullName>Entire Relationship</fullName>
                </value>
                <value>
                    <fullName>An Account Keep Relationship</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The contact person that will be handing the on-boarding process</inlineHelpText>
        <label>Client Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Client On-Boarding</relationshipLabel>
        <relationshipName>Client_On_Boarding</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Relationship Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client On-Boarding (Relationship Name)</relationshipLabel>
        <relationshipName>Client_On_Boarding</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsible_Department__c</fullName>
        <label>Responsible Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New to Bank</fullName>
                    <default>true</default>
                    <label>New to Bank</label>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>Mandates</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New to bank on-boarding (NTB)</fullName>
                    <default>true</default>
                    <label>New to bank on-boarding (NTB)</label>
                </value>
                <value>
                    <fullName>Existing Client</fullName>
                </value>
                <value>
                    <fullName>Migration</fullName>
                </value>
                <value>
                    <fullName>Exit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Client On-Boarding</label>
    <nameField>
        <displayFormat>ONB{00000}</displayFormat>
        <label>On-Boarding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client On-Boarding</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Day_1_Template__c.object
<CustomObject>
    <description>Day 1 Template</description>
    <fields>
        <fullName>Client_On_Boarding__c</fullName>
        <label>Client On-Boarding</label>
        <referenceTo>Client_On_Boarding__c</referenceTo>
        <relationshipLabel>Day 1 Templates</relationshipLabel>
        <relationshipName>Day_1_Templates</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Legal_Entity__c</fullName>
        <label>Primary Legal Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Day 1 Templates</relationshipLabel>
        <relationshipName>Day_1_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Day 1 Template</label>
    <nameField>
        <displayFormat>D1T{00000}</displayFormat>
        <label>Day 1 Template Account</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Day 1 Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Day_1_TemplateCS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>SendToGroupAddress__c</fullName>
        <label>SendToGroupAddress</label>
        <type>Email</type>
    </fields>
    <label>Day 1 Template CS</label>
</CustomObject>

classes/ZZTEST_Day1Template.cls
/**
* @author Deloitte
* @date 2015
*
* @group Unit Tests
*
* @description Unit Tests - Day1Template 
*
*	12-May-2016 - Mohsin Wadee - US-1089 - in getSampleDay1Template() method had to specify a Client On Boarding object for the test Day 1
*											Template being created.
*/
@isTest
public class ZZTEST_Day1Template {
	
	@isTest static void testSendDay1Template() 
	{
        User user1 = [Select ID from user where id =:userInfo.getUserId()];
        
        System.runAs(user1)
        {
		Day_1_Template__c day1 = ZZTEST_Day1Template.getSampleDay1Template();
		ZZTEST_Day1Template.setUpCustomSettings();
		ZZTEST_Day1Template.attachGStoDay1Template(day1);

		ApexPages.StandardController sc = new ApexPages.StandardController(day1);
		PageReference SendDay1Template = Page.SendDay1Template;
        ApexPages.currentPage().getParameters().put('id',day1.id);
        Test.setCurrentPage(SendDay1Template);

        SendDay1TemplateEmail sendController = new SendDay1TemplateEmail(sc);

        sendController.sendDay1TemplateAsEmail();
        }
	}

	@isTest static void testSendDay1TemplateTestErrors() 
	{
        User user1 = [Select ID from user where id =:userInfo.getUserId()];
        
        System.runAs(user1)
        {
            Day_1_Template__c day1 = ZZTEST_Day1Template.getSampleDay1Template();
            ZZTEST_Day1Template.setUpCustomSettings();
            ZZTEST_Day1Template.attachGStoDay1TemplateErrors(day1);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(day1);
            PageReference SendDay1Template = Page.SendDay1Template;
            ApexPages.currentPage().getParameters().put('id',day1.id);
            Test.setCurrentPage(SendDay1Template);
            
            SendDay1TemplateEmail sendController = new SendDay1TemplateEmail(sc);
            sendController.sendDay1TemplateAsEmail();
        }
		
	}

	private static Day_1_Template__c getSampleDay1Template()
	{
        // Create data container.
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        
        // Create test account.
        ZZTEST_F_Account accountFactory = ZZTEST_DataFactoryFacade.account;
        Account acc = accountFactory.getInsertedProduct(ZZTEST_F_Account.AccountRecordType.DEFAULT_ACCOUNT, dataContainer);
        
        // Create test contact.
        ZZTEST_F_Contact contactFactory = ZZTEST_DataFactoryFacade.contact;
    	Contact con = contactFactory.getInsertedProduct(ZZTEST_F_Contact.ContactRecordType.DEFAULT_CONTACT, dataContainer);
        
        // Create test Client On-Boarding.
        Client_On_Boarding__c clientOnBoarding = new Client_On_Boarding__c();
        clientOnBoarding.Client_Contact__c = con.Id;
        clientOnBoarding.Responsible_Department__c = 'New to Bank';
        clientOnBoarding.Priority__c = 'High';
        clientOnBoarding.Type__c = 'New to bank on-boarding (NTB)';
        clientOnBoarding.Case_Category__c = 'DAY 1 TEMPLATE';
        clientOnBoarding.Subject__c = 'Day 1 Template Test Client On-Boarding';
        clientOnBoarding.Relationship_Name__c = acc.Id;
        insert clientOnBoarding;
        
		Day_1_Template__c day1 = new Day_1_Template__c();
        day1.Client_On_Boarding__c = clientOnBoarding.Id;
		
        day1.Primary_Legal_Entity__c = acc.Id;
        try {
			insert day1;
		} catch(Exception e)
		{
			System.debug('XXXXXXXXXXXXXX day1 template sample insert failed ' + e.getMessage());
		}
		return day1;
	}

	private static void attachGStoDay1TemplateErrors(Day_1_Template__c day1)
	{
		ApexPages.StandardController sc = new ApexPages.StandardController(day1);
		PageReference Day1TemplateGSAtt = Page.Day1TemplateGSAtt;
        ApexPages.currentPage().getParameters().put('id',day1.id);

        Day1TemplateGSAttController day1AttController = new Day1TemplateGSAttController(sc);
        day1AttController.fileBody = null; //Blob.valueOf('UNIT.TEST');
        day1AttController.fileName = '';
        day1AttController.processUpload();
        day1AttController.back();
	}

	private static void attachGStoDay1Template(Day_1_Template__c day1)
	{
		ApexPages.StandardController sc = new ApexPages.StandardController(day1);
		PageReference Day1TemplateGSAtt = Page.Day1TemplateGSAtt;
        ApexPages.currentPage().getParameters().put('id',day1.id);

        Day1TemplateGSAttController day1AttController = new Day1TemplateGSAttController(sc);
        day1AttController.fileBody = Blob.valueOf('UNIT.TEST');
        day1AttController.fileName = 'UNITTEST';
        day1AttController.processUpload();
	}

	private static void setUpCustomSettings()
	{
		Day_1_TemplateCS__c c = new Day_1_TemplateCS__c();
		c.Name = 'SendToGroupAddress';
        c.SendToGroupAddress__c = 'jcicharski@deloittece.com';
        try {
			insert c;
		} catch(Exception e)
		{
			System.debug('XXXXXXXXXXXXXX custom settings insert for day1template (email address) failed: ' + e.getMessage());
		}
	}
}