objects/Collateral_Monitoring__c.object
<CustomObject>
    <customHelpPage>Collateral_Management</customHelpPage>
    <fields>
        <fullName>Days__c</fullName>
        <label>Days</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Days Before</fullName>
                </value>
                <value>
                    <fullName>Days After</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Once Off</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Bi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Days__c</fullName>
        <label>Number of Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Relative_Date__c</fullName>
        <label>Other Relative Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relative_Date__c</fullName>
        <label>Relative Date</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Effective Date</fullName>
                </value>
                <value>
                    <fullName>Signature Date</fullName>
                </value>
                <value>
                    <fullName>Financial Year End</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Collateral Monitoring</label>
    <nameField>
        <label>Collateral Monitoring Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Monitoring</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Collateral_Monitoring_Helper_Test.cls
/**
*** CHANGE LOG ***

29/11/2017 - TdB    - Created Class.

**/ 
@isTest(SeeAllData=false)
public class Collateral_Monitoring_Helper_Test 
{
    public static testMethod void testClass()
	{
        Date todaysDate = System.today();
        List<Collateral_Monitoring__c> collateralMonitoringList = new List<Collateral_Monitoring__c>();
        //Test Data
		Cloudsmiths_TestDataClass  testDataClass = new Cloudsmiths_TestDataClass();
        
        collateralMonitoringList.add(testDataClass.testCollateralMonitoring);
        
        test.startTest();
        
        testDataClass.testCollateralMonitoring.Frequency__c = 'Once Off';
        testDataClass.testCollateralMonitoring.Due_Date__c = todaysDate.addDays(100);
        
        update testDataClass.testCollateralMonitoring;
        
        testDataClass.testCollateralMonitoring.Frequency__c = 'Monthly';
        testDataClass.testCollateralMonitoring.Relative_Date__c = 'Other';
        testDataClass.testCollateralMonitoring.Number_Of_Days__c = 5;
        testDataClass.testCollateralMonitoring.Days__c = 'Days After';
        testDataClass.testCollateralMonitoring.Other_Relative_Date__c = todaysDate.addDays(50);
        testDataClass.testCollateralMonitoring.Due_Date__c = null;
        
        update testDataClass.testCollateralMonitoring;
        
        testDataClass.TestAgreement.Termination_Date__c = todaysDate.addYears(5) ;       
        update testDataClass.TestAgreement;
        
        Collateral_Monitoring_Helper.insertWatcherOccurence(collateralMonitoringList);
        
        test.stopTest();
    }

}