objects/Condition__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this condition is active and in a state when the condition occurrences can be generated.</description>
        <inlineHelpText>Indicates if this condition is active and in a state when the condition occurrences can be generated.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Forced_Update__c</fullName>
        <label>Forced Update</label>
        <type>DateTime</type>
    </fields>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Condition_Occurrence__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Condition Party</label>
        <referenceTo>Condition_Party__c</referenceTo>
        <relationshipLabel>Condition Occurrences</relationshipLabel>
        <relationshipName>Condition_Occurrences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <referenceTo>Condition__c</referenceTo>
        <relationshipName>Conditions_Due</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Condition Occurrence</label>
    <nameField>
        <label>Condition Occurrence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Occurrences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Condition_Party__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <referenceTo>Condition__c</referenceTo>
        <relationshipLabel>Condition Parties</relationshipLabel>
        <relationshipName>Condition_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Condition Party</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condition Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Condition_Party_Helper.cls
/**
_____ _                 _ _____           _ _   _         
/  __ \ |               | /  ___|         (_) | | |        
| /  \/ | ___  _   _  __| \ `--. _ __ ___  _| |_| |__  ___ 
| |   | |/ _ \| | | |/ _` |`--. \ '_ ` _ \| | __| '_ \/ __|
| \__/\ | (_) | |_| | (_| /\__/ / | | | | | | |_| | | \__ \
\____/_|\___/ \__,_|\__,_\____/|_| |_| |_|_|\__|_| |_|___/

 *** CHANGE LOG ***

 14/09/2017 - PG    - Created Class.
 18/08/2017 - PG 	- Added the "Before" & "After" delete logic. 
 10/10/2017 - PG 	- Removed "before delete" logic.
 					- Refactored and combined all into "updateSchedulingParties" method.

**/
public class Condition_Party_Helper 
{	
	/**
    * Variables
    **/
    public static final Map<String, RecordTypeInfo> occurrenceTypes = new Map<String, RecordTypeInfo>(Condition_Occurrence__c.sObjectType.getDescribe().getRecordTypeInfosByName());

	//After insert trigger handler.
	public static void afterInsert(List<Condition_Party__c> inputNewList)
	{
		System.debug('### Condition_Party_Helper : afterInsert');

		updateSchedulingParties(inputNewList);

		//addPartyOccurrences(inputNewList); 
	}

	//After delete trigger handler.
	public static void afterDelete(List<Condition_Party__c> inputOldList)
	{
		System.debug('### Condition_Party_Helper : afterDelete');

		updateSchedulingParties(inputOldList);

		//removePartyOccurrences(inputOldList);  
	}

	public static void updateSchedulingParties(List<Condition_Party__c> inputList)
	{
		//Blank vars.
		Set<Id> conditionIds = new Set<Id>();
		List<Condition__c> conditions = new List<Condition__c>();

		//Loop over condition parties.
		for(Condition_Party__c conditionParty : inputList)
		{
			conditionIds.add(conditionParty.Condition__c);
		}

		//Query condition records.
		conditions = [
			SELECT
				Id,
				Forced_Update__c,
				Active__c
			FROM Condition__c
			WHERE 
				Id IN :conditionIds 
				AND Active__c = true
		];

		//Set update on conditions.
		for(Condition__c condition : conditions)
		{
			condition.Forced_Update__c = DateTime.now();
		}

		//update records to reschedule with new parties.
		update conditions;
	}
}