objects/CSC_Exception_Audit_Trail__c.object
<CustomObject>
    <description>CloudSmiths - RN
The object stores all Apex handled exceptions if the developer explicitly handles and logs exceptions within his code.</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer_Notes__c</fullName>
        <label>Developer Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exception_DateTime__c</fullName>
        <label>Exception DateTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <label>Exception Message</label>
        <length>131000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <inlineHelpText>LIne number in the code where the exception occured</inlineHelpText>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Resolution Pending</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Ignore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSC Exception Audit Trail</label>
    <nameField>
        <displayFormat>AUDITLOG{0000000}</displayFormat>
        <label>CSC Error Logging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSC Exception Audit Trail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CSC_AuditTrailLog.cls
/**
* Date   : 13-08-2016
* Author : RN - CloudSmiths
* Desc   : Write exception into a custom object
**/
public class CSC_AuditTrailLog {

    public static CSC_Exception_Audit_Trail__c auditTrail;
    
    public static void logException(Exception e, String status, String severity, String classname, String method, String devnote){
			
        	auditTrail = new CSC_Exception_Audit_Trail__c();	
        	auditTrail.Severity__c = severity;
            auditTrail.Status__c = status;
			auditTrail.Class_Name__c = classname;
            auditTrail.Exception_DateTime__c = System.now();
            auditTrail.Exception_Message__c = e.GetMessage();
            auditTrail.Method_Name__c = method;
            auditTrail.Line_Number__c = e.getLineNumber();
            auditTrail.Stack_Trace__c = e.getStackTraceString();
            auditTrail.Developer_Notes__c = devnote;

            try{
            	insert auditTrail;
                System.debug('Error was logged in the CSC_Exception_Audit_Trail Object');
        		System.debug(e.getMessage());
            }catch(DMLException ex){
                System.debug('Error could not be logged in the audit trail object');
        		System.debug(ex.getMessage());
                System.debug('Original Error below:');
                System.debug(e.getMessage());
            }
        
        	
    }
    
}