objects/Custom_FRUP__c.object
<CustomObject>
    <fields>
        <fullName>CustomKey__c</fullName>
        <externalId>true</externalId>
        <label>CustomKey</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FolderId__c</fullName>
        <externalId>true</externalId>
        <label>FolderId</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentFolderId__c</fullName>
        <externalId>true</externalId>
        <label>ParentFolderId</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Custom FRUP</label>
    <nameField>
        <label>Custom FRUP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom FRUP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Legal_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Law Firm, External Legal Counsel</inlineHelpText>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Legal_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LEAP - Legal Quote Amount Lock</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Legal Quote #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legal Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Matter_Spend_Document__c.object
<CustomObject>
    <fields>
        <fullName>Box_Folder_Link__c</fullName>
        <label>Box Folder Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>On/Off Panel Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matter Spend Documents</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Quote</label>
        <referenceTo>Legal_Quote__c</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter_Spend_Schedule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Matter Spend Schedule</label>
        <referenceTo>Matter_Spend_Schedule__c</referenceTo>
        <relationshipLabel>Matter Spend Documents</relationshipLabel>
        <relationshipName>Matter_Spend_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Matter Spend Document</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Credit Note</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Matter Spend Document</label>
    <nameField>
        <displayFormat>MSD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matter Spend Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Matter_Spend_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Document_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Matter Spend Schedule</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Schedule #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matter Spend Schedules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BxdMatterSpendDocumentService.cls
public class BxdMatterSpendDocumentService {
    private static FolderHandler folderHandler = new FolderHandler();
    
    /**
    * createBoxFolderTrigger - prepares a set of matterSpendDocument records id, then pass it to createBoxFolder
	**/
    public static  void createBoxFolderTrigger(List<Matter_Spend_Document__c> spendDocuments) {
        Set<Id> spendIds = new Set<Id>(); 
        for(Matter_Spend_Document__c spend : spendDocuments){
            spendIds.Add(spend.id);           
        }
        
        createBoxFolder(spendIds);
    }

	/**
    * createBoxFolder - this method executes asynchronously, it calls createFolder for each matterSpendDocument record in the set
	**/    
    @Future(callout = true)
    public static void createBoxFolder(Set<Id> spendDocumentIds) {
        List<Matter_Spend_Document__c> spendindDocuments = new List<Matter_Spend_Document__c>();
        
        //Get documents.
        spendindDocuments = [
            SELECT
            Id, 
            Name, 
            Matter__c, 
            Legal_Quote__c, 
            Law_Firm__c, 
            RecordTypeId, Type__c
            FROM Matter_Spend_Document__c
            WHERE
            Id IN :spendDocumentIds
        ];
        
        //Loop through each document.
        for(Matter_Spend_Document__c spending : spendindDocuments){
            createFolder(spending);
        }
    }
    
    
    /**
	* createFolder - this method creates a box folder for matterSpendDocument record by calling createBoxFolder in BxdFolderHandler, this is dependant on the frup 
	* It also sets the collaborationType to Viewer Uploader and creates a shared link for the folder
	**/
    public static void createFolder(Matter_Spend_Document__c matterSpendDocument) {
        if(matterSpendDocument != null){
            if(matterSpendDocument != null){
                String folderId;
                String INVOICE_FOLDER = matterSpendDocument.Type__c + 's';
                List<Custom_FRUP__c> customFolders = new List<Custom_FRUP__c>();
                
                //Get existing parent folder
                String parentFolderId = folderHandler.getBoxFolderIdByRecordId(matterSpendDocument.Matter__c);
                
                String customKey = matterSpendDocument.Matter__c + ' - ' + INVOICE_FOLDER;
                List<Custom_FRUP__c> frups = [SELECT Id, CustomKey__c, FolderId__c, ParentFolderId__c FROM Custom_FRUP__c WHERE CustomKey__c =:customKey];
                if (frups == null || frups.isEmpty()){
                    //create holding folder
                    String staticQuoteRequestFolderId = folderHandler.createBoxFolder(INVOICE_FOLDER, parentFolderId);
                    //create record folder
                    folderId = folderHandler.createBoxFolder(matterSpendDocument.Name, staticQuoteRequestFolderId);
                    folderHandler.linkBoxFolderToSalesforceRecord(matterSpendDocument.Id, folderId);
                    //add to custom folder details
                    Custom_FRUP__c details = new Custom_FRUP__c(CustomKey__c = customKey, FolderId__c = staticQuoteRequestFolderId, ParentFolderId__c = parentFolderId);
                    customFolders.add(details);
                } else {
                    Custom_FRUP__c details = frups[0];
                    folderId = folderHandler.createBoxFolder(matterSpendDocument.Name, details.FolderId__c);
                    folderHandler.linkBoxFolderToSalesforceRecord(matterSpendDocument.Id, folderId);
                }
                //set collaboration le
                box.Toolkit.CollaborationType collabType = box.Toolkit.CollaborationType.VIEWERUPLOADER;
                BxdCollaborationRequest collabRequest = BxdCollaborationRequest.getRequest();
                collabRequest.recordId = matterSpendDocument.Id;
                
                //create response shared link
                String folderLink = createSharedLink(folderId, collabRequest);
                String tempFolderId = folderHandler.getBoxFolderIdByRecordId(matterSpendDocument.Id);
                folderHandler.commitBoxChanges();
                // insert
                if(!customFolders.isEmpty()){
                    insert customFolders;
                }
                //update link
                if(!String.isBlank(folderLink)){
                    String url = folderLink;
                    url = url.replace(tempFolderId, folderId);
                    matterSpendDocument.Box_Folder_Link__c = folderLink;            
                    update matterSpendDocument;
                } 
            }                   
        }
    }
    
    
    /**
    * afterUpdateBox - this method loops through the matterSpendDocument recods list then calls moveFolderToSpendSchedule or moveFolderFromSpendSchedule
    **/
    public static void afterUpdateBox(List<Matter_Spend_Document__c> inputNewList, Map<Id, Matter_Spend_Document__c> inputOldMap) 
    {
        for(Matter_Spend_Document__c spendDocument : inputNewList){
            Id oldDocumentScheduleId = inputOldMap.get(spendDocument.Id).Matter_Spend_Schedule__c;
            
            if(!String.isBlank(spendDocument.Matter_Spend_Schedule__c) && String.isBlank(oldDocumentScheduleId)){
                system.debug('****Move Spend Folder to Schedule '+spendDocument.Matter_Spend_Schedule__c);
                moveFolderToSpendSchedule(spendDocument.Id, spendDocument.Matter_Spend_Schedule__c);
            }			
            
            if(String.isBlank(spendDocument.Matter_Spend_Schedule__c) && !String.isBlank(oldDocumentScheduleId)){  
                system.debug('****Move Spend Folder from Schedule '+oldDocumentScheduleId);
                moveFolderFromSpendSchedule(spendDocument.Id, oldDocumentScheduleId);
            }
        }
    }
    
    /**
    * createSharedLink - it calls getBoxFolderURL in BxdFolderHandler for the passed folderId then returns the url 
    **/
    private static String createSharedLink(String folderId, BxdCollaborationRequest collabRequest) {
        PageReference res = folderHandler.getBoxFolderURL(collabRequest.recordId, false);
        if(res != null){
            return res.getUrl();
        }
        return '';
    }
    
    /**
    * moveFolderToSpendSchedule - this method executes asynchronously, it gets the folderId of the matterSpendDocument record, then move the folder to spendSchedule as the new parent folder
    **/
    @Future(callout = true)
    private static void moveFolderToSpendSchedule(Id spendDocumentId, Id scheduleId) {
        //Get Spend box folder
        String spendFolderId = folderHandler.getBoxFolderIdByRecordId(spendDocumentId);
        //Get Schedule box folder
        String scheduleFolderId = folderHandler.getBoxFolderIdByRecordId(scheduleId);
        if(!String.isBlank(spendFolderId) && !String.isBlank(scheduleFolderId)){
            Boolean moved = folderHandler.moveBoxFolder(spendFolderId, scheduleFolderId);
            system.debug('FOLDER MOVED '+moved);
        }
        folderHandler.commitBoxChanges();
    }
    
    /**
    * moveFolderFromSpendSchedule - this method executes asynchronously, it gets the folderId of the matterSpendDocument record, then move the folder from spendSchedule to a different parent folder, dependant on the frup 
    **/
    @Future(callout = true)
    private static void moveFolderFromSpendSchedule(Id spendDocumentId, Id scheduleId) {
        Matter_Spend_Document__c spendDocument = [
            SELECT
            Id, 
            Name, 
            Matter__c, 
            Type__c
            FROM Matter_Spend_Document__c
            WHERE
            Id =:spendDocumentId
        ];
        //Get static box folder
        String INVOICE_FOLDER = spendDocument.Type__c + 's';
        String customKey = spendDocument.Matter__c + ' - ' + INVOICE_FOLDER;
        List<Custom_FRUP__c> frups = [SELECT Id, CustomKey__c, FolderId__c, ParentFolderId__c FROM Custom_FRUP__c WHERE CustomKey__c =:customKey];
        if (frups != null && !frups.isEmpty()){
            Custom_FRUP__c details = frups[0];
            //Get Spend box folder
            String spendFolderId = folderHandler.getBoxFolderIdByRecordId(spendDocument.Id);
            Boolean moved = folderHandler.moveBoxFolder(spendFolderId, details.FolderId__c);
            system.debug('FOLDER MOVED '+moved);
        }
        folderHandler.commitBoxChanges();
    }
    
    private class FolderHandler extends BxdFolderHandler {
        private FolderHandler() {
            super();
        }
    }
}