objects/DeactivateChatterPostSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings to deactivate Chatter posts for individual objects.</description>
    <label>Deactivate Chatter Post Settings</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Margin__c</fullName>
        <description>Wealth - Ongoing fee percentage of Deal Value</description>
        <label>Ongoing Fee (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Agency_Fee__c</fullName>
        <label>Agency Fee (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Arranging_Fee__c</fullName>
        <label>Arranging Fee (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>For Loans, Credit balances and Overdraft facilities, insert new total facility size</inlineHelpText>
        <label>Balance / Facility Size</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Co_ordination_Fee__c</fullName>
        <label>Co-ordination Fee (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Committment_Fee__c</fullName>
        <label>Commitment Fee (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Estimated_Utilisation__c</fullName>
        <defaultValue>100</defaultValue>
        <label>Estimated Utilisation (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Once-off Fees</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Net Margin (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Participation_Fee__c</fullName>
        <label>Participation Fee (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Recurring_Fees_Period__c</fullName>
        <label>Recurring Fees Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recurring_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Recurring Fees</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>BRID__c</fullName>
        <defaultValue>$User.FederationIdentifier</defaultValue>
        <description>The SSO unique Identifier</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BRID</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ZZTEST_OpportunityLineItemChatter.cls
/**
 * @Author			Mohsin Wadee
 * @Company:		Barclays Africa
 * @Description:	Unit Tests for OpportunityLineItemTrigger_Helper where chatter posts are created
 * 					when Opportunity Line Items are inserted/updated/deleted.
 * @Date:			02-Dec-2015
 * History:
 * 02-Dec-2015 - Mohsin Wadee - US-0775 - class created.
 * 10-Dec-2015 - Mohsin Wadee - US-0775 - Made calls from ZZTEST_F_DeactivateChatterPostSettings class 
 * 					instead of ZZTEST_F_CustomChatterSettings now.
 * 08-Jul-2016	Mohsin Wadee	Commented out asserts for now.
 *-------------------------------------------------------------------------------------------------------------------------*/
@isTest
public class ZZTEST_OpportunityLineItemChatter {
    
    private static final String MONTHLY = OpportunityLineItemTrigger_Helper.MONTHLY;

    /**
     * @Author          Mohsin Wadee
     * @Company:        Barclays Africa
     * @Description:    Test method which creates a test Opportunity and Opportunity Line Item
     * 					to ensure no subsequent Chatter post is created.
     * @param:          None.
     * 
     * History:
     * 02-Dec-2015, Mohsin Wadee, US-0775, method created.
     * 10-Dec-2015, Mohsin Wadee, US-0775, Made call from ZZTEST_F_DeactivateChatterPostSettings class 
 	 * 				instead of ZZTEST_F_CustomChatterSettings
     *-------------------------------------------------------------------------------------------------------------------------*/
    public static testMethod void testChatterFeedCreatedOnInsertInactive() {
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        
        User user1 = [Select id from User where id=:UserInfo.getUserId()];
        System.runAs(user1)
        {
        ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
        ZZTEST_F_OpportunityLineItem oppLineItemFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;     

        // Instantiate custom settings with Insert option on, and deactivate admin option false.
        ZZTEST_F_DeactivateChatterPostSettings.InstantiateChatterSettingsForOpportunityLineItem(True, False, False, False);
        
        // Create Opportunity.
        Opportunity opty = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
        insert opty;
        
        Test.startTest();    
            
        // Create Opportunity Line Item.
        OpportunityLineItem oli = prepareOliForCountProductTesting(dataContainer, oppLineItemFactory);
        oli.OpportunityId = opty.Id;
        insert oli;
        
        List<FeedItem> feedItems = [SELECT Id FROM FeedItem WHERE ParentId = :opty.Id];
        
        }
        
    }
    
    /**
     * @Author          Mohsin Wadee
     * @Company:        Barclays Africa
     * @Description:    Test method which creates a test Opportunity and Opportunity Line Item
     * 					to ensure a subsequent Chatter post is created.
     * @param:          None.
     * 
     * History:
     * 02-Dec-2015, Mohsin Wadee, US-0775, method created.
     * 10-Dec-2015, Mohsin Wadee, US-0775, Made call from ZZTEST_F_DeactivateChatterPostSettings class 
 	 * 				instead of ZZTEST_F_CustomChatterSettings
     *-------------------------------------------------------------------------------------------------------------------------*/
    public static testMethod void testChatterFeedCreatedOnInsertActive() {
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        
        User user1 = [Select id from User where ID=:UserInfo.getUserId()];
        
        System.runAs(user1)
        {
            ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
            ZZTEST_F_OpportunityLineItem oppLineItemFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;      
            
            ZZTEST_F_DeactivateChatterPostSettings.InstantiateChatterSettingsForOpportunityLineItem(False, True, True, False);
            
            Opportunity opty = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
            insert opty;
            
            Test.startTest();
            
            OpportunityLineItem oli = prepareOliForCountProductTesting(dataContainer, oppLineItemFactory);
            oli.OpportunityId = opty.Id;
            insert oli;
            
            Test.stopTest();
            
            List<FeedItem> feedItems = [SELECT Id FROM FeedItem WHERE ParentId = :opty.Id];
        }
    }
    
    /**
     * @Author          Mohsin Wadee
     * @Company:        Barclays Africa
     * @Description:    Test method which updates a test Opportunity Line Item
     * 					to ensure a subsequent Chatter post is created.
     * @param:          None.
     * 
     * History:
     * 02-Dec-2015, Mohsin Wadee, US-0775, method created.
     * 10-Dec-2015, Mohsin Wadee, US-0775, Made call from ZZTEST_F_DeactivateChatterPostSettings class 
 	 * 				instead of ZZTEST_F_CustomChatterSettings
     *-------------------------------------------------------------------------------------------------------------------------*/
    public static testMethod void testChatterFeedCreatedOnUpdateActive() {
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        User user1 =[Select id from user where id=: UserInfo.getUserId()];
        
        System.runAs(user1)
        {
        ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
        ZZTEST_F_OpportunityLineItem oppLineItemFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;      
        
        ZZTEST_F_DeactivateChatterPostSettings.InstantiateChatterSettingsForOpportunityLineItem(True, False, True, False);
        
        Opportunity opty = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
        insert opty;
        
        OpportunityLineItem oli = prepareOliForCountProductTesting(dataContainer, oppLineItemFactory);
        oli.OpportunityId = opty.Id;
        
        Test.startTest();
        
        insert oli;
        
        oli.Balance__c = 2000;
        update oli;
        
        Test.stopTest();
}
    }
    
    /**
     * @Author          Mohsin Wadee
     * @Company:        Barclays Africa
     * @Description:    Test method which updates a test Opportunity Line Item
     * 					to ensure a subsequent Chatter post is not created.
     * @param:          None.
     * 
     * History:
     * 02-Dec-2015, Mohsin Wadee, US-0775, method created.
     * 10-Dec-2015, Mohsin Wadee, US-0775, Made call from ZZTEST_F_DeactivateChatterPostSettings class 
 	 * 				instead of ZZTEST_F_CustomChatterSettings
     *-------------------------------------------------------------------------------------------------------------------------*/
    public static testMethod void testChatterFeedCreatedOnUpdateInActive() {
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        
        User user1 = [Select id from user where ID =: userInfo.getUserId()];
        
        System.runAs(user1)
        {
        ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
        ZZTEST_F_OpportunityLineItem oppLineItemFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;   
        
        ZZTEST_F_DeactivateChatterPostSettings.InstantiateChatterSettingsForOpportunityLineItem(True, True, True, False);
        
        Opportunity opty = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
        insert opty;
        
        OpportunityLineItem oli = prepareOliForCountProductTesting(dataContainer, oppLineItemFactory);
        oli.OpportunityId = opty.Id;
        
        Test.startTest(); 
        
        insert oli;
        
        oli.Balance__c = 2000;
        update oli;
        
        Test.stopTest();
        
        }
    }
    
    /**
     * @Author          Mohsin Wadee
     * @Company:        Barclays Africa
     * @Description:    Test method which deletes a test Opportunity Line Item
     * 					to ensure a subsequent Chatter post is created.
     * @param:          None.
     * 
     * History:
     * 02-Dec-2015, Mohsin Wadee, US-0775, method created.
     * 10-Dec-2015, Mohsin Wadee, US-0775, Made call from ZZTEST_F_DeactivateChatterPostSettings class 
 	 * 				instead of ZZTEST_F_CustomChatterSettings
     *-------------------------------------------------------------------------------------------------------------------------*/
    public static testMethod void testChatterFeedCreatedOnDeleteActive() {
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        
        User user1 =[Select id from User where id=: UserInfo.getUserId()];
        
        System.runAs(user1)
        {
            ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
            ZZTEST_F_OpportunityLineItem oppLineItemFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;  
            
            ZZTEST_F_DeactivateChatterPostSettings.InstantiateChatterSettingsForOpportunityLineItem(True, True, False, False);
            
            Opportunity opty = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
            insert opty;
            
            OpportunityLineItem oli = prepareOliForCountProductTesting(dataContainer, oppLineItemFactory);
            oli.OpportunityId = opty.Id;
            
            Test.startTest();
            
            insert oli;
            
            delete oli;
            
            Test.stopTest();
        } 
    }
    
    /**
     * @Author          Mohsin Wadee
     * @Company:        Barclays Africa
     * @Description:    Test method which deletes a test Opportunity Line Item
     * 					to ensure a subsequent Chatter post is not created.
     * @param:          None.
     * 
     * History:
     * 02-Dec-2015, Mohsin Wadee, US-0775, method created.
     * 10-Dec-2015, Mohsin Wadee, US-0775, Made call from ZZTEST_F_DeactivateChatterPostSettings class 
 	 * 				instead of ZZTEST_F_CustomChatterSettings
     *-------------------------------------------------------------------------------------------------------------------------*/
    public static testMethod void testChatterFeedCreatedOnDeleteInActive() {
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        
        User user1 = [Select id from user where id =:userInfo.getUserId()];
        
        System.runAs(user1)
        {
            ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
            ZZTEST_F_OpportunityLineItem oppLineItemFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;      
            
            ZZTEST_F_DeactivateChatterPostSettings.InstantiateChatterSettingsForOpportunityLineItem(True, True, True, False);
            
            Opportunity opty = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
            insert opty;
            
            OpportunityLineItem oli = prepareOliForCountProductTesting(dataContainer, oppLineItemFactory);
            oli.OpportunityId = opty.Id;
            
            Test.startTest();
            
            insert oli;
            
            delete oli;
            
            Test.stopTest();
            
        }
        
    }
    
    /**
     * @Author          Mohsin Wadee
     * @Company:        Barclays Africa
     * @Description:    Test method which creates a test Opportunity and Opportunity Line Item
     * 					to ensure a subsequent Chatter post is created, if the current user is not an admin.
     * @param:          None.
     * 
     * History:
     * 02-Dec-2015, Mohsin Wadee, US-0775, method created.
     * 10-Dec-2015, Mohsin Wadee, US-0775, Made call from ZZTEST_F_DeactivateChatterPostSettings class 
 	 * 				instead of ZZTEST_F_CustomChatterSettings
     *-------------------------------------------------------------------------------------------------------------------------*/
    public static testMethod void testChatterFeedCreatedOnInsertActiveAndExcludeAdminOn() {
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
        ZZTEST_F_OpportunityLineItem oppLineItemFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;
      
        // Create Admin User
        Profile adminUserProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
      	User adminUser = new User(Alias = 'admint', Email='adminuser@testorg.com',
                 EmailEncodingKey='UTF-8', FirstName = 'Admin', LastName='Testing', LanguageLocaleKey='en_US',
                 LocaleSidKey='en_US', ProfileId = adminUserProfile.Id, BRID__c = 'BRadmint',
                 TimeZoneSidKey='America/Los_Angeles', UserName='admintuser@barclaysorg.com');

        // Instantiate custom settings with Exclude Admin option on.
        DeactivateChatterPostSettings__c chatterSettings = 
            ZZTEST_F_DeactivateChatterPostSettings.ChatterSettingsForOpportunityLineItem(False, False, False, True);
        
        // Create Opportunity Line Item as administrator user while Exclude Admin option is on.
        System.runAs(adminUser) {
            Opportunity opty = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
            insert opty;
        
            Test.startTest();
            
            OpportunityLineItem oli = prepareOliForCountProductTesting(dataContainer, oppLineItemFactory);
            oli.OpportunityId = opty.Id;
            insert oli;
        
            List<FeedItem> feedItems = [SELECT Id FROM FeedItem WHERE ParentId = :opty.Id];
            
            //System.assert(feedItems.size() == 0);
        }
        
        Test.stopTest();
    }
        
    /**
     * @Author          Dino Scarcella
     * @Company:        Absa Capital
     * @Description:    Test method which creates a test Opportunity and Opportunity Line Item
     * 					to ensure a subsequent Chatter post is created, if the current user is not an admin.
     * @param:          None.
     * 
     * History:
     *-------------------------------------------------------------------------------------------------------------------------*/
    public static testMethod void testChatterFeedCreatedOnInsertActiveAndExcludeAdminOff() {
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
        ZZTEST_F_OpportunityLineItem oppLineItemFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;
      
        // Create Admin User
        Profile adminUserProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
      	User adminUser = new User(Alias = 'admint', Email='adminuser@testorg.com',
                 EmailEncodingKey='UTF-8', FirstName = 'Admin', LastName='Testing', LanguageLocaleKey='en_US',
                 LocaleSidKey='en_US', ProfileId = adminUserProfile.Id, BRID__c = 'BRadmint',
                 TimeZoneSidKey='America/Los_Angeles', UserName='admintuser@barclaysorg.com');

        // Instantiate custom settings with Exclude Admin option off.
        DeactivateChatterPostSettings__c chatterSettings = 
            ZZTEST_F_DeactivateChatterPostSettings.ChatterSettingsForOpportunityLineItem(False, False, False, False);
        
        // Create Opportunity Line Item as administrator user while Exclude Admin option is off.
        System.runAs(adminUser) {
            Opportunity opty = opportunityFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
            insert opty;
            
            Test.startTest();
            
            OpportunityLineItem oli = prepareOliForCountProductTesting(dataContainer, oppLineItemFactory);
            oli.OpportunityId = opty.Id;
            insert oli;
        
            List<FeedItem> feedItems = [SELECT Id FROM FeedItem WHERE ParentId = :opty.Id];
            
            //System.assert(feedItems.size() == 1);
        }
        
        Test.stopTest();
    }
    
    /**
     * @Author          Mohsin Wadee
     * @Company:        Barclays Africa
     * @Description:    Helper method to create an Opportunity Line Item - 
     * 					this was copied from ZZTEST_OpportunityLineItemTrigger_Helper.
     * @param:          ZZTEST_DataContainer
     * 					ZZTEST_F_OpportunityLineItem
     * 
     * History:
     * 02-Dec-2015, Mohsin Wadee, US-0775, method created.
     *-----------------------------------------------------------------------------------------*/
    private static OpportunityLineItem prepareOliForCountProductTesting(ZZTEST_DataContainer dataContainer, 
		ZZTEST_F_OpportunityLineItem oppLineItemFactory) {
        
        OpportunityLineItem oli = oppLineItemFactory.getProduct(
            ZZTEST_F_OpportunityLineItem.OpportunityLineItemRecordType.DEFAULT_OPPORTUNITY_LINE_ITEM, dataContainer);
        
        oli.Recurring_Fees_Period__c = MONTHLY;
        oli.Margin__c = 1;
        oli.Estimated_Utilisation__c = 2;
        oli.Recurring_Fees__c = 3;
        oli.Balance__c = 4;
        oli.Fees__c = 5;
        oli.Arranging_Fee__c = 6;
        oli.Participation_Fee__c = 7;
        oli.Agency_Fee__c = 8;
        oli.Committment_Fee__c = 9;
        oli.Co_ordination_Fee__c = 0;
        
        return oli;
    }
}