objects/Delegate__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Delegates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Delegates</relationshipLabel>
        <relationshipName>Delegates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invitation_Status__c</fullName>
        <description>17-08-08 DH Added new field</description>
        <inlineHelpText>Manage the status of invitees until they are either approved to be invited to the event or not.  After this their status is tracked with RSVP Status and then Attendance Status</inlineHelpText>
        <label>Invitation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delegate_Invitation_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>Event__r.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The attendnace status of the delegate indicating if he/she actaully attended the event.</inlineHelpText>
        <label>Attendance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delegate_Attendance_Statuses</valueSetName>
        </valueSet>
    </fields>
    <label>Delegate</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Delegate #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EM_Event_Email_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attach_Delegate_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this option if you want to attach a PDF file containing the delegate&apos;s event schedule.</inlineHelpText>
        <label>Attach Delegate Schedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attach_Speaker_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attach Speaker Schedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegate_Attendance_Status__c</fullName>
        <label>Delegate Attendance Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delegate_Attendance_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delegate_Invitation_Status__c</fullName>
        <label>Delegate Invitation Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delegate_Invitation_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delegate_RSVP_Status__c</fullName>
        <label>Delegate RSVP Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delegate_RSVP_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delegate_Registration_Status__c</fullName>
        <label>Delegate Registration Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delegate_Registration_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Specify a single Delegate to send to just a single Delegate (eg: for testing purposes)</inlineHelpText>
        <label>Delegate</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Delegate__c.Event__c</field>
                <operation>equals</operation>
                <valueField>$Source.Event__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Delegate__c</referenceTo>
        <relationshipName>Event_Email_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Email Schedules</relationshipLabel>
        <relationshipName>Event_Email_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SMS_Text__c</fullName>
        <inlineHelpText>The content allows substitution of &lt;EventName&gt;, &lt;FirstName&gt; and &lt;DelegateID&gt;
Messages longer than 180 characters (after substitution) will use multi-part SMS messages and incur additional costs</inlineHelpText>
        <label>SMS Text</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Send_From_Name__c</fullName>
        <label>Send From Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_From__c</fullName>
        <label>Send From</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Before_After__c</fullName>
        <label>Start Before/After</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Before Start Date</fullName>
                </value>
                <value>
                    <fullName>After Start Date</fullName>
                </value>
                <value>
                    <fullName>Before End Date</fullName>
                </value>
                <value>
                    <fullName>After End Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Days__c</fullName>
        <label>Start Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Send_Time__c</fullName>
        <inlineHelpText>Messages will not be sent before this time of the day.  Blank means any time.</inlineHelpText>
        <label>Start Send Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Times_for_Event</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stop_Before_After__c</fullName>
        <label>Stop Before/After</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Before Start Date</fullName>
                </value>
                <value>
                    <fullName>After Start Date</fullName>
                </value>
                <value>
                    <fullName>Before End Date</fullName>
                </value>
                <value>
                    <fullName>After End Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stop_Days__c</fullName>
        <label>Stop Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stop_Send_Date__c</fullName>
        <inlineHelpText>The date up to which this scheduled email will be sent,  Leave blank to have no end date limit</inlineHelpText>
        <label>Stop Send Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stop_Send_Time__c</fullName>
        <inlineHelpText>Message will not be sent after this time of the day.  Leave blank for no restrictions</inlineHelpText>
        <label>Stop Send Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Times_for_Event</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Status__c</fullName>
        <label>Survey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Completed</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Email Schedule</label>
    <nameField>
        <displayFormat>SC{00000}</displayFormat>
        <label>Schedule Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Email Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Active Events allow Event Team Members to add Proposed Invitees to the Event</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Event Capacity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>I_have_read_Absa_Event_Governance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I have read Absa Event Governance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Online_Processing__c</fullName>
        <label>Online Processing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Create Opportunity; Optional Payment</fullName>
                </value>
                <value>
                    <fullName>Create Opportunity; Mandatory Payment</fullName>
                </value>
                <value>
                    <fullName>Do Not Create an Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Registration_Process__c</fullName>
        <label>Registration Process</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complex</fullName>
                    <label>Complex (Groups)</label>
                </value>
                <value>
                    <fullName>Simple</fullName>
                    <default>true</default>
                    <label>Simple (Individual)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Event/Function</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events/Functions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>SFA-327</description>
        <label>Acc Banker Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                    <label>Pending Approval</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Delegate_Attendance_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Attended_Partially</fullName>
        <label>Attended Partially</label>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>No Show</fullName>
    </customValue>
    <masterLabel>Delegate Attendance Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Delegate_Invitation_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Proposed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Delegate Invitation Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Delegate_Registration_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>Walk In</fullName>
    </customValue>
    <masterLabel>Delegate Registration Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Delegate_RSVP_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Maybe</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Delegate RSVP Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Times_for_Event.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>07:30</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:30</fullName>
    </customValue>
    <customValue>
        <fullName>09:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:30</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:30</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <customValue>
        <fullName>23:30</fullName>
    </customValue>
    <masterLabel>Times for Event</masterLabel>
</GlobalValueSet>

classes/evEventEmail_Batch_Test.cls
@istest
public class evEventEmail_Batch_Test 
{
    static testMethod void evEventEmail_Batch_Test() 
    {  
        evTestDataGenerator generator = new evTestDataGenerator();
        
        evEventEmail_Batch testbatch3 =  new evEventEmail_Batch(); 
        Account account = new Account();
        account.Name='Test Account ZxZ';
        account.BillingStreet='Test Street';
        account.BillingCity = 'Test City';
        account.BillingCountry='Canada';
        account.BillingState='Ontario';
        account.BillingPostalCode='9111';
        
        insert account;
        
        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName ='Contact';
        contact.AccountId = account.Id;
        contact.email='sample1@nowhere.com';
        contact.mobilephone = '27 11 1234567';
        insert contact;
        
        Contact contact2 = new Contact();
        contact2.FirstName = 'Test 2';
        contact2.LastName ='Contact 2';
        contact2.AccountId = account.Id;
        contact2.mobilephone = '27 11 1234567';
        contact2.email='sample2@nowhere.com';
        
        insert contact2;
        
        Event__c event  = new Event__c(); 
        event.Name = 'Test Event';
        event.Capacity__c = 2;
        event.Start_Date__c = Date.today();
        event.End_Date__c = Date.today()+3;
        event.Online_Processing__c = 'Do Not Create Opportunity';
        //event.Registration_Confirmation_Fields__c = 'First Name';
        event.Registration_Process__c = 'Simple';
        event.I_have_read_Absa_Event_Governance__c = true;
        insert event;       
        
        Delegate__c delegate = new Delegate__c();
        delegate.Status__c = null;
        delegate.Invitation_Status__c = 'Approved';
        delegate.Event__c = event.Id;
        delegate.Contact__c = contact.Id; 
        insert delegate;    
        
        Delegate__c delegate2 = new Delegate__c();
        delegate.Invitation_Status__c = 'Approved';
        delegate2.Status__c = 'Attended';
        delegate2.Event__c = event.Id;
        delegate2.Contact__c = contact2.Id; 
        insert delegate2;       
        
        EM_Event_Email_Configuration__c emailConfig = new EM_Event_Email_Configuration__c();
        emailconfig.Event__c = event.Id;
        emailconfig.Active__c = true;
        //DH this should be the ID of an org wide email address record.... //emailConfig.Send_From__c= 'test@test.com';
        emailconfig.Send_From__c = 'LoggedInUser';
        emailconfig.Delegate_Attendance_Status__c ='Attended';
        emailconfig.Delegate_Invitation_Status__c = 'Proposed';
        emailconfig.Delegate_Registration_Status__c ='Pending';
        emailconfig.Delegate_RSVP_Status__c ='Invited';
        emailconfig.Survey_Status__c = 'Both';

        emailConfig.Send_From_Name__c = 'Test'; 
        emailconfig.Start_Days__c = 4;
        emailconfig.Start_Before_After__c = 'Before Start Date';
        emailconfig.Start_Send_Time__c= '00:00';

        emailconfig.Stop_Days__c = 4;
        emailconfig.Stop_Before_After__c= 'After End Date';
        emailconfig.Stop_Send_Time__c= '23:30';
        emailconfig.Stop_Send_Date__c =  date.today().adddays(1);

        insert emailconfig;


        Test.startTest();
        
        evEventEmail_Batch testbatch =  new evEventEmail_Batch(); 
        
        database.executeBatch(testbatch);



/*        
       EM_Event_Email_Configuration__c emailConfig2 = new EM_Event_Email_Configuration__c();
        emailconfig2.Event__c = event.Id;
        emailconfig.Start_Days__c = 4;
        emailconfig.Start_Before_After__c = 'Before';
        emailconfig.Delegate_Attendance_Status__c ='Attended';
        emailconfig2.Survey_Status__c = 'Both';
        emailconfig.Delegate_Attendance_Status__c ='Attended';
        emailconfig.Delegate_Invitation_Status__c ='Approved';
        emailconfig.Delegate_Registration_Status__c ='Pending';
        emailconfig.Delegate_RSVP_Status__c ='Invited';
        emailconfig2.SMS_Text__c = 'Test';
        emailconfig2.Active__c = true;
        emailconfig2.Start_Days__c = 0;
        emailconfig2.Start_Days__c = 5;
        emailconfig2.Send_From__c= 'test@test.com';
        emailconfig2.Send_From_Name__c = 'Test'; 
        emailconfig2.Start_Before_After__c = 'Before Start Date';
        emailconfig2.Start_Send_Time__c= '00:00';
        emailconfig2.Stop_Before_After__c= 'After End Date';
        emailconfig2.Stop_Send_Time__c= '23:30';
        insert emailconfig2;
        evEventEmail_Batch testbatch2 =  new evEventEmail_Batch(); 
        database.executeBatch(testbatch2);

*/
        Test.stopTest();
    }
    
     static testMethod void evSingleEventEmail_Batch_Test() 
    {  
        evTestDataGenerator generator = new evTestDataGenerator();
        
        evEventEmail_Batch testbatch3 =  new evEventEmail_Batch(); 
        Account account = new Account();
        account.Name='Test Account ZxZ';
        account.BillingStreet='Test Street';
        account.BillingCity = 'Test City';
        account.BillingCountry='Canada';
        account.BillingState='Ontario';
        account.BillingPostalCode='9111';
        
        insert account;
        
        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName ='Contact';
        contact.AccountId = account.Id;
        contact.email='sample1@nowhere.com';
        contact.mobilephone = '27 11 1234567';
        insert contact;
        
        Contact contact2 = new Contact();
        contact2.FirstName = 'Test 2';
        contact2.LastName ='Contact 2';
        contact2.AccountId = account.Id;
        contact2.mobilephone = '27 11 1234567';
        contact2.email='sample2@nowhere.com';
        
        insert contact2;
        
        Event__c event  = new Event__c(); 
        event.Name = 'Test Event';
        event.Capacity__c = 2;
        event.Start_Date__c = Date.today();
        event.End_Date__c = Date.today()+3;
        event.Online_Processing__c = 'Do Not Create Opportunity';
        //event.Registration_Confirmation_Fields__c = 'First Name';
        event.Registration_Process__c = 'Simple';
         event.I_have_read_Absa_Event_Governance__c = true;
        insert event;       
        
        Delegate__c delegate = new Delegate__c();
        delegate.Status__c = null;
        delegate.Invitation_Status__c = 'Approved';
        delegate.Event__c = event.Id;
        delegate.Contact__c = contact.Id; 
        insert delegate;    
        
        Delegate__c delegate2 = new Delegate__c();
        delegate.Invitation_Status__c = 'Approved';
        delegate2.Status__c = 'Attended';
        delegate2.Event__c = event.Id;
        delegate2.Contact__c = contact2.Id; 
        insert delegate2;       
        
        EM_Event_Email_Configuration__c emailConfig = new EM_Event_Email_Configuration__c();
        EM_Event_Email_Configuration__c emailConfig2 = new EM_Event_Email_Configuration__c();
        EM_Event_Email_Configuration__c emailConfig3 = new EM_Event_Email_Configuration__c();
        
        emailconfig.Event__c = event.Id;
        emailconfig.Active__c = true;
        //DH this should be the ID of an org wide email address record.... //emailConfig.Send_From__c= 'test@test.com';
        emailconfig.Send_From__c = 'LoggedInUser';
        emailconfig.Delegate_Attendance_Status__c ='Attended';
        emailconfig.Delegate_Invitation_Status__c = null;
        emailconfig.Delegate_Registration_Status__c =null;
        emailconfig.Delegate_RSVP_Status__c =null;
        emailconfig.Survey_Status__c = 'Both';

        emailConfig.Send_From_Name__c = 'Test'; 
        emailconfig.Start_Days__c = 4;
        emailconfig.Start_Before_After__c = 'Before Start Date';
        emailconfig.Start_Send_Time__c= '00:00';

        emailconfig.Stop_Days__c = 4;
        emailconfig.Stop_Before_After__c= 'After End Date';
        emailconfig.Stop_Send_Time__c= '23:30';
        emailconfig.Stop_Send_Date__c =  date.today().adddays(1);
        
        emailconfig.Attach_Speaker_Schedule__c =  true;

        insert emailconfig;
        
        emailconfig2 = emailconfig.clone(false);
        emailconfig2.Attach_Speaker_Schedule__c =  false;
		emailconfig2.Attach_Delegate_Schedule__c =  true;
        
        insert emailconfig2;
        
        emailconfig3 = emailconfig.clone(false);
        emailconfig3.SMS_Text__c = 'Test SMS';
        
        insert emailconfig3;
        
        Test.startTest();
        
        database.executebatch(new evEventEmail_Batch(emailconfig.id),100);
        database.executebatch(new evEventEmail_Batch(emailconfig2.id),100);
        database.executebatch(new evEventEmail_Batch(emailconfig3.id),100);

        Test.stopTest();

    }
}