objects/Delegate__c.object
<CustomObject>
    <fields>
        <fullName>Accessibility__c</fullName>
        <label>Accessibility</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Availibility__c</fullName>
        <label>Availability</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dietary_Requirement__c</fullName>
        <description>13-08-22 DH New option of Vegan per training request</description>
        <label>Dietary Requirement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Halaal</fullName>
                </value>
                <value>
                    <fullName>Kosher</fullName>
                </value>
                <value>
                    <fullName>Vegetarian</fullName>
                </value>
                <value>
                    <fullName>Vegan</fullName>
                </value>
                <value>
                    <fullName>No Pork</fullName>
                </value>
                <value>
                    <fullName>No Shellfish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Name__c</fullName>
        <label>Emergency Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Relationship__c</fullName>
        <label>Emergency Contact Relationship</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Tel__c</fullName>
        <label>Emergency Contact Tel</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Event_Visit_Reason__c</fullName>
        <label>Event Visit Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Information about new product</fullName>
                </value>
                <value>
                    <fullName>Trends</fullName>
                </value>
                <value>
                    <fullName>Information about products</fullName>
                </value>
                <value>
                    <fullName>Systems</fullName>
                </value>
                <value>
                    <fullName>Applications</fullName>
                </value>
                <value>
                    <fullName>Information about prices</fullName>
                </value>
                <value>
                    <fullName>Making new business contacts</fullName>
                </value>
                <value>
                    <fullName>Cultivation of existing business contacts</fullName>
                </value>
                <value>
                    <fullName>Purchase negotiations</fullName>
                </value>
                <value>
                    <fullName>Initial orientation</fullName>
                </value>
                <value>
                    <fullName>Continuation training</fullName>
                </value>
                <value>
                    <fullName>Concluding purchases</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Aviation</fullName>
                </value>
                <value>
                    <fullName>Banking &amp;amp; Finance</fullName>
                </value>
                <value>
                    <fullName>Call Centre</fullName>
                </value>
                <value>
                    <fullName>Chemicals / Petro Chemicals</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Enterprise Development</fullName>
                </value>
                <value>
                    <fullName>Environmental / Horticulture</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Fmcg</fullName>
                </value>
                <value>
                    <fullName>Freight / Shipping</fullName>
                </value>
                <value>
                    <fullName>Governmental</fullName>
                </value>
                <value>
                    <fullName>Health &amp;amp; Fitness</fullName>
                </value>
                <value>
                    <fullName>Hotel / Catering / Hospitality</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
                <value>
                    <fullName>Information Technology</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Management</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Motor Industry</fullName>
                </value>
                <value>
                    <fullName>Municipal</fullName>
                </value>
                <value>
                    <fullName>NGO / Non Profit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Invitation from exhibitor</fullName>
                </value>
                <value>
                    <fullName>Invitation from organiser</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Newspaper advertisement</fullName>
                </value>
                <value>
                    <fullName>Trade publication</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Word of mouth</fullName>
                </value>
                <value>
                    <fullName>Visited last year</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Member_Name__c</fullName>
        <label>Main Member Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Aid_Name__c</fullName>
        <label>Medical Aid Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Aid_No__c</fullName>
        <label>Medical Aid No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Conditions__c</fullName>
        <label>Medical Conditions</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <label>Nationality</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries_For_Events</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>Type of partner if this delegate is a partner of an another delegate.</description>
        <inlineHelpText>Type of partner if this delegate is a partner of an another delegate.</inlineHelpText>
        <label>Partner Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSVP_Status__c</fullName>
        <label>RSVP Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delegate_RSVP_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Identification__c</fullName>
        <label>Type of Identification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SA ID Number</fullName>
                </value>
                <value>
                    <fullName>Passport</fullName>
                </value>
                <value>
                    <fullName>Non SA ID Number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Delegate</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Delegate #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Countries_For_Events.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Abu Dhabi Global Market</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa</fullName>
        <default>true</default>
        <label>South Africa</label>
    </customValue>
    <masterLabel>Countries For Events</masterLabel>
</GlobalValueSet>

globalValueSets/Delegate_RSVP_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>Maybe</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Delegate RSVP Statuses</masterLabel>
</GlobalValueSet>

classes/evRSVP_Controller_Test.cls
@isTest (seeAllData=false)
private without sharing class evRSVP_Controller_Test 
{
    public class MyException extends Exception {}     
    
    static testMethod void BHA_RSVP_Controller_test() 
    {
        
        
        //test yes
        
        evTestDataGenerator TDG = new evTestDataGenerator();
        
        PageReference RSVPPage = Page.evRSVP;
        RSVPPage.getParameters().put('delid', TDG.testDelegate.Id);
        RSVPPage.getParameters().put('rsvp', 'Yes');
        Test.setCurrentPage(RSVPPage); 
        
        evRSVP_Controller  RSVPCon =  new evRSVP_Controller();
        RSVPCon.HandleResponse();
        
        //test no        
        
        TDG.testDelegate.RSVP_Status__c = 'No';
        RSVPPage = Page.evRSVP;
        RSVPPage.getParameters().put('delid', TDG.testDelegate.Id);
        RSVPPage.getParameters().put('rsvp', 'No');
        Test.setCurrentPage(RSVPPage); 
        
        RSVPCon =  new evRSVP_Controller(); 
        RSVPCon.HandleResponse();
        
        //test maybe
        
        TDG.testDelegate.RSVP_Status__c = 'Maybe';
        RSVPPage = Page.evRSVP;
        RSVPPage.getParameters().put('delid', TDG.testDelegate.Id); 
        RSVPPage.getParameters().put('rsvp', 'Maybe');
        Test.setCurrentPage(RSVPPage); 
        
        RSVPCon =  new evRSVP_Controller();
        RSVPCon.HandleResponse();
        
        //test no parems 
        
        TDG.testDelegate.RSVP_Status__c = '';
        RSVPPage = Page.evRSVP;
        RSVPPage.getParameters().put('delid', TDG.testDelegate.Id);
        Test.setCurrentPage(RSVPPage); 
        
        RSVPCon =  new evRSVP_Controller();
        try//put this in a try catch as the handled error causes the test class to fail
        {
            RSVPCon.HandleResponse();
        }
        Catch(exception e)
        {
            //do nothing
        }
        
        
        
        //test bad parems
        
        TDG.testDelegate.RSVP_Status__c = 'Thinking about it xyz';        
        RSVPPage = Page.evRSVP;
        RSVPPage.getParameters().put('delid', TDG.testDelegate.Id);
        RSVPPage.getParameters().put('rsvp', 'Thinking about it xyz'); 
        Test.setCurrentPage(RSVPPage); 
        
        RSVPCon =  new evRSVP_Controller();
        try//put this in a try catch as the handled error causes the test class to fail
        {
            RSVPCon.HandleResponse();
        }
        Catch(exception e)
        {
            //do nothing
        }
        
        //RSVPCon.thisDelegate.firstname__c                             = 'newTestFirst';
        //RSVPCon.thisDelegate.lastname__c                              = 'TestLast';
        RSVPCon.thisDelegate.mobile__c                              = '085 555 5555';
        RSVPCon.thisDelegate.title__c                               = 'Analyst';
        RSVPCon.thisDelegate.Phone__c                               = '011 555 5555';
        RSVPCon.thisDelegate.id__C                                  = '6512016787653';
        RSVPCon.thisDelegate.Salutation__c                          = 'mr.';
        RSVPCon.thisDelegate.Industry__c                            = 'IT';
        RSVPCon.thisDelegate.email__c                               = 'newsomeone@somewhere.com';
        RSVPCon.thisDelegate.Event_Visit_Reason__c                  = 'newFood';
        RSVPCon.thisDelegate.Lead_Source__c                         = 'Website';
        RSVPCon.thisDelegate.Company__c                             = 'Test';
        RSVPCon.thisDelegate.Gender__c                              = 'Test';
        //RSVPCon.thisDelegate.Nationality__c                         = 'South Africa';
        RSVPCon.thisDelegate.Dietary_Requirement__c                 = 'Test';        
        RSVPCon.thisDelegate.Emergency_Contact_Name__c              = 'Test';
        RSVPCon.thisDelegate.Emergency_Contact_Relationship__c      = 'Test';
        RSVPCon.thisDelegate.Emergency_Contact_Tel__c               = 'Test';   
        RSVPCon.thisDelegate.Main_Member_Name__c                    = 'Test';            
        RSVPCon.thisDelegate.Medical_Aid_Name__c                    = 'Test';            
        RSVPCon.thisDelegate.Medical_Aid_No__c                      = 'Test';                                   
        RSVPCon.thisDelegate.Medical_Conditions__c                  = 'Test';            
        RSVPCon.thisDelegate.Address__c                             = 'Test';                    
        RSVPCon.thisDelegate.Postal_Code__c                         = 'Test';            
        //RSVPCon.thisDelegate.Type_of_Identification__c              = 'Passport';              
        RSVPCon.thisDelegate.Availibility__C                        = 'Test';            
        RSVPCon.thisDelegate.Accessibility__C                       = 'Test';
        RSVPCon.thisDelegate.age__C                                 = 1;
        
        RSVPCon.ConfirmAccept();
        RSVPCon.accept1                                             = true;
        RSVPCon.ConfirmAccept();
        
        //RSVPCon.decline();
        RSVPCon.CancelAccept();
        //RSVPCon.thisDelegate.RSVP_Status__c = 'Pending Declined';
        update RSVPCon.thisDelegate;
        RSVPCon.CancelDecline();
        //RSVPCon.thisDelegate.RSVP_Status__c = 'Pending Accepted';
        update RSVPCon.thisDelegate;
        RSVPCon.CancelDecline();
        RSVPCon.getErrorsLevel1();
        RSVPCon.getHasErrorsLevel1(); 
        RSVPCon.GetCompanyOrIndividualBookingTypes();
        RSVPCon.getCurrencyOptions();
        RSVPCon.getDelegateTypes();
        RSVPCon.getDietOptions();
        RSVPCon.getEventGenderTypes();
        RSVPCon.getEventIndustryTypes();
        RSVPCon.getIdentificationTypes();
        
        delegate__c testDel = new delegate__c();
        
        RSVPCon.listOfPartnerDelegates.add(testDel);
        RSVPCon.InsertPartnerDelegates();
        
        testDel.Last_Name__c = 'test';
        testDel.First_Name__c  = 'test';
        testDel.Email__c = 'test@test.com';
        testDel.Partner_Type__c = 'Partner';
        testDel.Dietary_Requirement__c = 'None';
        
        RSVPCon.listOfPartnerDelegates.Clear();
        RSVPCon.listOfPartnerDelegates.add(testDel);
        try
        {
        RSVPCon.InsertPartnerDelegates();  
        } 
        catch(exception e)
        {}
    }    
}