objects/Delegate__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Delegates</relationshipLabel>
        <relationshipName>Delegates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>First_Name__c &amp; &quot; &quot; &amp; Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invitation_Status__c</fullName>
        <description>17-08-08 DH Added new field</description>
        <inlineHelpText>Manage the status of invitees until they are either approved to be invited to the event or not.  After this their status is tracked with RSVP Status and then Attendance Status</inlineHelpText>
        <label>Invitation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delegate_Invitation_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The attendnace status of the delegate indicating if he/she actaully attended the event.</inlineHelpText>
        <label>Attendance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delegate_Attendance_Statuses</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT( Event__r.Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Delegate</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Delegate #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Time_Text__c</fullName>
        <formula>TEXT(HOUR(EventEndTime__c)) &amp; &quot;:&quot; &amp; IF(MINUTE(EventEndTime__c) &lt; 10, TEXT(MINUTE(EventEndTime__c)) &amp; &quot;0&quot;, TEXT(MINUTE(EventEndTime__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Time (Text)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>00:00</fullName>
                </value>
                <value>
                    <fullName>00:30</fullName>
                </value>
                <value>
                    <fullName>01:00</fullName>
                </value>
                <value>
                    <fullName>01:30</fullName>
                </value>
                <value>
                    <fullName>02:00</fullName>
                </value>
                <value>
                    <fullName>02:30</fullName>
                </value>
                <value>
                    <fullName>03:00</fullName>
                </value>
                <value>
                    <fullName>03:30</fullName>
                </value>
                <value>
                    <fullName>04:00</fullName>
                </value>
                <value>
                    <fullName>04:30</fullName>
                </value>
                <value>
                    <fullName>05:00</fullName>
                </value>
                <value>
                    <fullName>05:30</fullName>
                </value>
                <value>
                    <fullName>06:00</fullName>
                </value>
                <value>
                    <fullName>06:30</fullName>
                </value>
                <value>
                    <fullName>07:00</fullName>
                </value>
                <value>
                    <fullName>07:30</fullName>
                </value>
                <value>
                    <fullName>08:00</fullName>
                </value>
                <value>
                    <fullName>08:30</fullName>
                </value>
                <value>
                    <fullName>09:00</fullName>
                </value>
                <value>
                    <fullName>09:30</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                </value>
                <value>
                    <fullName>10:30</fullName>
                </value>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Agenda__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Agenda</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Configuration__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Event_Agenda</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Configuration__c</referenceTo>
        <relationshipLabel>Events/Functions (Event Agenda)</relationshipLabel>
        <relationshipName>Events_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Configuration__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event Configuration</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Event_Configuration__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Event Config</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Event_Configuration__c</referenceTo>
        <relationshipLabel>Events/Functions (Event Configuration)</relationshipLabel>
        <relationshipName>Events1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time_Text__c</fullName>
        <formula>TEXT(HOUR(EventStartTime__c)) &amp; &quot;:&quot; &amp; IF(MINUTE(EventStartTime__c) &lt; 10, TEXT(MINUTE(EventStartTime__c)) &amp; &quot;0&quot;, TEXT(MINUTE(EventStartTime__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time (Text)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Theme</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a valid Theme</errorMessage>
            <filterItems>
                <field>Event_Configuration__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Event Themes</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Configuration__c</referenceTo>
        <relationshipName>Events_Using_This</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event/Function</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events/Functions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event_Configuration__c.object
<CustomObject>
    <description>Configurations relating to Event including Badges and Themes</description>
    <fields>
        <fullName>Agenda_Logo__c</fullName>
        <label>Agenda Logo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Disclaimer__c</fullName>
        <label>Disclaimer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Social</fullName>
                </value>
                <value>
                    <fullName>Cloudsmiths</fullName>
                </value>
                <value>
                    <fullName>SocialV2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Configuration</label>
    <nameField>
        <label>Event Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Session__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time_Text__c</fullName>
        <formula>TEXT(HOUR(End_Time__c)) &amp; &quot;:&quot; &amp; IF(MINUTE(End_Time__c) &lt; 10, TEXT(MINUTE(End_Time__c)) &amp; &quot;0&quot;, TEXT(MINUTE(End_Time__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Time (Text)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Event_Function__c</fullName>
        <label>Event/Function</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Agendas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Time_Text__c</fullName>
        <formula>TEXT(HOUR(Start_Time__c)) &amp; &quot;:&quot; &amp; IF(MINUTE(Start_Time__c) &lt; 10, TEXT(MINUTE(Start_Time__c)) &amp; &quot;0&quot;, TEXT(MINUTE(Start_Time__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time (Text)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Session_Booking__c.object
<CustomObject>
    <fields>
        <fullName>Delegate__c</fullName>
        <label>Delegate</label>
        <referenceTo>Delegate__c</referenceTo>
        <relationshipLabel>Booked Sessions</relationshipLabel>
        <relationshipName>Booked_Sessions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invitation_Status__c</fullName>
        <label>Invitation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Walk In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Event_Session__c</referenceTo>
        <relationshipLabel>Session Participants</relationshipLabel>
        <relationshipName>Session_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isSpeaker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Speaker</label>
        <type>Checkbox</type>
    </fields>
    <label>Session Booking</label>
    <nameField>
        <displayFormat>SB-{000000}</displayFormat>
        <label>Session Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Delegate_Attendance_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Attended_Partially</fullName>
        <label>Attended Partially</label>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>No Show</fullName>
    </customValue>
    <masterLabel>Delegate Attendance Statuses</masterLabel>
</GlobalValueSet>

globalValueSets/Delegate_Invitation_Statuses.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Proposed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Delegate Invitation Statuses</masterLabel>
</GlobalValueSet>

classes/evScheduleExtension_Controller.cls
public with sharing class evScheduleExtension_Controller {
   
    public Event__c event {get;set;}
    public Account acc {get;set;}
    public Id accId {get;set;}
    public List<Event_Session_Booking__c> sessionSpeakerList {get;set;}
    public Set<String> sessionSpeakerSet {get;set;}
    public List<dayGroupWrapper> groups {get; set;}
    public Event_Configuration__c agendaConfig {get;set;}
    
    //Delegate Fields
    public String delFirstName {get;set;}
    public String delLastName {get;set;}
    public String delCompany {get;set;}
    public String delTitle {get;set;}
    public String delMobile {get;set;}
    public String delEmail {get;set;}
    
    //Holds Temp Id for Session to book delegate on
    public String delAgendaItem {get;set;}
    
    public evScheduleExtension_Controller(ApexPages.StandardController stdController) {
        
        if (!Test.isRunningTest()) 
        { 
            stdController.addFields(new List<String>{'Event_Agenda__c', 'Theme__r.Template__c'});
        }
        
        event = (Event__c)stdController.getRecord();
        accId = ApexPages.currentPage().getParameters().get('accId'); 
        
        String eventId = event.Id;
        
        if (accId != null) 
        {
            acc = 
                [
                    SELECT
                    Id,
                    Name
                    FROM
                    Account
                    WHERE
                    Id =: accId
                    LIMIT 1
                ];
        }
        
        if(event.Event_Agenda__c != null)
        {
            agendaConfig = 
                [
                    SELECT
                    Id,
                    Disclaimer__c,
                    Agenda_Logo__c 
                    FROM
                    Event_Configuration__c 
                    WHERE
                    Id =: event.Event_Agenda__c
                ];
        }
        
        sessionSpeakerList = 
            [
                SELECT
                Id,
                Delegate__r.Full_Name__c
                FROM
                Event_Session_Booking__c 
                WHERE
                Session__r.Event_Function__c =: event.Id
                AND
                isSpeaker__c = true
                AND
                Invitation_Status__c = 'Confirmed'
            ];
        
        //Add speakers to Set to dedup
        sessionSpeakerSet = new Set<String>();
        
        for(Event_Session_Booking__c sb : sessionSpeakerList)
        {
            sessionSpeakerSet.add(sb.Delegate__r.Full_Name__c);
        }
        
        List<Event_Session__c> sessionList = new List<Event_Session__c>();
        
        String queryString = 
            'SELECT Id, Name, Date__c, Start_Time__c, Start_Time_Text__c, End_Time__c, End_Time_Text__c, Type__c, ' +
            'Scheduled_Delegates_Confirmed__c, Session_Bookings_Walk_Ins__c, Room__r.Name, Participating_Company__r.Name, ' +
            '(SELECT Id, Session__c, Event_Id__c, Session__r.Date__c, Session__r.Start_Time__c, ' +
            'Session__r.Start_Time_Text__c, Session__r.End_Time_Text__c, Session__r.End_Time__c, Session__r.Type__c, ' +
            'Session__r.Room__r.Name, Session__r.Participating_Company__r.Name, Delegate__r.Full_Name__c, ' +
            'Delegate__r.Company__c, Delegate__r.Contact__r.Name, Delegate__r.Account__r.Name, Invitation_Status__c, ' +
            'Attendance_Status__c ' +
            'FROM Session_Bookings__r ' +
            'WHERE (Invitation_Status__c = \'Confirmed\' OR Invitation_Status__c = \'Walk In\') AND isSpeaker__c != true) ' +
            'FROM Event_Session__c WHERE Event_Function__c =: eventId AND Scheduled_Delegates_Confirmed__c > 0';
        
        if (accid != null)
        {
            queryString += ' AND Participating_Company__c =: accId';
        }
        
        queryString += ' ORDER BY Date__c, Start_Time__c';
        
        sessionList = Database.query(queryString);
        
        Map<String, List<Event_Session__c>> groupedMap = new Map<String, List<Event_Session__c>>();
        for (Event_Session__c session : sessionList)
        {
            Date d = session.Date__c;
            String key = DateTime.newInstance(d.year(),d.month(),d.day()).format('EEEE, MMM d, YYYY');
            
            List<Event_Session__c> groupedSessions = groupedMap.get(key);
            if (null==groupedSessions)
            {
                groupedSessions=new List<Event_Session__c>();
                groupedMap.put(key, groupedSessions);
            }
            
            groupedSessions.add(session);
        }
        
        groups = new List<dayGroupWrapper>();
        
        for (String key : groupedMap.keySet())
        {
            dayGroupWrapper gr = new dayGroupWrapper();
            groups.add(gr);
            gr.sessions = groupedMap.get(key);
            gr.groupedVal = key;
        }

    }
    
    @RemoteAction
    public static pageReference updateAttendance(String sdId, String attStatus)
    {
        
        Event_Session_Booking__c sbToUpdate =
            [
                SELECT
                Id,
                Attendance_Status__c
                FROM
                Event_Session_Booking__c
                WHERE
                Id =: sdId
            ];
        
        sbToUpdate.Attendance_Status__c = attStatus;
        
        update sbToUpdate;
        
        return null;
        
    }
    
    public pageReference addWalkIn() 
    {
        Delegate__c del = new Delegate__c();
        del.Event__c = event.Id;
        del.First_Name__c = delFirstName;
        del.Last_Name__c = delLastName;
        del.Company__c = delCompany;
        del.Mobile__c = delMobile;
        del.Title__c = delTitle;
        del.Email__c = delEmail;
        del.Registration_Status__c = 'Walk In';
        del.Registered_Date__c = DateTime.now();
        del.Walk_In__c = true;
        del.Status__c = 'Attended';
        del.CheckIn_Date__c = DateTime.now();      
        
        insert del;
        
        system.debug('delAgendaItem: ' + delAgendaItem);
        
        Event_Session_Booking__c sb = new Event_Session_Booking__c();
        sb.Delegate__c = del.Id;
        sb.Invitation_Status__c = 'Walk In';
        sb.Attendance_Status__c = 'Attended';
        sb.Session__c = delAgendaItem;
        
        insert sb;
        
        pageReference pg = new PageReference('/apex/evAttendanceRegister?id=' + event.Id);
        pg.setRedirect(true);
        return pg;
    }

    public class dayGroupWrapper
    {
        public List<Event_Session__c> sessions {get; set;}
        public String groupedVal {get; set;}
    }

}