objects/Event__c.object
<CustomObject>
    <label>Event/Function</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events/Functions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event_Team_Member__c.object
<CustomObject>
    <description>Event Team Members</description>
    <fields>
        <fullName>Event_Team_Member_Role__c</fullName>
        <description>Event Team Member Roles</description>
        <inlineHelpText>Roles of Event Team Members Specific to the Event</inlineHelpText>
        <label>Event Team Member Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Event_Team_Member_Role</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Event Specific to Event Team Members</description>
        <inlineHelpText>Event Specific to Event Team Members</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Event_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maximum_Number_of_Actual_Invitees__c</fullName>
        <description>Maximum number of guests per Event Team Member</description>
        <inlineHelpText>Maximum number of guests for this Event Team Member. This is the Maximum Number of your Invitees that can attend, which will be Decided based on the Prioritised List which will need to be Approved by the Event Coordinator and Compliance Prior.</inlineHelpText>
        <label>Maximum Guests</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Number_of_Proposed_Invitees__c</fullName>
        <description>Maximum Number of Proposed Invitees</description>
        <inlineHelpText>Maximum Number of Proposed Invitees. This is the Maximum Number of Invitees that you can propose for the event.</inlineHelpText>
        <label>Maximum Invitees</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event Team Member Name</description>
        <inlineHelpText>Event Team Member Name and Salesforce User</inlineHelpText>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Member</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Team Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Event_Team_Member_Role.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Host</fullName>
        <default>true</default>
        <label>Host</label>
    </customValue>
    <customValue>
        <fullName>Sponsor</fullName>
    </customValue>
    <customValue>
        <fullName>Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Requestor</fullName>
    </customValue>
    <masterLabel>Event Team Member Role</masterLabel>
</GlobalValueSet>

classes/evEventTeamMember_Trigger_test.cls
/**
* Author : Daniel Field
* Date   : 2017-10-26
* Desc   : Test class for the evEventTeamMember_Trigger
**/
@isTest
public class evEventTeamMember_Trigger_test 
{
    static testMethod void testAddContactsToEventExtr()
    {
        
        evTestDataGenerator testData = new evTestDataGenerator();
        Event_Team_Member__c  TestEventTeamMemmber = 
            [
                SELECT
                id
                FROM
                Event_Team_Member__c
                Limit 1 
            ];
        
        evTriggerHelperClass.evEventTeamMember_Trigger_FirstRun =  true;
        
        Delete TestEventTeamMemmber;
        
        evTriggerHelperClass.evEventTeamMember_Trigger_FirstRun =  true;
        
        id CurrentUserID =userInfo.getUserId();
        
        id userID = [SELECT id FROM USER WHERE isActive = true AND profile.name = 'Barclays Administrator' and id != : CurrentUserID limit 1].id;
        system.debug('userID' + userID);
        system.debug('CurrentUserID' + CurrentUserID);
        Event_Team_Member__c ETM = new Event_Team_Member__c
            (
                Event__c 								= testData.TestEvent.id,
                Team_Member__c 							= userID,
                Maximum_Number_of_Actual_Invitees__c 	= 0,
                Maximum_Number_of_Proposed_Invitees__c 	= 0,
                Event_Team_Member_Role__c 				= 'Coordinator'
            );
        insert ETM;
        evTriggerHelperClass.evEventTeamMember_Trigger_FirstRun =  true;
        delete ETM;
    }
    
    
}