objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Capacity_Status__c</fullName>
        <formula>IF(Number_Registered__c &lt; Capacity__c*0.9, &quot;Available&quot;, 
   IF (Number_Registered__c &lt; Capacity__c, &quot;Limited&quot;, 
          IF (Number_Registered__c = Capacity__c, &quot;Full&quot;, &quot;Overbooked&quot;)
       )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Capacity Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Event Capacity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Cities_For_Events</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries_For_Events</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration_Units__c</fullName>
        <label>Duration Units</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Day(s)</fullName>
                    <default>true</default>
                    <label>Day(s)</label>
                </value>
                <value>
                    <fullName>Hour(s)</fullName>
                </value>
                <value>
                    <fullName>Minute(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>Enter value as per duration unit.</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventEndTime__c</fullName>
        <label>Event End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>EventStartTime__c</fullName>
        <label>Event Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Hide__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Leave &quot;unchecked&quot; to make this show on the Calendar, else tick to hide the event.</inlineHelpText>
        <label>Hide Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Trainer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Registered__c</fullName>
        <inlineHelpText>The total number of delegates that are registered for the event including accepted invitations and open registrations.</inlineHelpText>
        <label>Number Registered</label>
        <summaryFilterItems>
            <field>Delegate__c.Registration_Status__c</field>
            <operation>equals</operation>
            <value>Accepted, Registered, Confirmed</value>
        </summaryFilterItems>
        <summaryForeignKey>Delegate__c.Event__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Outside_Trainer__c</fullName>
        <label>Outside Trainer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>User Group</fullName>
                </value>
                <value>
                    <fullName>Breakfast</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Dinner</fullName>
                </value>
                <value>
                    <fullName>Cocktail Party</fullName>
                </value>
                <value>
                    <fullName>Analyst Marketing: Roadshow</fullName>
                </value>
                <value>
                    <fullName>Company Marketing: Roadshow</fullName>
                </value>
                <value>
                    <fullName>Client Conference Calls</fullName>
                </value>
                <value>
                    <fullName>Bespoke Client Meetings</fullName>
                </value>
                <value>
                    <fullName>Company/Site Visits</fullName>
                </value>
                <value>
                    <fullName>Conference</fullName>
                </value>
                <value>
                    <fullName>Industry Expert Event</fullName>
                </value>
                <value>
                    <fullName>Investor/Sector Field Trip</fullName>
                </value>
                <value>
                    <fullName>Management Meeting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.City__c</field>
                <operation>equals</operation>
                <valueField>Venue__c.City__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>Venue__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Events/Functions</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event/Function</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events/Functions</pluralLabel>
    <recordTypes>
        <fullName>Archived</fullName>
        <active>true</active>
        <label>Archived</label>
    </recordTypes>
    <recordTypes>
        <fullName>Event_Request</fullName>
        <active>true</active>
        <description>Request to Host an Event</description>
        <label>Event Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Venue__c.object
<CustomObject>
    <description>Details of venues for Events</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Cities_For_Events</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries_For_Events</valueSetName>
        </valueSet>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Cities_For_Events.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accra</fullName>
    </customValue>
    <customValue>
        <fullName>Barcelona</fullName>
    </customValue>
    <customValue>
        <fullName>Bethlehem</fullName>
    </customValue>
    <customValue>
        <fullName>Blantyre</fullName>
    </customValue>
    <customValue>
        <fullName>Bloemfontein</fullName>
    </customValue>
    <customValue>
        <fullName>Cape Town</fullName>
    </customValue>
    <customValue>
        <fullName>Dar Es Salaam</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Durban</fullName>
    </customValue>
    <customValue>
        <fullName>East London</fullName>
    </customValue>
    <customValue>
        <fullName>Ebene</fullName>
    </customValue>
    <customValue>
        <fullName>Francis Town</fullName>
    </customValue>
    <customValue>
        <fullName>Gaborone</fullName>
    </customValue>
    <customValue>
        <fullName>George</fullName>
    </customValue>
    <customValue>
        <fullName>Harare</fullName>
    </customValue>
    <customValue>
        <fullName>Johannesburg</fullName>
        <default>true</default>
        <label>Johannesburg</label>
    </customValue>
    <customValue>
        <fullName>Kampala</fullName>
    </customValue>
    <customValue>
        <fullName>Kigali</fullName>
    </customValue>
    <customValue>
        <fullName>Kimberley</fullName>
    </customValue>
    <customValue>
        <fullName>Lagos</fullName>
    </customValue>
    <customValue>
        <fullName>Lisbon</fullName>
    </customValue>
    <customValue>
        <fullName>London</fullName>
    </customValue>
    <customValue>
        <fullName>Lusaka</fullName>
    </customValue>
    <customValue>
        <fullName>Mafikeng</fullName>
    </customValue>
    <customValue>
        <fullName>Nairobi</fullName>
    </customValue>
    <customValue>
        <fullName>Nelspruit</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Polokwane</fullName>
    </customValue>
    <customValue>
        <fullName>Port Elizabeth</fullName>
    </customValue>
    <customValue>
        <fullName>Port Louis</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <masterLabel>Cities For Events</masterLabel>
</GlobalValueSet>

globalValueSets/Countries_For_Events.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi</fullName>
    </customValue>
    <customValue>
        <fullName>Abu Dhabi Global Market</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Ajman</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>Countries For Events</masterLabel>
</GlobalValueSet>

classes/evCalendarComp_Controller.cls
/****************************************************************************
* @Author     : Daniel Field
* @Date       : 13/10/2016
* @Description: Controller class used for the Full calendar on the caseware community training pages, Fetches events and puts them in a unique list that is used by the Calendar JS
* @Purpose    : Controller class
* @Pages      :
* @Test Class : CQS_CasewareBookingController_Test
* @Notes : It takes 5 paremeters,
EventIDforcal - value of ID paremeter in the page URL
queryStart - datetime in miliseconds for the select
queryStart - datetime in miliseconds for the select
EventType  - The Type of event that will be selected, if left blank then it is not used as criteria
CourseID   - The ID of the course that events being selected should be linked to, If Left blank then it is not used as criteria
//----------------------------------------------------------------------------*/
Global class evCalendarComp_Controller 
{
    @RemoteAction
    global static list<calendarEvent> getEvents(id EventIDforcal, double queryStart, double queryEnd, String EventType, string coursetype ,  String CourseIDString , String EventCity)
    {
        try
        {
            ID Courseid;
            String eventQueryString;
            
            if(CourseIDString != null && CourseIDString != '')
            {
                Courseid =     id.valueOf(CourseIDString);
            }
            
            list<calendarEvent> events = new list<calendarEvent>();
            
            datetime startDate = datetime.newInstance(0);
            Integer startInt = integer.valueOf(queryStart);
            startDate = startDate.addSeconds(startInt);
            
            datetime endDate = datetime.newInstance(0);
            Integer endInt = integer.valueOf(queryEnd);
            endDate = endDate.addSeconds(endInt);
            
            //List used to exclude "Other" cities in City filter
            List<String> namedCities = new List<String>();
            namedCities.add('Johannesburg'); 
            namedCities.add('Durban'); 
            namedCities.add('Cape Town'); 
            namedCities.add('East London'); 
            namedCities.add('Port Elizabeth'); 
            namedCities.add('Bloemfontein'); 
            namedCities.add('Nelspruit'); 
            namedCities.add('Polokwane'); 
            
            
            //List used to group "Customer" course types 
            List<String> customerList = new List<String>();
            customerList.add('Customer'); 
            customerList.add('Marketing'); 
            customerList.add('User Group'); 
            
            List<String> StringOfEventTypesForQuery = new List<String>(); 
            list<event__c> EventList;
            
            String startdatestring = startDate.format('yyyy-MM-dd');
            
            String enddatestring = endDate.format('yyyy-MM-dd');
            
            String todaydatestring = DateTime.now().format('yyyy-MM-dd');
            
            eventQueryString=   
                'SELECT '+ 
                    'Name,'+
                    'Owner.Name,' +
                    'Start_Date__c,'+
                    'End_Date__c,'+
                    'EventStartTime__c,'+
                    'EventEndTime__c,'+
                    'Duration__c,'+
                    'Duration_Units__c,'+
                    'Type__c, '+
                    'City__c,'+
                    'Country__c,'+
                    'Venue__r.Name, '+
                    'Venue__r.Address__c, '+
                    'Capacity_Status__c, ' +
                    'Capacity__c, ' +
                    'Number_Registered__c, ' +
                    'Internal_Trainer__r.Name, '+
                    'Internal_Trainer__r.FullPhotoUrl, '+
                    'Outside_Trainer__c '+
                'FROM '+
                	'event__c '+
                'WHERE '+
                	'(RecordType.DeveloperName != \'Archived\' AND RecordType.DeveloperName != \'Event_Request\') ' +
                ' AND '+
                	'Hide__c = false';
                    
            system.debug('EventType : '+ EventType);
            if (EventType != null && EventType != '')
            {
                eventQueryString += ' AND Type__c =: EventType ';
            }
            
            EventList = new list<event__c>();
            List<sObject> sobjListOfEvents =  new List<sObject>();
            
            sobjListOfEvents =   Database.query(eventQueryString);
            
            EventList = sobjListOfEvents;
            
            for(event__c e : EventList)
            {
                calendarEvent thisEvent = new calendarEvent();
                
                thisEvent.id = e.id;
                thisEvent.title = e.name;       
                if( e.EventStartTime__c != null)
                {
                    
                    thisEvent.startTime = string.valueof(e.EventStartTime__c).left(5);
                }
                else
                {
                    thisEvent.startTime = 'TBC';
                }
                
                if( e.EventEndTime__c != null)
                {
                    thisEvent.endTime = string.valueof(e.EventEndTime__c).left(5);
                }
                else
                {
                    thisEvent.endTime = 'TBC';
                }
                
                thisEvent.venue = e.Venue__r.name;
                thisEvent.address = e.Venue__r.Address__c + ', ' + e.City__C + ', ' + e.Country__C;
                thisEvent.allDay = false;
                thisEvent.color = '#006991';
                
                if (e.Type__c == 'Customer' || e.Type__c == 'User Group' || e.Type__c == 'Marketing')
                {
                    thisEvent.color = '#77b800';
                }
                if (e.Type__c == 'Training' )
                {
                    thisEvent.color = '#006991';
                }
                if (e.Type__c == 'Webinar' )
                {
                    thisEvent.color = '#51626F';
                }
                
                if (e.City__C != null)
                {
                    if (e.City__C == 'Johannesburg')
                    {
                        thisEvent.title = 'JHB - '+  +thisEvent.title;
                    }
                    else if (e.City__C == 'Cape Town')
                    {
                        thisEvent.title = 'CPT - '+  +thisEvent.title;
                    }
                    else if (e.City__C == 'Durban')
                    {
                        thisEvent.title = 'DBN - '+  +thisEvent.title;
                    }                    
                    else
                    {
                        thisEvent.title = 'Other - '+  +thisEvent.title;
                    }
                }
                
                if (e.Capacity_Status__c == 'Full' || e.Capacity_Status__c == 'Overbooked')// if No spaces are availible put 'FULL' in front of event name and make it red
                {
                    thisEvent.title = 'FULL: '+  +thisEvent.title;
                    thisEvent.color = 'Red';
                   // thisEvent.space = 'hidden';
                }
                
                thisEvent.title += ' ('+e.Number_Registered__c + '/' + e.Capacity__c + ')';
                
                datetime StartDateTimeReplacement = e.Start_Date__c;
                datetime EndDateTimeReplacement = e.End_Date__c;
                
                double startDateTime 	= (dateTime.valueOf(StartDateTimeReplacement).getTime());
                double endDateTime 		= (dateTime.valueOf(EndDateTimeReplacement).getTime());
                
                thisEvent.start 	=	startDateTime;
                thisEvent.Eventend 	=	endDateTime;
                
                thisEvent.detailData = new map<string,string>();
                
                thisEvent.detailData.put('Name', e.name);
                thisEvent.detailData.put('Start date', e.Start_Date__c.format());
                thisEvent.detailData.put('End date', e.End_Date__c.format());
                
                if(e.Internal_Trainer__c != null && e.Internal_Trainer__r.name != null)
                {
                    thisEvent.detailData.put('trainer_name',  e.Internal_Trainer__r.name);
                    if(e.Internal_Trainer__r.FullPhotoUrl != null)
                    {
                        thisEvent.detailData.put('trainer_avatar', e.Internal_Trainer__r.FullPhotoUrl);
                    }
                    Else
                    {
                        thisEvent.detailData.put('trainer_avatar','https://c.eu7.content.force.com/servlet/servlet.ImageServer?id=0150J000003rPRs&oid=00D20000000BO9d');
                    }
                }
                else if(e.Internal_Trainer__c == null && e.Outside_Trainer__c != null)
                {
                    thisEvent.detailData.put('trainer_name',  e.Outside_Trainer__c);
                    thisEvent.detailData.put('trainer_avatar','https://c.eu7.content.force.com/servlet/servlet.ImageServer?id=0150J000003rPRs&oid=00D20000000BO9d');
                }
                else
                {
                    thisEvent.detailData.put('trainer_name',  e.owner.name);
                    thisEvent.detailData.put('trainer_avatar','https://c.eu7.content.force.com/servlet/servlet.ImageServer?id=0150J000003rPRs&oid=00D20000000BO9d');
                }
                thisEvent.detailData.put('duration',  e.Duration__c + ' ' + e.Duration_Units__c);
                PageReference prEvent =  new PageReference('/'+ e.id);
                thisEvent.detailData.put('event_url', prEvent.getUrl());
                events.add(thisEvent);
            }
            system.debug('events ' + events);
            return events;
        }
        Catch(Exception e)
        {
            return null;
            // do nothing as the calendar doesn't output an error
        }
        
    }
    Global class calendarEvent
    {
        string id{get;set;}
        string title{get;set;}
        string courseType{get;set;}
        string space{get;set;}
        string city{get;set;}
        string address{get;set;}
        string country{get;set;}
        string venue{get;set;}
        string color{get;set;}
        boolean allDay{get;set;}
        string startTime{get;set;}
        string endTime{get;set;}
        double start{get;set;}
        double Eventend{get;set;}
        string url{get;set;}
        map<string,string> detailData{get;set;}
        boolean editable{get;set;}
    }
}