objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Event Capacity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event/Function</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events/Functions</pluralLabel>
    <recordTypes>
        <fullName>Function</fullName>
        <active>true</active>
        <description>Social Engagement with Clients including Dinners/Breakfasts/Hospitality</description>
        <label>Function</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/evCalendarComp_Controller_test.cls
@isTest
public class evCalendarComp_Controller_test
{
    /****************************************************************************
* @Author     : Daniel Field
* @Date       : 13/11/2016
* @Description: Controller class used for the caseware CQS_TrainingCalendar_Controller
* @Purpose    : Test class
* @Class 	  : CQS_TrainingCalendar_Controller 
//----------------------------------------------------------------------------*/
    
    static testMethod void evCalendarComp_Controller_test()
    {
        
        evTestDataGenerator TDG = new evTestDataGenerator();
        TDG.TestEvent.Capacity__c = 0;
        update TDG.TestEvent;
        
        recordType FunctionRecType = 
            [
                SELECT
                id,
                name
                from
                recordType
                where
                developerName = 'Function'
                AND
                SobjectType = 'Event__c'
            ];
        
        TDG.TestEvent.recordtypeID = FunctionRecType.id;
        UPdate TDG.TestEvent;
        
        datetime startdate;
        startdate =  datetime.now();
        datetime enddate ;
        enddate =  datetime.now();
        enddate = enddate.addDays(31);
        
        PageReference pageRef = Page.evEventCalendar;
        Test.setCurrentPage(pageRef);    	    	
        
        evCalendarComp_Controller ConTest = new evCalendarComp_Controller();
        
        system.debug('startdate.getTime() :  '+ startdate.getTime());
        
        evCalendarComp_Controller.getEvents(TDG.TestEvent.id, startdate.getTime()/1000, enddate.getTime()/1000, '', '','','');
        
    }
    
}