objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Booking_Online_for_New_Customers__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Online Bookings for New Customers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Badge_Style__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select the badge template to be used for printed badges for this event</inlineHelpText>
        <label>Badge Style</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a valid badge</errorMessage>
            <filterItems>
                <field>Event_Configuration__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Event Badges</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Event_Configuration__c</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Event Capacity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dietary_Requirements_Requiring_Payment__c</fullName>
        <inlineHelpText>Semi-colon separated list of dietary requirements that require payment when selected, leave blank if all are free.</inlineHelpText>
        <label>Dietary Requirements Requiring Payment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Discount_2__c</fullName>
        <label>Discount 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Discount_Threshold_2__c</fullName>
        <label>Discount Threshold 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Threshold__c</fullName>
        <label>Discount Threshold</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_Number_Passport_at_Booking__c</fullName>
        <label>ID Number/Passport at Booking</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes - Mandatory</fullName>
                </value>
                <value>
                    <fullName>Yes - Optional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_have_read_Absa_Event_Governance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I have read Absa Event Governance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Online_Processing__c</fullName>
        <label>Online Processing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Create Opportunity; Optional Payment</fullName>
                </value>
                <value>
                    <fullName>Create Opportunity; Mandatory Payment</fullName>
                </value>
                <value>
                    <fullName>Do Not Create an Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Book_Entry_Id__c</fullName>
        <label>Price Book Entry Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Process__c</fullName>
        <label>Registration Process</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complex</fullName>
                    <label>Complex (Groups)</label>
                </value>
                <value>
                    <fullName>Simple</fullName>
                    <default>true</default>
                    <label>Simple (Individual)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Use_Ticket_Types_Batches__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Ticket Types/Batches</label>
        <type>Checkbox</type>
    </fields>
    <label>Event/Function</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events/Functions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event_Team_Member__c.object
<CustomObject>
    <description>Event Team Members</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Event Specific to Event Team Members</description>
        <inlineHelpText>Event Specific to Event Team Members</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Event_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Event Team Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/evEventMemberTrigger_Test.cls
/**
* Author : Rudolf Niehaus
* Date   : 2017-08-09
* Desc   : Test class for the Event_Team_Member__c tigger and trigger functions class evEventMemberTriggerFunctions
* Note Event_Team_Member__c for test is generated automatically by evEvent_trigger when new event created
**/
@isTest
public class evEventMemberTrigger_Test
{
    
    static testMethod void testEventMemberTrigger()
    {
        
        Test.startTest();
        //TEST DATA
        evTestDataGenerator testData = new evTestDataGenerator();
        
        Event__c TestEvent2  = new Event__c
            (
                Name = 'Test Event2', 
                Capacity__c = 2, 
                Start_Date__c = Date.today(),  
                End_Date__c = Date.today()+3,
                Discount_2__c = 10, 
                Discount__c = 5, 
                Discount_Threshold__c = 1, 
                Discount_Threshold_2__c = 2, 
                Online_Processing__c = 'Create Opportunity; Optional Payment' ,
                Currencyisocode='ZAR',
                Allow_Booking_Online_for_New_Customers__c = true,
                ID_Number_Passport_at_Booking__c = 'No',
                //Product__c = testData.Testproduct.Id,
                //PriceBook__c = test.getStandardPricebookId(),
                //Price_Book_Entry_id__c = testData.TestPricebookEntry.id,
                Use_Ticket_Types_Batches__c = True,
                Dietary_Requirements_Requiring_Payment__c =  'Kosher',
                Badge_Style__c = testData.TestBadgeEventConfig.id,
                Registration_Process__c = 'Simple',
                I_have_read_Absa_Event_Governance__c = true
            );
        
        insert TestEvent2;
        
        list<Event_Team_Member__c> teamList = new list<Event_Team_Member__c>();
        
        Event_Team_Member__c testTM =  
            [
                SELECT
                id
                FROM
                Event_Team_Member__c
                WHERE 
                EVent__C = : TestEvent2.id
                Limit 1
            ];
        
        delete testTM;
        
        Test.stopTest();
        
    }
}