objects/Fit_To_Lend_Checklist__c.object
<CustomObject>
    <customHelpPage>General_Deal_Management</customHelpPage>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipName>Fit_to_Lend</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fit To Lend Checklist</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Fit to Lend No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fit To Lend Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Fit_To_Lend_Trigger_Test.cls
@isTest(SeeAllData=false)
private class Fit_To_Lend_Trigger_Test 
{
    static testMethod void testUpdate()
    {
        Cloudsmiths_TestDataClass testData = new Cloudsmiths_TestDataClass();

        Contact random = new Contact(LastName = 'Smit', FirstName = 'Jan', Email = 'test@fakeDomadin.com');
        insert random;

        Fit_To_Lend_Checklist__c testRecord = new Fit_To_Lend_Checklist__c(Deal__c = testData.TestMatter.Id, Status__c = 'New');
        insert testRecord;

        Attachment file = new Attachment(ParentId = testRecord.Id, Body = Blob.valueOf('Blob'), Name = 'Test File', Description = 'System Generated');
        insert file;
        
        Test.startTest();

        testRecord.Status__c = 'Approved';
        update testRecord;

        Test.stopTest();
    }   
}