objects/Integration_Settings_General__mdt.object
<CustomObject>
    <description>RN - CloudSmiths 
General settings for outbound REST integrations</description>
    <fields>
        <fullName>ClientID__c</fullName>
        <label>Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentType__c</fullName>
        <label>Content Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>End Point</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Integration Settings General</label>
    <pluralLabel>Integration Settings General</pluralLabel>
</CustomObject>

objects/SWIFT_Message__c.object
<CustomObject>
    <description>RN - CloudSmiths 
Object stores new and updated SWIFT Messages related to a Payments Case</description>
    <fields>
        <fullName>Answers__c</fullName>
        <label>Answers</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ApproveMessage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>RN - CloudSmiths - Related payments case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SWIFT Messages</relationshipLabel>
        <relationshipName>SWIFT_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DateOfOriginalMessage__c</fullName>
        <description>Date of the original message</description>
        <label>Date of Original Message</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DestinationAddress__c</fullName>
        <label>Destination Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MT_the_Original_Message__c</fullName>
        <label>MT &amp; the Original Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MessageType__c</fullName>
        <label>Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>192</fullName>
                </value>
                <value>
                    <fullName>195</fullName>
                </value>
                <value>
                    <fullName>196</fullName>
                </value>
                <value>
                    <fullName>199</fullName>
                </value>
                <value>
                    <fullName>292</fullName>
                </value>
                <value>
                    <fullName>295</fullName>
                </value>
                <value>
                    <fullName>296</fullName>
                </value>
                <value>
                    <fullName>299</fullName>
                </value>
                <value>
                    <fullName>999</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Narrative_OriginalMsg__c</fullName>
        <label>Narrative OriginalMsg</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Narrative__c</fullName>
        <label>Narrative</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OriginalSWIFTId__c</fullName>
        <formula>Case__r.SWIFTId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Original SWIFT Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queries__c</fullName>
        <label>Queries</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RejectMessage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RelatedReference__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Related Reference</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Address__c</fullName>
        <defaultValue>&quot;ABSAZAJ0AXXX&quot;</defaultValue>
        <label>Sender Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusUpdate__c</fullName>
        <description>RN - CloudSmiths - Successes or failure and message response from Meridian when pushing SWIFT messages out from SF</description>
        <label>Status Update</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TransactionReference__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Transaction Reference</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>SWIFT Message</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Message Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SWIFT Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Payments_Outbound_SWIFT.cls
/**
* Date:  2017-08
* Autor: Rudolf Niehaus - CloudSmiths
* Desc:  RESTful Apex service for the SWIFT integration
**/
public class Payments_Outbound_SWIFT {

    public static String msgId = '';
    public static String msgName = '';
    
    public static void postToSWIFT(SWIFT_Message__c newMsg){
        
        msgId = newMsg.Id;
        msgName = newMsg.Name;
        String answers = '';
        String destinationAddress = '';
        Integer messageType = 0;
        String narrative = '';
        String narrativeOrig = '';
        String queries = '';
        String relatedReference = '';
        String salesforceId = '';
        String senderAddress = newMsg.Sender_Address__c;
        
        Long swiftId = 0;
        
        if(String.isNotBlank(newMsg.OriginalSWIFTId__c)){
            swiftId = Long.valueOf(newMsg.OriginalSWIFTId__c);
        }
        
        String transactionReference = '';
        
        //validation
        if(String.isNotBlank(newMsg.Answers__c)){
            answers = newMsg.Answers__c;
        }
        if(String.isNotBlank(newMsg.DestinationAddress__c)){
            destinationAddress = newMsg.DestinationAddress__c;
        }
        if(String.isNotBlank(newMsg.MessageType__c)){
            messageType = Integer.valueOf(newMsg.MessageType__c);
        }
        if(String.isNotBlank(newMsg.Narrative_OriginalMsg__c)){
            narrativeOrig = newMsg.Narrative_OriginalMsg__c;
        }
        if(String.isNotBlank(newMsg.Narrative__c))
        {
            narrative = newMsg.Narrative__c;
        }
        if(String.isNotBlank(newMsg.Queries__c)){
            queries = newMsg.Queries__c;
        }
        if(String.isNotBlank(newMsg.RelatedReference__c)){
            relatedReference = newMsg.RelatedReference__c;
        }
        if(String.isNotBlank(newMsg.Id)){
            salesforceId = newMsg.Case__c;
        }
        if(String.isNotBlank(newMsg.TransactionReference__c)){
            transactionReference = newMsg.TransactionReference__c;
            
            if(String.isNotBlank(newMsg.DateOfOriginalMessage__c ) && String.isNotBlank(newMsg.MT_the_Original_Message__c )){
                transactionReference = transactionReference+' ; '+newMsg.MT_the_Original_Message__c + '\n' + newMsg.DateOfOriginalMessage__c;
            }
        }
        
        //build JSON file
        JSONGenerator gen = JSON.createGenerator(true);
       
        gen.writeStartObject();
        
        gen.writeStringField('answers', answers);
        gen.writeStringField('destinationAddress', destinationAddress);
        gen.writeNumberField('messageType',messageType);
        gen.writeStringField('narrativeOriginalMsg',narrativeOrig);
        gen.writeStringField('narrative',narrative);
        gen.writeStringField('queries',queries);
        gen.writeStringField('relatedReference',relatedReference);
        gen.writeStringField('salesforceId',salesforceId);
        gen.writeStringField('senderAddress',senderAddress);
        gen.writeNumberField('swiftId', swiftId );
        gen.writeStringField('transactionReference',transactionReference);
        
        gen.writeEndObject();
        
        System.debug(gen.getAsString());
        
        doHttpPost(gen.getAsString(), msgId, msgName);            
        
    }
    
    @future (callout=true)
    private static void doHttpPost(String jsonBody, String msgId, String msgName) {
        
        //get api settings for Sf 2 SWIFT
        list<Integration_Settings_General__mdt> mdt = [Select ClientID__c, ClientSecret__c, ContentType__c, EndPoint__c 
                                                       From Integration_Settings_General__mdt  
                                                      Where DeveloperName = 'SF_2_SWIFT'];
        if(mdt.size() > 0){
            try{                        
                HttpRequest req = new HttpRequest();
                req.setMethod('POST');
                req.setTimeout(120000);
                req.setEndpoint(mdt[0].EndPoint__c);
                req.setHeader('Content-Type', mdt[0].ContentType__c);
                req.setHeader('X-IBM-Client-Id', mdt[0].ClientID__c);
                req.setHeader('X-IBM-Client-Secret', mdt[0].ClientSecret__c);
                req.setBody(jsonBody);
                
                Http http = new Http();
                HttpResponse response =  http.send(req);
                
                //handle response
                String jsonstr = response.getBody();
                System.debug(jsonstr);
                map<String, Object> objMap = (map<String, Object>)JSON.deserializeUntyped(jsonstr);
    
                logResults(objMap, msgId, msgName);            

                
            }catch(System.CalloutException e) {
                System.debug('CalloutException!');
                System.debug(e.getMessage());
            }
        }else{
            System.debug('There are no settings defined for the Sf to SWIFt API');
        }
    }
    
    public static void logResults(map<String, Object> theResult, String msgId, String msgName){
        
        
        String message = (String)theResult.get('message');
        String swiftMessage = (String)theResult.get('swiftMessage');
        String salesforceId = (String)theResult.get('salesforceId');
        Boolean success = (Boolean)theResult.get('sucess');
        
        SWIFT_Message__c updateMsg = [Select StatusUpdate__c From SWIFT_Message__c Where Id = :msgId];
        
        if(success != null){
            if(success){
                 updateMsg.StatusUpdate__c = 'Approved and Sent:\n' + swiftMessage;
            }else{
                updateMsg.StatusUpdate__c = 'Failed : \n' + message;
                updateMsg.RejectMessage__c = true;
                updateMsg.ApproveMessage__c = false;
            }        
        }else{
            updateMsg.StatusUpdate__c = 'No Information Available';
            updateMsg.RejectMessage__c = true;
            updateMsg.ApproveMessage__c = false;
        }
        
        try{
            update updateMsg;
        }catch(DMLexception ex){
            System.debug(ex.getMessage());
        }
        
        //Create new feeditem on the parent case

        FeedItem logmsg = new Feeditem();
        logmsg.ParentId = salesforceId;
        if(success != null){
            if(success){
                 logmsg.Body = msgName + ' Approved and Sent : ' + swiftMessage;
                 logmsg.Title = msgName + 'Approved and Sent : ' + swiftMessage;
            }else{
                logmsg.Title = msgName + ' Failed : ' + message;
                logmsg.Body = msgName + ' Failed : ' + message;
            }        
        }else{
            logmsg.Title = 'No Information Available';
            logmsg.Body = 'No Information Available';
        }
        try{
            insert logmsg;
        }catch(DMLexception ex){
            System.debug(ex.getMessage());
        }
    }
}