objects/Integration_Settings_General__mdt.object
<CustomObject>
    <description>RN - CloudSmiths 
General settings for outbound REST integrations</description>
    <fields>
        <fullName>ClientID__c</fullName>
        <label>Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentType__c</fullName>
        <label>Content Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>End Point</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Integration Settings General</label>
    <pluralLabel>Integration Settings General</pluralLabel>
</CustomObject>

classes/Payments_Outbound_Statements.cls
/**
* Date:  2017-09
* Autor: Rudolf Niehaus - CloudSmiths
* Desc:  Outbound API call to MIDAS Statements
**/
public class Payments_Outbound_Statements {

    public static Payments_JSON2ApexStat jsonclass = new Payments_JSON2ApexStat();
    
    public static Payments_JSON2ApexStat postToMIDAS(String CUST,String CURR,String ACOD,String ACSQ,String FDATE,String TDATE,String STYPE,String SPAGE,String SLINE) {
        
        //build JSON file
        JSONGenerator gen = JSON.createGenerator(true);
        
        gen.writeStartObject();
        
        gen.writeStringField('CUST',CUST);
        gen.writeStringField('CURR',CURR);
        gen.writeStringField('ACOD',ACOD);
        gen.writeStringField('ACSQ',ACSQ);
        gen.writeStringField('FDATE',FDATE);
        gen.writeStringField('TDATE',TDATE);
        gen.writeStringField('STYPE',STYPE);
        gen.writeStringField('SPAGE',SPAGE);
        gen.writeStringField('SLINE',SLINE);
        
        gen.writeEndObject();
        
        doHttpPost(gen.getAsString()); 
        
        return jsonclass;
    }
    
    //@future (callout=true)
    private static void doHttpPost(String jsonBody) {
       
        list<Integration_Settings_General__mdt> mdt = [Select ClientID__c, ClientSecret__c, ContentType__c, EndPoint__c 
                                                       From Integration_Settings_General__mdt  
                                                       Where DeveloperName = 'SF_2_MIDAS_STAT'];
        if(mdt.size() > 0){
            try{                        
                HttpRequest req = new HttpRequest();
                req.setMethod('POST');
                req.setTimeout(120000);
                req.setEndpoint(mdt[0].EndPoint__c);
                req.setHeader('Content-Type', mdt[0].ContentType__c);
                req.setHeader('X-IBM-Client-Id', mdt[0].ClientID__c);
                req.setHeader('X-IBM-Client-Secret', mdt[0].ClientSecret__c);
                
                req.setBody(jsonBody);
                
                Http http = new Http();
                HttpResponse response =  http.send(req);
                
                //get response json back into apex classes
                jsonclass = Payments_JSON2ApexStat.parse(response.getBody());

            }catch(System.CalloutException e) {
                System.debug('CalloutException!');
                System.debug(e.getMessage());
            }
        }else{
            System.debug('There are no settings defined for the Sf to MIDAS Statement API');
        }
    }
 
}