objects/JLOC__c.object
<CustomObject>
    <label>JLOC</label>
    <nameField>
        <displayFormat>JLOC-{000000}</displayFormat>
        <label>JLOC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JLOC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/JLOC_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Coverage</fullName>
                </value>
                <value>
                    <fullName>Investment Banking</fullName>
                </value>
                <value>
                    <fullName>Portfolio Management</fullName>
                </value>
                <value>
                    <fullName>Markets</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JLOC__c</fullName>
        <label>JLOC</label>
        <referenceTo>JLOC__c</referenceTo>
        <relationshipLabel>JLOC Attendees</relationshipLabel>
        <relationshipName>JLOC_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Present__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Present</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>JLOC_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>JLOC Attendee</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>JLOC Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JLOC Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ZZTEST_JLOC_CheckPresenceController.cls
/**
* @Author   Marta Malinowska
* @Company: Deloitte
* @Description Unit Tests for JLOC_CheckPresenceController
*              Tests executed:
*               1 - testCheckPresence()
*                   Test that JLOC Attendees Present field is updated.
*               2 - testCheckPresenceDmlExeption()
*                   Test that DML Exceptions are displayed.
*/
@isTest
private class ZZTEST_JLOC_CheckPresenceController {

	public static testMethod void testCheckPresence(){

		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_JLOC jlocFactory = ZZTEST_DataFactoryFacade.jloc;

        JLOC__c jloc = jlocFactory.getInsertedProduct(ZZTEST_F_JLOC.JlocRecordType.DEFAULT_JLOC, dataContainer);

        List<JLOC_Attendee__c> jlocAttendees = new List<JLOC_Attendee__c>();
        jlocAttendees.add(new JLOC_Attendee__c(JLOC__c = jloc.Id, Group__c = 'Other', User__c = UserInfo.getUserId()));
        insert jlocAttendees;
        
        Test.startTest();

		PageReference JLOC_CheckPresence = Page.JLOC_CheckPresence;
        Test.setCurrentPage(JLOC_CheckPresence);

        ApexPages.currentPage().getParameters().put('id', jloc.Id);
    	Apexpages.Standardcontroller stc = new ApexPages.StandardController(jloc);
        JLOC_CheckPresenceController controller = new JLOC_CheckPresenceController(stc);

        for(JLOC_Attendee__c attendee : controller.jlocAttendees){
        	attendee.Present__c = true;
        }

        controller.save();

        for(JLOC_Attendee__c jlocAttendee : [SELECT Id, Present__c FROM JLOC_Attendee__c WHERE JLOC__c = :jloc.Id]){
            System.assertEquals(jlocAttendee.Present__c, true);
        }

        Test.stopTest();
	}

	public static testMethod void testCheckPresenceDmlExeption(){

		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_JLOC jlocFactory = ZZTEST_DataFactoryFacade.jloc;

        JLOC__c jloc = jlocFactory.getInsertedProduct(ZZTEST_F_JLOC.JlocRecordType.DEFAULT_JLOC, dataContainer);

        List<JLOC_Attendee__c> jlocAttendees = new List<JLOC_Attendee__c>();
        jlocAttendees.add(new JLOC_Attendee__c(JLOC__c = jloc.Id, Group__c = 'Other', User__c = UserInfo.getUserId()));
        insert jlocAttendees;
        
        Test.startTest();

		PageReference JLOC_CheckPresence = Page.JLOC_CheckPresence;
        Test.setCurrentPage(JLOC_CheckPresence);

        ApexPages.currentPage().getParameters().put('id', jloc.Id);
    	Apexpages.Standardcontroller stc = new ApexPages.StandardController(jloc);
        JLOC_CheckPresenceController controller = new JLOC_CheckPresenceController(stc);

        for(JLOC_Attendee__c attendee : controller.jlocAttendees){
        	attendee.Present__c = null;
        }

        controller.save();

        System.assertEquals(ApexPages.getMessages().size(), controller.jlocAttendees.size());

        Test.stopTest();
	}
}