objects/JLOC__c.object
<CustomObject>
    <label>JLOC</label>
    <nameField>
        <displayFormat>JLOC-{000000}</displayFormat>
        <label>JLOC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JLOC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/JLOC_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>JLOC__c</fullName>
        <label>JLOC</label>
        <referenceTo>JLOC__c</referenceTo>
        <relationshipLabel>JLOC Attendees</relationshipLabel>
        <relationshipName>JLOC_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>JLOC Attendee</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>JLOC Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JLOC Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/JLOC_ApprovalProcessUtils.cls
public without sharing class JLOC_ApprovalProcessUtils {
	public static String STATUS_SENT_TO_COMMITTEE = 'Sent to Committee';

	public JLOC_ApprovalProcessUtils() {}

	public static void insertJlocAttendees(List<JLOC_Attendee__c> jlocAttendees){
		insert jlocAttendees;
	}

	public static void updateJlocAttendees(List<JLOC_Attendee__c> jlocAttendees){
		update jlocAttendees;
	}

	public static void updateJloc(JLOC__c jloc){
		update jloc;
	}
}