objects/Legal_Performance_Questionnaire__c.object
<CustomObject>
    <description>Legal Post Invoice Surveys</description>
    <fields>
        <fullName>LawFirm__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>On/Off Panel Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Legal Performance Questionnaires</relationshipLabel>
        <relationshipName>Legal_Performance_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MatterSpendDocument__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Matter Spend Document</label>
        <referenceTo>Matter_Spend_Document__c</referenceTo>
        <relationshipLabel>Legal Performance Questionnaires</relationshipLabel>
        <relationshipName>Legal_Performance_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Legal Performance Questionnaires</relationshipLabel>
        <relationshipName>Legal_Performance_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Legal Performance Questionnaire</label>
    <nameField>
        <displayFormat>Survey-{0000}</displayFormat>
        <label>Legal Questionnaire Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legal Performance Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Matter_Spend_Document__c.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>On/Off Panel Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matter Spend Documents</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <label>Matter</label>
        <referenceTo>advpm__Matter__c</referenceTo>
        <relationshipLabel>Matter Spend Document</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Matter Spend Document</label>
    <nameField>
        <displayFormat>MSD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matter Spend Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuestionnaireRedirect.cls
public class QuestionnaireRedirect {
    
    public id matter_spend_document_id {get; set;}
    public Matter_Spend_Document__c msd {get; set;}
    public Legal_Performance_Questionnaire__c lpq {get; set;}

    public QuestionnaireRedirect(ApexPages.StandardController controller){
        matter_spend_document_id = apexpages.currentpage().getparameters().get('id');
        msd = [select Law_Firm__c, id, Matter__c from Matter_Spend_Document__c where id = :matter_spend_document_id limit 1];
        
        lpq = new Legal_Performance_Questionnaire__c();
        lpq.LawFirm__c = msd.Law_Firm__c;
        lpq.MatterSpendDocument__c = msd.id;
        lpq.Matter__c = msd.Matter__c;
    }
}