objects/Matrix_Lead__c.object
<CustomObject>
    <customHelpPage>Help_for_Matrix_Lead</customHelpPage>
    <description>This Object will store all  the leads received from matrix, on quarterly basis.</description>
    <fields>
        <fullName>Assignment_Date__c</fullName>
        <description>Date the lead was assigned to the banker</description>
        <label>Assignment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contacted_Date__c</fullName>
        <description>Date on which the Lead was contacted</description>
        <label>Contacted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Conversion_Deadline__c</fullName>
        <label>Conversion Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Assignment</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>REF_NO_F__c</fullName>
        <formula>IF(CONTAINS(REF_NO__c, &quot; &quot;), LEFT(REF_NO__c, FIND(&quot; &quot;, REF_NO__c)-1), REF_NO__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>REF NO F</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REF_NO__c</fullName>
        <label>REF NO</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_unqualified_leads__c</fullName>
        <description>Reasons to provide why the lead was unqualified</description>
        <label>Reason for unqualified leads</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Could not get decision</fullName>
                </value>
                <value>
                    <fullName>Inaccurate data</fullName>
                </value>
                <value>
                    <fullName>Inconvenient timing</fullName>
                </value>
                <value>
                    <fullName>No Longer with the Company</fullName>
                </value>
                <value>
                    <fullName>No response</fullName>
                </value>
                <value>
                    <fullName>Not interested</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Extension_30_days__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requested Extension (30 days)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sector_Head_Email__c</fullName>
        <label>Sector Head Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Specify_Other__c</fullName>
        <description>Specify the reason why the lead was unqualified</description>
        <label>Specify Other</label>
        <type>TextArea</type>
    </fields>
    <label>Matrix Lead</label>
    <nameField>
        <displayFormat>ML-{0000}</displayFormat>
        <label>Matrix Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrix Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MatrixLeadSelectionLimit__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to manage the maximum number of unconverted matrix leads that a user can own</description>
    <fields>
        <fullName>Maximum_Number_of_Leads_Allowed__c</fullName>
        <description>Maximum number of unconverted matrix leads that a user is able to own</description>
        <label>Maximum Number of Leads Allowed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MatrixLeadSelectionLimit</label>
</CustomObject>

classes/MatrixLeadTriggerHelper.cls
/**
* @Author       Marta Malinowska
* Company:      Deloitte
* @Description: This class is used in trigger: MartixLeadTrigger.
* @Date:        10/2015
* @ConstructorParam:    None
* @TestClass:   ZZTEST_MatrixLeadTriggerHelper
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* 02/12/2015  Marta Malinowska   Add validation to check if user has up to 5 Open Matrix Leads.
* 04/12/2015  Marta Malinowska   Add methods to assign owner, set Lead Status and Conversion Deadline within the same company.
* 12/01/2016  Marta Malinowska   Match Matrix Leads within the same company by REF NO F.
* 15/01/2016  Marta Malinowska   Fix copy Comments and Reason for unqualified leads - copy every time the field is changed (not only when status is changed).
* 31/03/2016  Masie Maseli       Changed the Validation of the Open Leads from a number to a Hierachal Custom Setting
*------------------------------------------------------------*/
public class MatrixLeadTriggerHelper {
    public static String STATUS_OPEN = 'Open';
    public static String STATUS_PENDING_ASSIGNMENT = 'Pending Assignment';
    public static String STATUS_ASSIGNED = 'Assigned';
    public static String STATUS_CONTACTED = 'Contacted';
    public static String STATUS_UNQUALIFIED = 'Unqualified';
    public static String STATUS_CONVERTED = 'Converted';
    public static String QUEUE_UNASSIGNED_LEADS = 'Unassigned';

    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used to set status to "Open" and assign Matrix Lead to Unassigned Leads queue.
    * @param        List of Matrix Leads
    * @Returns:     None
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    *------------------------------------------------------------*/
    public static void setStatusOpenAndAssignToQueue(List<Matrix_Lead__c> matrixLeads){
        Group unassignedLeadsQueue;
        try{
            unassignedLeadsQueue = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND DeveloperName = :QUEUE_UNASSIGNED_LEADS];
        } catch(QueryException ex){
            System.debug('QUEUE QUERY EXCEPTION: '+ex);
        }
        for(Matrix_Lead__c matrixLead : matrixLeads){
            matrixLead.Lead_Status__c = STATUS_OPEN;
            if(unassignedLeadsQueue != null){
                matrixLead.OwnerId = unassignedLeadsQueue.Id;
            }
        }
    }

    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used to validate if new owner has no more than 5 Open Matrix Leads.
    * @param        Map of Matrix Leads with old values
    * @param        Map of Matrix Leads with new values
    * @Returns:     None
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    * 31/03/2016   Masie Maseli       Changed the Validation of the Open Leads from a number to a Hierachal Custom Setting
    *------------------------------------------------------------*/
    public static void validateIfNewOwnerHasUpTo5OpenLeads(Map<Id, Matrix_Lead__c> oldMatrixLeads, Map<Id, Matrix_Lead__c> newMatrixLeads){
        Matrix_Lead__c newMatrixLead;
        Matrix_Lead__c oldMatrixLead;
        Map<Id, Set<String>> companyRefNosByOwnerMap = new Map<Id, Set<String>>();
        Map<Id, List<Matrix_Lead__c>> matrixLeadsByOwnerMap = new Map<Id, List<Matrix_Lead__c>>();
        MatrixLeadSelectionLimit__c cs = MatrixLeadSelectionLimit__c.getInstance();
         
         

        for(Id matrixLeadId : newMatrixLeads.keySet()){
            newMatrixLead = newMatrixLeads.get(matrixLeadId);
            oldMatrixLead = oldMatrixLeads.get(matrixLeadId);
            if(newMatrixLead.OwnerId != oldMatrixLead.OwnerId && newMatrixLead.OwnerId.getSObjectType() == User.SObjectType){
                if(matrixLeadsByOwnerMap.containsKey(newMatrixLead.OwnerId)){
                    matrixLeadsByOwnerMap.get(newMatrixLead.OwnerId).add(newMatrixLead);
                } else{
                    matrixLeadsByOwnerMap.put(newMatrixLead.OwnerId, new List<Matrix_Lead__c>{newMatrixLead});
                }
                if(companyRefNosByOwnerMap.containsKey(newMatrixLead.OwnerId)){
                    companyRefNosByOwnerMap.get(newMatrixLead.OwnerId).add(newMatrixLead.REF_NO_F__c);
                } else{
                    companyRefNosByOwnerMap.put(newMatrixLead.OwnerId, new Set<String>{newMatrixLead.REF_NO_F__c});
                }
            }
        }
        if(matrixLeadsByOwnerMap.size() > 0){
            for(Matrix_Lead__c matrixLead : [SELECT Id, Name, OwnerId, REF_NO_F__c, Owner.UserRole.Name FROM Matrix_Lead__c 
                                                WHERE Lead_Status__c != :STATUS_UNQUALIFIED AND Lead_Status__c != :STATUS_CONVERTED
                                                AND OwnerId IN :matrixLeadsByOwnerMap.keySet()]){
                if(companyRefNosByOwnerMap.containsKey(matrixLead.OwnerId)){
                    companyRefNosByOwnerMap.get(matrixLead.OwnerId).add(matrixLead.REF_NO_F__c);
                } else{
                    companyRefNosByOwnerMap.put(matrixLead.OwnerId, new Set<String>{matrixLead.REF_NO_F__c});
                }
            }
            for(Id ownerId : companyRefNosByOwnerMap.keySet()){
                if(companyRefNosByOwnerMap.get(ownerId).size() > cs.Maximum_Number_of_Leads_Allowed__c){
                    for(Matrix_Lead__c matrixLead : matrixLeadsByOwnerMap.get(ownerId)){
                        matrixLead.addError(Label.errMsg_Only5OpenMatrixLeadsAllowed);
                    }
                }
            }
        }
    }

    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used to set Sector Head email.
    * @param        Map of Matrix Leads with old values
    * @param        Map of Matrix Leads with new values
    * @Returns:     None
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    *------------------------------------------------------------*/
    public static void setSectorHeadEmail(Map<Id, Matrix_Lead__c> oldMatrixLeads, Map<Id, Matrix_Lead__c> newMatrixLeads){
        Matrix_Lead__c oldMatrixLead;
        Matrix_Lead__c newMatrixLead;

        List<Matrix_Lead__c> matrixLeadsToUpd = new List<Matrix_Lead__c>();
        Set<Id> ownerIds = new Set<Id>();
        
        for(Id matrixLeadId : newMatrixLeads.keySet()){
            oldMatrixLead = oldMatrixLeads.get(matrixLeadId);
            newMatrixLead = newMatrixLeads.get(matrixLeadId);
            if(newMatrixLead.OwnerId != oldMatrixLead.OwnerId){
                matrixLeadsToUpd.add(newMatrixLead);
                ownerIds.add(newMatrixLead.OwnerId);
            }
        }

        Map<Id, User> mapUsers = new Map<Id, User>([SELECT Id, Manager.Email FROM User WHERE Id IN :ownerIds]);

        for(Matrix_Lead__c matrixLead : matrixLeadsToUpd){
            if(mapUsers.containsKey(matrixLead.OwnerId)){
                matrixLead.Sector_Head_Email__c = mapUsers.get(matrixLead.OwnerId).Manager.Email;
            } else{
                matrixLead.Sector_Head_Email__c = '';
            }
        }
    }

    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used to set contacted and conversion dates.
    * @param        Map of Matrix Leads with old values
    * @param        Map of Matrix Leads with new values
    * @Returns:     None
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    *------------------------------------------------------------*/
    public static void setContactedAndConversionDates(Map<Id, Matrix_Lead__c> oldMatrixLeads, Map<Id, Matrix_Lead__c> newMatrixLeads){
        Matrix_Lead__c oldMatrixLead;
        Matrix_Lead__c newMatrixLead;

        for(Id matrixLeadId : newMatrixLeads.keySet()){
            oldMatrixLead = oldMatrixLeads.get(matrixLeadId);
            newMatrixLead = newMatrixLeads.get(matrixLeadId);
            if(newMatrixLead.Lead_Status__c != oldMatrixLead.Lead_Status__c && newMatrixLead.Lead_Status__c == STATUS_CONTACTED){
                if(newMatrixLead.Assignment_Date__c != null){
                    newMatrixLead.Contacted_Date__c = Date.today();
                }
                newMatrixLead.Conversion_Deadline__c = Date.today().addDays(60);
            }
        }
    }

    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used change the owner for Matrix Lead within the same company.
    * @param        Map of Matrix Leads with old values
    * @param        Map of Matrix Leads with new values
    * @Returns:     None
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    *------------------------------------------------------------*/
    public static void assignMatrixLeadOwnersWithinTheSameCompany(Map<Id, Matrix_Lead__c> oldMatrixLeads, Map<Id, Matrix_Lead__c> newMatrixLeads){
        Matrix_Lead__c oldMatrixLead;
        Matrix_Lead__c newMatrixLead;
        Map<String, Matrix_Lead__c> mapMatrixLeadsByRefNos = new Map<String, Matrix_Lead__c>();
        for(Id matrixLeadId : newMatrixLeads.keySet()){
            oldMatrixLead = oldMatrixLeads.get(matrixLeadId);
            newMatrixLead = newMatrixLeads.get(matrixLeadId);
            if(newMatrixLead.OwnerId != oldMatrixLead.OwnerId && (newMatrixLead.Lead_Status__c == STATUS_OPEN 
                    || newMatrixLead.Lead_Status__c == STATUS_PENDING_ASSIGNMENT || newMatrixLead.Lead_Status__c == STATUS_ASSIGNED) 
                    && newMatrixLead.REF_NO__c != null ){
                mapMatrixLeadsByRefNos.put(newMatrixLead.REF_NO_F__c, newMatrixLead);
            }
        }

        List<Matrix_Lead__c> matrixLeadsToUpdate = new List<Matrix_Lead__c>();
        for(Matrix_Lead__c matrixLeadToUpd : [SELECT Id, OwnerId, REF_NO_F__c, Lead_Status__c FROM Matrix_Lead__c 
                                        WHERE REF_NO_F__c IN :mapMatrixLeadsByRefNos.keySet()]){
            Matrix_Lead__c matrixLeadToRef = mapMatrixLeadsByRefNos.get(matrixLeadToUpd.REF_NO_F__c);
            if(matrixLeadToUpd.OwnerId != matrixLeadToRef.OwnerId){
                matrixLeadToUpd.OwnerId = matrixLeadToRef.OwnerId;
                matrixLeadsToUpdate.add(matrixLeadToUpd);
            }
        }

        update matrixLeadsToUpdate;
    }

    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used change the Lead Status for Matrix Lead within the same company.
    * @param        Map of Matrix Leads with old values
    * @param        Map of Matrix Leads with new values
    * @Returns:     None
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    *------------------------------------------------------------*/
    public static void assignMatrixLeadStatusesWithinTheSameCompany(Map<Id, Matrix_Lead__c> oldMatrixLeads, Map<Id, Matrix_Lead__c> newMatrixLeads){
        Matrix_Lead__c newMatrixLead;
        Matrix_Lead__c oldMatrixLead;
        Map<String, Matrix_Lead__c> mapMatrixLeadsByRefNos = new Map<String, Matrix_Lead__c>();
        for(Id matrixLeadId : newMatrixLeads.keySet()){
            newMatrixLead = newMatrixLeads.get(matrixLeadId);
            oldMatrixLead = oldMatrixLeads.get(matrixLeadId);
            if(newMatrixLead.Lead_Status__c != oldMatrixLead.Lead_Status__c && (newMatrixLead.Lead_Status__c == STATUS_OPEN 
                    || newMatrixLead.Lead_Status__c == STATUS_PENDING_ASSIGNMENT || newMatrixLead.Lead_Status__c == STATUS_ASSIGNED
                    || newMatrixLead.Lead_Status__c == STATUS_CONTACTED || newMatrixLead.Lead_Status__c == STATUS_UNQUALIFIED)
                    && newMatrixLead.REF_NO__c != null){
                mapMatrixLeadsByRefNos.put(newMatrixLead.REF_NO_F__c, newMatrixLead);
            }
        }

        Group unassignedLeadsQueue;
        try{
            unassignedLeadsQueue = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND DeveloperName = :QUEUE_UNASSIGNED_LEADS];
        } catch(QueryException ex){
            System.debug('QUEUE QUERY EXCEPTION: '+ex);
        }

        List<Matrix_Lead__c> matrixLeadsToUpdate = new List<Matrix_Lead__c>();
        for(Matrix_Lead__c matrixLeadToUpd : [SELECT Id, REF_NO_F__c, Lead_Status__c, OwnerId, Comments__c, Reason_for_unqualified_leads__c, Specify_Other__c
                                            FROM Matrix_Lead__c WHERE REF_NO_F__c IN :mapMatrixLeadsByRefNos.keySet()]){
            Matrix_Lead__c matrixLeadToRef = mapMatrixLeadsByRefNos.get(matrixLeadToUpd.REF_NO_F__c);
            if(matrixLeadToUpd.Lead_Status__c != matrixLeadToRef.Lead_Status__c){
                matrixLeadToUpd.Lead_Status__c = matrixLeadToRef.Lead_Status__c;
                if(matrixLeadToRef.Lead_Status__c == STATUS_OPEN && unassignedLeadsQueue != null){
                    matrixLeadToUpd.OwnerId = unassignedLeadsQueue.Id;
                    matrixLeadToUpd.Assignment_Date__c = null;
                    matrixLeadToUpd.Contacted_Date__c = null;
                    matrixLeadToUpd.Conversion_Deadline__c = null;
                    matrixLeadToUpd.Requested_Extension_30_days__c = false;
                }
                if(matrixLeadToRef.Lead_Status__c == STATUS_CONTACTED){
                    matrixLeadToUpd.Comments__c = matrixLeadToRef.Comments__c;
                }
                if(matrixLeadToRef.Lead_Status__c == STATUS_UNQUALIFIED){
                    matrixLeadToUpd.Reason_for_unqualified_leads__c = matrixLeadToRef.Reason_for_unqualified_leads__c;
                    matrixLeadToUpd.Specify_Other__c = matrixLeadToRef.Specify_Other__c;
                }
                matrixLeadsToUpdate.add(matrixLeadToUpd);
            }
        }

        update matrixLeadsToUpdate;
    }
    
    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used change the Comments for Matrix Lead within the same company.
    * @param        Map of Matrix Leads with old values
    * @param        Map of Matrix Leads with new values
    * @Returns:     None
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    *------------------------------------------------------------*/
    public static void setCommentsWithinTheSameCompany(Map<Id, Matrix_Lead__c> oldMatrixLeads, Map<Id, Matrix_Lead__c> newMatrixLeads){
        Matrix_Lead__c newMatrixLead;
        Matrix_Lead__c oldMatrixLead;
        Map<String, Matrix_Lead__c> mapMatrixLeadsByRefNos = new Map<String, Matrix_Lead__c>();
        for(Id matrixLeadId : newMatrixLeads.keySet()){
            newMatrixLead = newMatrixLeads.get(matrixLeadId);
            oldMatrixLead = oldMatrixLeads.get(matrixLeadId);
            if(newMatrixLead.Comments__c != oldMatrixLead.Comments__c && newMatrixLead.Lead_Status__c == oldMatrixLead.Lead_Status__c && newMatrixLead.REF_NO__c != null){
                mapMatrixLeadsByRefNos.put(newMatrixLead.REF_NO_F__c, newMatrixLead);
            }
        }

        List<Matrix_Lead__c> matrixLeadsToUpdate = new List<Matrix_Lead__c>();
        for(Matrix_Lead__c matrixLeadToUpd : [SELECT Id, REF_NO_F__c, Comments__c FROM Matrix_Lead__c 
                                            WHERE REF_NO_F__c IN :mapMatrixLeadsByRefNos.keySet()]){
            Matrix_Lead__c matrixLeadToRef = mapMatrixLeadsByRefNos.get(matrixLeadToUpd.REF_NO_F__c);
            if(matrixLeadToUpd.Comments__c != matrixLeadToRef.Comments__c){
                matrixLeadToUpd.Comments__c = matrixLeadToRef.Comments__c;
                matrixLeadsToUpdate.add(matrixLeadToUpd);
            }
        }

        update matrixLeadsToUpdate;
    }

    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used change the Reason for Unqualified leads for Matrix Lead within the same company.
    * @param        Map of Matrix Leads with old values
    * @param        Map of Matrix Leads with new values
    * @Returns:     None
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    *------------------------------------------------------------*/
    public static void setReasonForUnqualifiedWithinTheSameCompany(Map<Id, Matrix_Lead__c> oldMatrixLeads, Map<Id, Matrix_Lead__c> newMatrixLeads){
        Matrix_Lead__c newMatrixLead;
        Matrix_Lead__c oldMatrixLead;
        Map<String, Matrix_Lead__c> mapMatrixLeadsByRefNos = new Map<String, Matrix_Lead__c>();
        for(Id matrixLeadId : newMatrixLeads.keySet()){
            newMatrixLead = newMatrixLeads.get(matrixLeadId);
            oldMatrixLead = oldMatrixLeads.get(matrixLeadId);
            if((newMatrixLead.Reason_for_unqualified_leads__c != oldMatrixLead.Reason_for_unqualified_leads__c || newMatrixLead.Specify_Other__c != oldMatrixLead.Specify_Other__c) 
                && newMatrixLead.Lead_Status__c == oldMatrixLead.Lead_Status__c && newMatrixLead.REF_NO__c != null){
                mapMatrixLeadsByRefNos.put(newMatrixLead.REF_NO_F__c, newMatrixLead);
            }
        }

        List<Matrix_Lead__c> matrixLeadsToUpdate = new List<Matrix_Lead__c>();
        for(Matrix_Lead__c matrixLeadToUpd : [SELECT Id, REF_NO_F__c, Reason_for_unqualified_leads__c, Specify_Other__c FROM Matrix_Lead__c 
                                            WHERE REF_NO_F__c IN :mapMatrixLeadsByRefNos.keySet()]){
            Matrix_Lead__c matrixLeadToRef = mapMatrixLeadsByRefNos.get(matrixLeadToUpd.REF_NO_F__c);
            if(matrixLeadToUpd.Reason_for_unqualified_leads__c != matrixLeadToRef.Reason_for_unqualified_leads__c || matrixLeadToUpd.Specify_Other__c != matrixLeadToRef.Specify_Other__c){
                matrixLeadToUpd.Reason_for_unqualified_leads__c = matrixLeadToRef.Reason_for_unqualified_leads__c;
                matrixLeadToUpd.Specify_Other__c = matrixLeadToRef.Specify_Other__c;
                matrixLeadsToUpdate.add(matrixLeadToUpd);
            }
        }

        update matrixLeadsToUpdate;
    }

    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used change the Conversion Deadline for Matrix Lead within the same company.
    * @param        Map of Matrix Leads with old values
    * @param        Map of Matrix Leads with new values
    * @Returns:     None
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    *------------------------------------------------------------*/
    public static void setConversionDeadlineWithinTheSameCompany(Map<Id, Matrix_Lead__c> oldMatrixLeads, Map<Id, Matrix_Lead__c> newMatrixLeads){
        Matrix_Lead__c newMatrixLead;
        Matrix_Lead__c oldMatrixLead;
        Map<String, Matrix_Lead__c> mapMatrixLeadsByRefNos = new Map<String, Matrix_Lead__c>();
        for(Id matrixLeadId : newMatrixLeads.keySet()){
            newMatrixLead = newMatrixLeads.get(matrixLeadId);
            oldMatrixLead = oldMatrixLeads.get(matrixLeadId);
            if(newMatrixLead.Conversion_Deadline__c != oldMatrixLead.Conversion_Deadline__c && newMatrixLead.REF_NO__c != null){
                mapMatrixLeadsByRefNos.put(newMatrixLead.REF_NO_F__c, newMatrixLead);
            }
        }

        List<Matrix_Lead__c> matrixLeadsToUpdate = new List<Matrix_Lead__c>();
        for(Matrix_Lead__c matrixLeadToUpd : [SELECT Id, REF_NO_F__c, Conversion_Deadline__c FROM Matrix_Lead__c 
                                            WHERE REF_NO_F__c IN :mapMatrixLeadsByRefNos.keySet()]){
            Matrix_Lead__c matrixLeadToRef = mapMatrixLeadsByRefNos.get(matrixLeadToUpd.REF_NO_F__c);
            if(matrixLeadToUpd.Conversion_Deadline__c != matrixLeadToRef.Conversion_Deadline__c){
                matrixLeadToUpd.Conversion_Deadline__c = matrixLeadToRef.Conversion_Deadline__c;
                matrixLeadToUpd.Requested_Extension_30_days__c = matrixLeadToRef.Requested_Extension_30_days__c;
                matrixLeadsToUpdate.add(matrixLeadToUpd);
            }
        }

        update matrixLeadsToUpdate;
    }
}