objects/Matrix_Lead__c.object
<CustomObject>
    <customHelpPage>Help_for_Matrix_Lead</customHelpPage>
    <description>This Object will store all  the leads received from matrix, on quarterly basis.</description>
    <fields>
        <fullName>Assignment_Date__c</fullName>
        <description>Date the lead was assigned to the banker</description>
        <label>Assignment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assignment_Request_Date__c</fullName>
        <label>Assignment Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contacted_Date__c</fullName>
        <description>Date on which the Lead was contacted</description>
        <label>Contacted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Conversion_Deadline__c</fullName>
        <label>Conversion Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Assignment</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>REF_NO__c</fullName>
        <label>REF NO</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_unqualified_leads__c</fullName>
        <description>Reasons to provide why the lead was unqualified</description>
        <label>Reason for unqualified leads</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Could not get decision</fullName>
                </value>
                <value>
                    <fullName>Inaccurate data</fullName>
                </value>
                <value>
                    <fullName>Inconvenient timing</fullName>
                </value>
                <value>
                    <fullName>No Longer with the Company</fullName>
                </value>
                <value>
                    <fullName>No response</fullName>
                </value>
                <value>
                    <fullName>Not interested</fullName>
                </value>
                <value>
                    <fullName>Other(please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Extension_30_days__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requested Extension (30 days)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sector_Head_Email__c</fullName>
        <label>Sector Head Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specify_Other__c</fullName>
        <description>Specify the reason why the lead was unqualified</description>
        <label>Specify Other</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unique_External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Matrix Lead</label>
    <nameField>
        <displayFormat>ML-{0000}</displayFormat>
        <label>Matrix Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrix Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ZZTEST_MatrixLeadTriggerHelper.cls
/**
* @Author   Marta Malinowska
* @Company: Deloitte
* @Description Unit Tests for MatrixLeadTriggerHelper
*              Tests executed:
*               1 - tesSetStatusOpenAndAssignToQueue()
*                   Test that Unique External Id is set and Matrix Lead is assign to Unassigned Leads queue.
*               2 - testMatrixLeadOwnerAssignmentRequest()
*                   Test that all Matrix Lead within the same company are set to status "Pending Assignment".
*				3 - testMatrixLeadOwnerAssignmentRejected()
*                   Test that all Matrix Lead within the same company are assigned back to queue if request is rejected.
*               4 - testMatrixLeadOwnerAssignmentApproved()
*                   Test that all Matrix Lead within the same company are assigned to banker if request is approved.
*               5 - testMatrixLeadBackToUnassignedQueue()
*                   Test that all Matrix Lead within the same company are assigned back to the Unassigned queue.
*               6 - testMatrixLeadMoveToStatusContacted()
*                   Test that all Matrix Lead within the same company are set to status "Contacted".
*               7 - testMatrixLeadMoveToStatusUnqualified()
*                   Test that all Matrix Lead within the same company are set to status "Unqualified".
*               8 - testMatrixLeadExtensionApproved()
*                   Tests that conversion deadline date is extended for all Matrix Leads within the same company if request is approved.
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* 07/12/2015  Marta Malinowska    Add test methods for owner assignment and extension approval processes 
* 12/01/2016  Marta Malinowska   Change tests to match Matrix Leads within the same company by REF NO F.
* ----------------------------------------------------------------------------*/
@isTest
private class ZZTEST_MatrixLeadTriggerHelper {

	public static testMethod void tesSetStatusOpenAndAssignToQueue(){
		Integer BATCH_SIZE = 200;
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
		ZZTEST_F_MatrixLead matrixLeadFactory = ZZTEST_DataFactoryFacade.matrixLead;

		Group unassignedLeads = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND DeveloperName = :MatrixLeadTriggerHelper.QUEUE_UNASSIGNED_LEADS];

		List<Matrix_Lead__c> matrixLeads = new List<Matrix_Lead__c>();
		for(Integer i=0; i<BATCH_SIZE; i++){
			Matrix_Lead__c matrixLead = matrixLeadFactory.getProduct(ZZTEST_F_MatrixLead.MatrixLeadRecordType.DEFAULT_MATRIX_LEAD, dataContainer);
			matrixLead.Sequence__c = String.valueOf(i);
			matrixLeads.add(matrixLead);
		}

        Test.startTest();

        insert matrixLeads;

        Test.stopTest();

        Set<Id> matrixLeadIds = new Set<Id>();
        for(Matrix_Lead__c matrixLead : matrixLeads){
        	matrixLeadIds.add(matrixLead.Id);
        }

        for(Matrix_Lead__c matrixLead : [SELECT Id, OwnerId, Unique_External_Id__c, Sequence__c, REF_NO__c, Lead_Status__c FROM Matrix_Lead__c WHERE Id IN :matrixLeadIds]){
        	System.assertEquals(matrixLead.Lead_Status__c, MatrixLeadTriggerHelper.STATUS_OPEN);
        	System.assertEquals(matrixLead.OwnerId, unassignedLeads.Id);
        }
	}

    public static testMethod void testMatrixLeadOwnerAssignmentRequest(){
        Integer BATCH_SIZE = 200;
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        System.runAs(currentUser) {
            
            ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
            ZZTEST_F_MatrixLead matrixLeadFactory = ZZTEST_DataFactoryFacade.matrixLead;
            
            User barclaysStandardUser = userFactory.getBarclaysStandardUser(); 
            
            PermissionSet ps = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Key_Matrix_Leads_Qualification'];
            insert new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = barclaysStandardUser.Id);
            
            barclaysStandardUser.ManagerId = currentUser.Id;
            update barclaysStandardUser;
            
            
            List<Matrix_Lead__c> matrixLeads = new List<Matrix_Lead__c>();
            for(Integer i=0; i<BATCH_SIZE; i++){
                Matrix_Lead__c matrixLead = matrixLeadFactory.getProduct(ZZTEST_F_MatrixLead.MatrixLeadRecordType.DEFAULT_MATRIX_LEAD, dataContainer);
                matrixLead.Sequence__c = String.valueOf(i);
                matrixLeads.add(matrixLead);
            }
            insert matrixLeads;
            
            Matrix_Lead__c mainMatrixLead = matrixLeads[0];
            mainMatrixLead.OwnerId = barclaysStandardUser.Id;
            update mainMatrixLead;
            
            Test.startTest();
            
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request for approval.');
            req1.setObjectId(mainMatrixLead.Id);
            Approval.ProcessResult result1 = Approval.process(req1);
            
            Test.stopTest();
            
            for(Matrix_Lead__c matrixLead : [SELECT Id, OwnerId, Sector_Head_Email__c, Lead_Status__c, Assignment_Request_Date__c FROM Matrix_Lead__c WHERE REF_NO__c = :mainMatrixLead.REF_NO__c]){
                System.assertEquals(matrixLead.OwnerId, barclaysStandardUser.Id);
                System.assertEquals(matrixLead.Sector_Head_Email__c, UserInfo.getUserEmail());
                System.assertEquals(matrixLead.Lead_Status__c, MatrixLeadTriggerHelper.STATUS_PENDING_ASSIGNMENT);
            }
            
            mainMatrixLead = [SELECT Id, Name, Assignment_Request_Date__c FROM Matrix_Lead__c WHERE Id = :mainMatrixLead.Id];
            System.assertEquals(mainMatrixLead.Assignment_Request_Date__c, Date.today());
        }
    }

	public static testMethod void testMatrixLeadOwnerAssignmentRejected(){
        Integer BATCH_SIZE = 200;
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        System.runAs(currentUser) {
            ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
            ZZTEST_F_MatrixLead matrixLeadFactory = ZZTEST_DataFactoryFacade.matrixLead;
            
            User barclaysStandardUser = userFactory.getBarclaysStandardUser(); 
            
            PermissionSet ps = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Key_Matrix_Leads_Qualification'];
            insert new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = barclaysStandardUser.Id);
            
            barclaysStandardUser.ManagerId = currentUser.Id;
            update barclaysStandardUser;
            
            
            List<Matrix_Lead__c> matrixLeads = new List<Matrix_Lead__c>();
            for(Integer i=0; i<BATCH_SIZE; i++){
                Matrix_Lead__c matrixLead = matrixLeadFactory.getProduct(ZZTEST_F_MatrixLead.MatrixLeadRecordType.DEFAULT_MATRIX_LEAD, dataContainer);
                matrixLead.Sequence__c = String.valueOf(i);
                matrixLeads.add(matrixLead);
            }
            insert matrixLeads;
            
            Matrix_Lead__c mainMatrixLead = matrixLeads[0];
            mainMatrixLead.OwnerId = barclaysStandardUser.Id;
            update mainMatrixLead;
            
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request for approval.');
            req1.setObjectId(mainMatrixLead.Id);
            Approval.ProcessResult result1 = Approval.process(req1);
            
            Test.startTest();
            
            List<Id> newWorkItemIds = result1.getNewWorkitemIds();
            Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
            req2.setComments('Approving request.');
            req2.setAction('Reject');
            req2.setWorkitemId(newWorkItemIds.get(0));
            Approval.ProcessResult result2 =  Approval.process(req2);
            
            Test.stopTest();
            
            Group unassignedLeads = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND DeveloperName = :MatrixLeadTriggerHelper.QUEUE_UNASSIGNED_LEADS];
            
            for(Matrix_Lead__c matrixLead : [SELECT Id, OwnerId, Sector_Head_Email__c, Lead_Status__c FROM Matrix_Lead__c WHERE REF_NO__c = :mainMatrixLead.REF_NO__c]){
                System.assertEquals(matrixLead.OwnerId, unassignedLeads.Id);
                System.assertEquals(matrixLead.Sector_Head_Email__c, null);
                System.assertEquals(matrixLead.Lead_Status__c, MatrixLeadTriggerHelper.STATUS_OPEN);
            }
            
            mainMatrixLead = [SELECT Id, Name, Assignment_Request_Date__c FROM Matrix_Lead__c WHERE Id = :mainMatrixLead.Id];
            System.assertEquals(mainMatrixLead.Assignment_Request_Date__c, null);
        }
	}

	public static testMethod void testMatrixLeadOwnerAssignmentApproved(){
		Integer BATCH_SIZE = 200;
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
		ZZTEST_F_MatrixLead matrixLeadFactory = ZZTEST_DataFactoryFacade.matrixLead;

        User barclaysStandardUser = userFactory.getBarclaysStandardUser();  
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        System.runAs(currentUser) {
            PermissionSet ps = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Key_Matrix_Leads_Qualification'];
            insert new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = barclaysStandardUser.Id);
    
            barclaysStandardUser.ManagerId = currentUser.Id;
            update barclaysStandardUser;
            
            List<Matrix_Lead__c> matrixLeads = new List<Matrix_Lead__c>();
		for(Integer i=0; i<BATCH_SIZE; i++){
			Matrix_Lead__c matrixLead = matrixLeadFactory.getProduct(ZZTEST_F_MatrixLead.MatrixLeadRecordType.DEFAULT_MATRIX_LEAD, dataContainer);
			matrixLead.Sequence__c = String.valueOf(i);
			matrixLeads.add(matrixLead);
		}
		insert matrixLeads;

        Matrix_Lead__c mainMatrixLead = matrixLeads[0];
        mainMatrixLead.OwnerId = barclaysStandardUser.Id;
        update mainMatrixLead;

        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
		req1.setObjectId(mainMatrixLead.Id);
		Approval.ProcessResult result1 = Approval.process(req1);

        Test.startTest();

        List<Id> newWorkItemIds = result1.getNewWorkitemIds();
        Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setWorkitemId(newWorkItemIds.get(0));
        Approval.ProcessResult result2 =  Approval.process(req2);

        Test.stopTest();

        for(Matrix_Lead__c matrixLead : [SELECT Id, Lead_Status__c FROM Matrix_Lead__c WHERE REF_NO__c = :mainMatrixLead.REF_NO__c]){
            System.assertEquals(matrixLead.Lead_Status__c, MatrixLeadTriggerHelper.STATUS_ASSIGNED);
        }

        mainMatrixLead = [SELECT Id, Name, Assignment_Request_Date__c, Assignment_Date__c FROM Matrix_Lead__c WHERE Id = :mainMatrixLead.Id];
        System.assertEquals(mainMatrixLead.Assignment_Request_Date__c, null);
        System.assertEquals(mainMatrixLead.Assignment_Date__c, Date.today());
        }

		
	}

    public static testMethod void testMatrixLeadBackToUnassignedQueue(){
        Integer BATCH_SIZE = 200;
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
       
            
        ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
        ZZTEST_F_MatrixLead matrixLeadFactory = ZZTEST_DataFactoryFacade.matrixLead;

        User barclaysStandardUser = userFactory.getBarclaysStandardUser();  
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        System.runAs(currentUser) {
            PermissionSet ps = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Key_Matrix_Leads_Qualification'];
            insert new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = barclaysStandardUser.Id);
    
            barclaysStandardUser.ManagerId = currentUser.Id;
            update barclaysStandardUser;
             List<Matrix_Lead__c> matrixLeads = new List<Matrix_Lead__c>();
        for(Integer i=0; i<BATCH_SIZE; i++){
            Matrix_Lead__c matrixLead = matrixLeadFactory.getProduct(ZZTEST_F_MatrixLead.MatrixLeadRecordType.DEFAULT_MATRIX_LEAD, dataContainer);
            matrixLead.Sequence__c = String.valueOf(i);
            matrixLeads.add(matrixLead);
        }
        insert matrixLeads;

        Matrix_Lead__c mainMatrixLead = matrixLeads[0];
        mainMatrixLead.OwnerId = barclaysStandardUser.Id;
        mainMatrixLead.Lead_Status__c = MatrixLeadTriggerHelper.STATUS_ASSIGNED;
        mainMatrixLead.Assignment_Date__c = Date.today();
        update mainMatrixLead;

        Test.startTest();

        mainMatrixLead.Lead_Status__c = MatrixLeadTriggerHelper.STATUS_OPEN;
        mainMatrixLead.Assignment_Date__c = null;
        update mainMatrixLead;

        Test.stopTest();

        Group unassignedLeads = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND DeveloperName = :MatrixLeadTriggerHelper.QUEUE_UNASSIGNED_LEADS];
        for(Matrix_Lead__c matrixLead : [SELECT Id, OwnerId, Sector_Head_Email__c, Lead_Status__c FROM Matrix_Lead__c WHERE REF_NO__c = :mainMatrixLead.REF_NO__c]){
            System.assertEquals(matrixLead.OwnerId, unassignedLeads.Id);
            System.assertEquals(matrixLead.Sector_Head_Email__c, null);
            System.assertEquals(matrixLead.Lead_Status__c, MatrixLeadTriggerHelper.STATUS_OPEN);
        }

        mainMatrixLead = [SELECT Id, Name, Assignment_Request_Date__c FROM Matrix_Lead__c WHERE Id = :mainMatrixLead.Id];
        System.assertEquals(mainMatrixLead.Assignment_Request_Date__c, null);
        }

       
    }

    public static testMethod void testMatrixLeadMoveToStatusContacted(){
        Integer BATCH_SIZE = 200;
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
        ZZTEST_F_MatrixLead matrixLeadFactory = ZZTEST_DataFactoryFacade.matrixLead;

        User barclaysStandardUser = userFactory.getBarclaysStandardUser();  
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        System.runAs(currentUser) {
            PermissionSet ps = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Key_Matrix_Leads_Qualification'];
            insert new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = barclaysStandardUser.Id);
    
            barclaysStandardUser.ManagerId = currentUser.Id;
            update barclaysStandardUser;
            
             List<Matrix_Lead__c> matrixLeads = new List<Matrix_Lead__c>();
        for(Integer i=0; i<BATCH_SIZE; i++){
            Matrix_Lead__c matrixLead = matrixLeadFactory.getProduct(ZZTEST_F_MatrixLead.MatrixLeadRecordType.DEFAULT_MATRIX_LEAD, dataContainer);
            matrixLead.Sequence__c = String.valueOf(i);
            matrixLeads.add(matrixLead);
        }
        insert matrixLeads;

        Matrix_Lead__c mainMatrixLead = matrixLeads[0];
        mainMatrixLead.OwnerId = barclaysStandardUser.Id;
        mainMatrixLead.Lead_Status__c = MatrixLeadTriggerHelper.STATUS_ASSIGNED;
        mainMatrixLead.Assignment_Date__c = Date.today();
        update mainMatrixLead;

        Test.startTest();

        mainMatrixLead.Lead_Status__c = MatrixLeadTriggerHelper.STATUS_CONTACTED;
        mainMatrixLead.Comments__c = 'original comments';
        update mainMatrixLead;

        mainMatrixLead.Comments__c = 'updated comments';
        update mainMatrixLead;

        Test.stopTest();

        for(Matrix_Lead__c matrixLead : [SELECT Id, Comments__c, Lead_Status__c, Conversion_Deadline__c, Requested_Extension_30_days__c
                                        FROM Matrix_Lead__c WHERE REF_NO__c = :mainMatrixLead.REF_NO__c]){
                                            System.assertEquals(matrixLead.Comments__c, 'updated comments');
                                            System.assertEquals(matrixLead.Lead_Status__c, MatrixLeadTriggerHelper.STATUS_CONTACTED);
                                            System.assertEquals(matrixLead.Conversion_Deadline__c, Date.today().addDays(60));
                                            System.assertEquals(matrixLead.Requested_Extension_30_days__c, false);
                                        }
            mainMatrixLead = [SELECT Id, Name, Contacted_Date__c FROM Matrix_Lead__c WHERE Id = :mainMatrixLead.Id];
            System.assertEquals(mainMatrixLead.Contacted_Date__c, Date.today());
            
        }

        
    }

    public static testMethod void testMatrixLeadMoveToStatusUnqualified(){
        Integer BATCH_SIZE = 200;
        ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
        ZZTEST_F_MatrixLead matrixLeadFactory = ZZTEST_DataFactoryFacade.matrixLead;

        User barclaysStandardUser = userFactory.getBarclaysStandardUser();  
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        System.runAs(currentUser) {
            PermissionSet ps = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Key_Matrix_Leads_Qualification'];
            insert new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = barclaysStandardUser.Id);
    
            barclaysStandardUser.ManagerId = currentUser.Id;
            update barclaysStandardUser;
            
            List<Matrix_Lead__c> matrixLeads = new List<Matrix_Lead__c>();
        for(Integer i=0; i<BATCH_SIZE; i++){
            Matrix_Lead__c matrixLead = matrixLeadFactory.getProduct(ZZTEST_F_MatrixLead.MatrixLeadRecordType.DEFAULT_MATRIX_LEAD, dataContainer);
            matrixLead.Sequence__c = String.valueOf(i);
            matrixLeads.add(matrixLead);
        }
        insert matrixLeads;

        Matrix_Lead__c mainMatrixLead = matrixLeads[0];
        mainMatrixLead.OwnerId = barclaysStandardUser.Id;
        mainMatrixLead.Lead_Status__c = MatrixLeadTriggerHelper.STATUS_ASSIGNED;
        mainMatrixLead.Assignment_Date__c = Date.today();
        update mainMatrixLead;

        Test.startTest();

        mainMatrixLead.Lead_Status__c = MatrixLeadTriggerHelper.STATUS_UNQUALIFIED;
        mainMatrixLead.Reason_for_unqualified_leads__c = 'Reason for Unqualified';
        update mainMatrixLead;

        mainMatrixLead.Specify_Other__c = 'Other reason';
        update mainMatrixLead;

        Test.stopTest();

        Group unassignedLeads = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND DeveloperName = :MatrixLeadTriggerHelper.QUEUE_UNASSIGNED_LEADS];
        for(Matrix_Lead__c matrixLead : [SELECT Id, Reason_for_unqualified_leads__c, Specify_Other__c, Lead_Status__c FROM Matrix_Lead__c WHERE REF_NO__c = :mainMatrixLead.REF_NO__c]){
            System.assertEquals(matrixLead.Reason_for_unqualified_leads__c, 'Reason for Unqualified');
            System.assertEquals(matrixLead.Specify_Other__c, 'Other reason');
            System.assertEquals(matrixLead.Lead_Status__c, MatrixLeadTriggerHelper.STATUS_UNQUALIFIED);
        }
        }

        
    }

	public static testMethod void testMatrixLeadExtensionApproved(){
		Integer BATCH_SIZE = 200;
		ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
        ZZTEST_F_User userFactory = ZZTEST_DataFactoryFacade.user;
		ZZTEST_F_MatrixLead matrixLeadFactory = ZZTEST_DataFactoryFacade.matrixLead;

        User barclaysStandardUser = userFactory.getBarclaysStandardUser();  
        User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        System.runAs(currentUser) {
            PermissionSet ps = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Key_Matrix_Leads_Qualification'];
            insert new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = barclaysStandardUser.Id);
    
            barclaysStandardUser.ManagerId = currentUser.Id;
            update barclaysStandardUser;
            
            List<Matrix_Lead__c> matrixLeads = new List<Matrix_Lead__c>();
		for(Integer i=0; i<BATCH_SIZE; i++){
			Matrix_Lead__c matrixLead = matrixLeadFactory.getProduct(ZZTEST_F_MatrixLead.MatrixLeadRecordType.DEFAULT_MATRIX_LEAD, dataContainer);
			matrixLead.Sequence__c = String.valueOf(i);
			matrixLeads.add(matrixLead);
		}
		insert matrixLeads;

        String comments = 'comments...';
        Matrix_Lead__c mainMatrixLead = matrixLeads[0];
        mainMatrixLead.OwnerId = barclaysStandardUser.Id;
        mainMatrixLead.Lead_Status__c = MatrixLeadTriggerHelper.STATUS_ASSIGNED;
        mainMatrixLead.Assignment_Date__c = Date.today();
        update mainMatrixLead;
        mainMatrixLead.Lead_Status__c = MatrixLeadTriggerHelper.STATUS_CONTACTED;
        mainMatrixLead.Comments__c = comments;
        update mainMatrixLead;

        mainMatrixLead = [SELECT Id, Requested_Extension_30_days__c, Conversion_Deadline__c FROM Matrix_Lead__c WHERE Id = :mainMatrixLead.Id];

        Test.startTest();

        mainMatrixLead.Requested_Extension_30_days__c = true;
        update mainMatrixLead;

        //Approve
        mainMatrixLead.Conversion_Deadline__c = mainMatrixLead.Conversion_Deadline__c.addDays(30);
        mainMatrixLead.Requested_Extension_30_days__c = false;
		update mainMatrixLead;

        Test.stopTest();

        for(Matrix_Lead__c matrixLead : [SELECT Id, Conversion_Deadline__c, Requested_Extension_30_days__c FROM Matrix_Lead__c WHERE REF_NO__c = :mainMatrixLead.REF_NO__c]){
        	System.assertEquals(matrixLead.Conversion_Deadline__c, Date.today().addDays(90));
        	System.assertEquals(matrixLead.Requested_Extension_30_days__c, false);
        }
        }

		
	}
}