objects/Matrix_Lead__c.object
<CustomObject>
    <customHelpPage>Help_for_Matrix_Lead</customHelpPage>
    <description>This Object will store all  the leads received from matrix, on quarterly basis.</description>
    <fields>
        <fullName>Bank__c</fullName>
        <label>Bank</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Name of the company</description>
        <label>Company Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Assignment</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <description>Organisation&apos;s postal code</description>
        <label>Post Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Address1__c</fullName>
        <description>Lead&apos;s postal address</description>
        <label>Postal Address1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Area__c</fullName>
        <description>Leads postal area</description>
        <label>Postal Area</label>
        <length>29</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REF_NO_F__c</fullName>
        <formula>IF(CONTAINS(REF_NO__c, &quot; &quot;), LEFT(REF_NO__c, FIND(&quot; &quot;, REF_NO__c)-1), REF_NO__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>REF NO F</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REF_NO__c</fullName>
        <label>REF NO</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REG_No__c</fullName>
        <description>Registration number of the lead</description>
        <label>REG No</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsibility__c</fullName>
        <label>Responsibility</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SICCODE_Description__c</fullName>
        <label>SICCODE Description</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Surname__c</fullName>
        <label>Surname</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tel_Code__c</fullName>
        <label>Tel Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tel_No__c</fullName>
        <label>Tel No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Trade_Division__c</fullName>
        <description>Name of the trade division</description>
        <label>Trade Division</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Turn_Over__c</fullName>
        <label>Turn Over</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Matrix Lead</label>
    <nameField>
        <displayFormat>ML-{0000}</displayFormat>
        <label>Matrix Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrix Leads</pluralLabel>
    <recordTypes>
        <fullName>Converted_Leads</fullName>
        <active>true</active>
        <description>Record type for leads that have been converted.It is read only for all records</description>
        <label>Converted Leads</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MatrixLeadConversion.cls
/**
* @Author       Marta Malinowska
* Company:      Deloitte
* @Description: This class is invoked from custom button on Matrix Lead object and its purpose is to convert Matrix Lead to Prospect.
* @Date:        10/2015
* @ConstructorParam:    None
* @TestClass:   ZZTEST_MatrixLeadConversion
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* 14/12/2015  Marta Malinowska   Add Matrix Lead Position to Contact Job Role mapping.
* 12/01/2016  Marta Malinowska   Match Matrix Leads within the same company by REF NO F.
*------------------------------------------------------------*/
global class MatrixLeadConversion {
    public static String STATUS_CONVERTED = 'Converted';
    public static String SOURCE_MATRIX = 'Matrix Database';
    public static String ERR_MSG_MATRIX_LEAD_DELETED = 'ERROR: Matrix Lead has been deleted.';
    public static String ERR_MSG_REF_NO_EMPTY = 'ERROR: REF NO cannot be empty.';
    public static String ERR_MSG_PROSPECT_RECORD_TYPE = 'ERROR: Prospect cannot be created. Please contact your System Administrator.';
    public static String ERR_MSG_MATRIX_LEAD_RECORD_TYPE = 'ERROR: Matrix Lead cannot be converted. Please contact your System Administrator.';
    public static String ERR_MSG_PROSPECT_CANNOT_BE_CREATED = 'ERROR: Prospect cannot be created.';
    public static String ERR_MSG_CONTACTS_CANNOT_BE_CREATED = 'ERROR: One or more Contacts cannot be created.';
    public static String ERR_MSG_MATRIX_LEADS_CANNOT_BE_CONVERTED = 'ERROR: One or more Matrix Leads cannot be converted.';

    /**
    * @Author:      Marta Malinowska
    * @Company:     Deloitte
    * @Description: This method is used to convert Matrix Leads to Prospect Account with the related list of Contacts.
    * @param        The Id of Matrix Lead that will be converted
    * @Returns:     Id of created Prospect Account if it has been successfull
    *               Error Message in case of any errors
    * History
    * <Date>      <Authors Name>     <Brief Description of Change>
    * 14/12/2015  Marta Malinowska   Add Matrix Lead Position to Contact Job Role mapping.
    *------------------------------------------------------------*/
    @AuraEnabled
    webservice static String convertMatrixLeadToProspect(Id matrixLeadId) {
        String errMsg;
        Matrix_Lead__c mainMatrixLead;
        try{
            mainMatrixLead = [SELECT Id, Name, CurrencyIsoCode, REF_NO__c, REF_NO_F__c, Company_Name__c, Trade_Division__c, REG_No__c, SICCODE_Description__c, Bank__c, Turn_Over__c
                                FROM Matrix_Lead__c WHERE Id = :matrixLeadId];
        } catch(QueryException ex){
            System.debug('MATRIX LEAD QUERY EXCEPTION: '+ex);
            return ERR_MSG_MATRIX_LEAD_DELETED;
        }

        if(mainMatrixLead.REF_NO__c == null){
            return ERR_MSG_REF_NO_EMPTY;
        }

        RecordType prospectRecordType;
        try{
            prospectRecordType = [SELECT Id FROM RecordType  WHERE SobjectType = 'Account' AND DeveloperName = 'Prospect'];
        } catch(QueryException ex){
            System.debug('RECORD TYPE QUERY EXCEPTION: '+ex);
            return ERR_MSG_PROSPECT_RECORD_TYPE;
        }

        RecordType convertedLeadRecordType;
        try{
            convertedLeadRecordType = [SELECT Id FROM RecordType  WHERE SobjectType = 'Matrix_Lead__c' AND DeveloperName = 'Converted_Leads'];
        } catch(QueryException ex){
            System.debug('RECORD TYPE QUERY EXCEPTION: '+ex);
            return ERR_MSG_MATRIX_LEAD_RECORD_TYPE;
        }

        Savepoint sp = Database.setSavepoint();

        Account account = new Account();
        account.RecordTypeId = prospectRecordType.Id;
        account.CurrencyIsoCode = mainMatrixLead.CurrencyIsoCode;
        account.REF_NO__c = mainMatrixLead.REF_NO__c;
        account.Name = mainMatrixLead.Company_Name__c;
        account.Trade_Division__c = mainMatrixLead.Trade_Division__c;
        account.Registration_Number__c = mainMatrixLead.REG_No__c;
        account.SICCODE_Description__c = mainMatrixLead.SICCODE_Description__c;
        account.Primary_Bank_Name__c = mainMatrixLead.Bank__c;
        account.Turn_Over_Proxy__c = mainMatrixLead.Turn_Over__c;
        account.AccountSource = SOURCE_MATRIX;
        try{
            insert account;
        } catch(DmlException ex){
            return ERR_MSG_PROSPECT_CANNOT_BE_CREATED+' '+ex.getDmlMessage(0);
        }

        List<Contact> contacts = new List<Contact>();
        List<Matrix_Lead__c> matrixLeadsToUpd = new List<Matrix_Lead__c>();
        for(Matrix_Lead__c matrixLead : [SELECT Id, Name, Postal_Address1__c, Postal_Area__c, Post_Code__c, Street_Address_1__c, Tel_Code__c,
                                        Tel_No__c, Responsibility__c, Position__c, Salutation__c, First_Name__c, Surname__c, Job_Title__c, 
                                        Personal_Email__c, Province__c
                                        FROM Matrix_Lead__c WHERE REF_NO_F__c = :mainMatrixLead.REF_NO_F__c]){
            Contact contact = new Contact();
            contact.AccountId = account.Id;
            contact.Address_line_1__c = matrixLead.Postal_Address1__c;
            contact.Postal_Area__c = matrixLead.Postal_Area__c;
            contact.Post_code__c = matrixLead.Post_Code__c;
            contact.Address_line_2__c = matrixLead.Street_Address_1__c;
            contact.Phone = matrixLead.Tel_No__c;
            contact.Responsibility__c = matrixLead.Responsibility__c;
            contact.Position__c = matrixLead.Position__c;
            contact.Job_Role__c = matrixLead.Position__c;
            contact.Salutation = matrixLead.Salutation__c;
            contact.FirstName = matrixLead.First_Name__c;
            contact.LastName = matrixLead.Surname__c;
            contact.Job_title__c = matrixLead.Job_Title__c;
            contact.Email = matrixLead.Personal_Email__c;
            contact.Province__c = matrixLead.Province__c;
            contacts.add(contact);
            matrixLead.RecordTypeId = convertedLeadRecordType.Id;
            matrixLead.Lead_Status__c = STATUS_CONVERTED;
            matrixLeadsToUpd.add(matrixLead);
        }

        try{
            insert contacts;
        } catch(DmlException ex){
            Database.rollback(sp);
            errMsg = ERR_MSG_CONTACTS_CANNOT_BE_CREATED;
            for(Integer i=0; i < ex.getNumDml(); i++){
                errMsg += '\n'+ex.getDmlMessage(i);
            }
            return errMsg;
        }

        try{
            update matrixLeadsToUpd;
        } catch(DmlException ex){
            Database.rollback(sp);
            errMsg = ERR_MSG_MATRIX_LEADS_CANNOT_BE_CONVERTED;
            for(Integer i=0; i < ex.getNumDml(); i++){
                errMsg += '\n'+ex.getDmlMessage(i);
            }
            return errMsg;
        }

        return account.Id;
    }
}