objects/Matter_Spend_Document__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The individual that needs to approve this document before it can be submitted for payment processing.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Matter_Spend_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matter_Spend_Schedule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Matter Spend Schedule</label>
        <referenceTo>Matter_Spend_Schedule__c</referenceTo>
        <relationshipLabel>Matter Spend Documents</relationshipLabel>
        <relationshipName>Matter_Spend_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Queried</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved For Payment</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Matter Spend Document</label>
    <nameField>
        <displayFormat>MSD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matter Spend Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Matter_Spend_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Exported</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Matter Spend Schedule</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>Schedule #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matter Spend Schedules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BxdMatterSpendScheduleService.cls
public class BxdMatterSpendScheduleService implements BxdServiceInterface {
    private static FolderHandler folderHandler = new FolderHandler();
    private static PermissionHandler permissionHander = new PermissionHandler();
    
    /**
	* createBoxFolderSync - this method takes in a matterSpendSchedule record id then request a box folder to be created for this record
	**/
    public String createBoxFolderSync(Id recordId){
        String folderId = createBoxFolderForRecord(recordId);
        system.debug('****MANUAL BOX FOLDER**** '+folderId);
        folderHandler.commitBoxChanges();
        return folderId;
    }

  	/**
    * createBoxFolderTrigger - prepares a set of matterSpendSchedule records id, then pass it to createBoxFolder
	**/    
    public static void createBoxFolderTrigger(List<Matter_Spend_Schedule__c> schedules) {
        Set<Id> inputScheduleIds = new Set<Id>(); 
        for(Matter_Spend_Schedule__c schedule : schedules){
            inputScheduleIds.Add(schedule.id);           
        }      
        createBoxFolder(inputScheduleIds);
    }
    
    /**
    * createBoxFolder - this method executes asynchronously, it create box folder for each matterSpendSchedule record, then save box changes after
	**/
    @Future(callout = true)
    public static void createBoxFolder(Set<Id> inputScheduleIds) {
        
        List<Matter_Spend_Schedule__c> schedules = new List<Matter_Spend_Schedule__c>();
        
        //Get schedules and documents for it.
        schedules = [
            SELECT
            Id,
            Status__c,
            (
                SELECT
                Id,
                Status__c,
                Matter_Spend_Schedule__c
                FROM Matter_Spend_Documents__r
                
            )
            FROM Matter_Spend_Schedule__c
            WHERE
            Id IN :inputScheduleIds
        ];
        
        //Loop through each schedule.
        for(Matter_Spend_Schedule__c schedule : schedules)
        {
            String folderId = createBoxFolderForRecord(schedule.Id);
            if(!String.isBlank(folderId) && schedule.Matter_Spend_Documents__r != null){
                for(Matter_Spend_Document__c spendDocument : schedule.Matter_Spend_Documents__r){
                    moveFolderToSpendSchedule(spendDocument, folderId);
                }
            }          
        }
        folderHandler.commitBoxChanges();
    }
    
    /**
    * createBoxFolderForRecord - used to create a box folder for matterSpendSchedule record, and creates collaboration on this record assigning the user as an editor
	**/
    public static String createBoxFolderForRecord(Id scheduleId) {
        String folderId;
        if(scheduleId != null){
            folderId = folderHandler.createBoxFolderForRecord(scheduleId);
            
            Id userId = UserInfo.getUserId();
            if(userId != null){
                box.Toolkit.CollaborationType collabType = box.Toolkit.CollaborationType.EDITOR;
                String collabId = folderHandler.createCollaborationOnRecord(userId, scheduleId, collabType);
                system.debug('matter new collaboration id: ' + collabId);    
            }                  
        }        
        return folderId;
    }
    
    /**
    * getBoxFolderLink - used to make a call to getBoxFolderURL in BxdFolderHandler to get the link for the given matterSpendSchedule record
	**/
    public static String getBoxFolderLink(Matter_Spend_Schedule__c schedule) {
        PageReference res = folderHandler.getBoxFolderURL(schedule.Id, false);
        if(res != null){
            return res.getUrl();
        }
        return '';
    }
    
    /**
    * createViewerPermission - used to create permission for the user on the given matterSpendSchedule record, by calling createPermissionForUser in BxdPermissionHandler 
	**/
    public static void createViewerPermission(Matter_Spend_Schedule__c schedule) {  
        Id userId = UserInfo.getUserId();
        if(userId != null){
            permissionHander.createPermissionForUser(schedule.Id, userId);   
        }       
    }
    
    /**
    * moveFolderToSpendSchedule - used to call getBoxFolderIdByRecordId in BxdFolderHandler then move the returned folder
	**/
    private static void moveFolderToSpendSchedule(Matter_Spend_Document__c spendDocument, String scheduleFolderId) {
        String spendFolderId = folderHandler.getBoxFolderIdByRecordId(spendDocument.Id);
        if(!String.isBlank(spendFolderId)){
            Boolean moved = folderHandler.moveBoxFolder(spendFolderId, scheduleFolderId);
            system.debug('FOLDER MOVED '+moved);
        }        
    }
    
    private class FolderHandler extends BxdFolderHandler {
        private FolderHandler() {
            super();
        }
    }
    
    private class PermissionHandler extends BxdPermissionHandler {
        private PermissionHandler() {
        }
    }
}