objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_via_Visual_Workflow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to determine whether an opportunity is closed through the visual workflow. It is set through the Close Opportunity Flow.</description>
        <label>Closed via Visual Workflow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Parent_Opportunity__c</fullName>
        <label>Is Parent Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notify_ABSA_Insurance_Of_This_Deal__c</fullName>
        <label>Notify ABSA Insurance Of This Deal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.Is_Parent_Opportunity__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductLevel3Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Holds the number of Level 3 Products on an Opportunity</description>
        <label>Product Level 3 Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reason_Won_Lost__c</fullName>
        <description>Wealth - Reason for winning or losing the Opportunity</description>
        <label>Reason Won / Lost</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Client need change / not taken up</fullName>
                </value>
                <value>
                    <fullName>Credit Policy Decision</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Product / Solution</fullName>
                </value>
                <value>
                    <fullName>Regulatory / Compliance</fullName>
                </value>
                <value>
                    <fullName>Relationship</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ZZTEST_ChildOpportunitiesController.cls
/**
* @Author:        Dino Scarcella
* @Company:       ABSA Capital
* @Description:   Unit Tests for ChildOpportunitiesController
*                   Tests executed:
*                   1 - testChildOpportunitiesController()
*						Tests main functionality related to Child Opportunities VF Page                       
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* ---------------------------------------------------------------------------------------------------------------------------------------------------*/
@isTest
public class ZZTEST_ChildOpportunitiesController {
	public static testMethod void testChildOpportunitiesController() {
        // First create a User
        ZZTEST_F_User userFactory = ZZTEST_F_User.getInstance();
        User u = userFactory.getBarclaysStandardUser();

        System.runAs(u) {
            ZZTEST_F_Opportunity oppFactory = ZZTEST_DataFactoryFacade.opportunity;
            // Create Opportunities
            ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
            Opportunity parentOpp = oppFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
            Opportunity childOpp = oppFactory.getProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
			
            // Create link between child and parent opportunity
            parentOpp.Is_Parent_Opportunity__c = 'Yes';
            insert parentOpp;
        	childOpp.Parent_Opportunity__c = parentOpp.Id;
        	insert childOpp;
            
            // Initialize controller
            PageReference pipelineReportPage = Page.ChildOpportunities;
            Test.setCurrentPage(pipelineReportPage);
            Apexpages.Standardcontroller stc = new ApexPages.StandardController(parentOpp);
            ChildOpportunitiesController ctrl = new ChildOpportunitiesController(stc);
            
            Test.startTest();
            // Simulate a user selecting to edit an opportunity before selecting anything
            ctrl.StartEditing();
            // Simulate a user selecting an opportunity
            ctrl.opportunityItems[0].isSelected = true;
            // Simulate a user selecting to edit the opportunity selected
            ctrl.StartEditing();
            System.assertEquals(true, ctrl.Editing);
            System.assertEquals(false, ctrl.ErrorsExist);
            // Update the parentOpportunity
            parentOpp.StageName = 'Closed Won';
            parentOpp.Probability = 100;
            parentOpp.Reason_Won_Lost__c = 'Other';
            parentOpp.Closed_via_Visual_Workflow__c = true;
            parentOpp.ProductLevel3Count__c = 1;
            parentOpp.Notify_ABSA_Insurance_Of_This_Deal__c = 'No';
            update parentOpp;
            // Simulate a user saving
            ctrl.save();
            // Simulate a user cancelling edit on opportunity selected
            ctrl.CancelEditing();
            System.assertEquals(false, ctrl.Editing);
            Test.stopTest();
        }
    }
}