objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Reason_for_probability_change__c</fullName>
        <description>Wealth - Reason why the probability % was manually overwritten</description>
        <label>Reason for Probability Change</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Email_Alert_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Config setting used to define criteria for sending out emails based on opportunity that meet the defined criteria</description>
    <fields>
        <fullName>Future_Warning_Days__c</fullName>
        <description>This is the future warning date that can be changed to any Date</description>
        <label>Future Warning Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StageName__c</fullName>
        <label>StageName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starting_Year__c</fullName>
        <description>This field will hold the starting year to look at for the opportunity createdDate</description>
        <label>Starting Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Email Alert Config</label>
</CustomObject>

classes/Batch_SendOpportunityEmailAlert_Test.cls
/*-------------------------------------------------------
@CreatedBY : Mabhedle Tonga 
@CreatedDate : 2017-05-31
@Description : Test class
------------------------------------------------------*/
@isTest
public class Batch_SendOpportunityEmailAlert_Test {

    static testMethod void sendOpportunityEmail()
    {
        
        
        ZZTEST_F_User userFactory = ZZTEST_F_User.getInstance();
        User u = userFactory.getBarclaysStandardUserWithCIBRole();

        User cU = [Select UserRole.Name from User where ID  =: u.ID];
        System.debug(cU);
        System.runAs(u) {
			ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
			ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
			ZZTEST_F_OpportunityLineItem oliFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;
			ZZTEST_F_Product productFactory = ZZTEST_DataFactoryFacade.product;
			ZZTEST_F_PricebookEntry pricebookEntryFactory = ZZTEST_DataFactoryFacade.pricebookEntry;

			dataContainer.put(u);

			setupData();

			Opportunity opp = opportunityFactory.getInsertedProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
            opp.StageName = 'Client Engaged';
            opp.closeDate = Date.today();
            opp.Reason_for_probability_change__c='Just came from a meeting';
            update opp;
            
            Test.startTest();
            Database.executeBatch(new Batch_SendOpportunityEmailAlert());
            Test.stopTest();
        }
    }
    
    private static void setupData()
    {
        Opportunity_Email_Alert_Config__c opportunityConfig = new Opportunity_Email_Alert_Config__c
            (Name = 'ClosedOpportunityAlert',
             Future_Warning_Days__c=5,
             Starting_Year__c = 2017,
             StageName__c = 'Closed Won;Closed Lost');
        insert opportunityConfig;
    }
}