objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Country__c</fullName>
        <description>Used in Process Flow:  Update GF Region based on Opp Country</description>
        <label>Opportunity Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cabo Verde</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Central African Republic (CAR)</fullName>
                </value>
                <value>
                    <fullName>Chad</fullName>
                </value>
                <value>
                    <fullName>Comoros</fullName>
                </value>
                <value>
                    <fullName>Congo (DRC)</fullName>
                </value>
                <value>
                    <fullName>Cote d’Ivoire</fullName>
                </value>
                <value>
                    <fullName>Djibouti</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Equatorial Guinea</fullName>
                </value>
                <value>
                    <fullName>Eritrea</fullName>
                </value>
                <value>
                    <fullName>Ethiopia</fullName>
                </value>
                <value>
                    <fullName>Gabon</fullName>
                </value>
                <value>
                    <fullName>Gambia</fullName>
                </value>
                <value>
                    <fullName>Ghana</fullName>
                </value>
                <value>
                    <fullName>Guinea</fullName>
                </value>
                <value>
                    <fullName>Guinea-Bissau</fullName>
                </value>
                <value>
                    <fullName>Kenya</fullName>
                </value>
                <value>
                    <fullName>Lesotho</fullName>
                </value>
                <value>
                    <fullName>Liberia</fullName>
                </value>
                <value>
                    <fullName>Libya</fullName>
                </value>
                <value>
                    <fullName>Madagascar</fullName>
                </value>
                <value>
                    <fullName>Malawi</fullName>
                </value>
                <value>
                    <fullName>Mali</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Level_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Level 2</label>
        <referenceTo>Product_Level_2__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product_Level_2__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Level 2</relationshipLabel>
        <relationshipName>Product_Level_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Level 2</label>
    <nameField>
        <label>Level 2 Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Level 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ZZTEST_ProductPartnerLookupController.cls
/**
* @Author:        Dino Scarcella
* @Company:       Absa Capital
* @Description:   Unit Tests for ProductPartnerLookup on AddProductToOpportunity Page
*                 Tests executed:
*                 1 - testProductPartnerLookup()
*                   Tests the product partner lookup on AddProductToOpportunity Page
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* 2018-07-04  Dino Scarcella	 Added Country Support to testProductPartnerLookup test
* ------------------------------------------------------------------------------------------------------*/
@isTest
public class ZZTEST_ProductPartnerLookupController {
	public static testMethod void testProductPartnerLookup() {
        //Create a User
        ZZTEST_F_User userFactory = ZZTEST_F_User.getInstance();
        User u = userFactory.getBarclaysStandardUser();

        System.runAs(u) {
            ZZTEST_F_DeactivateChatterPostSettings.InstantiateChatterSettingsForOpportunityLineItem(False, False, False, False);
			ZZTEST_DataContainer dataContainer = new ZZTEST_DataContainer();
			ZZTEST_F_Opportunity opportunityFactory = ZZTEST_DataFactoryFacade.opportunity;
			ZZTEST_F_OpportunityLineItem oliFactory = ZZTEST_DataFactoryFacade.opportunityLineItem;
			ZZTEST_F_Product productFactory = ZZTEST_DataFactoryFacade.product;
            Product2 sampleProduct = productFactory.getProduct(ZZTEST_F_Product.ProductRecordType.DEFAULT_PRODUCT, dataContainer);
			INSERT sampleProduct;
            Product_Level_2__c prdLevel2 = new Product_Level_2__c(Name='Debt Finance', Product__c=sampleProduct.Id);
            INSERT prdLevel2;
            
            Test.startTest();

			Opportunity opp = opportunityFactory.getInsertedProduct(ZZTEST_F_Opportunity.OpportunityRecordType.DEFAULT_OPPORTUNITY, dataContainer);
			OpportunityLineItem oli1 = oliFactory.getProduct(ZZTEST_F_OpportunityLineItem.OpportunityLineItemRecordType.DEFAULT_OPPORTUNITY_LINE_ITEM, dataContainer);
			opp.Opportunity_Country__c = 'South Africa';
            update opp;
            
            PageReference ProductPartnerLookup = Page.ProductPartnerLookup;
            Test.setCurrentPage(ProductPartnerLookup);
    
            ApexPages.currentPage().getParameters().put('lksrch', '');
            ApexPages.currentPage().getParameters().put('ExcludeProductPartner', 'true');
            ApexPages.currentPage().getParameters().put('txt', 'j_id0%3AtheForm%3AaddProductToOpportunity%3AProductPartnerInputF&');
            ApexPages.currentPage().getParameters().put('frm', 'j_id0%3AtheForm');
            ApexPages.currentPage().getParameters().put('OpportunityId', opp.Id);
            ApexPages.currentPage().getParameters().put('ProductLevel2', prdLevel2.Id);
            ProductPartnerLookupController pplc = new ProductPartnerLookupController();
            pplc.search();
            
            System.assertEquals(true, pplc.results.size() > 0);
            System.assertEquals('j_id0%3AtheForm%3AaddProductToOpportunity%3AProductPartnerInputF&', pplc.getTextBox());
            System.assertEquals('j_id0%3AtheForm', pplc.getFormTag());
            
            Test.stopTest();
        }
    }
}