objects/Product_Setting__mdt.object
<CustomObject>
    <description>This custom metadata type holds sets of Products to allow for configurable settings regarding Products</description>
    <fields>
        <fullName>ProductName__c</fullName>
        <description>The name of the Product</description>
        <label>Product Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductSet__c</fullName>
        <description>The set of products grouped for a particular functionality eg. Product Partner exclusion</description>
        <label>Product Set</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Setting</label>
    <pluralLabel>Product Settings</pluralLabel>
</CustomObject>

classes/ZZTEST_ACMProductSearchController.cls
/**
* @Author:        Dino Scarcella
* @Company:       ABSA Capital
* @Description:   Unit Tests for ClientPlanACMProductSearchController
*                 Tests executed:
*                 1 - testGetAllACMProductsJson()
*                   Tests getter of all products in JSON
* History
* <Date>      <Authors Name>     <Brief Description of Change>
* ----------------------------------------------------------------------------*/
@isTest
public class ZZTEST_ACMProductSearchController {
	static testMethod void testGetAllACMProductsJson() {
        List<Product_Setting__mdt> prods = [
            SELECT 	 Id, ProductName__c
      		FROM 	 Product_Setting__mdt  
      		WHERE 	 ProductSet__c = 'ACMProducts'
            ORDER BY ProductName__c
        ];
        String prodsJson = JSON.serializePretty(prods);

        String result = ClientPlanACMProductSearchController.getAllACMProductsJson();
        System.assertEquals(prodsJson, result);
    }
}