objects/Request_Country__c.object
<CustomObject>
    <description>This object stores all countries that the request system holds with their associated</description>
    <fields>
        <fullName>LocaleSidKey__c</fullName>
        <description>The LocalSidKey linked to this Request Country</description>
        <inlineHelpText>The LocalSidKey linked to this Request Country</inlineHelpText>
        <label>LocaleSidKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ar_AE</fullName>
                </value>
                <value>
                    <fullName>ar_BH</fullName>
                </value>
                <value>
                    <fullName>ar_DZ</fullName>
                </value>
                <value>
                    <fullName>ar_EG</fullName>
                </value>
                <value>
                    <fullName>ar_IQ</fullName>
                </value>
                <value>
                    <fullName>ar_JO</fullName>
                </value>
                <value>
                    <fullName>ar_KW</fullName>
                </value>
                <value>
                    <fullName>ar_LB</fullName>
                </value>
                <value>
                    <fullName>ar_LY</fullName>
                </value>
                <value>
                    <fullName>ar_MA</fullName>
                </value>
                <value>
                    <fullName>ar_OM</fullName>
                </value>
                <value>
                    <fullName>ar_QA</fullName>
                </value>
                <value>
                    <fullName>ar_SA</fullName>
                </value>
                <value>
                    <fullName>ar_SD</fullName>
                </value>
                <value>
                    <fullName>ar_SY</fullName>
                </value>
                <value>
                    <fullName>ar_TN</fullName>
                </value>
                <value>
                    <fullName>ar_YE</fullName>
                </value>
                <value>
                    <fullName>az_AZ</fullName>
                </value>
                <value>
                    <fullName>be_BY</fullName>
                </value>
                <value>
                    <fullName>bg_BG</fullName>
                </value>
                <value>
                    <fullName>bn_BD</fullName>
                </value>
                <value>
                    <fullName>bs_BA</fullName>
                </value>
                <value>
                    <fullName>ca_ES</fullName>
                </value>
                <value>
                    <fullName>ca_ES_EURO</fullName>
                </value>
                <value>
                    <fullName>cs_CZ</fullName>
                </value>
                <value>
                    <fullName>cy_GB</fullName>
                </value>
                <value>
                    <fullName>da_DK</fullName>
                </value>
                <value>
                    <fullName>de_AT</fullName>
                </value>
                <value>
                    <fullName>de_AT_EURO</fullName>
                </value>
                <value>
                    <fullName>de_CH</fullName>
                </value>
                <value>
                    <fullName>en_US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFCountry__c</fullName>
        <description>The country used in Salesforce.</description>
        <inlineHelpText>The country used in Salesforce.</inlineHelpText>
        <label>SFCountry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Ghana</fullName>
                </value>
                <value>
                    <fullName>Kenya</fullName>
                </value>
                <value>
                    <fullName>Mauritius</fullName>
                </value>
                <value>
                    <fullName>Mozambique</fullName>
                </value>
                <value>
                    <fullName>Seychelles</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>Tanzania, United Republic of</fullName>
                </value>
                <value>
                    <fullName>Uganda</fullName>
                </value>
                <value>
                    <fullName>United Arab Emirates</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Zambia</fullName>
                </value>
                <value>
                    <fullName>Zimbabwe</fullName>
                </value>
                <value>
                    <fullName>Nigeria</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeZoneSidKey__c</fullName>
        <description>Salesforce TimeZone Id linked to the Request Country</description>
        <inlineHelpText>Salesforce TimeZone Id linked to the Request Country</inlineHelpText>
        <label>TimeZoneSidKey</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Africa/Algiers</fullName>
                </value>
                <value>
                    <fullName>Africa/Cairo</fullName>
                </value>
                <value>
                    <fullName>Africa/Casablanca</fullName>
                </value>
                <value>
                    <fullName>Africa/Johannesburg</fullName>
                </value>
                <value>
                    <fullName>Africa/Nairobi</fullName>
                </value>
                <value>
                    <fullName>America/Anchorage</fullName>
                </value>
                <value>
                    <fullName>America/Argentina/Buenos_Aires</fullName>
                </value>
                <value>
                    <fullName>America/Bogota</fullName>
                </value>
                <value>
                    <fullName>America/Caracas</fullName>
                </value>
                <value>
                    <fullName>America/Chicago</fullName>
                </value>
                <value>
                    <fullName>America/Denver</fullName>
                </value>
                <value>
                    <fullName>America/El_Salvador</fullName>
                </value>
                <value>
                    <fullName>America/Halifax</fullName>
                </value>
                <value>
                    <fullName>America/Indiana/Indianapolis</fullName>
                </value>
                <value>
                    <fullName>America/Lima</fullName>
                </value>
                <value>
                    <fullName>America/Los_Angeles</fullName>
                </value>
                <value>
                    <fullName>America/Mexico_City</fullName>
                </value>
                <value>
                    <fullName>America/New_York</fullName>
                </value>
                <value>
                    <fullName>America/Panama</fullName>
                </value>
                <value>
                    <fullName>America/Phoenix</fullName>
                </value>
                <value>
                    <fullName>America/Puerto_Rico</fullName>
                </value>
                <value>
                    <fullName>America/Santiago</fullName>
                </value>
                <value>
                    <fullName>America/Sao_Paulo</fullName>
                </value>
                <value>
                    <fullName>America/St_Johns</fullName>
                </value>
                <value>
                    <fullName>America/Tijuana</fullName>
                </value>
                <value>
                    <fullName>Asia/Baghdad</fullName>
                </value>
                <value>
                    <fullName>Asia/Bangkok</fullName>
                </value>
                <value>
                    <fullName>Asia/Colombo</fullName>
                </value>
                <value>
                    <fullName>Asia/Dhaka</fullName>
                </value>
                <value>
                    <fullName>Asia/Dubai</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Country</label>
    <nameField>
        <label>Request Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RequestChoice__c.object
<CustomObject>
    <description>This object stored all the request choice combinations with the associated role for each choice combination. Used as setup data in the API which is used by the request system.</description>
    <fields>
        <fullName>Business_Area__c</fullName>
        <description>The Business Area which is entered into the request system.</description>
        <inlineHelpText>The Business Area which is entered into the request system.</inlineHelpText>
        <label>Business Area</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country which one chooses on the request system</description>
        <inlineHelpText>The country which one chooses on the request system</inlineHelpText>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>The division that is chosen in request.</description>
        <inlineHelpText>The division that is chosen in request.</inlineHelpText>
        <label>Division</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hub__c</fullName>
        <description>The Hub the user chooses on the request system</description>
        <inlineHelpText>The Hub the user chooses on the request system</inlineHelpText>
        <label>Hub</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_ID__c</fullName>
        <label>Profile ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>The Region which someone chooses in Request</description>
        <inlineHelpText>The Region which someone chooses in Request</inlineHelpText>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <description>The Team Role chosen on the request system.</description>
        <inlineHelpText>The Team Role chosen on the request system.</inlineHelpText>
        <label>Team Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <description>The Team which is selected in the request system</description>
        <label>Team</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserRoleId__c</fullName>
        <description>This field holds the role that will map to all the choices one picks on the request system</description>
        <inlineHelpText>This field holds the role that will map to all the choices one picks on the request system</inlineHelpText>
        <label>UserRoleId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Request Choice</label>
    <nameField>
        <label>RequestChoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>BRID__c</fullName>
        <defaultValue>$User.FederationIdentifier</defaultValue>
        <description>The SSO unique Identifier</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BRID</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Business_Area__c</fullName>
        <label>Business Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To DO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hub__c</fullName>
        <label>Hub</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserRequestSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Setting__c</fullName>
        <description>The setting for the User Request Web API</description>
        <label>Setting</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>User Request Setting</label>
    <pluralLabel>User Request Settings</pluralLabel>
</CustomObject>

classes/UserRequest.cls
/**
* @Author:          Dino Scarcella
* @Company:         Absa Capital
* @Description:     Class which exposes custom API for User Operations to be called by external systems
* History
* <Date>      <Authors Name>     <Brief Description of Change>
*------------------------------------------------------------*/
@RestResource(urlMapping='/Users/v1/*')
global with sharing class UserRequest {
	public static String UsernameDomain;
	
	@HttpDelete
    global static String disableUser() {
        RestRequest request = RestContext.request;
        String BRID = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        List<User> UserToDisable = [SELECT Id FROM User WHERE BRID__c = :BRID LIMIT 1];
        if (UserToDisable != null && UserToDisable.size()>0) {
        	UserToDisable[0].isActive = false;
        	update UserToDisable[0];
        	return 'User successfully disabled';
        } else {
        	RestContext.response.statusCode = 400; return 'Invalid User';
        }
    }

	@HttpPost
    global static String upsertUser(String FirstName, String LastName, String EmailAddress, String FederationIdentifier, String Country, 
    								String BusinessArea, String Division, String Hub, String Region, String Team, String TeamRole, 
    								String Phone, String ManagerFederationIdentifier, String License) {
        User UserToUpsert = new User();
        Profile ChatterFreeProfile = [SELECT id, Name FROM Profile where name = 'Chatter Free User'].get(0);
        UserToUpsert.isActive = true;
        List<Request_Country__c> rcntry = [SELECT LocaleSidKey__c, SFCountry__c, TimeZoneSidKey__c, CurrencyIsoCode 
        						 FROM Request_Country__c WHERE Name =:Country LIMIT 1];
        if (rcntry != null && rcntry.size() > 0) {
        	UserToUpsert.Country = rcntry[0].SFCountry__c;
        	UserToUpsert.LocaleSidKey = rcntry[0].LocaleSidKey__c;
        	UserToUpsert.TimeZoneSidKey = rcntry[0].TimeZoneSidKey__c;
        	UserToUpsert.CurrencyIsoCode = rcntry[0].CurrencyIsoCode;
        	UserToUpsert.DefaultCurrencyIsoCode = rcntry[0].CurrencyIsoCode;
        } else {
        	RestContext.response.statusCode = 400; return 'Invalid Country';
        }
        
        if (FirstName != null && FirstName != '') {
        	UserToUpsert.FirstName = FirstName;
        } else {
        	RestContext.response.statusCode = 400; return 'Invalid FirstName';
        }
        
        if (LastName != null && LastName != '') {
        	UserToUpsert.LastName = LastName;
        } else {
        	RestContext.response.statusCode = 400; return 'Invalid LastName';
        }
        
        Integer LastNameEndIndex = 4;
        if (LastName.length() < 4) LastNameEndIndex = LastName.length();
        UserToUpsert.Alias = FirstName.substring(0,1).toLowerCase() + LastName.substring(0,LastNameEndIndex).toLowerCase();
        if ((FirstName.toLowerCase() + '.' + LastName.toLowerCase()).length() > 40)
        	UserToUpsert.CommunityNickname = (FirstName.toLowerCase() + '.' + LastName.toLowerCase()).substring(0,40);
        else
        	UserToUpsert.CommunityNickname = FirstName.toLowerCase() + '.' + LastName.toLowerCase();
        
        for(UserRequestSetting__mdt settings : [SELECT DeveloperName, Setting__c FROM UserRequestSetting__mdt WHERE DeveloperName IN('UsernameDomain')]){
        	if (settings.DeveloperName == 'UsernameDomain') UsernameDomain = settings.Setting__c;
        }
        if (UsernameDomain == null || UsernameDomain == '') { RestContext.response.statusCode = 400; return 'Invalid User Domain Setting'; }
        UserToUpsert.Username = UserToUpsert.CommunityNickname + UsernameDomain;
        
        if (EmailAddress != null && EmailAddress != '' && validateEmail(EmailAddress)) {
        	UserToUpsert.Email = EmailAddress;
        } else {
        	RestContext.response.statusCode = 400; return 'Invalid Email';
        }
        
        if (Phone != null && Phone != '') {
        	if (Phone.length() > 40) UserToUpsert.Phone = Phone.substring(0,40);
        	else UserToUpsert.Phone = Phone; 	
        }
        
        UserToUpsert.EmailEncodingKey = 'ISO-8859-1';
     	UserToUpsert.LanguageLocaleKey = 'en_US';
     	
     	if (License == null || (License != 'Collaboration' && License != 'Complete CRM Functionality')) {
			RestContext.response.statusCode = 400; return 'Invalid License Type';
     	}
     	
     	if (Division != null && Division != '') {
        	UserToUpsert.Division__c = Division;
        } else {
        	RestContext.response.statusCode = 400; return 'Invalid Division';
     	}
     	
     	if (License == 'Complete CRM Functionality') {
     		if (BusinessArea != null && BusinessArea != '') {
        		UserToUpsert.Business_Area__c = BusinessArea;
        	} else {
        		RestContext.response.statusCode = 400; return 'Invalid Business Area';
        	}
        	if (Hub != null && Hub != '') {
        		UserToUpsert.Hub__c = Hub;
        	} else {
        		RestContext.response.statusCode = 400; return 'Invalid Hub';
        	}
	        if (Region != null && Region != '') {
	        	UserToUpsert.Region__c = Region;
	        } else {
	        	RestContext.response.statusCode = 400; return 'Invalid Region';
	        }
	        if (Team != null && Team != '') {
	        	UserToUpsert.Team__c = Team;
	        } else {
	        	RestContext.response.statusCode = 400; return 'Invalid Team';
	        }
	        if (TeamRole != null && TeamRole != '') {
	        	UserToUpsert.Team_Role__c = TeamRole;
	        } else {
	        	RestContext.response.statusCode = 400; return 'Invalid Team Role';
	        }
	        if (ManagerFederationIdentifier != null && ManagerFederationIdentifier != '') {
				List<User> Manager = [SELECT Id FROM User WHERE BRID__c =:ManagerFederationIdentifier LIMIT 1];
				if (Manager != null && Manager.size()>0) {
					UserToUpsert.ManagerID = Manager[0].Id;					
				} else {
					RestContext.response.statusCode = 400; return 'Invalid Manager Federation Identifier';
				}       	
	        }
	     	List<RequestChoice__c> rchoice = [SELECT 	Profile_ID__c, UserRoleId__c, 
	     												UserPermissionsKnowledgeUser__c, UserPermissionsSupportUser__c
	        						 FROM RequestChoice__c WHERE Country__c =:Country AND Business_Area__c =:BusinessArea
	        						 							 AND Division__c =:Division AND Hub__c =:Hub AND Region__c =:Region
	        						 							 AND Team__c =:Team AND Team_Role__c =:TeamRole LIMIT 1];
	        if (rchoice != null && rchoice.size()>0) {
	 			UserToUpsert.ProfileId = rchoice[0].Profile_ID__c;
	 			UserToUpsert.UserRoleId = rchoice[0].UserRoleId__c;
	 			UserToUpsert.UserPermissionsKnowledgeUser = rchoice[0].UserPermissionsKnowledgeUser__c;
	 			UserToUpsert.UserPermissionsSupportUser = rchoice[0].UserPermissionsSupportUser__c;
	        } else {
	        	RestContext.response.statusCode = 400; return 'No Profile and Role found for this combination';
	        }	
     	} else {
			UserToUpsert.ProfileId = ChatterFreeProfile.Id;
     	}
        
        if (FederationIdentifier != null && FederationIdentifier != '') {
        	UserToUpsert.FederationIdentifier = FederationIdentifier;
        	Integer FederationIdentifierEndIndex = 9;
        	if (FederationIdentifier.length() < 9) FederationIdentifierEndIndex = FederationIdentifier.length();
        	UserToUpsert.BRID__c = FederationIdentifier.substring(0,FederationIdentifierEndIndex);
        } else {
        	RestContext.response.statusCode = 400; return 'Invalid Federation Identifier';
        }
        
        UserToUpsert.UserPreferencesHideChatterOnboardingSplash = true;
        UserToUpsert.UserPreferencesHideSecondChatterOnboardingSplash = true;
		
		// if we're updating Chatter Free User make sure notifications work
		Database.DMLOptions dlo;
     	if (License == 'Collaboration') {
     		dlo = new Database.DMLOptions();
     		dlo.EmailHeader.triggerUserEmail = true;
     		dlo.EmailHeader.triggerAutoResponseEmail = true;
     		UserToUpsert.setOptions(dlo);					
     	}
		
		try {
     		List<User> UsersToUpsert = [SELECT Id, ProfileId FROM User WHERE BRID__c =:UserToUpsert.BRID__c LIMIT 1];
     		if (UsersToUpsert != null && UsersToUpsert.size() > 0) {
     			UserToUpsert.Id = UsersToUpsert[0].Id;
     			// we're upgrading a user from chatter free to full profile, need to do an update of user role after update of profile
     			if (ChatterFreeProfile.Id == UsersToUpsert[0].ProfileId && License == 'Complete CRM Functionality') {
     				String UserRoleId = UserToUpsert.UserRoleId;
     				dlo = new Database.DMLOptions();
     				dlo.EmailHeader.triggerUserEmail = false;
     				dlo.EmailHeader.triggerAutoResponseEmail = false;
     				UserToUpsert.setOptions(dlo);
     				UserToUpsert.UserRoleId = null;
     				update UserToUpsert;
					UserToUpsert.UserRoleId = UserRoleId;
     			}
     			update UserToUpsert;
	        	return 'User successfully updated';
        	} else {
        		insert UserToUpsert;
        		return 'User successfully inserted';
        	}
     	} catch (Exception exc) {
     		RestContext.response.statusCode = 400; return 'User Upsert Failed: ' + exc.getMessage();
     	}
    }
    
    private static Boolean validateEmail(String Email) {
    	String emailRegex = '([a-zA-Z0-9_\\-\\.]+)@((\\[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})';
    	Pattern MyPattern = Pattern.compile(emailRegex);
	    Matcher MyMatcher = MyPattern.matcher(Email);
    	if (!MyMatcher.matches()) return false;
    	return true;
	}
}