objects/Service_Mapping__c.object
<CustomObject>
    <description>Object to Capture Service Process and Resulting Service Category, Sub-Category and Type Applicable Information to Render on Cases Page</description>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <label>Business Hours</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Hours</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Channel</description>
        <inlineHelpText>Please select appropriate Channel. Selection is dependent on Service Type.</inlineHelpText>
        <label>Channel</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Complexity__c</fullName>
        <label>Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Complexity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Convert_To_RecordType__c</fullName>
        <description>RN - CloudSmith - If populated change the Case record type to the value in this field</description>
        <inlineHelpText>Please enter the record type Developer Name if you want the Case record type to change for this Service Type after classification</inlineHelpText>
        <label>Convert To RecordType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Department</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>RN : CloudSmiths
The date when this service mapping with SLA is effective from</description>
        <inlineHelpText>The date when this service mapping with SLA is effective from</inlineHelpText>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_SLA_Time_Measure__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Email SLA Time Measure</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Time_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_SLA_Units__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Email SLA Units</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feedback_Time_Measure__c</fullName>
        <description>RN - CloudSmiths - the time units for the feedback alert email to be sent for a service type</description>
        <label>Feedback Time Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Time_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feedback_Units__c</fullName>
        <description>RN - CloudSmiths - Units for each client  feedback email alert</description>
        <label>Feedback Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Approval__c</fullName>
        <description>First Approval</description>
        <inlineHelpText>First Approval</inlineHelpText>
        <label>First Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Team Memeber</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Escalation_Time__c</fullName>
        <label>First Escalation Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Full_Department__c</fullName>
        <label>Full Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Absa Electronic Banking Helpdesk</fullName>
                </value>
                <value>
                    <fullName>Absa Electronic Banking Service Support</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Support Corporate Cape Town</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Commercial Cape Town</fullName>
                </value>
                <value>
                    <fullName>Trade Client Service Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Enterprise Pretoria</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Commercial Pretoria</fullName>
                </value>
                <value>
                    <fullName>Channel Specialist</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Corporate Cape Town</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Support Corporate Pretoria</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Corporate Pretoria</fullName>
                </value>
                <value>
                    <fullName>Product On-boarding</fullName>
                </value>
                <value>
                    <fullName>Digital Ops Support</fullName>
                </value>
                <value>
                    <fullName>Botswana CCC SA</fullName>
                </value>
                <value>
                    <fullName>Payments Operations</fullName>
                </value>
                <value>
                    <fullName>Transfer Inwards</fullName>
                </value>
                <value>
                    <fullName>Structured Commodity Finance</fullName>
                </value>
                <value>
                    <fullName>Structured Trade Finance</fullName>
                </value>
                <value>
                    <fullName>RBB Cash Operations</fullName>
                </value>
                <value>
                    <fullName>Open Account - Middle Office</fullName>
                </value>
                <value>
                    <fullName>Functions Technology</fullName>
                </value>
                <value>
                    <fullName>Salesforce Africa</fullName>
                </value>
                <value>
                    <fullName>Trade Operations</fullName>
                </value>
                <value>
                    <fullName>CIB Financial Crime Compliance</fullName>
                </value>
                <value>
                    <fullName>Future clearing</fullName>
                    <label>Futures clearing</label>
                </value>
                <value>
                    <fullName>SA Migrations</fullName>
                </value>
                <value>
                    <fullName>Wholesale Client Service Centre</fullName>
                </value>
                <value>
                    <fullName>inward payments Client service and support</fullName>
                </value>
                <value>
                    <fullName>Cash Send</fullName>
                </value>
                <value>
                    <fullName>Refresh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ID_V_Required__c</fullName>
        <description>ID&amp;V Required</description>
        <inlineHelpText>Level of ID&amp;V Required. Dependent on Service Type.</inlineHelpText>
        <label>ID&amp;V Required</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Strong</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Priority</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>RN : CloudSmiths</description>
        <inlineHelpText>Please use the Queue API name</inlineHelpText>
        <label>Queue Name (API Name)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Queue</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Response_From_Email_Address__c</fullName>
        <description>RN - CloudSmiths - Org wide email address that will be used as the from address when the support process sends out email responses</description>
        <inlineHelpText>Please enter a valid Org Wide Email Address to be used as the from address on email responses from Salesforce</inlineHelpText>
        <label>Response From Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SLA_Pause_Status_Internal__c</fullName>
        <description>RN - CloudSmiths - indicates which case statuses should pause the SLA RAG indicator tracking for internal related holdups</description>
        <inlineHelpText>Add valid Case status values here, that will indicates which case statuses should pause the SLA RAG indicator tracking, per service type. These are internal delays. 
Comma separate multiple values: e.g. Closed Duplicate,Awaiting Feedback - 3rd Party</inlineHelpText>
        <label>SLA Pause Status (Internal)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Pause_Status__c</fullName>
        <description>RN - CloudSmiths - indicates which case statuses should pause the SLA RAG indicator tracking</description>
        <inlineHelpText>Add valid Case status values here, that will indicates which case statuses should pause the SLA RAG indicator tracking, per service type. 
Comma separate multiple values:  e.g. Closed Duplicate,Awaiting Feedback - Client</inlineHelpText>
        <label>SLA Pause Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Time_Measure__c</fullName>
        <label>SLA Time Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Time_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA_Units__c</fullName>
        <label>SLA Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <formula>TEXT( SLA_Units__c ) &amp; &quot; &quot; &amp; TEXT( SLA_Time_Measure__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLA</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Second_Approval__c</fullName>
        <description>Second Approval</description>
        <inlineHelpText>Second Approval</inlineHelpText>
        <label>Second Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EBSH Team Member</fullName>
                </value>
                <value>
                    <fullName>EBSS Team Leader</fullName>
                </value>
                <value>
                    <fullName>EBSS Team Member</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>EBSH Team Leader</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Escalation_Time__c</fullName>
        <label>Second Escalation Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Category__c</fullName>
        <label>Service Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Email_Address__c</fullName>
        <label>Support Email Address</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Email</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Manager__c</fullName>
        <label>Team Manager</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Team_Manager</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Team</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template_Name_Email_Receipt__c</fullName>
        <description>RN : CloudSmiths
Email Template API name - utilized in the Case trigger</description>
        <inlineHelpText>Email Template API name</inlineHelpText>
        <label>Template Name - Email Receipt</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Service Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Business_Hours.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Monday to Friday 06:00 - 19:00</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 07:30 - 17:00</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 08:00 - 16:30</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 07:00 - 16:30</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 08:00 - 18:00</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday     08:00 - 17:00</fullName>
    </customValue>
    <masterLabel>Business Hours</masterLabel>
</GlobalValueSet>

globalValueSets/Complexity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>High</fullName>
    </customValue>
    <customValue>
        <fullName>Medium</fullName>
    </customValue>
    <customValue>
        <fullName>Low</fullName>
    </customValue>
    <masterLabel>Complexity</masterLabel>
</GlobalValueSet>

globalValueSets/Department.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>EBSS</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Commercial PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Commercial CPT</fullName>
    </customValue>
    <customValue>
        <fullName>TCSM</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate CPT &amp; PTA</fullName>
    </customValue>
    <customValue>
        <fullName>POB</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Enterprise PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>DOS</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH ROA</fullName>
    </customValue>
    <customValue>
        <fullName>Investigations</fullName>
    </customValue>
    <customValue>
        <fullName>ITC</fullName>
    </customValue>
    <customValue>
        <fullName>TRI</fullName>
    </customValue>
    <customValue>
        <fullName>SCF</fullName>
    </customValue>
    <customValue>
        <fullName>STF</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Operations</fullName>
    </customValue>
    <customValue>
        <fullName>OA - MO</fullName>
    </customValue>
    <customValue>
        <fullName>F-Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>BGI</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Crime Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Future Clearing</fullName>
    </customValue>
    <customValue>
        <fullName>SA Migrations - JHB</fullName>
    </customValue>
    <masterLabel>Department</masterLabel>
</GlobalValueSet>

globalValueSets/Email.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>absaeb@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>absaglobalsa@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>africaebprocessing@barclaysafrica.com</fullName>
    </customValue>
    <customValue>
        <fullName>barclays.netonboarding@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>barclays.netsupport@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>barclays.netsupport@barclaysafrica.com</fullName>
    </customValue>
    <customValue>
        <fullName>biactivations@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>biocert@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>cashfocus@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>cscdocumentation@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>EBS.2ndLineEscalations@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebs.moten.ngele@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebs.natalie.marais@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebsamendments@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebslimitsbilling@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebsnewregistration@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>EFXSupport@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>magtapes@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>Passwords@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>paymentssupport@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>cscsupport@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>xracscsupport@barclayscapital.com</fullName>
    </customValue>
    <customValue>
        <fullName>xracscsupporthelpdes@barclayscapital.com</fullName>
    </customValue>
    <customValue>
        <fullName>ebs.Insan.Parton@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>xraCorporateProductO@barclayscapital.com</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corpdvb@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corplc@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corpmc@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corpni@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corprc@absa.co.za</fullName>
    </customValue>
    <masterLabel>Email</masterLabel>
</GlobalValueSet>

globalValueSets/Priority.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Occured</fullName>
    </customValue>
    <customValue>
        <fullName>High</fullName>
    </customValue>
    <customValue>
        <fullName>Medium</fullName>
    </customValue>
    <customValue>
        <fullName>Low</fullName>
    </customValue>
    <masterLabel>Priority</masterLabel>
</GlobalValueSet>

globalValueSets/Queue.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Banking Advisory Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Breaks</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Send</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Bloem</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare DBN</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Goodwood</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Kempton</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Klerksdorp</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Ormonde</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare PE</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare PTA</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Vaal</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Witbank</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement DBN</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement JHB</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement PE</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Finance Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Client</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Csctradesupport</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - DebiCheck</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - General</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - NovoFX</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - 2nd Line</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - Absa Electronic Banking</fullName>
    </customValue>
    <masterLabel>Queue</masterLabel>
</GlobalValueSet>

globalValueSets/Service_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Incident</fullName>
    </customValue>
    <customValue>
        <fullName>Service Related</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request</fullName>
    </customValue>
    <customValue>
        <fullName>Service Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Migration-Phase 2 Local Banking to BIO</fullName>
    </customValue>
    <masterLabel>Service Category</masterLabel>
</GlobalValueSet>

globalValueSets/SLA_Time_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <customValue>
        <fullName>Hour(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Day(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Week(s)</fullName>
    </customValue>
    <masterLabel>SLA Time Measure</masterLabel>
</GlobalValueSet>

globalValueSets/SLA_Unit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <masterLabel>SLA Unit</masterLabel>
</GlobalValueSet>

globalValueSets/Team.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2nd Line</fullName>
    </customValue>
    <customValue>
        <fullName>Absa Electronic Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Absa Global</fullName>
    </customValue>
    <customValue>
        <fullName>Activations</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net Amendments</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net CSC Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net Processing</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net Rest of Africa</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net SA</fullName>
    </customValue>
    <customValue>
        <fullName>Billing &amp; Limits</fullName>
    </customValue>
    <customValue>
        <fullName>C2B</fullName>
    </customValue>
    <customValue>
        <fullName>CSC Documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Diamond</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Certificates</fullName>
    </customValue>
    <customValue>
        <fullName>EBSS Approvals</fullName>
    </customValue>
    <customValue>
        <fullName>EFX Support</fullName>
    </customValue>
    <customValue>
        <fullName>Magtapes</fullName>
    </customValue>
    <customValue>
        <fullName>New Registrations</fullName>
    </customValue>
    <customValue>
        <fullName>Passwords</fullName>
    </customValue>
    <customValue>
        <fullName>Sweeping</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>TCSM</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Product On-boarding</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Ops Support</fullName>
    </customValue>
    <customValue>
        <fullName>NovoFX</fullName>
    </customValue>
    <masterLabel>Team</masterLabel>
</GlobalValueSet>

globalValueSets/Team_Manager.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Almarie Boshoff</fullName>
    </customValue>
    <customValue>
        <fullName>Ameeth Lakhani</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Henery</fullName>
    </customValue>
    <customValue>
        <fullName>Berenice Thaver</fullName>
    </customValue>
    <customValue>
        <fullName>Bernadette Mckay</fullName>
    </customValue>
    <customValue>
        <fullName>Brian Shabane</fullName>
    </customValue>
    <customValue>
        <fullName>Carmen Zandberg</fullName>
    </customValue>
    <customValue>
        <fullName>Charmaine Burger</fullName>
    </customValue>
    <customValue>
        <fullName>Corne Geyer</fullName>
    </customValue>
    <customValue>
        <fullName>Daniel Coetzee</fullName>
    </customValue>
    <customValue>
        <fullName>Daniel Masindi</fullName>
    </customValue>
    <customValue>
        <fullName>Dudu Mtsweni</fullName>
    </customValue>
    <customValue>
        <fullName>Eleanor Snyders</fullName>
    </customValue>
    <customValue>
        <fullName>Elmarie Meyer</fullName>
    </customValue>
    <customValue>
        <fullName>Frederik Theodorus Ferreira</fullName>
    </customValue>
    <customValue>
        <fullName>Gerard Voskuil</fullName>
    </customValue>
    <customValue>
        <fullName>Hajira Bagus</fullName>
    </customValue>
    <customValue>
        <fullName>Iraan Singh</fullName>
    </customValue>
    <customValue>
        <fullName>Isebeau Spies</fullName>
    </customValue>
    <customValue>
        <fullName>Jacky Naidoo</fullName>
    </customValue>
    <customValue>
        <fullName>Jessica Gounden</fullName>
    </customValue>
    <customValue>
        <fullName>Jordaan Sonja</fullName>
    </customValue>
    <customValue>
        <fullName>Kgopotso Mathole</fullName>
    </customValue>
    <customValue>
        <fullName>Knowledge Zulu</fullName>
    </customValue>
    <customValue>
        <fullName>Lethabo Ramokoka</fullName>
    </customValue>
    <customValue>
        <fullName>Marius Goeieman</fullName>
    </customValue>
    <customValue>
        <fullName>Marsha De Wet</fullName>
    </customValue>
    <customValue>
        <fullName>Monica Tyler</fullName>
    </customValue>
    <customValue>
        <fullName>Narina Butler</fullName>
    </customValue>
    <customValue>
        <fullName>Nomcebo Mdlozini</fullName>
    </customValue>
    <masterLabel>Team Manager</masterLabel>
</GlobalValueSet>

classes/CSC_Case_Functions_Complaint.cls
/**
* Date   : 11-05-2016
* Author : RN - CloudSmiths
* Desc   : Utility class for Cases. Contains Functions that can be used with Case creations and updates
*--------------------------------------------
* Date   : 20170322
* Author : RN - CloudSmiths
* Desc   : Add new Org Wide Address feature for responses out of SF
*
* UPDATES:
*---------
*2017-05-16: Rudolf Niehaus - CloudSmiths : Add flexi email SLA times
*2017-05-18: Rudolf Niehaus - CloudSmiths : SLA Pause feature 
*2017-07-11: Rudolf Niehaus - CloudSmmiths : SLA 3rd party pause feature
**/
public class CSC_Case_Functions_Complaint {
    
    public Case theCase {get;set;}
    public map<String,String> serviceMap = new map<String,String>();
    public list<Service_Mapping__c> sm = new list<Service_Mapping__c>();
    public map<String,String> templateMapEmailReceipt = new map<String,String>();
    public map<String,String> templateMapCaseCreation = new map<String,String>();
    public map<String,String> templateMapCaseClose = new map<String,String>();
    public map<String,String> templateMapCaseFeedback = new map<String,String>();
    public map<String,String> orgWideAddressMap = new map<String,String>();
    
    //prevent triggers firing twice after WF field updates
    public static boolean firstRun = true;
    public static boolean firstRunTracking = true;
    
    //constructor that takes only the support email address and map relevent values out for the service mapping table
    //This constructor is used in the email to case custom email handler
    public CSC_Case_Functions_Complaint(String emailAddress){
        
        //get to to email address prefix
        String[] splitEmail = emailAddress.split('@');
        String emailPrefix = splitEmail[0];
        
        //Chater for netsupport between ABSA and Barcalys
        if(emailPrefix.contains('barclaysafrica') && emailPrefix.contains('barclays.netsupport')){
            emailPrefix = 'barclays.netsupport@barclaysafrica';
        }else if(emailPrefix.contains('absa') && emailPrefix.contains('barclays.netsupport')){
            emailPrefix = 'barclays.netsupport@absa';
        }else{
            emailPrefix+= '@';
        }
        
        sm = [Select Id, Team__c, Queue_Name__c, Queue__c, Business_Hours__c, Department__c,Channel__c, Support_Email_Address__c, 
              Full_Department__c, Team_Manager__c, Response_From_Email_Address__c, Email_SLA_Time_Measure__c , Email_SLA_Units__c   
              From Service_Mapping__c 
              Where Support_Email_Address__c like :emailPrefix + '%' 
              Order By Effective_Date__c DESC limit 1];
        
        //map service type values ONLY if we get a record back from the mapping table
        if(sm.size() > 0){
            serviceMap.put('Support_Email_Address__c', sm[0].Support_Email_Address__c);
            serviceMap.put('Team_Manager__c', sm[0].Team_Manager__c);
            serviceMap.put('Team__c', sm[0].Team__c);
            serviceMap.put('Queue_Name__c', sm[0].Queue_Name__c);
            serviceMap.put('Queue__c', sm[0].Queue__c);
            serviceMap.put('Department__c', sm[0].Department__c);
            serviceMap.put('Business_Hours__c', sm[0].Business_Hours__c);
            serviceMap.put('Channel__c', sm[0].Channel__c);
            serviceMap.put('Full_Department__c ', sm[0].Full_Department__c );
            serviceMap.put('Response_From_Email_Address__c ', sm[0].Response_From_Email_Address__c );
            serviceMap.put('Id', sm[0].Id);
            serviceMap.put('Email_SLA_Time_Measure__c', sm[0].Email_SLA_Time_Measure__c);
            serviceMap.put('Email_SLA_Units__c', sm[0].Email_SLA_Units__c);
        }
    }
    
    //
    public CSC_Case_Functions_Complaint(){}
    
    //constructor - takes the Case in scope as param and retrieve the relevant service mapping for this case
    public CSC_Case_Functions_Complaint(Case c){
        
        this.theCase = c;
        if(String.isNotBlank(theCase.Complaint_Service_Category__c)){
                sm = [Select Id, Complexity__c, First_Approval__c, ID_V_Required__c, Priority__c,SLA_Pause_Status__c,SLA_Pause_Status_Internal__c,
                      SLA__c, Second_Approval__c, Team__c, Queue_Name__c,Department__c,Queue__c, Feedback_Time_Measure__c, Feedback_Units__c,   
                      First_Escalation_Time__c, Second_Escalation_Time__c, Support_Email_Address__c,Response_From_Email_Address__c, 
                      Channel__c, Business_Hours__c, SLA_Time_Measure__c , SLA_Units__c, Full_Department__c, Team_Manager__c, Convert_To_RecordType__c     
                      From Service_Mapping__c 
                      Where Queue__c = :theCase.Resolving_Team__c 
                      and Service_Category__c = :theCase.Complaint_Service_Category__c 
                      Order By Effective_Date__c DESC Limit 1 ];
            }else{
                sm = [Select Id, Complexity__c, First_Approval__c, ID_V_Required__c, Priority__c,SLA_Pause_Status__c,SLA_Pause_Status_Internal__c,
                      SLA__c, Second_Approval__c, Team__c, Queue_Name__c,Department__c,Queue__c,Feedback_Time_Measure__c, Feedback_Units__c,   
                      First_Escalation_Time__c, Second_Escalation_Time__c, Support_Email_Address__c,Response_From_Email_Address__c, 
                      Channel__c, Business_Hours__c, SLA_Time_Measure__c , SLA_Units__c, Full_Department__c, Team_Manager__c, Convert_To_RecordType__c     
                      From Service_Mapping__c 
                      Where Queue__c = :theCase.Resolving_Team__c 
                      Order By Effective_Date__c DESC Limit 1 ];
            }
            
            System.debug('sm Size '+sm.size());
            if(sm.size() == 0){
                sm = [Select Id, Complexity__c, First_Approval__c, ID_V_Required__c, Priority__c,SLA_Pause_Status__c,SLA_Pause_Status_Internal__c,
                      SLA__c, Second_Approval__c, Team__c, Queue_Name__c,Department__c,Queue__c,Feedback_Time_Measure__c, Feedback_Units__c,   
                      First_Escalation_Time__c, Second_Escalation_Time__c, Support_Email_Address__c,Response_From_Email_Address__c, 
                      Channel__c, Business_Hours__c, SLA_Time_Measure__c , SLA_Units__c, Full_Department__c, Team_Manager__c, Convert_To_RecordType__c     
                      From Service_Mapping__c 
                      Where Queue__c = :theCase.Resolving_Team__c 
                      Order By Effective_Date__c DESC Limit 1 ];
            }
        
        
        
        //map service type values ONLY if we get a record back from the mapping table
        if(sm.size() > 0){
            serviceMap.put('SLA_Time_Measure__c', sm[0].SLA_Time_Measure__c);
            serviceMap.put('SLA_Units__c', sm[0].SLA_Units__c);
            serviceMap.put('Complexity__c', sm[0].Complexity__c);
            serviceMap.put('First_Approval__c', sm[0].First_Approval__c);
            serviceMap.put('ID_V__c', sm[0].ID_V_Required__c);
            serviceMap.put('Priority', sm[0].Priority__c);
            serviceMap.put('SLA__c', sm[0].SLA__c);
            serviceMap.put('Second_Approval__c', sm[0].Second_Approval__c);
            serviceMap.put('Team__c', sm[0].Team__c);
            serviceMap.put('Team_Manager__c', sm[0].Team_Manager__c);
            serviceMap.put('Queue_Name__c', sm[0].Queue_Name__c);
            serviceMap.put('First_Escalation_Time__c', String.valueOf(sm[0].First_Escalation_Time__c));
            serviceMap.put('Second_Escalation_Time__c', String.valueOf(sm[0].Second_Escalation_Time__c));
            serviceMap.put('Business_Hours__c', sm[0].Business_Hours__c);
            serviceMap.put('Channel__c', sm[0].Channel__c);
            serviceMap.put('Department__c', sm[0].Department__c);
            serviceMap.put('Full_Department__c', sm[0].Full_Department__c );
            serviceMap.put('Queue__c', sm[0].Queue__c);
            serviceMap.put('Id', sm[0].Id);
            serviceMap.put('Convert_To_RecordType__c', sm[0].Convert_To_RecordType__c);
            serviceMap.put('Feedback_Time_Measure__c', sm[0].Feedback_Time_Measure__c);
            serviceMap.put('Feedback_Units__c', sm[0].Feedback_Units__c);
            serviceMap.put('Response_From_Email_Address__c ', sm[0].Response_From_Email_Address__c );
            serviceMap.put('SLA_Pause_Status__c', sm[0].SLA_Pause_Status__c);
            serviceMap.put('SLA_Pause_Status_Internal__c', sm[0].SLA_Pause_Status_Internal__c);
        }
    }
    
    //The method returns a map with the queue a keys and email template ID as values and the Org Wide Addresses per queue
    public void populateQueueTemplateIDMaps(){
        
        map<String,String> templateMap = new map<String,String>();
        for(EmailTemplate et :[Select Id, DeveloperName, IsActive From EmailTemplate]){
            templateMap.put(et.DeveloperName, et.Id);
        }
        
        
        for(Service_Mapping__c smap :ServiceMappingHandler.getServiceMappingInstance()){
                                          
                                          templateMapEmailReceipt.put(smap.Queue__c,templateMap.get(smap.Template_Name_Email_Receipt__c));
                                          templateMapCaseCreation.put(smap.Queue__c,templateMap.get(smap.Template_Name_Case_Creation__c));
                                          templateMapCaseClose.put(smap.Queue__c,templateMap.get(smap.Template_Name_Case_Close__c));
                                          templateMapCaseFeedback.put(smap.Queue__c,templateMap.get(smap.Template_Name_Feedback_Email__c));
                                          orgWideAddressMap.put(smap.Queue__c,smap.Response_From_Email_Address__c);
                                          
                                          
                                      }
    }
    
    //return a map that contains the Case API Field names as keys and the service mapping values per key
    public map<String,String> getServiceMapping(){
        return serviceMap;
    }
    
    //Ajust SLA End date base on queue and business hours
    public list<DateTime> getSLAEndDate(DateTime slaStartDate){
        
        String nameOfBusinessHours = '';
        if(serviceMap.containsKey('Business_Hours__c')){
            nameOfBusinessHours = serviceMap.get('Business_Hours__c');
        }
        
        list<BusinessHours> bhId = [Select Id From BusinessHours Where IsActive=true and Name = :nameOfBusinessHours];
        
        if(bhId.size() == 0){
            bhId = [Select Id From BusinessHours Where IsDefault=true];
        }
        
        String timeMeasure = serviceMap.get('SLA_Time_Measure__c');
        Integer timeUnits = Integer.valueOf(serviceMap.get('SLA_Units__c'));
        
        //hours in milliseconds
        if(timeMeasure.contains('Hour')){
            timeUnits = timeUnits * 60 * 60 * 1000;
        }else if(timeMeasure.contains('Day')){
            timeUnits = timeUnits * 9; //9 hour day
            timeUnits = timeUnits * 60 * 60 * 1000;
        }else if(timeMeasure.contains('Week')){
            timeUnits = timeUnits * 45; //5 day week at 9 hours per day
            timeUnits = timeUnits * 60 * 60 * 1000;
        }
        
        Integer warningTime = 0;
        
        if(timeUnits == (60 * 60 * 1000)){
            warningTime = 30 * 60 * 1000; //30min
        }else if(timeUnits > (60 * 60 * 1000)){
            warningTime = 60 * 60 * 1000; //60min
        }
        
        list<DateTime> returnArray = new list<DateTime>();
        
        returnArray.add(BusinessHours.add(bhId[0].Id, slaStartDate, (timeUnits - warningTime)));
        returnArray.add(BusinessHours.add(bhId[0].Id, slaStartDate, timeUnits));
        
        return returnArray;
    }
    
    //Get client feedback due date
    public DateTime getFeedbackDueDate(DateTime feedbackStartDate){
        
        String nameOfBusinessHours = '';
        if(serviceMap.containsKey('Business_Hours__c')){
            nameOfBusinessHours = serviceMap.get('Business_Hours__c');
        }
        
        list<BusinessHours> bhId = [Select Id From BusinessHours Where IsActive=true and Name = :nameOfBusinessHours];
        
        if(bhId.size() == 0){
            bhId = [Select Id From BusinessHours Where IsDefault=true];
        }
        
        String timeMeasure = 'Day';
        
        if(serviceMap.get('Feedback_Time_Measure__c') != null){
            timeMeasure = serviceMap.get('Feedback_Time_Measure__c');
        }    
        
        
        Integer timeUnits = 0;
        
        if(serviceMap.get('Feedback_Units__c') != null){
            timeUnits = Integer.valueOf(serviceMap.get('Feedback_Units__c'));
        }
        
        //hours in milliseconds
        if(timeMeasure.contains('Hour')){
            timeUnits = timeUnits * 60 * 60 * 1000;
        }else if(timeMeasure.contains('Day')){
            timeUnits = timeUnits * 9; //9 hour day
            timeUnits = timeUnits * 60 * 60 * 1000;
        }else if(timeMeasure.contains('Week')){
            timeUnits = timeUnits * 45; //5 day week at 9 hours per day
            timeUnits = timeUnits * 60 * 60 * 1000;
        }
        
        DateTime duedate = BusinessHours.add(bhId[0].Id, feedbackStartDate, timeUnits);       
        return duedate;
    }
    
    //Get Email SLA dates base on queue
    public list<DateTime> getEmailSLAEndDate(DateTime slaStartDate){
        
        String nameOfBusinessHours = '';
        if(serviceMap.containsKey('Business_Hours__c')){
            nameOfBusinessHours = serviceMap.get('Business_Hours__c');
        }
        
        list<BusinessHours> bhId = [Select Id From BusinessHours Where IsActive=true and Name = :nameOfBusinessHours];
        
        if(bhId.size() == 0){
            bhId = [Select Id From BusinessHours Where IsDefault=true];
        }
        
        String timeMeasure = serviceMap.get('Email_SLA_Time_Measure__c');
        Integer timeUnits = Integer.valueOf(serviceMap.get('Email_SLA_Units__c'));
        
        //hours in milliseconds
        if(timeMeasure.contains('Hour')){
            timeUnits = timeUnits * 60 * 60 * 1000;
        }else if(timeMeasure.contains('Day')){
            timeUnits = timeUnits * 9; //9 hour day
            timeUnits = timeUnits * 60 * 60 * 1000;
        }else if(timeMeasure.contains('Week')){
            timeUnits = timeUnits * 45; //5 day week at 9 hours per day
            timeUnits = timeUnits * 60 * 60 * 1000;
        }
        
        Integer warningTime = 0;
        
        if(timeUnits == (60 * 60 * 1000)){
            warningTime = 30 * 60 * 1000; //30min
        }else if(timeUnits > (60 * 60 * 1000)){
            warningTime = 60 * 60 * 1000; //60min
        }
        
        list<DateTime> returnArray = new list<DateTime>();
        
        returnArray.add(BusinessHours.add(bhId[0].Id, slaStartDate, (timeUnits - warningTime)));
        returnArray.add(BusinessHours.add(bhId[0].Id, slaStartDate, timeUnits));
        
        return returnArray;
    }
    
    //validate if a user selected the correct channel relevant to his service type selection
    public Boolean isChannelValid(){
        String cha = sm[0].Channel__c;
        set<String> channels = new set<String>(cha.split(';'));
        if(channels.contains(theCase.Channel__c)){
            return true;   
        }else{
            return false;
        }
    }
    
    //all below methods returns one mapping value relevant to the Case in scope based on the key
    //---------------------------------------------------------------------------------- 
    public String getSLAInternalPauseStatus(){
        if(serviceMap.containsKey('SLA_Pause_Status_Internal__c')){
            return serviceMap.get('SLA_Pause_Status_Internal__c'); 
        }else{
            return null;
        }
    }
    public String getSLAPauseStatus(){
        if(serviceMap.containsKey('SLA_Pause_Status__c')){
            return serviceMap.get('SLA_Pause_Status__c'); 
        }else{
            return null;
        }
    }
    public String getConvertRecordType(){
        if(serviceMap.containsKey('Convert_To_RecordType__c')){
            return serviceMap.get('Convert_To_RecordType__c'); 
        }else{
            return null;
        }
    } 
    public String getFullDepartment(){
        if(serviceMap.containsKey('Full_Department__c')){
            return serviceMap.get('Full_Department__c'); 
        }else{
            return null;
        }
    }
    public String getDepartment(){
        if(serviceMap.containsKey('Department__c')){
            return serviceMap.get('Department__c'); 
        }else{
            return null;
        }
    }
    public String getComplexity(){
        if(serviceMap.containsKey('Complexity__c')){
            return serviceMap.get('Complexity__c'); 
        }else{
            return null;
        }
    }
    public String getFirstApproval(){
        if(serviceMap.containsKey('First_Approval__c')){
            return serviceMap.get('First_Approval__c'); 
        }else{
            return null;
        }
    }
    public String getIDVRequired(){
        
        if(serviceMap.containsKey('ID_V__c')){
            return serviceMap.get('ID_V__c');
        }else{
            return null;
        }
    }
    public String getPriority(){
        
        if(serviceMap.containsKey('Priority')){
            return serviceMap.get('Priority');
        }else{
            return null;
        }
    }
    public String getSecondEscalationTime(){
        
        if(serviceMap.containsKey('Second_Escalation_Time__c')){
            return serviceMap.get('Second_Escalation_Time__c');
        }else{
            return null;
        }
    }
    public String getQueueAPIName(){
        
        if(serviceMap.containsKey('Queue_Name__c')){
            return serviceMap.get('Queue_Name__c');
        }else{
            return null;
        }
    }
    public String getQueueName(){
        
        if(serviceMap.containsKey('Queue__c')){
            return serviceMap.get('Queue__c');
        }else{
            return null;
        }
    }
    public String getTeam(){
        
        if(serviceMap.containsKey('Team__c')){
            return serviceMap.get('Team__c');
        }else{
            return null;
        }
    }
    public String getTeamManager(){
        
        if(serviceMap.containsKey('Team_Manager__c')){
            return serviceMap.get('Team_Manager__c');
        }else{
            return null;
        }
    }
    public String getSecondApproval(){
        
        if(serviceMap.containsKey('Second_Approval__c')){
            return serviceMap.get('Second_Approval__c');
        }else{
            return null;
        }
    }
    public String getSLA(){
        
        if(serviceMap.containsKey('SLA__c')){
            return serviceMap.get('SLA__c');
        }else{
            return null;
        }
    }
    public String getFirstEscalationTime(){
        
        if(serviceMap.containsKey('First_Escalation_Time__c')){
            return serviceMap.get('First_Escalation_Time__c');
        }else{
            return null;
        }
    }
    public String getBusinessHours(){
        
        if(serviceMap.containsKey('Business_Hours__c')){
            return serviceMap.get('Business_Hours__c');
        }else{
            return null;
        }
    }
    public String getRecordId(){
        
        if(serviceMap.containsKey('Id')){
            return serviceMap.get('Id');
        }else{
            return null;
        }
    }
    public String getSupportEmailAddress(){
        if(serviceMap.containsKey('Support_Email_Address__c')){
            return serviceMap.get('Support_Email_Address__c'); 
        }else{
            return null;
        }
    }
    public String getResponseFromEmailAddress(){
        if(serviceMap.containsKey('Response_From_Email_Address__c')){
            return serviceMap.get('Response_From_Email_Address__c'); 
        }else{
            return null;
        }
    }
}