objects/Service_Mapping__c.object
<CustomObject>
    <description>Object to Capture Service Process and Resulting Service Category, Sub-Category and Type Applicable Information to Render on Cases Page</description>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <label>Business Hours</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Hours</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Channel</description>
        <inlineHelpText>Please select appropriate Channel. Selection is dependent on Service Type.</inlineHelpText>
        <label>Channel</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Complexity__c</fullName>
        <label>Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Complexity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Department</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>RN : CloudSmiths
The date when this service mapping with SLA is effective from</description>
        <inlineHelpText>The date when this service mapping with SLA is effective from</inlineHelpText>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_SLA_Time_Measure__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Email SLA Time Measure</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Time_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_SLA_Units__c</fullName>
        <description>RN - CloudSmiths</description>
        <label>Email SLA Units</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Feedback_Time_Measure__c</fullName>
        <description>RN - CloudSmiths - the time units for the feedback alert email to be sent for a service type</description>
        <label>Feedback Time Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Time_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Approval__c</fullName>
        <description>First Approval</description>
        <inlineHelpText>First Approval</inlineHelpText>
        <label>First Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Team Memeber</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Escalation_Time__c</fullName>
        <label>First Escalation Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Full_Department__c</fullName>
        <label>Full Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Absa Electronic Banking Helpdesk</fullName>
                </value>
                <value>
                    <fullName>Absa Electronic Banking Service Support</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Support Corporate Cape Town</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Commercial Cape Town</fullName>
                </value>
                <value>
                    <fullName>Trade Client Service Manager</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Enterprise Pretoria</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Commercial Pretoria</fullName>
                </value>
                <value>
                    <fullName>Channel Specialist</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Corporate Cape Town</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Support Corporate Pretoria</fullName>
                </value>
                <value>
                    <fullName>Regional Service Centre Corporate Pretoria</fullName>
                </value>
                <value>
                    <fullName>Product On-boarding</fullName>
                </value>
                <value>
                    <fullName>Digital Ops Support</fullName>
                </value>
                <value>
                    <fullName>Botswana CCC SA</fullName>
                </value>
                <value>
                    <fullName>Payments Operations</fullName>
                </value>
                <value>
                    <fullName>Transfer Inwards</fullName>
                </value>
                <value>
                    <fullName>Structured Commodity Finance</fullName>
                </value>
                <value>
                    <fullName>Structured Trade Finance</fullName>
                </value>
                <value>
                    <fullName>RBB Cash Operations</fullName>
                </value>
                <value>
                    <fullName>Open Account - Middle Office</fullName>
                </value>
                <value>
                    <fullName>Functions Technology</fullName>
                </value>
                <value>
                    <fullName>Salesforce Africa</fullName>
                </value>
                <value>
                    <fullName>Trade Operations</fullName>
                </value>
                <value>
                    <fullName>CIB Financial Crime Compliance</fullName>
                </value>
                <value>
                    <fullName>Future clearing</fullName>
                    <label>Futures clearing</label>
                </value>
                <value>
                    <fullName>SA Migrations</fullName>
                </value>
                <value>
                    <fullName>Wholesale Client Service Centre</fullName>
                </value>
                <value>
                    <fullName>inward payments Client service and support</fullName>
                </value>
                <value>
                    <fullName>Cash Send</fullName>
                </value>
                <value>
                    <fullName>Refresh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ID_V_Required__c</fullName>
        <description>ID&amp;V Required</description>
        <inlineHelpText>Level of ID&amp;V Required. Dependent on Service Type.</inlineHelpText>
        <label>ID&amp;V Required</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Weak</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Strong</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Priority</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>RN : CloudSmiths</description>
        <inlineHelpText>Please use the Queue API name</inlineHelpText>
        <label>Queue Name (API Name)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Queue</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA_Time_Measure__c</fullName>
        <label>SLA Time Measure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Time_Measure</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA_Units__c</fullName>
        <label>SLA Units</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SLA_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Approval__c</fullName>
        <description>Second Approval</description>
        <inlineHelpText>Second Approval</inlineHelpText>
        <label>Second Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EBSH Team Member</fullName>
                </value>
                <value>
                    <fullName>EBSS Team Leader</fullName>
                </value>
                <value>
                    <fullName>EBSS Team Member</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>EBSH Team Leader</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Escalation_Time__c</fullName>
        <label>Second Escalation Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Category__c</fullName>
        <label>Service Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Sub_Category__c</fullName>
        <label>Service Sub-Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Sub_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Email_Address__c</fullName>
        <label>Support Email Address</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Email</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Manager__c</fullName>
        <label>Team Manager</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Team_Manager</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Team</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template_Name_Case_Close__c</fullName>
        <description>RN : CloudSmiths
Email Template API name - utilized in the Case trigger</description>
        <inlineHelpText>Email Template API name</inlineHelpText>
        <label>Template Name - Case Close</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name_Case_Creation__c</fullName>
        <description>RN : CloudSmiths
Email Template API name - utilized in the Case trigger</description>
        <inlineHelpText>Email Template API name</inlineHelpText>
        <label>Template Name - Case Creation</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name_Email_Receipt__c</fullName>
        <description>RN : CloudSmiths
Email Template API name - utilized in the Case trigger</description>
        <inlineHelpText>Email Template API name</inlineHelpText>
        <label>Template Name - Email Receipt</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name_Feedback_Email__c</fullName>
        <description>RN : CloudSmiths
Email Template API name - utilized in the Case trigger</description>
        <inlineHelpText>Please enter the email template API name for the Feedback email to be send to the client based on the feedback interval period</inlineHelpText>
        <label>Template Name - Feedback Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Service Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>BRID__c</fullName>
        <defaultValue>$User.FederationIdentifier</defaultValue>
        <description>The SSO unique Identifier</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BRID</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Business_Hours.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Monday to Friday 06:00 - 19:00</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 07:30 - 17:00</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 08:00 - 16:30</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 07:00 - 16:30</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday 08:00 - 18:00</fullName>
    </customValue>
    <customValue>
        <fullName>Monday to Friday     08:00 - 17:00</fullName>
    </customValue>
    <masterLabel>Business Hours</masterLabel>
</GlobalValueSet>

globalValueSets/Complexity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>High</fullName>
    </customValue>
    <customValue>
        <fullName>Medium</fullName>
    </customValue>
    <customValue>
        <fullName>Low</fullName>
    </customValue>
    <masterLabel>Complexity</masterLabel>
</GlobalValueSet>

globalValueSets/Department.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>EBSS</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Commercial PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Commercial CPT</fullName>
    </customValue>
    <customValue>
        <fullName>TCSM</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate CPT &amp; PTA</fullName>
    </customValue>
    <customValue>
        <fullName>POB</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Enterprise PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>DOS</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH ROA</fullName>
    </customValue>
    <customValue>
        <fullName>Investigations</fullName>
    </customValue>
    <customValue>
        <fullName>ITC</fullName>
    </customValue>
    <customValue>
        <fullName>TRI</fullName>
    </customValue>
    <customValue>
        <fullName>SCF</fullName>
    </customValue>
    <customValue>
        <fullName>STF</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Operations</fullName>
    </customValue>
    <customValue>
        <fullName>OA - MO</fullName>
    </customValue>
    <customValue>
        <fullName>F-Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>BGI</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Crime Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Future Clearing</fullName>
    </customValue>
    <customValue>
        <fullName>SA Migrations - JHB</fullName>
    </customValue>
    <masterLabel>Department</masterLabel>
</GlobalValueSet>

globalValueSets/Email.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>absaeb@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>absaglobalsa@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>africaebprocessing@barclaysafrica.com</fullName>
    </customValue>
    <customValue>
        <fullName>barclays.netonboarding@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>barclays.netsupport@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>barclays.netsupport@barclaysafrica.com</fullName>
    </customValue>
    <customValue>
        <fullName>biactivations@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>biocert@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>cashfocus@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>cscdocumentation@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>EBS.2ndLineEscalations@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebs.moten.ngele@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebs.natalie.marais@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebsamendments@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebslimitsbilling@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>ebsnewregistration@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>EFXSupport@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>magtapes@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>Passwords@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>paymentssupport@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>cscsupport@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>xracscsupport@barclayscapital.com</fullName>
    </customValue>
    <customValue>
        <fullName>xracscsupporthelpdes@barclayscapital.com</fullName>
    </customValue>
    <customValue>
        <fullName>ebs.Insan.Parton@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>xraCorporateProductO@barclayscapital.com</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corpdvb@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corplc@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corpmc@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corpni@absa.co.za</fullName>
    </customValue>
    <customValue>
        <fullName>rsc.corprc@absa.co.za</fullName>
    </customValue>
    <masterLabel>Email</masterLabel>
</GlobalValueSet>

globalValueSets/Priority.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Occured</fullName>
    </customValue>
    <customValue>
        <fullName>High</fullName>
    </customValue>
    <customValue>
        <fullName>Medium</fullName>
    </customValue>
    <customValue>
        <fullName>Low</fullName>
    </customValue>
    <masterLabel>Priority</masterLabel>
</GlobalValueSet>

globalValueSets/Queue.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Banking Advisory Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Breaks</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Send</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Bloem</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare DBN</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Goodwood</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Kempton</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Klerksdorp</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Ormonde</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare PE</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare PTA</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Vaal</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Witbank</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement DBN</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement JHB</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement PE</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Finance Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Client</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Csctradesupport</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - DebiCheck</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - General</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - NovoFX</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - 2nd Line</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - Absa Electronic Banking</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - Passwords</fullName>
    </customValue>
    <masterLabel>Queue</masterLabel>
</GlobalValueSet>

globalValueSets/Service_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Complaint</fullName>
    </customValue>
    <customValue>
        <fullName>Incident</fullName>
    </customValue>
    <customValue>
        <fullName>Service Related</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request</fullName>
    </customValue>
    <customValue>
        <fullName>Service Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Migration-Phase 2 Local Banking to BIO</fullName>
    </customValue>
    <masterLabel>Service Category</masterLabel>
</GlobalValueSet>

globalValueSets/Service_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Absa Wealth Batch</fullName>
    </customValue>
    <customValue>
        <fullName>ACB Credit/Debit</fullName>
    </customValue>
    <customValue>
        <fullName>ACB Credit/Debit - Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Access Request For Extranet</fullName>
    </customValue>
    <customValue>
        <fullName>Account/Certificate of Balance</fullName>
    </customValue>
    <customValue>
        <fullName>Account Balance</fullName>
    </customValue>
    <customValue>
        <fullName>Account Category Change</fullName>
    </customValue>
    <customValue>
        <fullName>Account Closure</fullName>
    </customValue>
    <customValue>
        <fullName>Account closures Vostro/Nostro/CFC/GPP</fullName>
    </customValue>
    <customValue>
        <fullName>Account Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Account Holder Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Account Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Account Key Creations</fullName>
    </customValue>
    <customValue>
        <fullName>Account Level Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Account Not DR/CR</fullName>
    </customValue>
    <customValue>
        <fullName>Account Opening</fullName>
    </customValue>
    <customValue>
        <fullName>Activation</fullName>
    </customValue>
    <customValue>
        <fullName>Add/Amend/Delete Account on Profile</fullName>
    </customValue>
    <customValue>
        <fullName>Add/Delete Abbreviated Name</fullName>
    </customValue>
    <customValue>
        <fullName>Add/Delete User</fullName>
    </customValue>
    <customValue>
        <fullName>Add 3rd Party Account</fullName>
    </customValue>
    <customValue>
        <fullName>Add Account to C2B</fullName>
    </customValue>
    <customValue>
        <fullName>Add BII Account on Imex</fullName>
    </customValue>
    <customValue>
        <fullName>Add Entity</fullName>
    </customValue>
    <customValue>
        <fullName>Add Limit</fullName>
    </customValue>
    <customValue>
        <fullName>Add Module</fullName>
    </customValue>
    <customValue>
        <fullName>Add Operator</fullName>
    </customValue>
    <customValue>
        <fullName>Add System Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Add User</fullName>
    </customValue>
    <customValue>
        <fullName>Add Validation Rule</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <masterLabel>Service Type</masterLabel>
</GlobalValueSet>

globalValueSets/SLA_Time_Measure.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <customValue>
        <fullName>Hour(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Day(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Week(s)</fullName>
    </customValue>
    <masterLabel>SLA Time Measure</masterLabel>
</GlobalValueSet>

globalValueSets/SLA_Unit.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <masterLabel>SLA Unit</masterLabel>
</GlobalValueSet>

globalValueSets/Team.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2nd Line</fullName>
    </customValue>
    <customValue>
        <fullName>Absa Electronic Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Absa Global</fullName>
    </customValue>
    <customValue>
        <fullName>Activations</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net Amendments</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net CSC Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net Processing</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net Rest of Africa</fullName>
    </customValue>
    <customValue>
        <fullName>B.Net SA</fullName>
    </customValue>
    <customValue>
        <fullName>Billing &amp; Limits</fullName>
    </customValue>
    <customValue>
        <fullName>C2B</fullName>
    </customValue>
    <customValue>
        <fullName>CSC Documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Diamond</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Certificates</fullName>
    </customValue>
    <customValue>
        <fullName>EBSS Approvals</fullName>
    </customValue>
    <customValue>
        <fullName>EFX Support</fullName>
    </customValue>
    <customValue>
        <fullName>Magtapes</fullName>
    </customValue>
    <customValue>
        <fullName>New Registrations</fullName>
    </customValue>
    <customValue>
        <fullName>Passwords</fullName>
    </customValue>
    <customValue>
        <fullName>Sweeping</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>TCSM</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Product On-boarding</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Ops Support</fullName>
    </customValue>
    <customValue>
        <fullName>NovoFX</fullName>
    </customValue>
    <masterLabel>Team</masterLabel>
</GlobalValueSet>

globalValueSets/Team_Manager.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Almarie Boshoff</fullName>
    </customValue>
    <customValue>
        <fullName>Ameeth Lakhani</fullName>
    </customValue>
    <customValue>
        <fullName>Anna Henery</fullName>
    </customValue>
    <customValue>
        <fullName>Berenice Thaver</fullName>
    </customValue>
    <customValue>
        <fullName>Bernadette Mckay</fullName>
    </customValue>
    <customValue>
        <fullName>Brian Shabane</fullName>
    </customValue>
    <customValue>
        <fullName>Carmen Zandberg</fullName>
    </customValue>
    <customValue>
        <fullName>Charmaine Burger</fullName>
    </customValue>
    <customValue>
        <fullName>Corne Geyer</fullName>
    </customValue>
    <customValue>
        <fullName>Daniel Coetzee</fullName>
    </customValue>
    <customValue>
        <fullName>Daniel Masindi</fullName>
    </customValue>
    <customValue>
        <fullName>Dudu Mtsweni</fullName>
    </customValue>
    <customValue>
        <fullName>Eleanor Snyders</fullName>
    </customValue>
    <customValue>
        <fullName>Elmarie Meyer</fullName>
    </customValue>
    <customValue>
        <fullName>Frederik Theodorus Ferreira</fullName>
    </customValue>
    <customValue>
        <fullName>Gerard Voskuil</fullName>
    </customValue>
    <customValue>
        <fullName>Hajira Bagus</fullName>
    </customValue>
    <customValue>
        <fullName>Iraan Singh</fullName>
    </customValue>
    <customValue>
        <fullName>Isebeau Spies</fullName>
    </customValue>
    <customValue>
        <fullName>Jacky Naidoo</fullName>
    </customValue>
    <customValue>
        <fullName>Jessica Gounden</fullName>
    </customValue>
    <customValue>
        <fullName>Jordaan Sonja</fullName>
    </customValue>
    <customValue>
        <fullName>Kgopotso Mathole</fullName>
    </customValue>
    <customValue>
        <fullName>Knowledge Zulu</fullName>
    </customValue>
    <customValue>
        <fullName>Lethabo Ramokoka</fullName>
    </customValue>
    <customValue>
        <fullName>Marius Goeieman</fullName>
    </customValue>
    <customValue>
        <fullName>Marsha De Wet</fullName>
    </customValue>
    <customValue>
        <fullName>Monica Tyler</fullName>
    </customValue>
    <customValue>
        <fullName>Narina Butler</fullName>
    </customValue>
    <customValue>
        <fullName>Nomcebo Mdlozini</fullName>
    </customValue>
    <customValue>
        <fullName>Tanya Theunissen</fullName>
    </customValue>
    <masterLabel>Team Manager</masterLabel>
</GlobalValueSet>

classes/CSC_TestDataFactory.cls
/**
* Date   : 06-08-2016
* Author : RN - CloudSmiths
* Desc   : Test Data factory for CSC Service Cloud Code, some methods could be use to generate data outside of the CSC implimentation 
**/

@isTest
public class CSC_TestDataFactory {
    
    //default number of records to create
    public static Integer testDataSize = 10;
    
    // Get Contact Record type Map
    public static Map <String, Schema.RecordTypeInfo> mapContactRecordTypes = Contact.sObjectType.getDescribe().getRecordTypeInfosByName();
    
    // Get Account Record type Map
    public static Map <String, Schema.RecordTypeInfo> mapAccountRecordTypes = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
    
    // Get Case Record type Map
    public static Map <String, Schema.RecordTypeInfo> mapCaseRecordTypes = Case.sObjectType.getDescribe().getRecordTypeInfosByName();
    
    /**
* @Description Method to create a user
* @Param Profile Name, User Name
* @Return User
**/
    public static User createUser(string profile, string username) {
        username = Math.random()+ username;
        user newUser;
        try {
            Profile userProfile = [select Name from Profile where Name = :profile];
            newUser = new User(Alias = 'test',
                               Email = 'one@test.sbsa.co.za',
                               Emailencodingkey = 'UTF-8',
                               Lastname = profile + ' User',
                               Languagelocalekey = 'en_US',
                               City = 'Johannesburg',
                               Country = 'South Africa',
                               Division__c = 'Barclays',
                               BRID__c = String.valueOf(Math.random()).left(9),
                               Localesidkey = 'en_US',
                               Profileid = userProfile.Id,
                               Timezonesidkey = 'America/Los_Angeles',
                               Username = username);
        } Catch(Exception e) {
            system.assertEquals('List has no rows for assignment to SObject Profile', e.getMessage());
        }
        return newUser;
    }
    
    /**
* @Description Create Account records
* @Param RecordTypeId
* @Return List<Account>
**/
    
    public static list<Account> getTestAccountList(String recordTypeName) {
        
        list <Account> lstAccount = new list <Account> ();
        
        for (Integer i = 0; i < testDataSize; i++) {
            
            Account testAccount = new Account();
            testAccount.recordTypeId = mapAccountRecordTypes.get(recordTypeName).getRecordTypeId();
            testAccount.Name = 'Cloudsmiths ' +  recordTypeName  + i;
            testAccount.ShippingCountry = 'South Africa';
            
            lstAccount.add(testAccount);
        }
        return lstAccount;
    }  
    
    /**
* @Description Populate Contact record
* @Param List<Account>
* @Return List<Contact>
**/
    
    public static list<Contact> getTestContactList(list<Account> lstAccount) {
        
        list <Contact> lstcontact = new list <Contact> ();
        
        for (Integer i = 0; i < lstAccount.size(); i++) {
            
            Contact con = new Contact();
            con.AccountId = lstAccount[i].Id;
            con.LastName = 'testcontact' + i;
            con.FirstName = 'test' + i;
            con.MobilePhone = '0823343399';
            con.Email = Math.Random()+'absa@test.co.za';
            lstcontact.add(con);
        }
        return lstcontact;
    }  
    
    /**
* @Description Returns the default Contact used in all CSC comms on email template outbound emails 
* @Param NONE 
* @Return Contact
**/
    public static Contact getDefaultEmailSupportContact() {
        
        Contact con = new Contact();
        //con.AccountId = lstAccount[i].Id;
        con.LastName = 'Support';
        con.FirstName = 'Agent';
        con.MobilePhone = '27 11 237 1434';
        con.Email = 'agents@support.co.za';
        
        return con;
    }  
    /**
* @Description Populate one sservice mapping record
* @Param NONE 
* @Return Service_Mapping__c
**/
    public static Service_Mapping__c getServiceMapRecord() {
        
        Service_Mapping__c sm = new Service_Mapping__c();       
        sm.SLA_Time_Measure__c = 'Hour(s)';
        sm.SLA_Units__c = '2';
        sm.Email_SLA_Time_Measure__c = 'Hour(s)';
        sm.Email_SLA_Units__c = '2';
        sm.Complexity__c = 'Medium';
        sm.First_Approval__c = 'Not Applicable';
        sm.ID_V_Required__c = 'Moderate';
        sm.Priority__c = 'High';
        sm.Second_Approval__c = 'Not Applicable';
        sm.Team__c = 'Passwords';
        sm.Queue_Name__c = 'EBSH_Passwords';
        sm.First_Escalation_Time__c = 8;
        sm.Second_Escalation_Time__c = 9;
        sm.Business_Hours__c = 'Monday to Friday 08:00 - 16:30';
        sm.Channel__c = 'AMS;Authenticated Collections;AVS;Bankserv;B.Net;BDI;BI Online;BICOS;BII ICM;BII Trade Finance;Billway;C2B;Cash Focus;CF Dial Up;CLP;CSS;EDI;Filegateway;Generic Banking Processing RSC Support;H2H;International Banking Payments;Link Direct;Local Banking;Magtapes;Mailbox;NMB;Recon Focus;Statement Delivery;Zram;Not Applicable';
        sm.Department__c = 'EBSH';
        sm.Full_Department__c = 'Absa Electronic Banking Helpdesk';
        sm.Queue__c = 'EBSH - Passwords';
        sm.Effective_Date__c = System.today();
        sm.Template_Name_Email_Receipt__c = 'CSC_Email_Receipt_EBSH_Passwords';
        sm.Template_Name_Case_Creation__c = 'CSC_Case_Creation_EBSH_1';
        sm.Template_Name_Case_Close__c = 'CSC_Case_Closure_EBSH_1';
        sm.Support_Email_Address__c = 'Passwords@absa.co.za';
        sm.Service_Type__c = 'System';
        sm.Service_Category__c = 'Incident';
        sm.Priority__c = 'High';
        sm.Service_Sub_Category__c = 'Change/Enhance';
        sm.Team_Manager__c = 'Tanya Theunissen';
        sm.Template_Name_Feedback_Email__c = 'CSC_Case_Creation_EBSH_1';
        sm.Feedback_Time_Measure__c = 'Hour';
        sm.Feedback_Units__c = '1';
        sm.Response_From_Email_Address__c = 'Passwords@absa.co.za';
        sm.SLA_Pause_Status__c = 'Awaiting Feedback - Client';
        sm.SLA_Pause_Status_Internal__c = 'Awaiting Feedback - 3rd Party';
        sm.Convert_To_RecordType__c = 'CSC_Emails';
        return sm;
    }       
    
    /**
* @Description Create Case records
* @Param RecordTypeId
* @Param OwnerId
* @Return list<Case>
**/
    
    public static list<Case> getTestCaseList(String recordTypeName, String ownerId) {
        
        list<Case> lstCases = new list<Case>();
        
        for (Integer i = 0; i < testDataSize; i++) {
            
            Case testCase = new Case();
            testCase.recordTypeId = mapCaseRecordTypes.get(recordTypeName).getRecordTypeId();
            testCase.Subject = 'Support test ' +  recordTypeName  + i;
            testCase.OwnerId = ownerId;
            testCase.Origin = 'Email';
            testCase.Status = 'New';
            testCase.Priority = 'High';
            testCase.Email_From_Address__c = 'wouter@styne.co.za';
            lstCases.add(testCase);
        }
        
        return lstCases;
    }  
    
    /**
* @Description Create EmailMessage records
* @Param isHtml
* @Param ParentId
* @Return list<EmailMessage>
**/
    
    public static list<EmailMessage> getTestEmailMessageList(String parentObjId, Boolean isHTML) {
        
        list<EmailMessage> lstEmailMessages = new list<EmailMessage>();
        
        for (Integer i = 0; i < testDataSize; i++) {
            
            EmailMessage testEmailMessage = new EmailMessage();
            testEmailMessage.Subject = 'Email Message test ' + i;
            testEmailMessage.ParentId = parentObjId;
            testEmailMessage.MessageDate = System.now();
            
            if(isHTML){
                testEmailMessage.HtmlBody = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Outlook</title></head><table><tr><td>Test Email HTML body</td></tr></table></html>';
            }else{
                testEmailMessage.TextBody = 'Test Email Plaintext body';
            }
            
            lstEmailMessages.add(testEmailMessage);
        }
        return lstEmailMessages;
    }  
    
    /**
* @Description Create a Queue
* @Param QueueName
* @Return QueueId
**/
    /**
    public static String getTestQueueId(String qname) {
        Group  testgroup = new group();
        testgroup.Name = qname;
        testgroup.Type = 'Queue';
        insert testgroup;
        
        QueueSobject mappingObject = new QueueSobject(QueueId = testgroup.Id, SobjectType = 'Case');
        System.runAs(new User(Id = UserInfo.getUserId())){
            insert mappingObject;
        }
        
        return testgroup.Id;
    } **/
    
    /**
* @Description Create a Queue
* @Param QueueName
* @Return QueueId
**/
    
    public static list<CaseComment> getCaseComments(String caseID, Boolean pvt) {
        list<CaseComment> newCaseComments = new list<CaseComment>();
        
        for (Integer i = 0; i < testDataSize; i++){
            
            CaseComment cc = new CaseComment();
            cc.IsPublished = pvt;
            cc.CommentBody = 'Comment Number ' + i;
            cc.ParentId = caseID;
            
            newCaseComments.add(cc); 
        }
        
        return newCaseComments;
    }  
    
    /**
* @Description Create an InboundEmail record
* @Return Messaging.InboundEmail
**/
    public static Messaging.InboundEmail getTestInboundEmail() {
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        email.htmlBody = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Outlook</title></head><table><tr><td>Pls rest my password</td></tr></table></html>';
        email.subject = 'Please reset my pwd...now!';
        email.fromName = 'Wouter Styne';
        email.fromAddress = 'wouter@styne.co.za';
        return email;
    }  
    /**
* @Description Create an InboundEnvelope record
* @Return Messaging.InboundEnvelope
**/
    public static Messaging.InboundEnvelope getTestInboundEnvelope() {
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        env.toAddress = 'Passwords@absa.co.za';
        env.fromAddress = 'wouter@styne.co.za';
        return env;
    } 
    /**
* @Description Create an InboundEmail BinaryAttachment record
* @Return an array of Messaging.InboundEmail.BinaryAttachment[]
**/
    public static Messaging.InboundEmail.BinaryAttachment[] getTestBinaryAttachment() {
        Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
        attachment.body = blob.valueOf('my attachment text');
        attachment.fileName = 'textfile.txt';
        attachment.mimeTypeSubType = 'text/plain';
        return new Messaging.inboundEmail.BinaryAttachment[] { attachment };
            }  
    
    /**
* @Description Create an Attachment record
* @Param Attachment ParentId
* @Return an Attachment Record
**/
    public static Attachment getAttachment(String pid) {
        Attachment att = new Attachment();
        att.body = blob.valueOf('my attachment text');
        att.Description = 'Test Att';
        att.Name = 'Afile.txt';
        att.ParentId = pid;
        return att;
    }  
    
    
    /**
* @Description get the thread ID of a case
* @Param Case.Id
* @Return the Thread ID as String
**/
    public static String getTestCaseThreadID(String caseID) {
        return 'ref:_'  + UserInfo.getOrganizationId().left(4)  + 'E' + UserInfo.getOrganizationId().mid(11,4) + '._' + caseID.left(4) + 'E' + caseID.mid(10,5) + ':ref';
    }      
    
   
    public static void insertCustomSetting()
    {
        Case_Resolution_Date_Setting__c CRDS = new Case_Resolution_Date_Setting__c();
        CRDS.Name='Complaint';
        CRDS.Number_of_Days_Allowed__c =3;
        CRDS.Number_of_Times_Date_Change_Limit__c=4;
        insert CRDS;
    }
}