objects/Service_Mapping__c.object
<CustomObject>
    <description>Object to Capture Service Process and Resulting Service Category, Sub-Category and Type Applicable Information to Render on Cases Page</description>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Department</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <label>Queue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Queue</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Service Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Department.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>EBSS</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Commercial PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Commercial CPT</fullName>
    </customValue>
    <customValue>
        <fullName>TCSM</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Corporate CPT</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate CPT &amp; PTA</fullName>
    </customValue>
    <customValue>
        <fullName>POB</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSCS Corporate PTA</fullName>
    </customValue>
    <customValue>
        <fullName>RSC Enterprise PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>DOS</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH ROA</fullName>
    </customValue>
    <customValue>
        <fullName>Investigations</fullName>
    </customValue>
    <customValue>
        <fullName>ITC</fullName>
    </customValue>
    <customValue>
        <fullName>TRI</fullName>
    </customValue>
    <customValue>
        <fullName>SCF</fullName>
    </customValue>
    <customValue>
        <fullName>STF</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Operations</fullName>
    </customValue>
    <customValue>
        <fullName>OA - MO</fullName>
    </customValue>
    <customValue>
        <fullName>F-Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>BGI</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Crime Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Future Clearing</fullName>
    </customValue>
    <customValue>
        <fullName>SA Migrations - JHB</fullName>
    </customValue>
    <masterLabel>Department</masterLabel>
</GlobalValueSet>

globalValueSets/Queue.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Banking Advisory Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Breaks</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Send</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Bloem</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare DBN</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Goodwood</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Kempton</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Klerksdorp</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Ormonde</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare PE</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare PTA</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Vaal</fullName>
    </customValue>
    <customValue>
        <fullName>ClientCare Witbank</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement CPT</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement DBN</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement JHB</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement PE</fullName>
    </customValue>
    <customValue>
        <fullName>Client engagement PTA</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Property Finance Complaints</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Client</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Corporate</fullName>
    </customValue>
    <customValue>
        <fullName>Complaints Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Csctradesupport</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - DebiCheck</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - General</fullName>
    </customValue>
    <customValue>
        <fullName>DOS - NovoFX</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - 2nd Line</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - Absa Electronic Banking</fullName>
    </customValue>
    <customValue>
        <fullName>EBSH - Passwords</fullName>
    </customValue>
    <masterLabel>Queue</masterLabel>
</GlobalValueSet>

globalValueSets/Service_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Absa Wealth Batch</fullName>
    </customValue>
    <customValue>
        <fullName>ACB Credit/Debit</fullName>
    </customValue>
    <customValue>
        <fullName>ACB Credit/Debit - Bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Access Request For Extranet</fullName>
    </customValue>
    <customValue>
        <fullName>Account/Certificate of Balance</fullName>
    </customValue>
    <customValue>
        <fullName>Account Balance</fullName>
    </customValue>
    <customValue>
        <fullName>Account Category Change</fullName>
    </customValue>
    <customValue>
        <fullName>Account Closure</fullName>
    </customValue>
    <customValue>
        <fullName>Account closures Vostro/Nostro/CFC/GPP</fullName>
    </customValue>
    <customValue>
        <fullName>Account Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Account Holder Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Account Issue</fullName>
    </customValue>
    <customValue>
        <fullName>Account Key Creations</fullName>
    </customValue>
    <customValue>
        <fullName>Account Level Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Account Not DR/CR</fullName>
    </customValue>
    <customValue>
        <fullName>Account Opening</fullName>
    </customValue>
    <customValue>
        <fullName>Activation</fullName>
    </customValue>
    <customValue>
        <fullName>Add/Amend/Delete Account on Profile</fullName>
    </customValue>
    <customValue>
        <fullName>Add/Delete Abbreviated Name</fullName>
    </customValue>
    <customValue>
        <fullName>Add/Delete User</fullName>
    </customValue>
    <customValue>
        <fullName>Add 3rd Party Account</fullName>
    </customValue>
    <customValue>
        <fullName>Add Account to C2B</fullName>
    </customValue>
    <customValue>
        <fullName>Add BII Account on Imex</fullName>
    </customValue>
    <customValue>
        <fullName>Add Entity</fullName>
    </customValue>
    <customValue>
        <fullName>Add Limit</fullName>
    </customValue>
    <customValue>
        <fullName>Add Module</fullName>
    </customValue>
    <customValue>
        <fullName>Add Operator</fullName>
    </customValue>
    <customValue>
        <fullName>Add System Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Add User</fullName>
    </customValue>
    <customValue>
        <fullName>Add Validation Rule</fullName>
    </customValue>
    <customValue>
        <fullName>System</fullName>
    </customValue>
    <masterLabel>Service Type</masterLabel>
</GlobalValueSet>

classes/CSC_EmailMessage_Trigger_Test.cls
/**
* Date   : 11-08-2016
* Author : RN - CloudSmiths
* Desc   : Test class for: CSC_Quick_Action_Transfer_Case_Cont
**/
@IsTest(SeeAllData=true)
public class CSC_EmailMessage_Trigger_Test {
	
    public static testMethod void messageTriggerTest() {
        CSC_TestDataFactory.testDataSize = 1;
        //create some service mapping data
        Service_Mapping__c sm = CSC_TestDataFactory.getServiceMapRecord();
        insert sm;

        //inbound email and envelope objects
        Messaging.InboundEmail email = CSC_TestDataFactory.getTestInboundEmail();
        Messaging.InboundEnvelope env = CSC_TestDataFactory.getTestInboundEnvelope();
        email.binaryAttachments = CSC_TestDataFactory.getTestBinaryAttachment();
        
        list<Case> caseInsertList = CSC_TestDataFactory.getTestCaseList( 'CSC Emails' , UserInfo.getUserId() );
        insert caseInsertList;
        
        Test.startTest();
       
        CSC_Inbound_Email_Service emailService = new CSC_Inbound_Email_Service();
        emailService.handleInboundEmail(email, env);
        
        list<Case> c = [Select Id From Case Where Email_From_Address__c = 'wouter@styne.co.za' limit 1];
        c[0].Queue__c = 'EBSH - Passwords';
        c[0].Department__c = 'EBSH';
        c[0].Service_Type__c = 'System';
        update c[0];
        
        list<EmailMessage> msg = CSC_TestDataFactory.getTestEmailMessageList(c[0].Id, true);
        insert msg;
        
        try{
            delete msg;
        }catch(Exception e){
            System.debug('Catch message delete error');
        }
        Test.stopTest();
    }
}