objects/System_Limits_Tracker__c.object
<CustomObject>
    <description>RN - CloudSmiths 
Object where a developers can track running and system limits that are not available in Apex. e.g. Single Outbound Email limits</description>
    <fields>
        <fullName>Activate_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>RN - CloudSmiths</description>
        <label>Activate Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enforce_Workaround_Percentage__c</fullName>
        <description>RN - CloudSmiths
Workaround threshold percentage. If this threshold is reached Salesforce will by pass the process that counts towards this specific limit and use an alternative process</description>
        <inlineHelpText>Enter a Workaround threshold percentage. If this threshold is reached Salesforce will by pass the process that counts towards this specific limit and use an alternative process</inlineHelpText>
        <label>Enforce Workaround Percentage</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Limit_Was_Reset_At__c</fullName>
        <description>RN - CloudSmiths
When was the 24 hour limit reset by the system</description>
        <inlineHelpText>When was the 24 hour limit reset by the system</inlineHelpText>
        <label>Limit Was Reset At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>System_Limit__c</fullName>
        <description>RN - CloudSmiths
The current Salesforce system limit as</description>
        <inlineHelpText>Please enter the current Salesforce system limit</inlineHelpText>
        <label>System Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Use_WorkAround__c</fullName>
        <defaultValue>false</defaultValue>
        <description>RN - CloudSmiths
Flag that could be used by code to by pass current processes and user alternative processes</description>
        <inlineHelpText>Set this flag to switch between the current process and the alternative workaround process. If CHECKED the workaround process will be enforced.</inlineHelpText>
        <label>Use WorkAround</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Warning_Percentage__c</fullName>
        <description>RN - CloudSmiths 
If this percentage threshold is reached SF will send an email notification to Absa SF Support</description>
        <inlineHelpText>Enter a warning threshold percentage. If this threshold is reached Salesforce will send an email notification to Absa Salesforce Support</inlineHelpText>
        <label>Warning Percentage</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Warning_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Warning Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X24_Running_Limit__c</fullName>
        <defaultValue>0</defaultValue>
        <description>RN - CloudSmiths
The current running limit within a 24 hour cycle</description>
        <inlineHelpText>The current running limit within a 24 hour cycle - This value gets reset at 12:00GMT</inlineHelpText>
        <label>24 Hour Running Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>System Limits Tracker</label>
    <nameField>
        <label>Limits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Limits Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/scheduledResetLimits_Test.cls
/* 20170406
 * RN - CloudSmiths
 * Test class for : scheduledResetLimits
 */
@isTest
public class scheduledResetLimits_Test{
    static testMethod void scheduledResetLimits_Test(){
        //test data
        System_Limits_Tracker__c st = new System_Limits_Tracker__c();
        st.Warning_Sent__c = false;
        st.Activate_Rule__c = true; 
        st.Limit_Was_Reset_At__c = System.now();
        st.Use_WorkAround__c = false; 
        st.Enforce_Workaround_Percentage__c = 90; 
        st.Warning_Percentage__c = 60;
        st.X24_Running_Limit__c = 100;
        st.System_Limit__c = 1000;
        st.Name = 'SingleEmail';
        insert st;
        
        Test.startTest();
        	//set the cron instructions : runs every day at 02:00AM
        	String CRON_EXP = '0 0 13 * * ?';
        	String jobId = System.schedule('ResetLimitsDaily',CRON_EXP, new scheduledResetLimits());
        	// Get the information from the CronTrigger API object
      		CronTrigger ct = [select Id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId];
			System.assertEquals(CRON_EXP, ct.CronExpression);
        
        Test.stopTest();
    }
}