objects/Trigger__c.object
<CustomObject>
    <customHelpPage>SPV</customHelpPage>
    <fields>
        <fullName>Days__c</fullName>
        <label>Days</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Days Before</fullName>
                </value>
                <value>
                    <fullName>Days After</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Once Off</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Bi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Days__c</fullName>
        <label>Number of Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Relative_Date__c</fullName>
        <label>Other Relative Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relative_Date__c</fullName>
        <label>Relative Date</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Frequency__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Effective Date</fullName>
                </value>
                <value>
                    <fullName>Signature Date</fullName>
                </value>
                <value>
                    <fullName>Financial Year End</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trigger</label>
    <nameField>
        <label>Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Trigger_Helper_Test.cls
/**
*** CHANGE LOG ***

10/01/2017 - TdB    - Created Class.

**/ 
@isTest(SeeAllData=false)
public class Trigger_Helper_Test {
    
    public static testMethod void testAgreementLevel()
    {
        Date todaysDate = System.today();
        List<Trigger__c> triggerList = new List<Trigger__c>();
        //Test Data
        Cloudsmiths_TestDataClass  testDataClass = new Cloudsmiths_TestDataClass();
        
        triggerList.add(testDataClass.testTrigger);
        
        test.startTest();
        
        testDataClass.testTrigger.Frequency__c = 'Once Off';
        testDataClass.testTrigger.Due_Date__c = todaysDate.addDays(100);
        
        update testDataClass.testTrigger;
        
        testDataClass.testTrigger.Frequency__c = 'Monthly';
        testDataClass.testTrigger.Relative_Date__c = 'Other';
        testDataClass.testTrigger.Number_Of_Days__c = 5;
        testDataClass.testTrigger.Days__c = 'Days After';
        testDataClass.testTrigger.Other_Relative_Date__c = todaysDate.addDays(50);
        testDataClass.testTrigger.Due_Date__c = null;
        
        update testDataClass.testTrigger;
        
        testDataClass.TestAgreement.Termination_Date__c = todaysDate.addYears(5) ;       
        update testDataClass.TestAgreement;
        
        trigger_Helper.insertWatcherOccurence(triggerList);
        
        test.stopTest();
        
    }
}