objects/WIP_Log__c.object
<CustomObject>
    <fields>
        <fullName>BRID__c</fullName>
        <label>BRID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>WIP Logs</relationshipLabel>
        <relationshipName>WIP_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Actioned__c</fullName>
        <label>Date Actioned</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Type_Task__c</fullName>
        <label>Service Type Task</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workout__c</fullName>
        <label>Workout</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WIP Log</label>
    <nameField>
        <displayFormat>WIP-{00000000}</displayFormat>
        <label>WIP Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WIP Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CSC_Utility_Test.cls
@isTest(SeeAllData=true)
public class CSC_Utility_Test {

    static testMethod void myUnitTest()
    {
        Test.startTest();
        
        List<Case>Caselist =[Select ID,CaseNumber,Queue__c,Subcategory__c,IsClosed,Service_Type__c,CreatedDate,WIP__c,(SELECT Id 
                                                                                                          FROM WIP_Logs__r 
                                                                                                          where Processed__c =false) 
                                         From case 
                                         where IsClosed =false limit 10];
        
        
        
        CSC_Utility.createWIPFile(caseList);
        
        
        
        List<WIP_Log__c> wipList = [SELECT Id, Case__c, Date_Actioned__c, BRID__c, Team__c, Service_Type_Task__c,
                                        Processed__c,Name,Case__r.CaseNumber,Workout__c
                                        FROM WIP_Log__c 
                                        where Processed__c =false];
        
        CSC_Utility.createWorkoutFile(wipList);
        Test.StopTest();
    }
   
}